In [1]:
%matplotlib inline

In [2]:
#Import Libraries here

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
from pathlib import Path
from IPython.display import display

In [3]:
#Import your modules here
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
PARSED_DATA_DIR = PROJECT_ROOT / "data" / "parsed_sales_runs"

#Manually select the folder with the data from the latest scrape of imot.bg
LATEST_RUN = "parsed_sales_full_20260608_081646"

In [4]:
parsed_df = pd.read_parquet(PARSED_DATA_DIR / LATEST_RUN / "parsed_listings.parquet")
parsed_df

,ad_id,ad_url,ad_url_path,ad_url_slug,html_path,listing_type,title,deal_raw,property_type_raw,title_city_raw,...,location_raw,description_raw,description_clean,features_raw,features_pipe,features_count,published_raw,views,training_eligible,parse_error
0,1a155107752004273,https://www.imot.bg/obiava-1a155107752004273-p...,/obiava-1a155107752004273-prodava-ednostaen-ap...,obiava-1a155107752004273-prodava-ednostaen-apa...,data\raw_listing_html\948e49be77a55a7a.html,single_property_listing,"Продава 1-СТАЕН в област Пазарджик, гр. Велинг...",Продава,1-СТАЕН,област Пазарджик,...,"област Пазарджик, гр. Велинград, Цар Самуил",ЕДНОСТАЕН АПАРТАМЕНТ В ЦЕНТЪРА НА ВЕЛИНГРАД ...,ЕДНОСТАЕН АПАРТАМЕНТ В ЦЕНТЪРА НА ВЕЛИНГРАД ...,Тухла\nАсансьор\nС гараж\nС паркинг\nЛизинг,Тухла|Асансьор|С гараж|С паркинг|Лизинг,5,None,9.0,True,NaN
1,1a146979303032401,https://www.imot.bg/obiava-1a146979303032401-p...,/obiava-1a146979303032401-prodava-ednostaen-ap...,obiava-1a146979303032401-prodava-ednostaen-apa...,data\raw_listing_html\9b4948bfbf128a8a.html,single_property_listing,"Продава 1-СТАЕН в град София, Малинова долина ...",Продава,1-СТАЕН,град София,...,"град София, Малинова долина",🏙️ ЕДНОСТАЕН АПАРТАМЕНТ В НОВА СГРАДА НА ЕТАП ...,🏙️ ЕДНОСТАЕН АПАРТАМЕНТ В НОВА СГРАДА НА ЕТАП ...,Тухла,Тухла,1,None,734.0,True,NaN
2,1a140680337846667,https://www.imot.bg/obiava-1a140680337846667-p...,/obiava-1a140680337846667-prodava-ednostaen-ap...,obiava-1a140680337846667-prodava-ednostaen-apa...,data\raw_listing_html\d014b1815f2f9c9b.html,single_property_listing,"Продава 1-СТАЕН в град Варна, м-т Ален мак - 3...",Продава,1-СТАЕН,град Варна,...,"град Варна, м-т Ален мак, спортпалас","апартамент в затворен комплекс,до комплекс спо...","апартамент в затворен комплекс,до комплекс спо...",Тухла\nЛизинг\nБартер,Тухла|Лизинг|Бартер,3,"Публикувана в 13:42 на 31 юли, 2014 год.",13987.0,True,NaN
3,1a154997703660554,https://www.imot.bg/obiava-1a154997703660554-p...,/obiava-1a154997703660554-prodava-ednostaen-ap...,obiava-1a154997703660554-prodava-ednostaen-apa...,data\raw_listing_html\6a625253f270be91.html,single_property_listing,"Продава 1-СТАЕН в област Бургас, гр. Свети Вла...",Продава,1-СТАЕН,област Бургас,...,"област Бургас, гр. Свети Влас",Собственик продава студио в жилищен комплекс И...,Собственик продава студио в жилищен комплекс И...,Тухла\nАсансьор\nС паркинг\nЛизинг\nИнтернет в...,Тухла|Асансьор|С паркинг|Лизинг|Интернет връзк...,11,None,24930.0,True,NaN
4,1a155107630313014,https://www.imot.bg/obiava-1a155107630313014-p...,/obiava-1a155107630313014-prodava-ednostaen-ap...,obiava-1a155107630313014-prodava-ednostaen-apa...,data\raw_listing_html\a31953e77840ec11.html,single_property_listing,"Продава 1-СТАЕН в област Пазарджик, гр. Велинг...",Продава,1-СТАЕН,област Пазарджик,...,"област Пазарджик, гр. Велинград, Кисловодск",НОВО СТРОИТЕЛСТВО -гарантиран строител\n🏡 Пано...,НОВО СТРОИТЕЛСТВО -гарантиран строител 🏡 Панор...,Тухла\nАсансьор\nС гараж\nС паркинг\nЛизинг\nИ...,Тухла|Асансьор|С гараж|С паркинг|Лизинг|Интерн...,7,None,4.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164977,8694,https://www.imot.bg/obiava-8694-zhilishtna-sgr...,/obiava-8694-zhilishtna-sgrada-grad-plovdiv-va...,obiava-8694-zhilishtna-sgrada-grad-plovdiv-vas...,data\raw_listing_html\1402e0190cd8e671.html,new_building_project,"Жилищна сграда в град Пловдив, Въстанически ::...",None,None,None,...,"град Пловдив, Въстанически, От строителя,нов,3...",Без КОМИСИОННА. Директно от строителя. Тристае...,Без КОМИСИОННА. Директно от строителя. Тристае...,None,None,0,"Публикувана в 15:43 на 4 юни, 2026 год.",532.0,False,NaN
164978,8727,https://www.imot.bg/obiava-8727-zhilishten-kom...,/obiava-8727-zhilishten-kompleks-oblast-sofiya...,obiava-8727-zhilishten-kompleks-oblast-sofiya-...,data\raw_listing_html\dedcfe5eb2177d0f.html,new_building_project,"Жилищен комплекс в област София, гр. Самоков :...",None,None,None,...,"област София, гр. Самоков",Директно от Инвеститора на 10км от Боровец!\nД...,Директно от Инвеститора на 10км от Боровец! До...,None,None,0,"Публикувана в 12:33 на 1 юни, 2026 год.",104.0,False,NaN
164979,8729,https://www.imot.bg/obiava-8729-zhilishten-kom...,/obiava-8729-zhilishten-kompleks-grad-burgas-k...,obiava-8729-zhilishten-kompleks-grad-burgas-kr...,data\raw_listing_html\2a3b8aa43b20e4a6.html,new_building_project,"Жилищен комплекс в град Бургас, Крайморие :: i...",None,None,None,...,"град Бургас, Крайморие",Цени от 1233 до 2331 евро /м² без ДДС / 2412...,Цени от 1233 до 2331 евро /м² без ДДС / 2412...,None,None,0,"Публикувана в 16:48 на 1 юни, 2026 год.",223.0,False,NaN
164980,8737,https://www.imot.bg/obiava-8737-zhilishten-kom...,/obiava-8737-zhilishten-kompleks-grad-plovdiv-...,obiava-8737-zhilishten-kompleks-grad-plovdiv-o...,data\raw_listing_html\9aff48c302e6f470.html,new_building_project,"Жилищен комплекс в град Пловдив, Остромила :: ...",None,None,None,...,"град Пловдив, Остромила",Представяме ви нов жилищен комплекс с цени от ...,Представяме ви нов жилищен комплекс с цени от ...,None,None,0,"Публикувана в 15:09 на 4 юни, 2026 год.",38.0,False,NaN
164981,8739,https://www.imot.bg/obiava-8739-zhilishten-kom...,/obiava-8739-zhilishten-kompleks-grad-sofiya-d...,obiava-8739-zhilishten-kompleks-grad-sofiya-dr...,data\raw_listing_html\54e80dabb4fc57e4.html,new_building_project,"Жилищен комплекс в град София, Дружба 1 :: imo...",None,None,None,...,"град София, Дружба 1",461939 БЕЗ КОМИСИОНА! ПРЕФЕРЕНЦИАЛНИ ЦЕНИ НА И...,461939 БЕЗ КОМИСИОНА! ПРЕФЕРЕНЦИАЛНИ ЦЕНИ НА И...,None,None,0,"Публикувана в 12:56 на 8 юни, 2026 год.",47.0,False,NaN

In [5]:
parsed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164982 entries, 0 to 164981
Data columns (total 39 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              164982 non-null  object
 1   ad_url             164982 non-null  object
 2   ad_url_path        164982 non-null  object
 3   ad_url_slug        164982 non-null  object
 4   html_path          164982 non-null  object
 5   listing_type       164982 non-null  object
 6   title              164982 non-null  object
 7   deal_raw           164658 non-null  object
 8   property_type_raw  164658 non-null  object
 9   title_city_raw     164658 non-null  object
 10  title_geo_2_raw    164655 non-null  object
 11  title_area_sqm     161190 non-null  float64
 12  title_price_eur    161018 non-null  float64
 13  title_price_bgn    161018 non-null  float64
 14  seller_name_raw    152894 non-null  object
 15  title_ad_id        164960 non-null  float64
 16  total_price        164664 non-null  float64
 17  currency           164665 non-null  object
 18  price_raw          164665 non-null  object
 19  vat_status         164982 non-null  object
 20  area_sqm           163643 non-null  float64
 21  area_raw           163643 non-null  object
 22  price_per_sqm      163451 non-null  float64
 23  floor              100991 non-null  float64
 24  total_floors       93245 non-null   float64
 25  floor_raw          100991 non-null  object
 26  construction_raw   164982 non-null  object
 27  construction_type  125932 non-null  object
 28  construction_year  164982 non-null  int64
 29  location_raw       164959 non-null  object
 30  description_raw    163391 non-null  object
 31  description_clean  163391 non-null  object
 32  features_raw       144747 non-null  object
 33  features_pipe      144747 non-null  object
 34  features_count     164982 non-null  int64
 35  published_raw      43556 non-null   object
 36  views              164960 non-null  float64
 37  training_eligible  164982 non-null  bool
 38  parse_error        0 non-null       float64
dtypes: bool(1), float64(11), int64(2), object(25)
memory usage: 48.0+ MB

In [6]:
audit_summary = pd.DataFrame({
    "column": parsed_df.columns,
    "dtype": parsed_df.dtypes.astype(str).values,
    "non_null": parsed_df.notna().sum().values,
    "missing": parsed_df.isna().sum().values,
    "missing_pct": (parsed_df.isna().mean() * 100).round(2).values,
    "n_unique": parsed_df.nunique(dropna=True).values,
})

audit_summary.sort_values("missing_pct", ascending=False)
audit_summary

               column    dtype  non_null  missing  missing_pct  n_unique
0               ad_id   object    164982        0         0.00    164972
1              ad_url   object    164982        0         0.00    164982
2         ad_url_path   object    164982        0         0.00    164982
3         ad_url_slug   object    164982        0         0.00    164982
4           html_path   object    164982        0         0.00    164982
5        listing_type   object    164982        0         0.00         3
6               title   object    164982        0         0.00    164958
7            deal_raw   object    164658      324         0.20         1
8   property_type_raw   object    164658      324         0.20        44
9      title_city_raw   object    164658      324         0.20        55
10    title_geo_2_raw   object    164655      327         0.20      3719
11     title_area_sqm  float64    161190     3792         2.30      8152
12    title_price_eur  float64    161018     3964         2.40     25680
13    title_price_bgn  float64    161018     3964         2.40     25681
14    seller_name_raw   object    152894    12088         7.33      3671
15        title_ad_id  float64    164960       22         0.01    151942
16        total_price  float64    164664      318         0.19     25739
17           currency   object    164665      317         0.19         2
18          price_raw   object    164665      317         0.19     25787
19         vat_status   object    164982        0         0.00         4
20           area_sqm  float64    163643     1339         0.81      8417
21           area_raw   object    163643     1339         0.81      9413
22      price_per_sqm  float64    163451     1531         0.93     56461
23              floor  float64    100991    63991        38.79        26
24       total_floors  float64     93245    71737        43.48        29
25          floor_raw   object    100991    63991        38.79       368
26   construction_raw   object    164982        0         0.00       356
27  construction_type   object    125932    39050        23.67         9
28  construction_year    int64    164982        0         0.00        93
29       location_raw   object    164959       23         0.01     17161
30    description_raw   object    163391     1591         0.96    157916
31  description_clean   object    163391     1591         0.96    157892
32       features_raw   object    144747    20235        12.26      6495
33      features_pipe   object    144747    20235        12.26      6495
34     features_count    int64    164982        0         0.00        27
35      published_raw   object     43556   121426        73.60     30582
36              views  float64    164960       22         0.01      9938
37  training_eligible     bool    164982        0         0.00         2
38        parse_error  float64         0   164982       100.00         0

In [7]:
parsed_df.listing_type.value_counts()

listing_type
single_property_listing    162503
unknown                      1576
new_building_project          903
Name: count, dtype: int64

In [8]:
parsed_df.deal_raw.value_counts()

deal_raw
Продава    164658
Name: count, dtype: int64

In [9]:
# ------------------------------------------------------------
# STEP 2 — Row-level validity checks
# ------------------------------------------------------------
print("Rows:", len(parsed_df))
print("Columns:", len(parsed_df.columns))

# 1. Listing type distribution
print("\nlisting_type distribution:")
display(
    parsed_df["listing_type"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 2. Training eligibility distribution
print("\ntraining_eligible distribution:")
display(
    parsed_df["training_eligible"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 3. Deal type distribution
print("\ndeal_raw distribution:")
display(
    parsed_df["deal_raw"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 4. Currency distribution
print("\ncurrency distribution:")
display(
    parsed_df["currency"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 5. VAT status distribution
print("\nvat_status distribution:")
display(
    parsed_df["vat_status"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 6. Duplicate checks
duplicate_summary = {
    "duplicate_ad_url_rows": parsed_df.duplicated("ad_url").sum(),
    "duplicate_ad_id_rows": parsed_df.duplicated("ad_id").sum(),
    "duplicate_title_rows": parsed_df.duplicated("title").sum(),
    "duplicate_html_path_rows": parsed_df.duplicated("html_path").sum(),
}

print("\nDuplicate summary:")
display(pd.DataFrame([duplicate_summary]))

# 7. Inspect duplicated ad_id rows
dup_ad_ids = parsed_df.loc[parsed_df.duplicated("ad_id", keep=False), [
    "ad_id",
    "ad_url",
    "title",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "location_raw",
]]

print("\nDuplicated ad_id rows:")
display(dup_ad_ids.sort_values("ad_id"))

# 8. Core ML validity flags
validity = pd.DataFrame({
    "has_deal": parsed_df["deal_raw"].notna(),
    "has_property_type": parsed_df["property_type_raw"].notna(),
    "has_city": parsed_df["title_city_raw"].notna(),
    "has_area": parsed_df["area_sqm"].notna(),
    "has_total_price": parsed_df["total_price"].notna(),
    "has_price_per_sqm": parsed_df["price_per_sqm"].notna(),
    "positive_area": parsed_df["area_sqm"].gt(0),
    "positive_total_price": parsed_df["total_price"].gt(0),
    "positive_price_per_sqm": parsed_df["price_per_sqm"].gt(0),
    "training_eligible": parsed_df["training_eligible"].eq(True),
})

validity_summary = (
    validity
    .sum()
    .to_frame("valid_count")
    .assign(
        invalid_count=lambda x: len(parsed_df) - x["valid_count"],
        valid_pct=lambda x: (x["valid_count"] / len(parsed_df) * 100).round(2)
    )
)

print("\nValidity summary:")
display(validity_summary)

# 9. First strict candidate rows for regression
df_candidate = parsed_df[
    parsed_df["training_eligible"].eq(True)
    & parsed_df["deal_raw"].notna()
    & parsed_df["property_type_raw"].notna()
    & parsed_df["title_city_raw"].notna()
    & parsed_df["area_sqm"].gt(0)
    & parsed_df["total_price"].gt(0)
    & parsed_df["price_per_sqm"].gt(0)
].copy()

print("\nFirst-pass ML candidate rows:", len(df_candidate))
print("Share of dataset:", round(len(df_candidate) / len(parsed_df) * 100, 2), "%")

# 10. Candidate property type distribution
print("\nCandidate property_type_raw distribution:")
display(
    df_candidate["property_type_raw"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(df_candidate) * 100).round(2))
    .head(50)
)

Rows: 164982
Columns: 39

listing_type distribution:

                          count    pct
listing_type
single_property_listing  162503  98.50
unknown                    1576   0.96
new_building_project        903   0.55

training_eligible distribution:

                    count    pct
training_eligible
True               161438  97.85
False                3544   2.15

deal_raw distribution:

           count   pct
deal_raw
Продава   164658  99.8
None         324   0.2

currency distribution:

           count    pct
currency
EUR       164656  99.80
None         317   0.19
BGN            9   0.01

vat_status distribution:

             count    pct
vat_status
no_vat       90028  54.57
with_vat     57961  35.13
without_vat  10179   6.17
unknown       6814   4.13

Duplicate summary:

,duplicate_ad_url_rows,duplicate_ad_id_rows,duplicate_title_rows,duplicate_html_path_rows
0,0,10,24,0

Duplicated ad_id rows:

,ad_id,ad_url,title,total_price,area_sqm,price_per_sqm,location_raw
35671,1b177868016706713,https://www.imot.bg/obiava-1b177868016706713-p...,"Продава 2-СТАЕН в град София, Люлин 7 - 78 кв....",158000.0,78.0,2025.64,"град София, Люлин 7"
35672,1b177868016706713,https://www.imot.bg/obiava-1b177868016706713-p...,"Продава 2-СТАЕН в град София, Люлин 7 - 78 кв....",158000.0,78.0,2025.64,"град София, Люлин 7"
36483,1b177910832780724,https://www.imot.bg/obiava-1b177910832780724-p...,"Продава 2-СТАЕН в град София, Зона Б-18 - 80 к...",209989.0,80.0,2624.86,"град София, Зона Б-18, ул. Пиротска"
36499,1b177910832780724,https://www.imot.bg/obiava-1b177910832780724-p...,"Продава 2-СТАЕН в град София, Зона Б-18 - 80 к...",209989.0,80.0,2624.86,"град София, Зона Б-18, ул. Пиротска"
40095,1b178056900650253,https://www.imot.bg/obiava-1b178056900650253-p...,"Продава 2-СТАЕН в град Русе, Здравец - 50 кв.м...",98000.0,50.0,1960.00,"град Русе, Здравец"
40123,1b178056900650253,https://www.imot.bg/obiava-1b178056900650253-p...,"Продава 2-СТАЕН в град Русе, Здравец - 50 кв.м...",98000.0,50.0,1960.00,"град Русе, Здравец"
66250,1c177641032363084,https://www.imot.bg/obiava-1c177641032363084-p...,"Продава 3-СТАЕН в град Варна, Виница - 70 кв.м...",155000.0,70.0,2214.29,"град Варна, Виница, АКТ 16!"
66255,1c177641032363084,https://www.imot.bg/obiava-1c177641032363084-p...,"Продава 3-СТАЕН в град Варна, Виница - 70 кв.м...",155000.0,70.0,2214.29,"град Варна, Виница, АКТ 16!"
73678,1c178045319938599,https://www.imot.bg/obiava-1c178045319938599-p...,"Продава 3-СТАЕН в град София, Оборище - 86 кв....",229500.0,86.0,2668.60,"град София, Оборище"
73675,1c178045319938599,https://www.imot.bg/obiava-1c178045319938599-p...,"Продава 3-СТАЕН в град София, Оборище - 86 кв....",229500.0,86.0,2668.60,"град София, Оборище"
74757,1c178091897425060,https://www.imot.bg/obiava-1c178091897425060-p...,"Продава 3-СТАЕН в град Враца, Център - 80 кв.м...",180000.0,80.0,2250.00,"град Враца, Център, Петропавловска"
74776,1c178091897425060,https://www.imot.bg/obiava-1c178091897425060-p...,"Продава 3-СТАЕН в град Враца, Център - 80 кв.м...",180000.0,80.0,2250.00,"град Враца, Център, Петропавловска"
87232,1h178048978769029,https://www.imot.bg/obiava-1h178048978769029-p...,"Продава АТЕЛИЕ, ТАВАН в град София, Център - 2...",155000.0,20.0,7750.00,"град София, Център"
87236,1h178048978769029,https://www.imot.bg/obiava-1h178048978769029-p...,"Продава АТЕЛИЕ, ТАВАН в град София, Център - 2...",155000.0,20.0,7750.00,"град София, Център"
110899,1j177877083437776,https://www.imot.bg/obiava-1j177877083437776-p...,"Продава КЪЩА в област София, с. Алино - 68 кв....",37000.0,68.0,544.12,"област София, с. Алино"
110909,1j177877083437776,https://www.imot.bg/obiava-1j177877083437776-p...,"Продава КЪЩА в област София, с. Алино - 68 кв....",37000.0,68.0,544.12,"област София, с. Алино"
160533,1s173072792235631,https://www.imot.bg/obiava-1s173072792235631-p...,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Х...",27500.0,630.0,43.65,"област Пловдив, с. Храбрино"
160565,1s173072792235631,https://www.imot.bg/obiava-1s173072792235631-p...,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Х...",27500.0,630.0,43.65,"област Пловдив, с. Храбрино"
162134,1s177357537544015,https://www.imot.bg/obiava-1s177357537544015-p...,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Силистра, с. ...",12950.0,NaN,NaN,"област Силистра, с. Ветрен, Царска милост"
162161,1s177357537544015,https://www.imot.bg/obiava-1s177357537544015-p...,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Силистра, с. ...",12950.0,NaN,NaN,"област Силистра, с. Ветрен, Царска милост"

Validity summary:

                        valid_count  invalid_count  valid_pct
has_deal                     164658            324      99.80
has_property_type            164658            324      99.80
has_city                     164658            324      99.80
has_area                     163643           1339      99.19
has_total_price              164664            318      99.81
has_price_per_sqm            163451           1531      99.07
positive_area                163587           1395      99.15
positive_total_price         164664            318      99.81
positive_price_per_sqm       163450           1532      99.07
training_eligible            161438           3544      97.85

First-pass ML candidate rows: 161383
Share of dataset: 97.82 %

Candidate property_type_raw distribution:

                             count    pct
property_type_raw
2-СТАЕН                      33873  20.99
3-СТАЕН                      33672  20.86
ПАРЦЕЛ                       33468  20.74
КЪЩА                         23865  14.79
1-СТАЕН                       6541   4.05
4-СТАЕН                       5276   3.27
МАГАЗИН                       3404   2.11
МНОГОСТАЕН                    3103   1.92
ОФИС                          2377   1.47
ЗЕМЕДЕЛСКА ЗЕМЯ               2254   1.40
ПРОМ. ПОМЕЩЕНИЕ               1976   1.22
ЕТАЖ ОТ КЪЩА                  1848   1.15
ГАРАЖ                         1558   0.97
МЕЗОНЕТ                       1383   0.86
ВИЛА                          1110   0.69
ЗАВЕДЕНИЕ                     1061   0.66
ХОТЕЛ                         1001   0.62
СКЛАД                          753   0.47
ПАРКОМЯСТО                     746   0.46
САМОСТОЯТЕЛНА СГРАДА           480   0.30
ФАБРИКА/ЗАВОД                  251   0.16
ТЪРГОВСКИ КОМПЛЕКС             213   0.13
АТЕЛИЕ, ТАВАН                  198   0.12
ФЕРМА                          148   0.09
ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН    100   0.06
ВИЛНО СЕЛИЩЕ                    97   0.06
ФИТНЕС ЗАЛА                     80   0.05
АВТОСЕРВИЗ                      76   0.05
СОЛАРЕН ПАРК                    64   0.04
КЛИНИКА                         62   0.04
ЛЕКАРСКИ КАБИНЕТ                62   0.04
СПА/СОЛАРНО СТУДИО              41   0.03
БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ       39   0.02
ГАРАЖ, ПАРКОМЯСТО               35   0.02
ДЕТСКИ ЦЕНТЪР                   35   0.02
ДОМ ЗА ВЪЗРАСТНИ ХОРА           31   0.02
СТОМАТОЛОГИЧЕН КАБИНЕТ          29   0.02
БАНКОВ ОФИС                     23   0.01
ПАРКИНГ                         18   0.01
АПТЕКА                          16   0.01
АВТОМИВКА                       10   0.01
ХЛАДИЛЕН СКЛАД                   3   0.00
АКВАПАРК                         2   0.00
ФОТОГРАФСКО СТУДИО               1   0.00

In [10]:
df_ml_base = df_candidate.copy()

print("Rows in df_candidate:", len(df_candidate))
print("Rows in df_ml_base:", len(df_ml_base))

# ------------------------------------------------------------
# Step 2: Target and numeric variable audit
# Uses existing df_candidate from Step 1
# ------------------------------------------------------------



# ------------------------------------------------------------
# Overall numeric distribution
# ------------------------------------------------------------

numeric_cols = [
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title_price_eur",
    "title_area_sqm",
    "views",
    "floor",
    "total_floors",
    "construction_year",
    "features_count",
]

available_numeric_cols = [
    col for col in numeric_cols
    if col in df_ml_base.columns
]

overall_numeric_summary = (
    df_ml_base[available_numeric_cols]
    .describe(percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])
    .T
)

display(overall_numeric_summary)

# ------------------------------------------------------------
# Target distribution by property type
# ------------------------------------------------------------

target_by_property_type = (
    df_ml_base
    .groupby("property_type_raw")
    .agg(
        count=("ad_id", "count"),
        price_median=("total_price", "median"),
        price_p01=("total_price", lambda x: x.quantile(0.01)),
        price_p05=("total_price", lambda x: x.quantile(0.05)),
        price_p95=("total_price", lambda x: x.quantile(0.95)),
        price_p99=("total_price", lambda x: x.quantile(0.99)),
        area_median=("area_sqm", "median"),
        area_p01=("area_sqm", lambda x: x.quantile(0.01)),
        area_p99=("area_sqm", lambda x: x.quantile(0.99)),
        ppm_median=("price_per_sqm", "median"),
        ppm_p01=("price_per_sqm", lambda x: x.quantile(0.01)),
        ppm_p99=("price_per_sqm", lambda x: x.quantile(0.99)),
    )
    .sort_values("count", ascending=False)
)

display(target_by_property_type)

# ------------------------------------------------------------
# Target distribution by city
# ------------------------------------------------------------

target_by_city = (
    df_ml_base
    .groupby("title_city_raw")
    .agg(
        count=("ad_id", "count"),
        price_median=("total_price", "median"),
        price_p05=("total_price", lambda x: x.quantile(0.05)),
        price_p95=("total_price", lambda x: x.quantile(0.95)),
        area_median=("area_sqm", "median"),
        ppm_median=("price_per_sqm", "median"),
        ppm_p05=("price_per_sqm", lambda x: x.quantile(0.05)),
        ppm_p95=("price_per_sqm", lambda x: x.quantile(0.95)),
    )
    .sort_values("count", ascending=False)
)

display(target_by_city.head(30))

# ------------------------------------------------------------
# Suspicious low / high values
# ------------------------------------------------------------

review_cols = [
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]

suspicious_low_price = df_ml_base[
    df_ml_base["total_price"] <= df_ml_base["total_price"].quantile(0.001)
][review_cols]

suspicious_high_price = df_ml_base[
    df_ml_base["total_price"] >= df_ml_base["total_price"].quantile(0.999)
][review_cols]

suspicious_low_ppm = df_ml_base[
    df_ml_base["price_per_sqm"] <= df_ml_base["price_per_sqm"].quantile(0.001)
][review_cols]

suspicious_high_ppm = df_ml_base[
    df_ml_base["price_per_sqm"] >= df_ml_base["price_per_sqm"].quantile(0.999)
][review_cols]

print("Suspicious low price rows:", len(suspicious_low_price))
display(suspicious_low_price.head(20))

print("Suspicious high price rows:", len(suspicious_high_price))
display(suspicious_high_price.head(20))

print("Suspicious low price_per_sqm rows:", len(suspicious_low_ppm))
display(suspicious_low_ppm.head(20))

print("Suspicious high price_per_sqm rows:", len(suspicious_high_ppm))
display(suspicious_high_ppm.head(20))

Rows in df_candidate: 161383
Rows in df_ml_base: 161383

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
total_price,161383.0,257383.501494,2.254996e+06,31.00,8200.00,20700.00,75500.0,134700.0,240000.000,675000.00,2065000.00,4.711950e+08
area_sqm,161383.0,1488.253547,2.177826e+04,0.26,20.00,42.00,73.0,111.0,440.000,5498.90,20000.00,4.854710e+06
price_per_sqm,161383.0,1406.420028,6.180116e+03,0.01,3.84,15.52,330.0,1300.0,1990.735,3205.13,4666.67,1.673833e+06
title_price_eur,157995.0,253524.201380,2.264048e+06,500.00,8436.32,20852.10,75152.0,134027.0,239000.000,660000.00,2000000.00,4.711950e+08
title_area_sqm,159129.0,1419.338600,1.943406e+04,1.00,20.00,42.00,72.0,110.0,394.000,5298.60,19591.84,4.854710e+06
views,161383.0,1573.130162,2.398627e+03,1.00,9.00,48.00,296.0,940.0,1999.000,4983.00,10477.54,1.241930e+05
floor,99857.0,3.176222,2.559464e+00,0.00,0.00,0.00,1.0,3.0,4.000,8.00,12.00,2.500000e+01
total_floors,92202.0,6.112785,3.147519e+00,1.00,1.00,2.00,4.0,6.0,7.000,12.00,18.00,4.000000e+01
construction_year,161383.0,2017.481271,1.714667e+01,1950.00,1960.00,1980.00,2018.0,2026.0,2026.000,2027.00,2028.00,2.049000e+03
features_count,161383.0,2.678213,2.393187e+00,0.00,0.00,0.00,1.0,2.0,4.000,8.00,10.00,3.900000e+01

,count,price_median,price_p01,price_p05,price_p95,price_p99,area_median,area_p01,area_p99,ppm_median,ppm_p01,ppm_p99
property_type_raw,,,,,,,,,,,,
2-СТАЕН,33873,115230.00,48572.0000,64900.0000,239408.40,3.200000e+05,68.0,40.00,125.00,1692.310,741.3464,4380.9968
3-СТАЕН,33672,180000.00,66491.3000,90000.0000,414800.00,6.000000e+05,103.0,60.00,217.00,1785.710,700.0000,4900.9367
ПАРЦЕЛ,33468,80000.00,4777.1600,10737.1300,1060295.00,3.200000e+06,1904.5,278.00,50779.91,44.255,1.4800,1000.0000
КЪЩА,23865,130000.00,8947.6100,17500.0000,700000.00,1.551800e+06,148.0,38.64,1000.00,936.510,60.7104,4400.7812
1-СТАЕН,6541,66000.00,28500.0000,35500.0000,144864.00,1.930606e+05,42.0,20.00,86.00,1577.780,712.7640,4301.2300
4-СТАЕН,5276,279952.50,69000.0000,99900.0000,760250.00,1.250000e+06,141.0,78.75,359.00,1973.675,609.0650,5884.4900
МАГАЗИН,3404,154500.00,12782.8310,30000.0000,899985.00,2.375500e+06,95.0,13.00,1364.55,1700.000,144.0375,7096.1310
МНОГОСТАЕН,3103,291000.00,63600.0000,100000.0000,999998.10,1.557664e+06,157.0,81.02,545.88,1809.520,488.3128,6696.0000
ОФИС,2377,200000.00,18760.0000,35000.0000,1343600.00,4.043200e+06,106.0,15.00,2409.12,1831.670,194.1616,5501.7120
ЗЕМЕДЕЛСКА ЗЕМЯ,2254,50000.00,1331.2000,4000.0000,502414.30,1.818874e+07,1500.0,4.00,41373.99,29.885,0.3706,47911.4431
ПРОМ. ПОМЕЩЕНИЕ,1976,308250.00,19729.4500,44000.0000,2962497.50,6.225000e+06,1099.5,55.75,51200.00,320.000,10.0000,2907.4600
ЕТАЖ ОТ КЪЩА,1848,133000.00,25000.0000,45175.0000,355000.00,5.926500e+05,105.0,42.00,328.48,1204.215,242.2713,3900.0000
ГАРАЖ,1558,30000.00,8102.9819,12782.3000,79913.50,1.641900e+05,21.0,12.00,280.75,1315.790,194.4400,3729.6453
МЕЗОНЕТ,1383,275000.00,65000.0000,98891.9000,799800.00,1.500000e+06,153.0,50.00,505.08,1772.730,583.1438,5057.9314
ВИЛА,1110,53685.65,7182.8357,11845.0000,641000.00,2.782000e+06,70.0,15.00,1118.20,875.000,33.2117,8356.5003
ЗАВЕДЕНИЕ,1061,240000.00,19600.0000,45000.0000,1350000.00,2.140000e+06,211.0,26.60,2500.00,1200.000,85.2840,6000.0000
ХОТЕЛ,1001,800000.00,51129.1900,178952.1600,3937500.00,7.199000e+06,1000.0,165.00,17419.00,840.000,29.6300,3800.0000
СКЛАД,753,305000.00,6895.1200,22394.5820,4000000.00,2.200000e+07,618.0,9.04,35424.00,590.000,15.6088,4390.0500
ПАРКОМЯСТО,746,23000.00,7335.0000,10000.0000,63145.50,1.577500e+05,16.0,11.00,330.00,1283.750,290.6870,3495.6345
САМОСТОЯТЕЛНА СГРАДА,480,420000.00,18555.0000,51427.5000,4500000.00,7.344100e+06,878.5,46.53,9559.75,618.390,16.2512,4190.5046
ФАБРИКА/ЗАВОД,251,766000.00,37450.0000,104500.0000,4002500.00,7.575000e+06,3500.0,159.50,75872.50,191.280,5.4350,2386.4000
ТЪРГОВСКИ КОМПЛЕКС,213,435200.00,19787.7508,45000.0000,5161282.00,1.064000e+07,740.0,53.24,29100.00,619.830,6.4396,4757.6132
"АТЕЛИЕ, ТАВАН",198,89200.00,20438.1296,27764.8500,244354.00,2.973564e+05,50.0,14.88,194.27,1738.615,361.8975,4380.0551
ФЕРМА,148,240000.00,22589.3904,42510.9335,3800000.00,6.740525e+06,5042.5,134.63,108000.00,50.755,5.4894,2346.3860
ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,100,107000.00,23995.0000,40858.1825,555999.05,1.477550e+06,60.0,19.99,409.15,1675.000,464.1119,5155.0975
ВИЛНО СЕЛИЩЕ,97,450000.00,44600.0000,79000.0000,2040000.00,6.010700e+06,2000.0,88.76,65080.00,264.710,6.9588,3437.2848
ФИТНЕС ЗАЛА,80,240000.00,30089.0000,41424.0500,1250000.00,4.833198e+06,240.0,79.58,1600.28,992.425,105.6928,3580.7503
АВТОСЕРВИЗ,76,270500.00,23547.8325,45942.7750,1300000.00,1.825000e+06,370.0,52.00,13227.75,728.360,12.0200,5081.9275
СОЛАРЕН ПАРК,64,127000.00,25585.4762,29000.0000,2535000.00,6.256475e+06,3195.0,183.35,319060.95,50.000,4.2554,528.5370
КЛИНИКА,62,610392.50,61100.0000,98935.4000,1758500.00,2.793940e+06,367.5,62.20,5501.25,1944.445,46.0350,5502.9659
ЛЕКАРСКИ КАБИНЕТ,62,211250.00,25660.0000,59960.0000,1092500.00,2.828600e+06,92.5,24.66,1706.80,2000.000,474.8616,4917.8674
СПА/СОЛАРНО СТУДИО,41,268000.00,36600.0000,57837.0000,1552000.00,2.256000e+06,359.0,44.00,18597.60,945.120,50.4280,3135.2940
БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ,39,260000.00,19803.0000,29095.0000,841500.00,1.825080e+06,2000.0,136.60,7487.62,183.330,7.5768,2395.8610
"ГАРАЖ, ПАРКОМЯСТО",35,15000.00,7102.0000,8990.1850,133850.00,2.145200e+05,20.0,11.34,2718.00,764.710,100.6124,2066.6696
ДЕТСКИ ЦЕНТЪР,35,255000.00,14080.0000,31030.0000,3009000.00,5.200000e+06,192.0,56.70,3524.00,1678.320,22.8408,3013.6342
ДОМ ЗА ВЪЗРАСТНИ ХОРА,31,630000.00,74200.0000,91466.0000,2045000.00,3.220000e+06,1500.0,290.60,9752.50,317.290,37.4870,2875.8630
СТОМАТОЛОГИЧЕН КАБИНЕТ,29,200000.00,69172.0000,82696.0000,1490000.00,2.390000e+06,100.0,25.08,1678.00,1923.080,660.1120,8640.1692
БАНКОВ ОФИС,23,409000.00,64829.6908,85840.0000,2675000.00,2.780000e+06,289.0,71.10,1300.00,1716.870,104.0610,5418.8912
ПАРКИНГ,18,426162.50,17821.9623,45109.8115,2792962.50,3.598592e+06,3909.0,434.00,16173.24,130.405,8.2556,901.8339
АПТЕКА,16,205990.00,71098.5000,79492.5000,869250.00,1.973850e+06,92.5,44.30,304.15,2114.835,399.1060,32627.3625
АВТОМИВКА,10,494999.50,36925.0000,84625.0000,855000.00,8.910000e+05,500.0,198.38,3321.60,615.685,61.1955,1913.7692
ХЛАДИЛЕН СКЛАД,3,361050.00,222821.0000,234105.0000,537945.00,5.536690e+05,373.0,279.90,8043.46,589.810,78.4362,1284.5614
АКВАПАРК,2,5125340.00,229906.8000,629534.0000,9621146.00,1.002077e+07,3638.0,3577.24,3698.76,1432.655,63.0903,2802.2197
ФОТОГРАФСКО СТУДИО,1,148900.00,148900.0000,148900.0000,148900.00,1.489000e+05,123.0,123.00,123.00,1210.570,1210.5700,1210.5700

,count,price_median,price_p05,price_p95,area_median,ppm_median,ppm_p05,ppm_p95
title_city_raw,,,,,,,,
град София,34402,259310.000,79000.0000,1200000.000,114.0,2345.355,72.0840,4388.8755
област Бургас,18177,98000.000,30000.0000,465000.000,86.0,1289.470,15.0000,2309.0680
град Варна,17360,158774.000,53000.0000,579000.000,90.0,1816.785,88.2195,3268.0710
град Пловдив,17136,137854.000,67000.0000,460500.000,92.0,1463.155,160.0900,2597.4075
област Пловдив,7931,100000.000,16280.5000,525000.000,630.0,114.940,7.6150,1730.0100
област София,5041,118000.000,20000.0000,912600.000,735.0,110.000,10.0000,2110.0000
град Бургас,4458,146942.000,32000.0000,494096.000,96.0,1589.995,16.4080,2925.6435
област Велико Търново,3966,45000.000,7943.7650,370000.000,150.0,250.000,5.2550,1277.9025
област Варна,3725,82900.000,15500.0000,550000.000,548.0,193.000,6.9000,1713.4340
град Стара Загора,3483,120000.000,29910.0000,370000.000,100.0,1211.270,29.0010,2010.5300
област Добрич,3460,82000.000,11000.0000,500000.000,165.5,602.180,6.4390,1744.2820
град Русе,3106,108000.000,15700.0000,430675.000,90.0,1234.620,20.3050,2214.1725
град Плевен,2817,119900.000,24800.0000,360000.000,92.0,1304.450,30.0000,2218.1320
област Благоевград,2750,88250.000,25000.0000,537750.000,115.0,926.505,17.9505,1880.4010
град Шумен,2690,120000.000,30000.0000,263000.000,86.0,1450.000,30.0000,2166.6700
област Стара Загора,2099,61355.030,10500.0000,390000.000,343.0,240.620,5.5540,1567.6940
град Велико Търново,2049,134000.000,27000.0000,461600.000,100.0,1336.210,56.0760,2250.0000
област Пазарджик,1964,80000.000,16891.7355,617332.539,312.5,405.485,9.3255,1597.7045
област Габрово,1732,47775.070,8500.0000,348900.000,196.5,281.250,5.1810,1358.8315
област Ловеч,1636,43307.405,6500.0000,402257.625,648.0,92.135,2.9875,1269.0900
област Перник,1616,66467.940,15338.5700,426924.000,300.0,324.935,10.0000,2056.5025
град Кърджали,1319,95000.000,15338.7600,282000.000,108.0,935.460,31.7950,1777.7800
град Перник,1239,120000.000,39027.0000,522725.000,103.0,1199.220,37.9860,2112.0070
област Шумен,1106,43459.810,9203.2500,298750.000,215.0,236.600,5.3575,1393.3675
област Русе,1104,41450.000,7500.0000,359999.850,200.0,242.710,6.2665,1432.7950
област Плевен,1055,40000.000,6646.7900,326200.000,165.0,194.440,4.0440,1256.8190
град Враца,992,116200.000,19955.0000,587992.113,100.0,1194.470,12.7440,2449.1450
област Кюстендил,973,64000.000,11000.0000,555290.036,279.0,271.740,10.0000,1456.2680
област Хасково,854,61355.030,14836.2000,493609.871,138.0,410.395,7.9720,1386.5515
Гърция,842,240000.000,67000.0000,1700000.000,110.0,2439.380,68.8810,5589.8645

Suspicious low price rows: 162

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
9801,1b173616280291614,https://www.imot.bg/obiava-1b173616280291614-p...,2-СТАЕН,град Монтана,"град Монтана, в.з. Запад, язовир ,, Огоста''",1400.00,85.0,16.47,"Продава 2-СТАЕН в град Монтана, в.з. Запад - 8..."
81864,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.00,1.0,950.00,"Продава МНОГОСТАЕН в град Кърджали, Център - 1..."
91274,1j169322678528539,https://www.imot.bg/obiava-1j169322678528539-p...,КЪЩА,област Кърджали,"област Кърджали, с. Срединка",55.00,200.0,0.28,"Продава КЪЩА в област Кърджали, с. Срединка - ..."
92461,1j171319088818131,https://www.imot.bg/obiava-1j171319088818131-p...,КЪЩА,област Добрич,"област Добрич, с. Краище",2300.81,70.0,32.87,"Продава КЪЩА в област Добрич, с. Краище - 70 к..."
125411,1r119770677083487,https://www.imot.bg/obiava-1r119770677083487-p...,ПАРЦЕЛ,област Плевен,"област Плевен, с. Ореховица",2045.17,1060.0,1.93,"Продава ПАРЦЕЛ в област Плевен, с. Ореховица -..."
125712,1r129836973937027,https://www.imot.bg/obiava-1r129836973937027-p...,ПАРЦЕЛ,град София,"град София, Бъкстон",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м ..."
125713,1r129837016910336,https://www.imot.bg/obiava-1r129837016910336-p...,ПАРЦЕЛ,град София,"град София, Изток",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / ..."
125714,1r129836999298495,https://www.imot.bg/obiava-1r129836999298495-p...,ПАРЦЕЛ,град София,"град София, Манастирски ливади",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Манастирски ливад..."
125716,1r129837027077889,https://www.imot.bg/obiava-1r129837027077889-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
125738,1r129837078094806,https://www.imot.bg/obiava-1r129837078094806-p...,ПАРЦЕЛ,град София,"град София, Борово",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
125743,1r129837036109746,https://www.imot.bg/obiava-1r129837036109746-p...,ПАРЦЕЛ,град София,"град София, Павлово",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м ..."
126070,1r140187131835609,https://www.imot.bg/obiava-1r140187131835609-p...,ПАРЦЕЛ,град София,"град София, Редута",1000.00,400.0,2.50,"Продава ПАРЦЕЛ в град София, Редута - 400 кв.м..."
126682,1r151023473457367,https://www.imot.bg/obiava-1r151023473457367-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, с. Пчелище",2300.81,4420.0,0.52,"Продава ПАРЦЕЛ в област Велико Търново, с. Пче..."
127041,1r154462348986606,https://www.imot.bg/obiava-1r154462348986606-p...,ПАРЦЕЛ,град Велико Търново,"град Велико Търново, Промишлена зона - Запад",1234.00,3000.0,0.41,"Продава ПАРЦЕЛ в град Велико Търново, Промишле..."
127219,1r155661113661224,https://www.imot.bg/obiava-1r155661113661224-p...,ПАРЦЕЛ,област Силистра,"област Силистра, с. Каменци",2300.81,2600.0,0.88,"Продава ПАРЦЕЛ в област Силистра, с. Каменци -..."
128049,1r160526162464092,https://www.imot.bg/obiava-1r160526162464092-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Бежаново",2200.00,618.0,3.56,"Продава ПАРЦЕЛ в област Ловеч, с. Бежаново - 6..."
129117,1r164322566448704,https://www.imot.bg/obiava-1r164322566448704-p...,ПАРЦЕЛ,град Ямбол,"град Ямбол, Промишлена зона",1738.39,548.0,3.17,"Продава ПАРЦЕЛ в град Ямбол, Промишлена зона -..."
129280,1r164614155136903,https://www.imot.bg/obiava-1r164614155136903-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1500.00,5000.0,0.30,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."
129282,1r164614436553901,https://www.imot.bg/obiava-1r164614436553901-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Кърпачево",1000.00,1500.0,0.67,"Продава ПАРЦЕЛ в област Ловеч, с. Кърпачево - ..."
129301,1r164614174065380,https://www.imot.bg/obiava-1r164614174065380-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1600.00,5600.0,0.29,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."

Suspicious high price rows: 162

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
85234,1g173470575981747,https://www.imot.bg/obiava-1g173470575981747-p...,ОФИС,град София,"град София, Гоце Делчев",15000000.0,9000.0,1666.67,"Продава ОФИС в град София, Гоце Делчев - 9000 ..."
85418,1g174699117198253,https://www.imot.bg/obiava-1g174699117198253-p...,ОФИС,град София,"град София, Център",16800000.0,6000.0,2800.00,"Продава ОФИС в град София, Център - 6000 кв.м ..."
85419,1g174699202740588,https://www.imot.bg/obiava-1g174699202740588-p...,ОФИС,град София,"град София, Център",16800000.0,6000.0,2800.00,"Продава ОФИС в град София, Център - 6000 кв.м ..."
85440,1g174776979932737,https://www.imot.bg/obiava-1g174776979932737-p...,ОФИС,град София,"град София, Център, бул. Витоша",8500000.0,3200.0,2656.25,"Продава ОФИС в град София, Център - 3200 кв.м ..."
86261,1g177133995357205,https://www.imot.bg/obiava-1g177133995357205-p...,ОФИС,град София,"град София, Център, бул. Тодор Александров",10500000.0,6500.0,1615.38,"Продава ОФИС в град София, Център - 6500 кв.м ..."
92238,1j171086779696897,https://www.imot.bg/obiava-1j171086779696897-p...,КЪЩА,град София,"град София, Бояна",8000000.0,1040.0,7692.31,"Продава КЪЩА в град София, Бояна - 1040 кв.м /..."
99109,1j175630317787949,https://www.imot.bg/obiava-1j175630317787949-p...,КЪЩА,област Бургас,"област Бургас, с. Равда",10000000.0,1000.0,10000.00,"Продава КЪЩА в област Бургас, с. Равда - 1000 ..."
104243,1j176941336469721,https://www.imot.bg/obiava-1j176941336469721-p...,КЪЩА,град София,"град София, м-т Камбаните",15500000.0,2000.0,7750.00,"Продава КЪЩА в град София, м-т Камбаните - 200..."
104261,1j176949856360345,https://www.imot.bg/obiava-1j176949856360345-p...,КЪЩА,град София,"град София, гр. Банкя",22995000.0,5199.0,4422.97,"Продава КЪЩА в град София, гр. Банкя - 5199 кв..."
112463,1j178025669385878,https://www.imot.bg/obiava-1j178025669385878-p...,КЪЩА,град София,"град София, Център",7500000.0,950.0,7894.74,"Продава КЪЩА в град София, Център - 950 кв.м /..."
113715,1k171984522416868,https://www.imot.bg/obiava-1k171984522416868-p...,ВИЛА,Гърция,"Гърция, Халкидики",17500000.0,1000.0,17500.00,"Продава ВИЛА в Гърция, Халкидики - 1000 кв.м /..."
113718,1k171984525859775,https://www.imot.bg/obiava-1k171984525859775-p...,ВИЛА,Гърция,"Гърция, Халкидики",12000000.0,1000.0,12000.00,"Продава ВИЛА в Гърция, Халкидики - 1000 кв.м /..."
114667,1l141050030858795,https://www.imot.bg/obiava-1l141050030858795-p...,МАГАЗИН,град Ловеч,"град Ловеч, Център",12500000.0,2500.0,5000.00,"Продава МАГАЗИН в град Ловеч, Център - 2500 кв..."
119274,1n168233966358888,https://www.imot.bg/obiava-1n168233966358888-p...,СКЛАД,област София,"област София, гр. Елин Пелин",8850000.0,8450.0,1047.34,"Продава СКЛАД в област София, гр. Елин Пелин -..."
119291,1n170480055370411,https://www.imot.bg/obiava-1n170480055370411-p...,СКЛАД,град София,"град София, Център, пл. Сточна гара",12000000.0,7373.0,1627.56,"Продава СКЛАД в град София, Център - 7373 кв.м..."
119409,1n173797586240382,https://www.imot.bg/obiava-1n173797586240382-p...,СКЛАД,област София,"област София, гр. Елин Пелин",22000000.0,3258.0,6752.61,"Продава СКЛАД в област София, гр. Елин Пелин -..."
119418,1n173749402091719,https://www.imot.bg/obiava-1n173749402091719-p...,СКЛАД,област София,"област София, с. Гара Елин Пелин",22000000.0,3258.0,6752.61,"Продава СКЛАД в област София, с. Гара Елин Пел..."
119427,1n173815085615503,https://www.imot.bg/obiava-1n173815085615503-p...,СКЛАД,град Русе,"град Русе, Промишлена зона - Запад",7500000.0,31200.0,240.38,"Продава СКЛАД в град Русе, Промишлена зона - З..."
119445,1n174297984628158,https://www.imot.bg/obiava-1n174297984628158-p...,СКЛАД,област София,"област София, с. Столник",22000000.0,65455.0,336.11,"Продава СКЛАД в област София, с. Столник - 654..."
119472,1n174593519780244,https://www.imot.bg/obiava-1n174593519780244-p...,СКЛАД,област София,"област София, гр. Елин Пелин, Гара Елин Пелин",22000000.0,3258.0,6752.61,"Продава СКЛАД в област София, гр. Елин Пелин -..."

Suspicious low price_per_sqm rows: 163

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
89095,1i178074574794884,https://www.imot.bg/obiava-1i178074574794884-p...,ЕТАЖ ОТ КЪЩА,град Хасково,"град Хасково, Македонски",85000.00,120000.0,0.71,"Продава ЕТАЖ ОТ КЪЩА в град Хасково, Македонск..."
91274,1j169322678528539,https://www.imot.bg/obiava-1j169322678528539-p...,КЪЩА,област Кърджали,"област Кърджали, с. Срединка",55.00,200.0,0.28,"Продава КЪЩА в област Кърджали, с. Срединка - ..."
120964,1o176373075998653,https://www.imot.bg/obiava-1o176373075998653-p...,ПАРКОМЯСТО,град Варна,"град Варна, Виница",16000.00,1000000.0,0.02,"Продава ПАРКОМЯСТО в град Варна, Виница - 1000..."
126682,1r151023473457367,https://www.imot.bg/obiava-1r151023473457367-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, с. Пчелище",2300.81,4420.0,0.52,"Продава ПАРЦЕЛ в област Велико Търново, с. Пче..."
126683,1r151066590726245,https://www.imot.bg/obiava-1r151066590726245-p...,ПАРЦЕЛ,област София,"област София, гр. Елин Пелин, м. Соленико",120000.00,1031000.0,0.12,"Продава ПАРЦЕЛ в област София, гр. Елин Пелин ..."
126688,1r151119773445530,https://www.imot.bg/obiava-1r151119773445530-p...,ПАРЦЕЛ,област София,"област София, с. Караполци, м. Копанината",35050.00,345732.0,0.10,"Продава ПАРЦЕЛ в област София, с. Караполци - ..."
126694,1r151197862312006,https://www.imot.bg/obiava-1r151197862312006-p...,ПАРЦЕЛ,област Враца,"област Враца, гр. Бяла Слатина",8000.00,91000.0,0.09,"Продава ПАРЦЕЛ в област Враца, гр. Бяла Слатин..."
126804,1r152276705539618,https://www.imot.bg/obiava-1r152276705539618-p...,ПАРЦЕЛ,град Ловеч,"град Ловеч, Промишлена зона, Баховско шосе",11000.00,30000.0,0.37,"Продава ПАРЦЕЛ в град Ловеч, Промишлена зона -..."
127009,1r153992249301189,https://www.imot.bg/obiava-1r153992249301189-p...,ПАРЦЕЛ,област Ямбол,"област Ямбол, с. Савино",8500.00,20850.0,0.41,"Продава ПАРЦЕЛ в област Ямбол, с. Савино - 208..."
127041,1r154462348986606,https://www.imot.bg/obiava-1r154462348986606-p...,ПАРЦЕЛ,град Велико Търново,"град Велико Търново, Промишлена зона - Запад",1234.00,3000.0,0.41,"Продава ПАРЦЕЛ в град Велико Търново, Промишле..."
127210,1r155688330519275,https://www.imot.bg/obiava-1r155688330519275-p...,ПАРЦЕЛ,област Перник,"област Перник, с. Кралев дол",30000.00,200000.0,0.15,"Продава ПАРЦЕЛ в област Перник, с. Кралев дол ..."
127382,1r156829059149246,https://www.imot.bg/obiava-1r156829059149246-p...,ПАРЦЕЛ,област Добрич,"област Добрич, гр. Балчик, фиш-фиш",40000.00,94000.0,0.43,"Продава ПАРЦЕЛ в област Добрич, гр. Балчик - 9..."
128076,1r160639737234969,https://www.imot.bg/obiava-1r160639737234969-p...,ПАРЦЕЛ,област Добрич,"област Добрич, гр. Каварна, С.Божурец",25000.00,68116.0,0.37,"Продава ПАРЦЕЛ в област Добрич, гр. Каварна - ..."
128462,1r162263913439041,https://www.imot.bg/obiava-1r162263913439041-p...,ПАРЦЕЛ,област Шумен,"област Шумен, гр. Нови пазар",14000.00,33000.0,0.42,"Продава ПАРЦЕЛ в област Шумен, гр. Нови пазар ..."
128585,1r162728761839736,https://www.imot.bg/obiava-1r162728761839736-p...,ПАРЦЕЛ,област Хасково,"област Хасково, гр. Любимец, Йерусалимово",15000.00,25000.0,0.60,"Продава ПАРЦЕЛ в област Хасково, гр. Любимец -..."
128831,1r163550574890576,https://www.imot.bg/obiava-1r163550574890576-p...,ПАРЦЕЛ,град Бургас,"град Бургас, Банево",20000.00,40000.0,0.50,"Продава ПАРЦЕЛ в град Бургас, Банево - 40000 к..."
129205,1r164466204982974,https://www.imot.bg/obiava-1r164466204982974-p...,ПАРЦЕЛ,област Габрово,"област Габрово, гр. Дряново",25411.21,83935.0,0.30,"Продава ПАРЦЕЛ в област Габрово, гр. Дряново -..."
129219,1r164457233746463,https://www.imot.bg/obiava-1r164457233746463-p...,ПАРЦЕЛ,област Русе,"област Русе, с. Иваново, Стрелбище",6500.00,9500.0,0.68,"Продава ПАРЦЕЛ в област Русе, с. Иваново - 950..."
129279,1r164613796043510,https://www.imot.bg/obiava-1r164613796043510-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Тепава",2556.46,10005.0,0.26,"Продава ПАРЦЕЛ в област Ловеч, с. Тепава - 100..."
129280,1r164614155136903,https://www.imot.bg/obiava-1r164614155136903-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1500.00,5000.0,0.30,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."

Suspicious high price_per_sqm rows: 163

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
64,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",89500.0,1.0,89500.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
7728,1b169623222441373,https://www.imot.bg/obiava-1b169623222441373-p...,2-СТАЕН,град София,"град София, Център, ул. Московска",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
28568,1b177426474262322,https://www.imot.bg/obiava-1b177426474262322-p...,2-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
32238,1b177678862962152,https://www.imot.bg/obiava-1b177678862962152-p...,2-СТАЕН,град София,"град София, Център",550000.0,59.0,9322.03,"Продава 2-СТАЕН в град София, Център - 59 кв.м..."
38906,1b178025803445406,https://www.imot.bg/obiava-1b178025803445406-p...,2-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
44112,1c172839456370807,https://www.imot.bg/obiava-1c172839456370807-p...,3-СТАЕН,град Варна,"град Варна, Център, ОБЩИНАТА",1200000.0,90.0,13333.33,"Продава 3-СТАЕН в град Варна, Център - 90 кв.м..."
45348,1c173834640237899,https://www.imot.bg/obiava-1c173834640237899-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
46154,1c174196381828349,https://www.imot.bg/obiava-1c174196381828349-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
48440,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",125220.0,1.0,125220.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
53106,1c176150505544467,https://www.imot.bg/obiava-1c176150505544467-p...,3-СТАЕН,град Варна,"град Варна, Център, Над Ритуална зала",1200000.0,100.0,12000.00,"Продава 3-СТАЕН в град Варна, Център - 100 кв...."
55877,1c176537220648919,https://www.imot.bg/obiava-1c176537220648919-p...,3-СТАЕН,град София,"град София, Център",1300000.0,120.0,10833.33,"Продава 3-СТАЕН в град София, Център - 120 кв...."
60110,1c177114417060072,https://www.imot.bg/obiava-1c177114417060072-p...,3-СТАЕН,град София,"град София, Докторски паметник",749000.0,80.0,9362.50,"Продава 3-СТАЕН в град София, Докторски паметн..."
62515,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",113000.0,1.0,113000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
62516,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
62614,1c177332627033073,https://www.imot.bg/obiava-1c177332627033073-p...,3-СТАЕН,град София,"град София, Център, ул. Съборна",970000.0,95.0,10210.53,"Продава 3-СТАЕН в град София, Център - 95 кв.м..."
64761,1c177504230745497,https://www.imot.bg/obiava-1c177504230745497-p...,3-СТАЕН,град София,"град София, Център",1300000.0,140.0,9285.71,"Продава 3-СТАЕН в град София, Център - 140 кв...."
69497,1c177858126583960,https://www.imot.bg/obiava-1c177858126583960-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
72983,1c178025854324607,https://www.imot.bg/obiava-1c178025854324607-p...,3-СТАЕН,град София,"град София, Оборище",1000000.0,110.0,9090.91,"Продава 3-СТАЕН в град София, Оборище - 110 кв..."
74626,1c178084235219273,https://www.imot.bg/obiava-1c178084235219273-p...,3-СТАЕН,град София,"град София, Надежда 4",900000.0,97.0,9278.35,"Продава 3-СТАЕН в град София, Надежда 4 - 97 к..."
75918,1d174774986717357,https://www.imot.bg/obiava-1d174774986717357-p...,4-СТАЕН,град София,"град София, Докторски паметник",1260000.0,140.0,9000.00,"Продава 4-СТАЕН в град София, Докторски паметн..."

In [11]:
MIN_AREA_BY_PROPERTY_TYPE = {
    "1-СТАЕН": 15,
    "2-СТАЕН": 25,
    "3-СТАЕН": 35,
    "4-СТАЕН": 45,
    "МНОГОСТАЕН": 50,
    "МЕЗОНЕТ": 40,
    "АТЕЛИЕ, ТАВАН": 10,
    "КЪЩА": 25,
    "ЕТАЖ ОТ КЪЩА": 25,
    "ВИЛА": 20,
    "ГАРАЖ": 8,
    "ПАРКОМЯСТО": 8,
    "МАГАЗИН": 5,
    "ОФИС": 5,
    "СКЛАД": 5,
    "ПАРЦЕЛ": 50,
    "ЗЕМЕДЕЛСКА ЗЕМЯ": 100,
}

df_ml_base["min_reasonable_area"] = (
    df_ml_base["property_type_raw"]
    .map(MIN_AREA_BY_PROPERTY_TYPE)
)

df_ml_base["suspicious_area_too_small"] = (
    df_ml_base["min_reasonable_area"].notna()
    & (df_ml_base["area_sqm"] < df_ml_base["min_reasonable_area"])
)

small_area_review = df_ml_base[
    df_ml_base["suspicious_area_too_small"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(["property_type_raw", "area_sqm"])

print("Suspicious too-small area rows:", len(small_area_review))
display(small_area_review.head(50))

Suspicious too-small area rows: 358

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
64,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",89500.00,1.0,89500.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
873,1a174617120400088,https://www.imot.bg/obiava-1a174617120400088-p...,1-СТАЕН,град Варна,"град Варна, Център",39500.00,10.0,3950.00,"Продава 1-СТАЕН в град Варна, Център - 10 кв.м..."
898,1a174720940537891,https://www.imot.bg/obiava-1a174720940537891-p...,1-СТАЕН,град Варна,"град Варна, Гръцка махала, ФК",31490.00,10.0,3149.00,"Продава 1-СТАЕН в град Варна, Гръцка махала - ..."
5039,1a177762783253610,https://www.imot.bg/obiava-1a177762783253610-p...,1-СТАЕН,град Варна,"град Варна, Христо Ботев, ул.Тодор Влайков",29900.00,10.0,2990.00,"Продава 1-СТАЕН в град Варна, Христо Ботев - 1..."
5040,1a177762750182371,https://www.imot.bg/obiava-1a177762750182371-p...,1-СТАЕН,град Варна,"град Варна, Левски 2, ул.Емануил Манолов",34900.00,10.0,3490.00,"Продава 1-СТАЕН в град Варна, Левски 2 - 10 кв..."
5234,1a177822677766997,https://www.imot.bg/obiava-1a177822677766997-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар",23000.00,11.0,2090.91,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
2883,1a176952090948960,https://www.imot.bg/obiava-1a176952090948960-p...,1-СТАЕН,област Бургас,"област Бургас, к.к. Слънчев бряг",24000.00,12.0,2000.00,"Продава 1-СТАЕН в област Бургас, к.к. Слънчев ..."
5062,1a177762644247321,https://www.imot.bg/obiava-1a177762644247321-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар, ул.Стоенчо Хаджи И...",34900.00,12.0,2908.33,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
4626,1a177667102639011,https://www.imot.bg/obiava-1a177667102639011-p...,1-СТАЕН,град София,"град София, Стрелбище",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Стрелбище - 13 к..."
4651,1a177667142731690,https://www.imot.bg/obiava-1a177667142731690-p...,1-СТАЕН,град София,"град София, Иван Вазов",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Иван Вазов - 13 ..."
11729,1b174712395287055,https://www.imot.bg/obiava-1b174712395287055-p...,2-СТАЕН,град Бургас,"град Бургас, Център",16500.00,14.0,1178.57,"Продава 2-СТАЕН в град Бургас, Център - 14 кв...."
48440,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",125220.00,1.0,125220.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
62515,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",113000.00,1.0,113000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
62516,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.00,1.0,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
114086,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.00,1.0,310000.00,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
114494,1k177830949732411,https://www.imot.bg/obiava-1k177830949732411-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",27000.00,9.0,3000.00,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113877,1k174238436132860,https://www.imot.bg/obiava-1k174238436132860-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",11248.42,10.0,1124.84,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
113905,1k174589655796135,https://www.imot.bg/obiava-1k174589655796135-p...,ВИЛА,град Русе,"град Русе, в.з. Кулата",20000.00,10.0,2000.00,"Продава ВИЛА в град Русе, в.з. Кулата - 10 кв...."
113629,1k170487729767222,https://www.imot.bg/obiava-1k170487729767222-p...,ВИЛА,област Габрово,"област Габрово, с. Борики",9700.00,12.0,808.33,"Продава ВИЛА в област Габрово, с. Борики - 12 ..."
114522,1k177874594569087,https://www.imot.bg/obiava-1k177874594569087-p...,ВИЛА,област Хасково,"област Хасково, с. Минерални бани",38000.00,12.0,3166.67,"Продава ВИЛА в област Хасково, с. Минерални ба..."
114263,1k176790178804201,https://www.imot.bg/obiava-1k176790178804201-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",48000.00,13.0,3692.31,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
113486,1k159187372423967,https://www.imot.bg/obiava-1k159187372423967-p...,ВИЛА,град Добрич,"град Добрич, в.з. Лозята",9714.55,14.0,693.90,"Продава ВИЛА в град Добрич, в.з. Лозята - 14 к..."
113812,1k173381990962779,https://www.imot.bg/obiava-1k173381990962779-p...,ВИЛА,град Търговище,"град Търговище, Вилна зона, Чокя",15338.76,14.0,1095.63,"Продава ВИЛА в град Търговище, Вилна зона - 14..."
114225,1k176556804152396,https://www.imot.bg/obiava-1k176556804152396-p...,ВИЛА,област Варна,"област Варна, с. Бенковски",23000.00,14.0,1642.86,"Продава ВИЛА в област Варна, с. Бенковски - 14..."
114230,1k176608838752786,https://www.imot.bg/obiava-1k176608838752786-p...,ВИЛА,град Добрич,"град Добрич, м-т Газибаба, алмалии",9200.00,14.0,657.14,"Продава ВИЛА в град Добрич, м-т Газибаба - 14 ..."
113588,1k166902483080379,https://www.imot.bg/obiava-1k166902483080379-p...,ВИЛА,град Русе,"град Русе, Долапите",5880.00,15.0,392.00,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
113623,1k170238482982981,https://www.imot.bg/obiava-1k170238482982981-p...,ВИЛА,град Русе,"град Русе, Долапите, 10-ти км",6391.15,15.0,426.08,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
113687,1k171153091465916,https://www.imot.bg/obiava-1k171153091465916-p...,ВИЛА,област Варна,"област Варна, с. Осеново",35000.00,15.0,2333.33,"Продава ВИЛА в област Варна, с. Осеново - 15 к..."
113815,1k173617831600509,https://www.imot.bg/obiava-1k173617831600509-p...,ВИЛА,град Плевен,"град Плевен, м-т Мъртва долина",5624.21,15.0,374.95,"Продава ВИЛА в град Плевен, м-т Мъртва долина ..."
113827,1k173771669891059,https://www.imot.bg/obiava-1k173771669891059-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",28990.25,15.0,1932.68,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113864,1k174285800592432,https://www.imot.bg/obiava-1k174285800592432-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",22000.00,15.0,1466.67,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113884,1k174360336907458,https://www.imot.bg/obiava-1k174360336907458-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",21500.00,15.0,1433.33,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113911,1k174697906929015,https://www.imot.bg/obiava-1k174697906929015-p...,ВИЛА,област Бургас,"област Бургас, с. Росен",26000.00,15.0,1733.33,"Продава ВИЛА в област Бургас, с. Росен - 15 кв..."
113993,1k175206432515505,https://www.imot.bg/obiava-1k175206432515505-p...,ВИЛА,област Русе,"област Русе, с. Пиргово",32000.00,15.0,2133.33,"Продава ВИЛА в област Русе, с. Пиргово - 15 кв..."
114313,1k177089513661784,https://www.imot.bg/obiava-1k177089513661784-p...,ВИЛА,област Търговище,"област Търговище, с. Разбойна, Серсема",33233.00,15.0,2215.53,"Продава ВИЛА в област Търговище, с. Разбойна -..."
114335,1k177306035384054,https://www.imot.bg/obiava-1k177306035384054-p...,ВИЛА,област Габрово,"област Габрово, с. Чукилите",14000.00,15.0,933.33,"Продава ВИЛА в област Габрово, с. Чукилите - 1..."
114574,1k178005241360877,https://www.imot.bg/obiava-1k178005241360877-p...,ВИЛА,област Бургас,"област Бургас, гр. Царево",115000.00,15.0,7666.67,"Продава ВИЛА в област Бургас, гр. Царево - 15 ..."
114591,1k178015236451071,https://www.imot.bg/obiava-1k178015236451071-p...,ВИЛА,област Перник,"област Перник, с. Поцърненци",40000.00,15.0,2666.67,"Продава ВИЛА в област Перник, с. Поцърненци - ..."
113560,1k165349073718160,https://www.imot.bg/obiava-1k165349073718160-p...,ВИЛА,област София,"област София, с. Свидня",14000.00,16.0,875.00,"Продава ВИЛА в област София, с. Свидня - 16 кв..."
113582,1k168630218456890,https://www.imot.bg/obiava-1k168630218456890-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",31000.00,16.0,1937.50,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113795,1k173131358442876,https://www.imot.bg/obiava-1k173131358442876-p...,ВИЛА,град Русе,"град Русе, в.з. Липака",10225.84,16.0,639.12,"Продава ВИЛА в град Русе, в.з. Липака - 16 кв...."
113796,1k173131452046414,https://www.imot.bg/obiava-1k173131452046414-p...,ВИЛА,област Русе,"област Русе, с. Николово",10225.84,16.0,639.12,"Продава ВИЛА в област Русе, с. Николово - 16 к..."
114624,1k178085536057395,https://www.imot.bg/obiava-1k178085536057395-p...,ВИЛА,област Пазарджик,"област Пазарджик, м-т Цигов чарк",29000.00,16.0,1812.50,"Продава ВИЛА в област Пазарджик, м-т Цигов чар..."
113889,1k174471450262174,https://www.imot.bg/obiava-1k174471450262174-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Крушевски баир",12271.01,17.0,721.82,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
114439,1k177592015889825,https://www.imot.bg/obiava-1k177592015889825-p...,ВИЛА,град Враца,"град Враца, Студентски град, Врачански лозя",15300.00,17.0,900.00,"Продава ВИЛА в град Враца, Студентски град - 1..."
113516,1k163422905045659,https://www.imot.bg/obiava-1k163422905045659-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",10225.84,18.0,568.10,"Продава ВИЛА в град Разград, Промишлена зона -..."
113559,1k166936354732929,https://www.imot.bg/obiava-1k166936354732929-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Севлиевски лозя",10225.84,18.0,568.10,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
113611,1k169877165462335,https://www.imot.bg/obiava-1k169877165462335-p...,ВИЛА,област София,"област София, с. Владо Тричков, Ромча",18000.00,18.0,1000.00,"Продава ВИЛА в област София, с. Владо Тричков ..."
114102,1k175922288191828,https://www.imot.bg/obiava-1k175922288191828-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",42437.23,18.0,2357.62,"Продава ВИЛА в град Разград, Промишлена зона -..."
114328,1k177194253564731,https://www.imot.bg/obiava-1k177194253564731-p...,ВИЛА,град Враца,"град Враца, Студентски град, м-ст Череша",9000.00,18.0,500.00,"Продава ВИЛА в град Враца, Студентски град - 1..."

In [12]:
# ------------------------------------------------------------
# Step 2B: Further filter the 338 suspicious area candidates
# using price_per_sqm
# ------------------------------------------------------------

# Replace this with the actual name of your 338-row dataframe if different
area_suspicious_df = small_area_review.copy()

print("Starting suspicious area candidates:", len(area_suspicious_df))


# ------------------------------------------------------------
# 1. Add a practical top price-per-sqm flag
# ------------------------------------------------------------

# These are review thresholds, not final ML rules.
# Keep them intentionally simple for now.

area_suspicious_df["very_high_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 10_000
)

area_suspicious_df["extreme_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 25_000
)

area_suspicious_df["absurd_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 50_000
)


# ------------------------------------------------------------
# 2. Add combined drop candidate logic
# ------------------------------------------------------------

area_suspicious_df["likely_bad_area_or_price"] = (
    (area_suspicious_df["area_sqm"] <= 2)
    | (
        (area_suspicious_df["area_sqm"] <= 10)
        & (area_suspicious_df["price_per_sqm"] >= 10_000)
    )
    | (area_suspicious_df["price_per_sqm"] >= 50_000)
)


# ------------------------------------------------------------
# 3. Inspect the strongest drop candidates first
# ------------------------------------------------------------

drop_review = area_suspicious_df[
    area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["price_per_sqm", "area_sqm"],
    ascending=[False, True]
)

print("Likely bad rows from the 338 candidates:", len(drop_review))
display(drop_review.head(100))


# ------------------------------------------------------------
# 4. Inspect borderline candidates separately
# ------------------------------------------------------------

borderline_review = area_suspicious_df[
    ~area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["area_sqm", "price_per_sqm"],
    ascending=[True, False]
)

print("Borderline rows still needing manual review:", len(borderline_review))
display(borderline_review.head(100))

Starting suspicious area candidates: 358
Likely bad rows from the 338 candidates: 53

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
131508,1r168321569073352,https://www.imot.bg/obiava-1r168321569073352-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, гр. Карлово",680000.00,1.000,680000.00,"Продава ПАРЦЕЛ в област Пловдив, гр. Карлово -..."
161780,1s176771053368590,https://www.imot.bg/obiava-1s176771053368590-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, гр. Кюстендил, Въртешево",48000000.00,72.000,666666.67,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр..."
135154,1r171576942411245,https://www.imot.bg/obiava-1r171576942411245-p...,ПАРЦЕЛ,област Благоевград,"област Благоевград, гр. Гоце Делчев, Местност ...",480000.00,1.000,480000.00,"Продава ПАРЦЕЛ в област Благоевград, гр. Гоце ..."
114086,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.00,1.000,310000.00,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
160994,1s174472213814965,https://www.imot.bg/obiava-1s174472213814965-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Баня",300000.00,1.000,300000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
62516,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.00,1.000,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
160568,1s173082154774113,https://www.imot.bg/obiava-1s173082154774113-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Войводиново",140000.00,1.000,140000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. В..."
48440,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",125220.00,1.000,125220.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
62515,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",113000.00,1.000,113000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
160999,1s174472241896851,https://www.imot.bg/obiava-1s174472241896851-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Резово",500000.00,5.139,97295.19,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ре..."
64,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",89500.00,1.000,89500.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
160519,1s172983627962992,https://www.imot.bg/obiava-1s172983627962992-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Банско, 'Овиначе'",521280.00,6.516,80000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
162255,1s177486195173601,https://www.imot.bg/obiava-1s177486195173601-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Сандански, Долна Граде...",1616000.00,24.327,66428.25,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
94039,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-p...,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",62000.00,1.000,62000.00,"Продава КЪЩА в област Пазарджик, гр. Септември..."
136460,1r172269115424343,https://www.imot.bg/obiava-1r172269115424343-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, гр. Карлово",680000.00,11.000,61818.18,"Продава ПАРЦЕЛ в област Пловдив, гр. Карлово -..."
81877,1e176876794712573,https://www.imot.bg/obiava-1e176876794712573-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Гледка",58450.00,1.000,58450.00,"Продава МНОГОСТАЕН в град Кърджали, Гледка - 1..."
161599,1s176287027588136,https://www.imot.bg/obiava-1s176287027588136-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костинброд, С. Безден",15000.00,0.260,57692.31,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
151613,1r176876865288529,https://www.imot.bg/obiava-1r176876865288529-p...,ПАРЦЕЛ,област Кърджали,"област Кърджали, с. Глухар",51130.00,1.000,51130.00,"Продава ПАРЦЕЛ в област Кърджали, с. Глухар - ..."
159834,1s168018942420237,https://www.imot.bg/obiava-1s168018942420237-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Добрич,"област Добрич, с. Ваклино",195000.00,4.000,48750.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, с. Ва..."
161406,1s175750711879706,https://www.imot.bg/obiava-1s175750711879706-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Брестник",129500.00,2.699,47980.73,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
161978,1s177149004657663,https://www.imot.bg/obiava-1s177149004657663-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Трояново",95700.00,2.000,47850.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Тр..."
161013,1s174472234785072,https://www.imot.bg/obiava-1s174472234785072-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Поморие",156280.00,3.907,40000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. П..."
161108,1s174703244961240,https://www.imot.bg/obiava-1s174703244961240-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костинброд",35000.00,1.000,35000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
159674,1s165779817079118,https://www.imot.bg/obiava-1s165779817079118-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Елин Пелин",131250.00,5.250,25000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ел..."
161191,1s175007382745819,https://www.imot.bg/obiava-1s175007382745819-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Маринка",24500.00,1.000,24500.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ма..."
160988,1s174472219289049,https://www.imot.bg/obiava-1s174472219289049-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Жиленци",24000.00,1.000,24000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
161104,1s174677671762908,https://www.imot.bg/obiava-1s174677671762908-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Разлог",49500.00,2.302,21503.04,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
162361,1s177685190752057,https://www.imot.bg/obiava-1s177685190752057-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Перник,"област Перник, с. Стефаново",43000.00,2.000,21500.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Перник, с. Ст..."
161219,1s175074737372727,https://www.imot.bg/obiava-1s175074737372727-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Първенец",88200.00,4.410,20000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. П..."
161981,1s177151989937075,https://www.imot.bg/obiava-1s177151989937075-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Калековец",119000.00,6.000,19833.33,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. К..."
160696,1s173601633745814,https://www.imot.bg/obiava-1s173601633745814-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Ресилово",30000.00,1.900,15789.47,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
161542,1s176156957009387,https://www.imot.bg/obiava-1s176156957009387-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Несебър, к.к. Слънчев Бряг",117900.00,8.000,14737.50,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Н..."
162722,1s178068121112070,https://www.imot.bg/obiava-1s178068121112070-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Варна,"област Варна, гр. Бяла, ЕКСКЛУЗИВ",11000.00,0.748,14705.88,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Варна, гр. Бя..."
161387,1s175620144557357,https://www.imot.bg/obiava-1s175620144557357-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Черноморец",95000.00,7.000,13571.43,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Ч..."
121377,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-p...,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градск...",12000.00,1.000,12000.00,"Продава ГАРАЖ в област Пазарджик, гр. Пещера -..."
159551,1s162142678282599,https://www.imot.bg/obiava-1s162142678282599-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Николичевци",84363.00,7.500,11248.40,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
160998,1s174472238104460,https://www.imot.bg/obiava-1s174472238104460-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костенец",37708.00,3.428,11000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
161341,1s175439501862736,https://www.imot.bg/obiava-1s175439501862736-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Варна,"област Варна, гр. Игнатиево",9000.00,0.880,10227.27,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Варна, гр. Иг..."
160905,1s174443975664895,https://www.imot.bg/obiava-1s174443975664895-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Ловеч,"област Ловеч, с. Голяма Желязна",25462.34,2.497,10197.17,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Ловеч, с. Гол..."
148290,1r176181905920944,https://www.imot.bg/obiava-1r176181905920944-p...,ПАРЦЕЛ,град София,"град София, Борово",5000.00,1.000,5000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
160847,1s174241970465675,https://www.imot.bg/obiava-1s174241970465675-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Варна,"област Варна, с. Припек",2300.81,0.580,3966.91,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Варна, с. При..."
138687,1r173210500743400,https://www.imot.bg/obiava-1r173210500743400-p...,ПАРЦЕЛ,град София,"град София, Лозенец",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м ..."
138704,1r173210689382131,https://www.imot.bg/obiava-1r173210689382131-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
138710,1r173210674853219,https://www.imot.bg/obiava-1r173210674853219-p...,ПАРЦЕЛ,град София,"град София, Оборище",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м ..."
125712,1r129836973937027,https://www.imot.bg/obiava-1r129836973937027-p...,ПАРЦЕЛ,град София,"град София, Бъкстон",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м ..."
125713,1r129837016910336,https://www.imot.bg/obiava-1r129837016910336-p...,ПАРЦЕЛ,град София,"град София, Изток",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / ..."
125714,1r129836999298495,https://www.imot.bg/obiava-1r129836999298495-p...,ПАРЦЕЛ,град София,"град София, Манастирски ливади",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Манастирски ливад..."
125716,1r129837027077889,https://www.imot.bg/obiava-1r129837027077889-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
125738,1r129837078094806,https://www.imot.bg/obiava-1r129837078094806-p...,ПАРЦЕЛ,град София,"град София, Борово",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
125743,1r129837036109746,https://www.imot.bg/obiava-1r129837036109746-p...,ПАРЦЕЛ,град София,"град София, Павлово",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м ..."
140243,1r173831670876756,https://www.imot.bg/obiava-1r173831670876756-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Дебелец",1111.00,1.000,1111.00,"Продава ПАРЦЕЛ в област Велико Търново, гр. Де..."
81864,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.00,1.000,950.00,"Продава МНОГОСТАЕН в град Кърджали, Център - 1..."
159373,1s148066780877500,https://www.imot.bg/obiava-1s148066780877500-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Климент",1073.00,1.310,819.08,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. К..."

Borderline rows still needing manual review: 305

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
160101,1s170435725629856,https://www.imot.bg/obiava-1s170435725629856-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Велико Търново,"област Велико Търново, с. Самоводене",22000.00,2.595,8477.84,Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Велико Търнов...
119763,1n177322468553738,https://www.imot.bg/obiava-1n177322468553738-p...,СКЛАД,град София,"град София, Кръстова вада, Ул. Ген. Иван Колев",5000.00,3.000,1666.67,"Продава СКЛАД в град София, Кръстова вада - 3 ..."
119313,1n171187720586372,https://www.imot.bg/obiava-1n171187720586372-p...,СКЛАД,град София,"град София, Връбница 2, бул. Ломско шосе",2700.00,3.000,900.00,"Продава СКЛАД в град София, Връбница 2 - 3 кв...."
160922,1s174443985769114,https://www.imot.bg/obiava-1s174443985769114-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Ловеч,"област Ловеч, с. Голяма Желязна",30012.83,3.086,9725.48,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Ловеч, с. Гол..."
159550,1s162982497186752,https://www.imot.bg/obiava-1s162982497186752-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Богдан",4218.16,3.303,1277.07,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
...,...,...,...,...,...,...,...,...,...
161370,1s175636549416627,https://www.imot.bg/obiava-1s175636549416627-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Добрич,"област Добрич, гр. Тервел, Войниково",60000.00,20.000,3000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, гр. Т..."
89071,1i178049854280678,https://www.imot.bg/obiava-1i178049854280678-p...,ЕТАЖ ОТ КЪЩА,град София,"град София, Център, ул. Тимок",54999.00,20.000,2749.95,"Продава ЕТАЖ ОТ КЪЩА в град София, Център - 20..."
89101,1i178049831333656,https://www.imot.bg/obiava-1i178049831333656-p...,ЕТАЖ ОТ КЪЩА,град София,"град София, Център",54999.00,20.000,2749.95,"Продава ЕТАЖ ОТ КЪЩА в град София, Център - 20..."
108148,1j177554821671263,https://www.imot.bg/obiava-1j177554821671263-p...,КЪЩА,област Варна,"област Варна, с. Доброглед",45900.00,20.000,2295.00,"Продава КЪЩА в област Варна, с. Доброглед - 20..."
108633,1j177625871240095,https://www.imot.bg/obiava-1j177625871240095-p...,КЪЩА,град Бургас,"град Бургас, гр. Българово, Лозницата",35000.00,20.000,1750.00,"Продава КЪЩА в град Бургас, гр. Българово - 20..."

In [13]:
# ------------------------------------------------------------
# Step 2D: Detect likely decare-parsed-as-sqm issue
# ------------------------------------------------------------

LAND_DECARE_LIKELY_TYPES = {
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

df_candidate = df_candidate.copy()

df_candidate["area_unit_suspected"] = None
df_candidate["area_sqm_corrected"] = df_candidate["area_sqm"]
df_candidate["price_per_sqm_corrected"] = df_candidate["price_per_sqm"]

likely_decare_mask = (
    df_candidate["property_type_raw"].isin(LAND_DECARE_LIKELY_TYPES)
    & df_candidate["area_sqm"].between(0.1, 100)
    & (df_candidate["price_per_sqm"] > 500)
)

df_candidate.loc[likely_decare_mask, "area_unit_suspected"] = "decare_parsed_as_sqm"

df_candidate.loc[likely_decare_mask, "area_sqm_corrected"] = (
    df_candidate.loc[likely_decare_mask, "area_sqm"] * 1000
)

df_candidate.loc[likely_decare_mask, "price_per_sqm_corrected"] = (
    df_candidate.loc[likely_decare_mask, "total_price"]
    / df_candidate.loc[likely_decare_mask, "area_sqm_corrected"]
)

print("Likely decare correction rows:", likely_decare_mask.sum())

display(
    df_candidate.loc[
        likely_decare_mask,
        [
            "ad_id",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "area_sqm_corrected",
            "price_per_sqm",
            "price_per_sqm_corrected",
            "title",
        ],
    ]
    .sort_values("price_per_sqm", ascending=False)
    .head(100)
)

Likely decare correction rows: 180

,ad_id,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,area_sqm_corrected,price_per_sqm,price_per_sqm_corrected,title
161780,1s176771053368590,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, гр. Кюстендил, Въртешево",48000000.00,72.000,72000.0,666666.67,666.666667,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр..."
160994,1s174472213814965,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Баня",300000.00,1.000,1000.0,300000.00,300.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
160568,1s173082154774113,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Войводиново",140000.00,1.000,1000.0,140000.00,140.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. В..."
161913,1s177027522738950,ЗЕМЕДЕЛСКА ЗЕМЯ,област Хасково,"област Хасково, гр. Симеоновград",11650600.00,100.000,100000.0,116506.00,116.506000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Хасково, гр. ..."
160999,1s174472241896851,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Резово",500000.00,5.139,5139.0,97295.19,97.295194,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ре..."
...,...,...,...,...,...,...,...,...,...,...
161389,1s175706802267632,ЗЕМЕДЕЛСКА ЗЕМЯ,област Добрич,"област Добрич, гр. Генерал Тошево",171900.00,80.000,80000.0,2148.75,2.148750,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, гр. Г..."
161144,1s174894289289444,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Приморско",175000.00,82.000,82000.0,2134.15,2.134146,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. П..."
162378,1s177694053564815,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Добралък",202500.00,100.000,100000.0,2025.00,2.025000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Д..."
159842,1s168130131217651,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Черноморец",127500.00,63.000,63000.0,2023.81,2.023810,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Ч..."
161709,1s176495030000453,ЗЕМЕДЕЛСКА ЗЕМЯ,област Добрич,"област Добрич, с. Прилеп",179974.74,90.000,90000.0,1999.72,1.999719,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, с. Пр..."

In [14]:
suspect_338 = small_area_review.copy()

# If your 338 dataframe has a different name, replace suspicious_candidates above.

suspect_338["suspect_group"] = "other_suspicious"

# 1. Agricultural land likely parsed in decares
suspect_338.loc[
    suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] < 200),
    "suspect_group"
] = "agricultural_land_likely_decares"

# 2. Very small residential/commercial areas
suspect_338.loc[
    ~suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] <= 20),
    "suspect_group"
] = "non_land_tiny_area"

# 3. High price per sqm but normal-ish area
suspect_338.loc[
    ~suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] > 20)
    & (suspect_338["price_per_sqm"] >= 9000),
    "suspect_group"
] = "non_land_high_price_per_sqm"

# 4. Agricultural land still expensive even after correction
if "price_per_sqm_corrected" in suspect_338.columns:
    suspect_338.loc[
        suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
        & (suspect_338["price_per_sqm_corrected"] > 100),
        "suspect_group"
    ] = "agricultural_land_extreme_even_after_correction"


suspect_summary = (
    suspect_338["suspect_group"]
    .value_counts()
    .rename_axis("suspect_group")
    .reset_index(name="rows")
)

suspect_summary["pct_of_338"] = (
    suspect_summary["rows"] / len(suspect_338) * 100
).round(2)

display(suspect_summary)

                      suspect_group  rows  pct_of_338
0  agricultural_land_likely_decares   216       60.34
1                non_land_tiny_area   105       29.33
2                  other_suspicious    37       10.34

In [15]:
tiny_non_land = suspect_338[
    suspect_338["suspect_group"].eq("non_land_tiny_area")
].copy()

tiny_non_land_summary = (
    tiny_non_land
    .groupby("property_type_raw")
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        median_area=("area_sqm", "median"),
        max_area=("area_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
        median_price_per_sqm=("price_per_sqm", "median"),
    )
    .sort_values("rows", ascending=False)
    .reset_index()
)

display(tiny_non_land_summary)

,property_type_raw,rows,min_area,median_area,max_area,min_price,median_price,max_price,median_price_per_sqm
0,ВИЛА,40,1.0,15.0,19.0,5624.21,19000.00,310000.0,1117.975
1,КЪЩА,23,1.0,20.0,20.0,5700.00,33233.97,140000.0,1750.000
2,ПАРЦЕЛ,19,1.0,1.0,20.0,1111.00,3000.00,680000.0,2000.000
3,1-СТАЕН,10,1.0,10.5,13.0,23000.00,34900.00,89500.0,3319.500
4,3-СТАЕН,3,1.0,1.0,1.0,113000.00,125220.00,210000.0,125220.000
5,ЕТАЖ ОТ КЪЩА,2,20.0,20.0,20.0,54999.00,54999.00,54999.0,2749.950
6,ГАРАЖ,2,1.0,4.0,7.0,12000.00,17000.00,22000.0,7571.430
7,СКЛАД,2,3.0,3.0,3.0,2700.00,3850.00,5000.0,1283.335
8,МНОГОСТАЕН,2,1.0,1.0,1.0,950.00,29700.00,58450.0,29700.000
9,2-СТАЕН,1,14.0,14.0,14.0,16500.00,16500.00,16500.0,1178.570
10,ПАРКОМЯСТО,1,6.0,6.0,6.0,10000.00,10000.00,10000.0,1666.670

In [16]:
multiroom_tiny = df_candidate[
    df_candidate["property_type_raw"].eq("МНОГОСТАЕН")
    & df_candidate["area_sqm"].lt(20)
].copy()

cols_to_review = [
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "floor",
    "total_floors",
    "construction_type",
    "construction_year",
    "features_count",
    "views",
    "title",
    "description_clean",
]

multiroom_tiny[cols_to_review]

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,floor,total_floors,construction_type,construction_year,features_count,views,title,description_clean
81864,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.0,1.0,950.0,NaN,NaN,Тухла,2026,5,847.0,"Продава МНОГОСТАЕН в град Кърджали, Център - 1...",Реф. : 55 Имоти България предлага за продажба...
81877,1e176876794712573,https://www.imot.bg/obiava-1e176876794712573-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Гледка",58450.0,1.0,58450.0,NaN,NaN,Тухла,2028,5,878.0,"Продава МНОГОСТАЕН в град Кърджали, Гледка - 1...",Реф. : 54 Имоти България предлага за продажба...

In [17]:
# Drop the 2 suspicious МНОГОСТАЕН rows with tiny area
before_rows = len(df_candidate)

drop_mask = (
    df_candidate["property_type_raw"].eq("МНОГОСТАЕН")
    & df_candidate["area_sqm"].lt(20)
)

dropped_multiroom_tiny = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

dropped_multiroom_tiny[
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_raw",
        "location_raw",
        "total_price",
        "area_sqm",
        "price_per_sqm",
        "title",
    ]
]

cleanup_actions = []

cleanup_actions.append({
    "rule": "drop_multiroom_tiny_area",
    "reason": "МНОГОСТАЕН listings below 20 sqm are structurally implausible for regression training",
    "rows_affected": len(dropped_multiroom_tiny),
})

Dropped rows: 2
Candidate rows before: 161383
Candidate rows after: 161381

In [18]:
types_to_check = [
    "1-СТАЕН",
    "3-СТАЕН",
    "КЪЩА",
    "ВИЛА",
    "ГАРАЖ",
]

manual_check_df = (
    small_area_review
    .loc[small_area_review["property_type_raw"].isin(types_to_check)
        & (small_area_review["area_sqm"] == 1)]
    .sort_values(
        ["property_type_raw", "area_sqm", "price_per_sqm"],
        ascending=[True, True, False],
    )
    .copy()
)

print("Rows to manually inspect:", len(manual_check_df))

manual_check_df[
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_raw",
        "location_raw",
        "total_price",
        "area_sqm",
        "price_per_sqm",
        "title",
    ]
]

with pd.option_context("display.max_colwidth", None):
    display(manual_check_df[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ])

Rows to manually inspect: 7

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
64,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-prodava-ednostaen-apartament-grad-veliko-tarnovo-tsentar,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",89500.0,1.0,89500.0,"Продава 1-СТАЕН в град Велико Търново, Център - 1 кв.м / При запитване, СЕНТЧЪРИ ХОУМС :: imot.bg Обява 915894"
62516,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-prodava-tristaen-apartament-oblast-kardzhali-gr-momchilgrad,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.0,"Продава 3-СТАЕН в област Кърджали, гр. Момчилград - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 045818"
48440,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-prodava-tristaen-apartament-grad-dobrich-tsentar,3-СТАЕН,град Добрич,"град Добрич, Център",125220.0,1.0,125220.0,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м / При запитване, АДРЕС НЕДВИЖИМИ ИМОТИ - ДОБРИЧ :: imot.bg Обява 054878"
62515,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-prodava-tristaen-apartament-grad-kardzhali-tsentar,3-СТАЕН,град Кърджали,"град Кърджали, Център",113000.0,1.0,113000.0,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 848711"
114086,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-prodava-vila-gartsiya-halkidiki,ВИЛА,Гърция,"Гърция, Халкидики",310000.0,1.0,310000.0,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 310 000 € » 606 307.30 лв., БРЕЙН ТРЪСТ :: imot.bg Обява 713961"
121377,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-prodava-garazh-parkomyasto-oblast-pazardzhik-gr-peshtera-tsentralna-gradska-chast,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градска част",12000.0,1.0,12000.0,"Продава ГАРАЖ в област Пазарджик, гр. Пещера - 1 кв.м / При запитване, ИМОТИ К1 :: imot.bg Обява 800843"
94039,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-prodava-kashta-oblast-pazardzhik-gr-septemvri-septemvri,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",62000.0,1.0,62000.0,"Продава КЪЩА в област Пазарджик, гр. Септември - 1 кв.м / При запитване :: imot.bg Обява 853529"

In [19]:
# Drop manually inspected 1 sqm suspicious rows
before_rows = len(df_candidate)

manual_drop_ad_ids = [
    "1a164924469915894",  # 1-СТАЕН, 1 sqm
    "1c177331151045818",  # 3-СТАЕН, 1 sqm
    "1c177331172848711",  # 3-СТАЕН, 1 sqm
    "1c175085717054878",  # 3-СТАЕН, 1 sqm
    "1k175862421713961",  # ВИЛА, 1 sqm
    "1o177179195800843",  # ГАРАЖ, 1 sqm
    "1j172909262853529",  # КЪЩА, 1 sqm
]

drop_mask = df_candidate["ad_id"].isin(manual_drop_ad_ids)

dropped_manual_1sqm = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_manual_1sqm[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_manual_1sqm_suspicious_rows",
    "reason": "Manually inspected 1 sqm listings with implausible area/price_per_sqm combinations; likely parsing or source-entry errors",
    "rows_affected": len(dropped_manual_1sqm),
})

Dropped rows: 7
Candidate rows before: 160567
Candidate rows after: 160560

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.0,1.0,35000.0,"Продава 1-СТАЕН в град Велико Търново, Център ..."
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",97000.0,1.0,97000.0,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.0,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.0,1.0,100000.0,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
93241,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-p...,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",55000.0,1.0,55000.0,"Продава КЪЩА в област Пазарджик, гр. Септември..."
111497,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.0,1.0,310000.0,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
118935,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-p...,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градск...",12000.0,1.0,12000.0,"Продава ГАРАЖ в област Пазарджик, гр. Пещера -..."

In [20]:
# Show full URL/title text in notebook output
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)

parcel_tiny_area_inspect = (
    df_candidate.loc[
        df_candidate["property_type_raw"].eq("ПАРЦЕЛ")
        & df_candidate["area_sqm"].lt(20)
    ]
    .sort_values(["area_sqm", "price_per_sqm"], ascending=[True, False])
    .copy()
)

print("Rows to manually inspect:", len(parcel_tiny_area_inspect))

display(
    parcel_tiny_area_inspect[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

Rows to manually inspect: 18

                    ad_id                                                                                                             ad_url property_type_raw         title_city_raw                                          location_raw  total_price  area_sqm  price_per_sqm                                                                                                                          title
128912  1r168321569073352                             https://www.imot.bg/obiava-1r168321569073352-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0       1.0      120000.00            Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 1 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 073352
132664  1r171576942411245  https://www.imot.bg/obiava-1r171576942411245-prodava-partsel-oblast-blagoevgrad-gr-gotse-delchev-mestnost-mochura            ПАРЦЕЛ     област Благоевград  област Благоевград, гр. Гоце Делчев, Местност Мочура      35500.0       1.0       35500.00                     Продава ПАРЦЕЛ в област Благоевград, гр. Гоце Делчев - 1 кв.м / При запитване, БКС :: imot.bg Обява 411245
150068  1r176876865288529                             https://www.imot.bg/obiava-1r176876865288529-prodava-partsel-oblast-kardzhali-s-gluhar            ПАРЦЕЛ        област Кърджали                            област Кърджали, с. Глухар      28200.0       1.0       28200.00            Продава ПАРЦЕЛ в област Кърджали, с. Глухар - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 288529
146598  1r176181905920944                                    https://www.imot.bg/obiava-1r176181905920944-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       5000.0       1.0        5000.00            Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 5 000 € » 9 779.15 лв., БМБ КОНСТРАКШЪН ЕООД :: imot.bg Обява 920944
136384  1r173210500743400                                  https://www.imot.bg/obiava-1r173210500743400-prodava-partsel-grad-sofiya-lozenets            ПАРЦЕЛ             град София                                   град София, Лозенец       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 743400
136400  1r173210674853219                                 https://www.imot.bg/obiava-1r173210674853219-prodava-partsel-grad-sofiya-oborishte            ПАРЦЕЛ             град София                                   град София, Оборище       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 853219
136403  1r173210689382131                                 https://www.imot.bg/obiava-1r173210689382131-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       3000.0       1.0        3000.00       Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 382131
123104  1r129836973937027                                   https://www.imot.bg/obiava-1r129836973937027-prodava-partsel-grad-sofiya-bakston            ПАРЦЕЛ             град София                                   град София, Бъкстон       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 937027
123105  1r129837036109746                                   https://www.imot.bg/obiava-1r129837036109746-prodava-partsel-grad-sofiya-pavlovo            ПАРЦЕЛ             град София                                   град София, Павлово       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 109746
123106  1r129837027077889                                 https://www.imot.bg/obiava-1r129837027077889-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       2000.0       1.0        2000.00           Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 077889
123107  1r129837078094806                                    https://www.imot.bg/obiava-1r129837078094806-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       2000.0       1.0        2000.00              Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 094806
123138  1r129836999298495                        https://www.imot.bg/obiava-1r129836999298495-prodava-partsel-grad-sofiya-manastirski-livadi            ПАРЦЕЛ             град София                        град София, Манастирски ливади       2000.0       1.0        2000.00  Продава ПАРЦЕЛ в град София, Манастирски ливади - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 298495
123141  1r129837016910336                                     https://www.imot.bg/obiava-1r129837016910336-prodava-partsel-grad-sofiya-iztok            ПАРЦЕЛ             град София                                     град София, Изток       2000.0       1.0        2000.00               Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 910336
138009  1r173831670876756                     https://www.imot.bg/obiava-1r173831670876756-prodava-partsel-oblast-veliko-tarnovo-gr-debelets            ПАРЦЕЛ  област Велико Търново                    област Велико Търново, гр. Дебелец       1111.0       1.0        1111.00    Продава ПАРЦЕЛ в област Велико Търново, гр. Дебелец - 1 кв.м / При запитване, АДРЕС НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 876756
154767  1r177502554613617                          https://www.imot.bg/obiava-1r177502554613617-prodava-partsel-oblast-burgas-gr-kableshkovo            ПАРЦЕЛ          област Бургас                         област Бургас, гр. Каблешково      13000.0       2.0        6500.00            Продава ПАРЦЕЛ в област Бургас, гр. Каблешково - 2 кв.м / При запитване, ЕКС НВД БУРГАС ООД :: imot.bg Обява 613617
138040  1r173850696242512          https://www.imot.bg/obiava-1r173850696242512-prodava-partsel-oblast-varna-s-zdravets-m-st-kurdzhieva-niva            ПАРЦЕЛ           област Варна         област Варна, с. Здравец, М-ст Курджиева нива      13000.0      10.0        1300.00         Продава ПАРЦЕЛ в област Варна, с. Здравец - 10 кв.м / 13 000 € » 25 425.79 лв., ДИМИТРОВ ИМОТИ :: imot.bg Обява 242512
134097  1r172269115424343                             https://www.imot.bg/obiava-1r172269115424343-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0      11.0       10909.09           Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 11 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 424343
153188  1r177330658387954                                   https://www.imot.bg/obiava-1r177330658387954-prodava-partsel-grad-ruse-druzhba-3            ПАРЦЕЛ              град Русе                                   град Русе, Дружба 3      17000.0      19.0         894.74              Продава ПАРЦЕЛ в град Русе, Дружба 3 - 19 кв.м / 17 000 € » 33 249.11 лв., ДУНАВСКИ ИМОТИ :: imot.bg Обява 387954

In [19]:
# Drop suspicious/fake ПАРЦЕЛ rows with tiny area
before_rows = len(df_candidate)

drop_mask = (
    df_candidate["property_type_raw"].eq("ПАРЦЕЛ")
    & df_candidate["area_sqm"].lt(20)
)

dropped_parcel_tiny_fake = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_parcel_tiny_fake[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_parcel_tiny_fake_ads",
    "reason": "ПАРЦЕЛ listings below 20 sqm appear to be fake/placeholder ads and are not valid regression training observations",
    "rows_affected": len(dropped_parcel_tiny_fake),
})

Dropped rows: 17
Candidate rows before: 161381
Candidate rows after: 161364

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
125712,1r129836973937027,https://www.imot.bg/obiava-1r129836973937027-p...,ПАРЦЕЛ,град София,"град София, Бъкстон",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м ..."
125713,1r129837016910336,https://www.imot.bg/obiava-1r129837016910336-p...,ПАРЦЕЛ,град София,"град София, Изток",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / ..."
125714,1r129836999298495,https://www.imot.bg/obiava-1r129836999298495-p...,ПАРЦЕЛ,град София,"град София, Манастирски ливади",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Манастирски ливад..."
125716,1r129837027077889,https://www.imot.bg/obiava-1r129837027077889-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
125738,1r129837078094806,https://www.imot.bg/obiava-1r129837078094806-p...,ПАРЦЕЛ,град София,"град София, Борово",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
125743,1r129837036109746,https://www.imot.bg/obiava-1r129837036109746-p...,ПАРЦЕЛ,град София,"град София, Павлово",2000.0,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м ..."
131508,1r168321569073352,https://www.imot.bg/obiava-1r168321569073352-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, гр. Карлово",680000.0,1.0,680000.00,"Продава ПАРЦЕЛ в област Пловдив, гр. Карлово -..."
135154,1r171576942411245,https://www.imot.bg/obiava-1r171576942411245-p...,ПАРЦЕЛ,област Благоевград,"област Благоевград, гр. Гоце Делчев, Местност ...",480000.0,1.0,480000.00,"Продава ПАРЦЕЛ в област Благоевград, гр. Гоце ..."
136460,1r172269115424343,https://www.imot.bg/obiava-1r172269115424343-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, гр. Карлово",680000.0,11.0,61818.18,"Продава ПАРЦЕЛ в област Пловдив, гр. Карлово -..."
138687,1r173210500743400,https://www.imot.bg/obiava-1r173210500743400-p...,ПАРЦЕЛ,град София,"град София, Лозенец",3000.0,1.0,3000.00,"Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м ..."
138704,1r173210689382131,https://www.imot.bg/obiava-1r173210689382131-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",3000.0,1.0,3000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
138710,1r173210674853219,https://www.imot.bg/obiava-1r173210674853219-p...,ПАРЦЕЛ,град София,"град София, Оборище",3000.0,1.0,3000.00,"Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м ..."
140243,1r173831670876756,https://www.imot.bg/obiava-1r173831670876756-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Дебелец",1111.0,1.0,1111.00,"Продава ПАРЦЕЛ в област Велико Търново, гр. Де..."
140265,1r173850696242512,https://www.imot.bg/obiava-1r173850696242512-p...,ПАРЦЕЛ,област Варна,"област Варна, с. Здравец, М-ст Курджиева нива",13000.0,10.0,1300.00,"Продава ПАРЦЕЛ в област Варна, с. Здравец - 10..."
148290,1r176181905920944,https://www.imot.bg/obiava-1r176181905920944-p...,ПАРЦЕЛ,град София,"град София, Борово",5000.0,1.0,5000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
151613,1r176876865288529,https://www.imot.bg/obiava-1r176876865288529-p...,ПАРЦЕЛ,област Кърджали,"област Кърджали, с. Глухар",51130.0,1.0,51130.00,"Продава ПАРЦЕЛ в област Кърджали, с. Глухар - ..."
158442,1r178015269820461,https://www.imot.bg/obiava-1r178015269820461-p...,ПАРЦЕЛ,град Русе,"град Русе, Дружба 3",17000.0,19.0,894.74,"Продава ПАРЦЕЛ в град Русе, Дружба 3 - 19 кв.м..."

In [20]:
# Correct agricultural land area values that appear to be entered in decares
before_rows = len(df_candidate)

agri_mask = (
    df_candidate["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & df_candidate["area_sqm"].notna()
    & df_candidate["total_price"].notna()
    & df_candidate["area_sqm"].between(0.01, 500)  # likely decares, not sqm
)

corrected_agri_land_decares = df_candidate.loc[agri_mask].copy()

df_candidate.loc[agri_mask, "area_sqm_original"] = df_candidate.loc[agri_mask, "area_sqm"]
df_candidate.loc[agri_mask, "price_per_sqm_original"] = df_candidate.loc[agri_mask, "price_per_sqm"]

df_candidate.loc[agri_mask, "area_sqm"] = (
    df_candidate.loc[agri_mask, "area_sqm"] * 1000
)

df_candidate.loc[agri_mask, "price_per_sqm"] = (
    df_candidate.loc[agri_mask, "total_price"] / df_candidate.loc[agri_mask, "area_sqm"]
)

after_rows = len(df_candidate)

print("Corrected agricultural land rows:", len(corrected_agri_land_decares))
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    df_candidate.loc[
        agri_mask,
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm_original",
            "area_sqm",
            "price_per_sqm_original",
            "price_per_sqm",
            "title",
        ]
    ].sort_values("price_per_sqm", ascending=False).head(100)
)

cleanup_actions.append({
    "rule": "correct_agricultural_land_decares_to_sqm",
    "reason": "ЗЕМЕДЕЛСКА ЗЕМЯ listings with very small area values are likely expressed in decares; converted area to sqm and recalculated price_per_sqm",
    "rows_affected": len(corrected_agri_land_decares),
})

Corrected agricultural land rows: 577
Candidate rows before: 161364
Candidate rows after: 161364

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm_original,area_sqm,price_per_sqm_original,price_per_sqm,title
160075,1s170166941027571,https://www.imot.bg/obiava-1s170166941027571-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, гр. Пловдив, до р.Марица",301290000.0,180.0,180000.0,1673833.33,1673.833333,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, гр. ..."
162015,1s177261153256353,https://www.imot.bg/obiava-1s177261153256353-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Ново Кономлади",471195000.0,413.0,413000.0,1140907.99,1140.907990,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
161780,1s176771053368590,https://www.imot.bg/obiava-1s176771053368590-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, гр. Кюстендил, Въртешево",48000000.0,72.0,72000.0,666666.67,666.666667,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр..."
160994,1s174472213814965,https://www.imot.bg/obiava-1s174472213814965-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Баня",300000.0,1.0,1000.0,300000.00,300.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
160568,1s173082154774113,https://www.imot.bg/obiava-1s173082154774113-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Войводиново",140000.0,1.0,1000.0,140000.00,140.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. В..."
...,...,...,...,...,...,...,...,...,...,...,...
159659,1s165537827544483,https://www.imot.bg/obiava-1s165537827544483-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пазарджик,"област Пазарджик, с. Звъничево",150000.0,51.0,51000.0,2941.18,2.941176,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пазарджик, с...."
160504,1s172924783379667,https://www.imot.bg/obiava-1s172924783379667-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Страцин",76000.0,26.0,26000.0,2923.08,2.923077,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ст..."
162089,1s177314698595140,https://www.imot.bg/obiava-1s177314698595140-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Сандански",275000.0,96.0,96000.0,2864.58,2.864583,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
161552,1s176183294684950,https://www.imot.bg/obiava-1s176183294684950-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Елин Пелин, с.Нови Хан",200000.0,70.0,70000.0,2857.14,2.857143,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ел..."
161410,1s175777352640762,https://www.imot.bg/obiava-1s175777352640762-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Стара Загора,"област Стара Загора, гр. Стара Загора, Герена",500000.0,179.0,179000.0,2793.30,2.793296,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора,..."

In [21]:
drop_review = area_suspicious_df[
    area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["price_per_sqm", "area_sqm"],
    ascending=[False, True]
)

drop_review.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 131508 to 159373
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ad_id              53 non-null     object
 1   ad_url             53 non-null     object
 2   property_type_raw  53 non-null     object
 3   title_city_raw     53 non-null     object
 4   location_raw       53 non-null     object
 5   total_price        53 non-null     float64
 6   area_sqm           53 non-null     float64
 7   price_per_sqm      53 non-null     float64
 8   title              53 non-null     object
dtypes: float64(3), object(6)
memory usage: 4.1+ KB

In [22]:
df_ml_base = df_candidate.copy()

print("Rows in df_candidate:", len(df_candidate))
print("Rows in df_ml_base:", len(df_ml_base))

df_ml_base["min_reasonable_area"] = (
    df_ml_base["property_type_raw"]
    .map(MIN_AREA_BY_PROPERTY_TYPE)
)

df_ml_base["suspicious_area_too_small"] = (
    df_ml_base["min_reasonable_area"].notna()
    & (df_ml_base["area_sqm"] < df_ml_base["min_reasonable_area"])
)

small_area_review = df_ml_base[
    df_ml_base["suspicious_area_too_small"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(["property_type_raw", "area_sqm"])

print("Suspicious too-small area rows:", len(small_area_review))
display(small_area_review.head(50))

Rows in df_candidate: 161364
Rows in df_ml_base: 161364
Suspicious too-small area rows: 123

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
64,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",89500.00,1.0,89500.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
873,1a174617120400088,https://www.imot.bg/obiava-1a174617120400088-p...,1-СТАЕН,град Варна,"град Варна, Център",39500.00,10.0,3950.00,"Продава 1-СТАЕН в град Варна, Център - 10 кв.м..."
898,1a174720940537891,https://www.imot.bg/obiava-1a174720940537891-p...,1-СТАЕН,град Варна,"град Варна, Гръцка махала, ФК",31490.00,10.0,3149.00,"Продава 1-СТАЕН в град Варна, Гръцка махала - ..."
5039,1a177762783253610,https://www.imot.bg/obiava-1a177762783253610-p...,1-СТАЕН,град Варна,"град Варна, Христо Ботев, ул.Тодор Влайков",29900.00,10.0,2990.00,"Продава 1-СТАЕН в град Варна, Христо Ботев - 1..."
5040,1a177762750182371,https://www.imot.bg/obiava-1a177762750182371-p...,1-СТАЕН,град Варна,"град Варна, Левски 2, ул.Емануил Манолов",34900.00,10.0,3490.00,"Продава 1-СТАЕН в град Варна, Левски 2 - 10 кв..."
5234,1a177822677766997,https://www.imot.bg/obiava-1a177822677766997-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар",23000.00,11.0,2090.91,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
2883,1a176952090948960,https://www.imot.bg/obiava-1a176952090948960-p...,1-СТАЕН,област Бургас,"област Бургас, к.к. Слънчев бряг",24000.00,12.0,2000.00,"Продава 1-СТАЕН в област Бургас, к.к. Слънчев ..."
5062,1a177762644247321,https://www.imot.bg/obiava-1a177762644247321-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар, ул.Стоенчо Хаджи И...",34900.00,12.0,2908.33,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
4626,1a177667102639011,https://www.imot.bg/obiava-1a177667102639011-p...,1-СТАЕН,град София,"град София, Стрелбище",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Стрелбище - 13 к..."
4651,1a177667142731690,https://www.imot.bg/obiava-1a177667142731690-p...,1-СТАЕН,град София,"град София, Иван Вазов",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Иван Вазов - 13 ..."
11729,1b174712395287055,https://www.imot.bg/obiava-1b174712395287055-p...,2-СТАЕН,град Бургас,"град Бургас, Център",16500.00,14.0,1178.57,"Продава 2-СТАЕН в град Бургас, Център - 14 кв...."
48440,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",125220.00,1.0,125220.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
62515,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",113000.00,1.0,113000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
62516,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.00,1.0,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
114086,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.00,1.0,310000.00,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
114494,1k177830949732411,https://www.imot.bg/obiava-1k177830949732411-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",27000.00,9.0,3000.00,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113877,1k174238436132860,https://www.imot.bg/obiava-1k174238436132860-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",11248.42,10.0,1124.84,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
113905,1k174589655796135,https://www.imot.bg/obiava-1k174589655796135-p...,ВИЛА,град Русе,"град Русе, в.з. Кулата",20000.00,10.0,2000.00,"Продава ВИЛА в град Русе, в.з. Кулата - 10 кв...."
113629,1k170487729767222,https://www.imot.bg/obiava-1k170487729767222-p...,ВИЛА,област Габрово,"област Габрово, с. Борики",9700.00,12.0,808.33,"Продава ВИЛА в област Габрово, с. Борики - 12 ..."
114522,1k177874594569087,https://www.imot.bg/obiava-1k177874594569087-p...,ВИЛА,област Хасково,"област Хасково, с. Минерални бани",38000.00,12.0,3166.67,"Продава ВИЛА в област Хасково, с. Минерални ба..."
114263,1k176790178804201,https://www.imot.bg/obiava-1k176790178804201-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",48000.00,13.0,3692.31,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
113486,1k159187372423967,https://www.imot.bg/obiava-1k159187372423967-p...,ВИЛА,град Добрич,"град Добрич, в.з. Лозята",9714.55,14.0,693.90,"Продава ВИЛА в град Добрич, в.з. Лозята - 14 к..."
113812,1k173381990962779,https://www.imot.bg/obiava-1k173381990962779-p...,ВИЛА,град Търговище,"град Търговище, Вилна зона, Чокя",15338.76,14.0,1095.63,"Продава ВИЛА в град Търговище, Вилна зона - 14..."
114225,1k176556804152396,https://www.imot.bg/obiava-1k176556804152396-p...,ВИЛА,област Варна,"област Варна, с. Бенковски",23000.00,14.0,1642.86,"Продава ВИЛА в област Варна, с. Бенковски - 14..."
114230,1k176608838752786,https://www.imot.bg/obiava-1k176608838752786-p...,ВИЛА,град Добрич,"град Добрич, м-т Газибаба, алмалии",9200.00,14.0,657.14,"Продава ВИЛА в град Добрич, м-т Газибаба - 14 ..."
113588,1k166902483080379,https://www.imot.bg/obiava-1k166902483080379-p...,ВИЛА,град Русе,"град Русе, Долапите",5880.00,15.0,392.00,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
113623,1k170238482982981,https://www.imot.bg/obiava-1k170238482982981-p...,ВИЛА,град Русе,"град Русе, Долапите, 10-ти км",6391.15,15.0,426.08,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
113687,1k171153091465916,https://www.imot.bg/obiava-1k171153091465916-p...,ВИЛА,област Варна,"област Варна, с. Осеново",35000.00,15.0,2333.33,"Продава ВИЛА в област Варна, с. Осеново - 15 к..."
113815,1k173617831600509,https://www.imot.bg/obiava-1k173617831600509-p...,ВИЛА,град Плевен,"град Плевен, м-т Мъртва долина",5624.21,15.0,374.95,"Продава ВИЛА в град Плевен, м-т Мъртва долина ..."
113827,1k173771669891059,https://www.imot.bg/obiava-1k173771669891059-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",28990.25,15.0,1932.68,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113864,1k174285800592432,https://www.imot.bg/obiava-1k174285800592432-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",22000.00,15.0,1466.67,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113884,1k174360336907458,https://www.imot.bg/obiava-1k174360336907458-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",21500.00,15.0,1433.33,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113911,1k174697906929015,https://www.imot.bg/obiava-1k174697906929015-p...,ВИЛА,област Бургас,"област Бургас, с. Росен",26000.00,15.0,1733.33,"Продава ВИЛА в област Бургас, с. Росен - 15 кв..."
113993,1k175206432515505,https://www.imot.bg/obiava-1k175206432515505-p...,ВИЛА,област Русе,"област Русе, с. Пиргово",32000.00,15.0,2133.33,"Продава ВИЛА в област Русе, с. Пиргово - 15 кв..."
114313,1k177089513661784,https://www.imot.bg/obiava-1k177089513661784-p...,ВИЛА,област Търговище,"област Търговище, с. Разбойна, Серсема",33233.00,15.0,2215.53,"Продава ВИЛА в област Търговище, с. Разбойна -..."
114335,1k177306035384054,https://www.imot.bg/obiava-1k177306035384054-p...,ВИЛА,област Габрово,"област Габрово, с. Чукилите",14000.00,15.0,933.33,"Продава ВИЛА в област Габрово, с. Чукилите - 1..."
114574,1k178005241360877,https://www.imot.bg/obiava-1k178005241360877-p...,ВИЛА,област Бургас,"област Бургас, гр. Царево",115000.00,15.0,7666.67,"Продава ВИЛА в област Бургас, гр. Царево - 15 ..."
114591,1k178015236451071,https://www.imot.bg/obiava-1k178015236451071-p...,ВИЛА,област Перник,"област Перник, с. Поцърненци",40000.00,15.0,2666.67,"Продава ВИЛА в област Перник, с. Поцърненци - ..."
113560,1k165349073718160,https://www.imot.bg/obiava-1k165349073718160-p...,ВИЛА,област София,"област София, с. Свидня",14000.00,16.0,875.00,"Продава ВИЛА в област София, с. Свидня - 16 кв..."
113582,1k168630218456890,https://www.imot.bg/obiava-1k168630218456890-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",31000.00,16.0,1937.50,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
113795,1k173131358442876,https://www.imot.bg/obiava-1k173131358442876-p...,ВИЛА,град Русе,"град Русе, в.з. Липака",10225.84,16.0,639.12,"Продава ВИЛА в град Русе, в.з. Липака - 16 кв...."
113796,1k173131452046414,https://www.imot.bg/obiava-1k173131452046414-p...,ВИЛА,област Русе,"област Русе, с. Николово",10225.84,16.0,639.12,"Продава ВИЛА в област Русе, с. Николово - 16 к..."
114624,1k178085536057395,https://www.imot.bg/obiava-1k178085536057395-p...,ВИЛА,област Пазарджик,"област Пазарджик, м-т Цигов чарк",29000.00,16.0,1812.50,"Продава ВИЛА в област Пазарджик, м-т Цигов чар..."
113889,1k174471450262174,https://www.imot.bg/obiava-1k174471450262174-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Крушевски баир",12271.01,17.0,721.82,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
114439,1k177592015889825,https://www.imot.bg/obiava-1k177592015889825-p...,ВИЛА,град Враца,"град Враца, Студентски град, Врачански лозя",15300.00,17.0,900.00,"Продава ВИЛА в град Враца, Студентски град - 1..."
113516,1k163422905045659,https://www.imot.bg/obiava-1k163422905045659-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",10225.84,18.0,568.10,"Продава ВИЛА в град Разград, Промишлена зона -..."
113559,1k166936354732929,https://www.imot.bg/obiava-1k166936354732929-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Севлиевски лозя",10225.84,18.0,568.10,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
113611,1k169877165462335,https://www.imot.bg/obiava-1k169877165462335-p...,ВИЛА,област София,"област София, с. Владо Тричков, Ромча",18000.00,18.0,1000.00,"Продава ВИЛА в област София, с. Владо Тричков ..."
114102,1k175922288191828,https://www.imot.bg/obiava-1k175922288191828-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",42437.23,18.0,2357.62,"Продава ВИЛА в град Разград, Промишлена зона -..."
114328,1k177194253564731,https://www.imot.bg/obiava-1k177194253564731-p...,ВИЛА,град Враца,"град Враца, Студентски град, м-ст Череша",9000.00,18.0,500.00,"Продава ВИЛА в град Враца, Студентски град - 1..."

In [23]:
# Drop final manually inspected suspicious listing
before_rows = len(df_candidate)

drop_ad_ids = {
    "1a177675907072610",
}

drop_mask = df_candidate["ad_id"].isin(drop_ad_ids)

dropped_final_manual = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_final_manual[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_manual_fake_tiny_area_single_room",
    "reason": "Manually inspected listing 1a177675907072610 has implausible 2 sqm area for a 1-СТАЕН listing and should not be used for regression training",
    "rows_affected": len(dropped_final_manual),
})

Dropped rows: 0
Candidate rows before: 161364
Candidate rows after: 161364

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_raw, location_raw, total_price, area_sqm, price_per_sqm, title]
Index: []

In [24]:
price_summary = df_candidate[
    [
        "total_price",
        "title_price_eur",
        "title_price_bgn",
        "area_sqm",
        "price_per_sqm",
    ]
].describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999]).T

display(price_summary)

print("Rows:", len(df_candidate))
print("Missing total_price:", df_candidate["total_price"].isna().sum())
print("Missing price_per_sqm:", df_candidate["price_per_sqm"].isna().sum())
print("Non-positive total_price:", (df_candidate["total_price"] <= 0).sum())
print("Non-positive price_per_sqm:", (df_candidate["price_per_sqm"] <= 0).sum())

,count,mean,std,min,0.1%,0.5%,1%,5%,50%,95%,99%,99.5%,99.9%,max
total_price,161364.0,257401.365736,2.255127e+06,31.000000,2556.46,6000.000000,8316.30,20800.00,134700.0,675000.0,2065000.00,3.200000e+06,7253860.22,4.711950e+08
title_price_eur,157983.0,253543.103986,2.264133e+06,500.000000,2700.00,6000.000000,8500.00,20900.00,134100.0,660000.0,2000000.00,3.100000e+06,7100000.00,4.711950e+08
title_price_bgn,157983.0,495887.209429,4.428260e+06,977.920000,5280.74,11734.980000,16624.56,40876.85,262276.8,1290847.8,3911660.00,6.063073e+06,13886393.00,9.215773e+08
area_sqm,161364.0,2109.696218,2.554189e+04,1.000000,12.00,17.000000,20.00,42.00,112.0,5895.0,26196.22,6.000000e+04,286911.00,4.854710e+06
price_per_sqm,161364.0,1362.246900,2.147311e+03,0.000431,0.16,1.288758,2.86,15.00,1300.0,3200.0,4611.11,5.378724e+03,7777.78,3.644979e+05

Rows: 161364
Missing total_price: 0
Missing price_per_sqm: 0
Non-positive total_price: 0
Non-positive price_per_sqm: 0

In [25]:
df_candidate["price_per_sqm_recalc"] = (
    df_candidate["total_price"] / df_candidate["area_sqm"]
)

df_candidate["price_per_sqm_diff_abs"] = (
    df_candidate["price_per_sqm"] - df_candidate["price_per_sqm_recalc"]
).abs()

df_candidate["price_per_sqm_diff_pct"] = (
    df_candidate["price_per_sqm_diff_abs"] / df_candidate["price_per_sqm_recalc"]
)

price_mismatch = df_candidate.loc[
    df_candidate["price_per_sqm_diff_pct"].gt(0.01)
].copy()

print("Price-per-sqm mismatch rows > 1%:", len(price_mismatch))

display(
    price_mismatch[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "price_per_sqm_recalc",
            "price_per_sqm_diff_pct",
            "price_raw",
            "title",
        ]
    ]
    .sort_values("price_per_sqm_diff_pct", ascending=False)
    .head(50)
)

Price-per-sqm mismatch rows > 1%: 32

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,price_per_sqm_recalc,price_per_sqm_diff_pct,price_raw,title
120964,1o176373075998653,https://www.imot.bg/obiava-1o176373075998653-p...,ПАРКОМЯСТО,град Варна,"град Варна, Виница",16000.00,1000000.0,0.02,0.016000,0.250000,16 000 €,"Продава ПАРКОМЯСТО в град Варна, Виница - 1000..."
146055,1r175689007326404,https://www.imot.bg/obiava-1r175689007326404-p...,ПАРЦЕЛ,област Габрово,"област Габрово, гр. Севлиево",23900.00,435958.0,0.05,0.054822,0.087954,23 900 €,"Продава ПАРЦЕЛ в област Габрово, гр. Севлиево ..."
161404,1s175639222039734,https://www.imot.bg/obiava-1s175639222039734-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Плевен,"област Плевен, гр. Плевен, КОМУДАРА",2300.00,52860.0,0.04,0.043511,0.080696,2 300 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Плевен, гр. П..."
159504,1s161296566514443,https://www.imot.bg/obiava-1s161296566514443-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Велико Търново,"област Велико Търново, гр. Велико Търново",4950.00,153000.0,0.03,0.032353,0.072727,4 950 €,Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Велико Търнов...
137080,1r172552687786745,https://www.imot.bg/obiava-1r172552687786745-p...,ПАРЦЕЛ,област Стара Загора,"област Стара Загора, с. Средно градище",21000.00,399000.0,0.05,0.052632,0.050000,21 000 €,"Продава ПАРЦЕЛ в област Стара Загора, с. Средн..."
159330,1s144766083882107,https://www.imot.bg/obiava-1s144766083882107-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, с. Хераково, местността 'Були ва...",511.00,8199.0,0.06,0.062325,0.037299,511 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Хер..."
148072,1r176155521345093,https://www.imot.bg/obiava-1r176155521345093-p...,ПАРЦЕЛ,област Перник,"област Перник, гр. Трън, Село Турковци",40903.35,3959900.0,0.01,0.010329,0.031889,40 903.35 €,"Продава ПАРЦЕЛ в област Перник, гр. Трън - 395..."
161536,1s176155601035714,https://www.imot.bg/obiava-1s176155601035714-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Перник,"област Перник, гр. Трън, село Турковци",40903.35,3959900.0,0.01,0.010329,0.031889,40 903.35 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Перник, гр. Т..."
126683,1r151066590726245,https://www.imot.bg/obiava-1r151066590726245-p...,ПАРЦЕЛ,област София,"област София, гр. Елин Пелин, м. Соленико",120000.00,1031000.0,0.12,0.116392,0.031000,120 000 €,"Продава ПАРЦЕЛ в област София, гр. Елин Пелин ..."
162227,1s177462535055312,https://www.imot.bg/obiava-1s177462535055312-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Ясна поляна, Трите круши",643.00,5999.0,0.11,0.107185,0.026267,643 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Яс..."
136176,1r172080513548610,https://www.imot.bg/obiava-1r172080513548610-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Дебелец",1111.00,6700.0,0.17,0.165821,0.025203,1 111 €,"Продава ПАРЦЕЛ в област Велико Търново, гр. Де..."
159950,1s169095777444571,https://www.imot.bg/obiava-1s169095777444571-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Пролом",1789.52,20369.0,0.09,0.087855,0.024414,1 789.52 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. П..."
126694,1r151197862312006,https://www.imot.bg/obiava-1r151197862312006-p...,ПАРЦЕЛ,област Враца,"област Враца, гр. Бяла Слатина",8000.00,91000.0,0.09,0.087912,0.023750,8 000 €,"Продава ПАРЦЕЛ в област Враца, гр. Бяла Слатин..."
132632,1r169571092600853,https://www.imot.bg/obiava-1r169571092600853-p...,ПАРЦЕЛ,област Бургас,"област Бургас, гр. Приморско",4000.00,21500.0,0.19,0.186047,0.021250,4 000 €,"Продава ПАРЦЕЛ в област Бургас, гр. Приморско ..."
137830,1r172899850546229,https://www.imot.bg/obiava-1r172899850546229-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1600.00,8598.0,0.19,0.186090,0.021012,1 600 €,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 8..."
142413,1r174644643585476,https://www.imot.bg/obiava-1r174644643585476-p...,ПАРЦЕЛ,област Бургас,"област Бургас, гр. Карнобат",49000.00,300000.0,0.16,0.163333,0.020408,49 000 €,"Продава ПАРЦЕЛ в област Бургас, гр. Карнобат -..."
91274,1j169322678528539,https://www.imot.bg/obiava-1j169322678528539-p...,КЪЩА,област Кърджали,"област Кърджали, с. Срединка",55.00,200.0,0.28,0.275000,0.018182,55 Eur,"Продава КЪЩА в област Кърджали, с. Срединка - ..."
129279,1r164613796043510,https://www.imot.bg/obiava-1r164613796043510-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Тепава",2556.46,10005.0,0.26,0.255518,0.017540,2 556.46 €,"Продава ПАРЦЕЛ в област Ловеч, с. Тепава - 100..."
161243,1s175033738856789,https://www.imot.bg/obiava-1s175033738856789-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, с. Пчелин",95000.00,345732.0,0.27,0.274779,0.017393,95 000 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Пче..."
138172,1r173018946969427,https://www.imot.bg/obiava-1r173018946969427-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, с. Бенковски, Тракия Икономиче...",18475.00,67031.0,0.28,0.275619,0.015896,18 475 €,"Продава ПАРЦЕЛ в област Пловдив, с. Бенковски ..."
131148,1r167931851525358,https://www.imot.bg/obiava-1r167931851525358-p...,ПАРЦЕЛ,област Русе,"област Русе, с. Писанец, Гимлийца",9900.00,32500.0,0.30,0.304615,0.015152,9 900 €,"Продава ПАРЦЕЛ в област Русе, с. Писанец - 325..."
129301,1r164614174065380,https://www.imot.bg/obiava-1r164614174065380-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1600.00,5600.0,0.29,0.285714,0.015000,1 600 €,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."
161486,1s175975386581408,https://www.imot.bg/obiava-1s175975386581408-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Плевен,"област Плевен, с. Николаево, до Магистралата",2658.72,26194.0,0.10,0.101501,0.014789,2 658.72 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Плевен, с. Ни..."
161422,1s175819638805908,https://www.imot.bg/obiava-1s175819638805908-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Стара Загора,"област Стара Загора, с. Кирилово, местност ВЪЛ...",205.00,1300.0,0.16,0.157692,0.014634,205 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора,..."
161057,1s174582430797703,https://www.imot.bg/obiava-1s174582430797703-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Горна Гращица",1380.00,8500.0,0.16,0.162353,0.014493,1 380 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
163069,1t169219786869638,https://www.imot.bg/obiava-1t169219786869638-p...,СОЛАРЕН ПАРК,област Варна,"област Варна, с. Генерал Киселово",80000.00,717243.0,0.11,0.111538,0.013791,80 000 €,"Продава СОЛАРЕН ПАРК в област Варна, с. Генера..."
126688,1r151119773445530,https://www.imot.bg/obiava-1r151119773445530-p...,ПАРЦЕЛ,област София,"област София, с. Караполци, м. Копанината",35050.00,345732.0,0.10,0.101379,0.013603,35 050 €,"Продава ПАРЦЕЛ в област София, с. Караполци - ..."
135052,1r171516251050830,https://www.imot.bg/obiava-1r171516251050830-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Стражица",3000.00,7998.0,0.38,0.375094,0.013080,3 000 €,"Продава ПАРЦЕЛ в област Велико Търново, гр. Ст..."
134470,1r171153791512892,https://www.imot.bg/obiava-1r171153791512892-p...,ПАРЦЕЛ,област Пазарджик,"област Пазарджик, м-т Цигов чарк",1111.00,2616.0,0.42,0.424694,0.011053,1 111 €,"Продава ПАРЦЕЛ в област Пазарджик, м-т Цигов ч..."
138684,1r173210477949657,https://www.imot.bg/obiava-1r173210477949657-p...,ПАРЦЕЛ,област Плевен,"област Плевен, с. Гривица",45000.00,189550.0,0.24,0.237404,0.010933,45 000 €,"Продава ПАРЦЕЛ в област Плевен, с. Гривица - 1..."
127382,1r156829059149246,https://www.imot.bg/obiava-1r156829059149246-p...,ПАРЦЕЛ,област Добрич,"област Добрич, гр. Балчик, фиш-фиш",40000.00,94000.0,0.43,0.425532,0.010500,40 000 €,"Продава ПАРЦЕЛ в област Добрич, гр. Балчик - 9..."
128462,1r162263913439041,https://www.imot.bg/obiava-1r162263913439041-p...,ПАРЦЕЛ,област Шумен,"област Шумен, гр. Нови пазар",14000.00,33000.0,0.42,0.424242,0.010000,14 000 €,"Продава ПАРЦЕЛ в област Шумен, гр. Нови пазар ..."

In [26]:
price_psqm_by_type = (
    df_candidate
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_ppsqm=("price_per_sqm", "min"),
        p01_ppsqm=("price_per_sqm", lambda s: s.quantile(0.01)),
        median_ppsqm=("price_per_sqm", "median"),
        p99_ppsqm=("price_per_sqm", lambda s: s.quantile(0.99)),
        max_ppsqm=("price_per_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(price_psqm_by_type)

,property_type_raw,rows,min_ppsqm,p01_ppsqm,median_ppsqm,p99_ppsqm,max_ppsqm,min_price,median_price,max_price
1,2-СТАЕН,33873,16.470000,741.3464,1692.310,4380.9968,9375.00,1400.00,115230.00,1200000.0
2,3-СТАЕН,33672,76.130000,700.0000,1785.710,4900.9367,210000.00,7500.00,180000.00,2190000.0
29,ПАРЦЕЛ,33451,0.010000,1.4800,44.210,981.0650,26947.89,250.00,80000.00,40000000.0
21,КЪЩА,23865,0.280000,60.7104,936.510,4400.7812,62000.00,55.00,130000.00,22995000.0
0,1-СТАЕН,6541,85.710000,712.7640,1577.780,4301.2300,89500.00,3000.00,66000.00,307860.0
3,4-СТАЕН,5276,204.520000,609.0650,1973.675,5884.4900,10292.89,20451.68,279952.50,2460000.0
23,МАГАЗИН,3404,13.460000,144.0375,1700.000,7096.1310,20370.37,3323.40,154500.00,12500000.0
25,МНОГОСТАЕН,3101,104.760000,488.2200,1809.520,6500.0000,10588.24,22000.00,291203.00,5000000.0
26,ОФИС,2377,8.110000,194.1616,1831.670,5501.7120,14990.00,4857.27,200000.00,16800000.0
19,ЗЕМЕДЕЛСКА ЗЕМЯ,2254,0.000431,0.0160,10.000,4485.4135,364497.91,31.00,50000.00,471195000.0
30,ПРОМ. ПОМЕЩЕНИЕ,1976,0.830000,10.0000,320.000,2907.4600,10000.00,3000.00,308250.00,15000000.0
17,ЕТАЖ ОТ КЪЩА,1848,0.710000,242.2713,1204.215,3900.0000,7111.11,4464.00,133000.00,1250000.0
13,ГАРАЖ,1558,68.510000,194.4400,1315.790,3729.6453,14076.92,3500.00,30000.00,792000.0
24,МЕЗОНЕТ,1383,235.040000,583.1438,1772.730,5057.9314,13750.00,36000.00,275000.00,2750000.0
11,ВИЛА,1110,3.090000,33.2117,875.000,8356.5003,310000.00,4500.00,53685.65,17500000.0
18,ЗАВЕДЕНИЕ,1061,21.050000,85.2840,1200.000,6000.0000,60500.00,8700.00,240000.00,4900000.0
43,ХОТЕЛ,1001,4.250000,29.6300,840.000,3800.0000,6923.08,18000.00,800000.00,12000000.0
32,СКЛАД,753,1.200000,15.6088,590.000,4390.0500,6752.61,2700.00,305000.00,22000000.0
28,ПАРКОМЯСТО,746,0.020000,290.6870,1283.750,3495.6345,6666.67,2750.00,23000.00,307000.0
31,САМОСТОЯТЕЛНА СГРАДА,480,5.180000,16.2512,618.390,4190.5046,6591.34,7000.00,420000.00,23267500.0
37,ФАБРИКА/ЗАВОД,251,1.250000,5.4350,191.280,2386.4000,5000.00,20000.00,766000.00,12500000.0
36,ТЪРГОВСКИ КОМПЛЕКС,213,3.000000,6.4396,619.830,4757.6132,6000.00,9714.55,435200.00,12500000.0
8,"АТЕЛИЕ, ТАВАН",198,266.670000,361.8975,1738.615,4380.0551,7750.00,10740.00,89200.00,319000.0
38,ФЕРМА,148,3.510000,5.4894,50.755,2346.3860,3330.17,8691.96,240000.00,7500000.0
41,ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,100,395.000000,464.1119,1675.000,5155.0975,10232.56,23500.00,107000.00,1730000.0
12,ВИЛНО СЕЛИЩЕ,97,6.930000,6.9588,264.710,3437.2848,5932.20,35000.00,450000.00,6267500.0
39,ФИТНЕС ЗАЛА,80,57.250000,105.6928,992.425,3580.7503,3920.00,22900.00,240000.00,4900000.0
5,АВТОСЕРВИЗ,76,2.060000,12.0200,728.360,5081.9275,5627.71,13191.33,270500.00,2800000.0
33,СОЛАРЕН ПАРК,64,0.110000,4.2554,50.000,528.5370,832.26,21474.26,127000.00,6267500.0
20,КЛИНИКА,62,19.500000,46.0350,1944.445,5502.9659,6000.00,55000.00,610392.50,3676000.0
22,ЛЕКАРСКИ КАБИНЕТ,62,431.210000,474.8616,2000.000,4917.8674,5223.88,22000.00,211250.00,4500000.0
34,СПА/СОЛАРНО СТУДИО,41,25.000000,50.4280,945.120,3135.2940,3225.49,31000.00,268000.00,2500000.0
10,БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ,39,3.830000,7.5768,183.330,2395.8610,2777.78,19100.00,260000.00,2199000.0
14,"ГАРАЖ, ПАРКОМЯСТО",35,57.140000,100.6124,764.710,2066.6696,2272.73,7000.00,15000.00,222000.0
15,ДЕТСКИ ЦЕНТЪР,35,21.440000,22.8408,1678.320,3013.6342,3072.92,10000.00,255000.00,5200000.0
16,ДОМ ЗА ВЪЗРАСТНИ ХОРА,31,31.250000,37.4870,317.290,2875.8630,3000.00,70000.00,630000.00,3700000.0
35,СТОМАТОЛОГИЧЕН КАБИНЕТ,29,557.100000,660.1120,1923.080,8640.1692,10232.56,65000.00,200000.00,2600000.0
9,БАНКОВ ОФИС,23,91.950000,104.0610,1716.870,5418.8912,5537.04,59309.86,409000.00,2780000.0
27,ПАРКИНГ,18,7.970000,8.2556,130.405,901.8339,950.00,11000.00,426162.50,3800000.0
7,АПТЕКА,16,328.360000,399.1060,2114.835,32627.3625,37500.00,69000.00,205990.00,2250000.0
4,АВТОМИВКА,10,41.670000,61.1955,615.685,1913.7692,2000.00,25000.00,494999.50,900000.0
42,ХЛАДИЛЕН СКЛАД,3,68.000000,78.4362,589.810,1284.5614,1298.74,220000.00,361050.00,557600.0
6,АКВАПАРК,2,35.140000,63.0903,1432.655,2802.2197,2830.17,130000.00,5125340.00,10120680.0
40,ФОТОГРАФСКО СТУДИО,1,1210.570000,1210.5700,1210.570,1210.5700,1210.57,148900.00,148900.00,148900.0

In [27]:
df_candidate["price_per_sqm_model"] = (
    df_candidate["total_price"] / df_candidate["area_sqm"]
)

In [28]:
# ------------------------------------------------------------
# Step 3A: Inspect extreme area values by property type
# ------------------------------------------------------------

area_by_type = (
    df_candidate
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        p01_area=("area_sqm", lambda s: s.quantile(0.01)),
        median_area=("area_sqm", "median"),
        p95_area=("area_sqm", lambda s: s.quantile(0.95)),
        p99_area=("area_sqm", lambda s: s.quantile(0.99)),
        max_area=("area_sqm", "max"),
        median_price=("total_price", "median"),
        median_ppsqm=("price_per_sqm_model", "median"),
    )
    .reset_index()
    .sort_values("max_area", ascending=False)
)

display(area_by_type)

,property_type_raw,rows,min_area,p01_area,median_area,p95_area,p99_area,max_area,median_price,median_ppsqm
29,ПАРЦЕЛ,33451,20.0,280.00,1908.0,17144.50,50835.50,4854710.0,80000.00,44.210526
19,ЗЕМЕДЕЛСКА ЗЕМЯ,2254,260.0,549.00,4272.5,303800.00,498470.00,3959900.0,50000.00,10.000000
28,ПАРКОМЯСТО,746,6.0,11.00,16.0,42.00,330.00,1000000.0,23000.00,1283.750000
33,СОЛАРЕН ПАРК,64,155.0,183.35,3195.0,66846.25,319060.95,717243.0,127000.00,50.000000
43,ХОТЕЛ,1001,9.0,165.00,1000.0,8000.00,17419.00,353199.0,800000.00,840.000000
21,КЪЩА,23865,1.0,38.64,148.0,490.00,1000.00,265000.0,130000.00,936.507937
12,ВИЛНО СЕЛИЩЕ,97,59.0,88.76,2000.0,22939.20,65080.00,235000.0,450000.00,264.705882
38,ФЕРМА,148,20.0,134.63,5042.5,63650.00,108000.00,180000.0,240000.00,50.755531
11,ВИЛА,1110,1.0,15.00,70.0,500.00,1118.20,175000.0,53685.65,875.000000
30,ПРОМ. ПОМЕЩЕНИЕ,1976,6.0,55.75,1099.5,15084.25,51200.00,150000.0,308250.00,320.000000
37,ФАБРИКА/ЗАВОД,251,67.0,159.50,3500.0,42400.00,75872.50,136000.0,766000.00,191.277735
17,ЕТАЖ ОТ КЪЩА,1848,20.0,42.00,105.0,213.30,328.48,120000.0,133000.00,1204.216867
32,СКЛАД,753,3.0,9.04,618.0,10208.40,35424.00,83000.0,305000.00,590.000000
36,ТЪРГОВСКИ КОМПЛЕКС,213,15.0,53.24,740.0,10179.20,29100.00,46000.0,435200.00,619.834711
31,САМОСТОЯТЕЛНА СГРАДА,480,22.0,46.53,878.5,6579.80,9559.75,31800.0,420000.00,618.392665
5,АВТОСЕРВИЗ,76,52.0,52.00,370.0,4412.75,13227.75,31017.0,270500.00,728.361864
34,СПА/СОЛАРНО СТУДИО,41,40.0,44.00,359.0,1000.00,18597.60,30000.0,268000.00,945.121951
27,ПАРКИНГ,18,400.0,434.00,3909.0,12754.20,16173.24,17028.0,426162.50,130.401535
18,ЗАВЕДЕНИЕ,1061,18.0,26.60,211.0,809.00,2500.00,11206.0,240000.00,1200.000000
16,ДОМ ЗА ВЪЗРАСТНИ ХОРА,31,290.0,290.60,1500.0,8281.00,9752.50,10375.0,630000.00,317.287234
20,КЛИНИКА,62,50.0,62.20,367.5,1991.90,5501.25,9695.0,610392.50,1944.444444
26,ОФИС,2377,10.0,15.00,106.0,779.20,2409.12,9000.0,200000.00,1831.666667
42,ХЛАДИЛЕН СКЛАД,3,278.0,279.90,373.0,7417.30,8043.46,8200.0,361050.00,589.812332
10,БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ,39,110.0,136.60,2000.0,5964.20,7487.62,8001.0,260000.00,183.333333
23,МАГАЗИН,3404,5.0,13.00,95.0,587.25,1364.55,5895.0,154500.00,1700.000000
1,2-СТАЕН,33873,14.0,40.00,68.0,95.00,125.00,4000.0,115230.00,1692.307692
15,ДЕТСКИ ЦЕНТЪР,35,55.0,56.70,192.0,2600.00,3524.00,4000.0,255000.00,1678.321678
6,АКВАПАРК,2,3576.0,3577.24,3638.0,3693.80,3698.76,3700.0,5125340.00,1432.651460
14,"ГАРАЖ, ПАРКОМЯСТО",35,11.0,11.34,20.0,441.20,2718.00,3500.0,15000.00,764.705882
4,АВТОМИВКА,10,191.0,198.38,500.0,2688.00,3321.60,3480.0,494999.50,615.686960
13,ГАРАЖ,1558,1.0,12.00,21.0,56.00,280.75,3200.0,30000.00,1315.789474
22,ЛЕКАРСКИ КАБИНЕТ,62,21.0,24.66,92.5,843.35,1706.80,3000.0,211250.00,2000.000000
39,ФИТНЕС ЗАЛА,80,78.0,79.58,240.0,833.75,1600.28,2918.0,240000.00,992.422727
35,СТОМАТОЛОГИЧЕН КАБИНЕТ,29,22.0,25.08,100.0,850.00,1678.00,2000.0,200000.00,1923.076923
25,МНОГОСТАЕН,3101,25.0,82.00,157.0,354.00,546.00,1930.0,291203.00,1809.523810
2,3-СТАЕН,33672,1.0,60.00,103.0,155.00,217.00,1450.0,180000.00,1785.714286
9,БАНКОВ ОФИС,23,70.0,71.10,289.0,1290.00,1300.00,1300.0,409000.00,1716.867470
0,1-СТАЕН,6541,1.0,20.00,42.0,64.00,86.00,1127.0,66000.00,1577.777778
24,МЕЗОНЕТ,1383,24.0,50.00,153.0,350.00,505.08,1071.0,275000.00,1772.727273
3,4-СТАЕН,5276,53.0,78.75,141.0,262.00,359.00,750.0,279952.50,1973.677632
41,ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,100,19.0,19.99,60.0,290.30,409.15,721.0,107000.00,1675.000000
8,"АТЕЛИЕ, ТАВАН",198,10.0,14.88,50.0,140.00,194.27,312.0,89200.00,1738.612836
7,АПТЕКА,16,44.0,44.30,92.5,280.75,304.15,310.0,205990.00,2114.832536
40,ФОТОГРАФСКО СТУДИО,1,123.0,123.00,123.0,123.00,123.00,123.0,148900.00,1210.569106

In [29]:
# ------------------------------------------------------------
# Step 3B: Manually inspect largest-area listings
# ------------------------------------------------------------

large_area_candidates = df_candidate.loc[
    df_candidate["area_sqm"].gt(df_candidate["area_sqm"].quantile(0.995))
].copy()

print("Large area candidates:", len(large_area_candidates))

display(
    large_area_candidates[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm_model",
            "price_raw",
            "title",
        ]
    ]
    .sort_values("area_sqm", ascending=False)
    .head(100)
)

Large area candidates: 794

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm_model,price_raw,title
132507,1r169452337555022,https://www.imot.bg/obiava-1r169452337555022-p...,ПАРЦЕЛ,област София,"област София, гр. Своге",7282065.00,4854710.0,1.500000,7 282 065 €,"Продава ПАРЦЕЛ в област София, гр. Своге - 485..."
161536,1s176155601035714,https://www.imot.bg/obiava-1s176155601035714-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Перник,"област Перник, гр. Трън, село Турковци",40903.35,3959900.0,0.010329,40 903.35 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Перник, гр. Т..."
148072,1r176155521345093,https://www.imot.bg/obiava-1r176155521345093-p...,ПАРЦЕЛ,област Перник,"област Перник, гр. Трън, Село Турковци",40903.35,3959900.0,0.010329,40 903.35 €,"Продава ПАРЦЕЛ в област Перник, гр. Трън - 395..."
129353,1r164760333818070,https://www.imot.bg/obiava-1r164760333818070-p...,ПАРЦЕЛ,област София,"област София, гр. Костинброд",30000000.00,1200000.0,25.000000,30 000 000 €,"Продава ПАРЦЕЛ в област София, гр. Костинброд ..."
157738,1r177944800076920,https://www.imot.bg/obiava-1r177944800076920-p...,ПАРЦЕЛ,област София,"област София, гр. Своге",499000.00,1035438.0,0.481922,499 000 €,"Продава ПАРЦЕЛ в област София, гр. Своге - 103..."
...,...,...,...,...,...,...,...,...,...,...
161007,1s174497706544349,https://www.imot.bg/obiava-1s174497706544349-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Брестовица",51000.00,400000.0,0.127500,51 000 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
162532,1s177909639235614,https://www.imot.bg/obiava-1s177909639235614-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Ловеч,"област Ловеч, с. Терзийско",35500.00,400000.0,0.088750,35 500 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Ловеч, с. Тер..."
160765,1s173978348446066,https://www.imot.bg/obiava-1s173978348446066-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Браниполе",100758.00,399000.0,0.252526,100 758 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
137080,1r172552687786745,https://www.imot.bg/obiava-1r172552687786745-p...,ПАРЦЕЛ,област Стара Загора,"област Стара Загора, с. Средно градище",21000.00,399000.0,0.052632,21 000 €,"Продава ПАРЦЕЛ в област Стара Загора, с. Средн..."
160216,1s171155127190158,https://www.imot.bg/obiava-1s171155127190158-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, гр. Асеновград",72500.00,392000.0,0.184949,72 500 €,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, гр. ..."

In [30]:
# ------------------------------------------------------------
# Step 3C: Segment large-area candidates by property type
# ------------------------------------------------------------

large_area_summary = (
    large_area_candidates
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        median_area=("area_sqm", "median"),
        max_area=("area_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
        median_ppsqm=("price_per_sqm_model", "median"),
        min_ppsqm=("price_per_sqm_model", "min"),
        max_ppsqm=("price_per_sqm_model", "max"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(large_area_summary)

,property_type_raw,rows,min_area,median_area,max_area,min_price,median_price,max_price,median_ppsqm,min_ppsqm,max_ppsqm
3,ЗЕМЕДЕЛСКА ЗЕМЯ,473,61000.0,168000.0,3959900.0,31.0,62888.90,471195000.0,0.364018,0.000431,1673.833333
6,ПАРЦЕЛ,274,60810.0,90000.0,4854710.0,8000.0,1499992.50,40000000.0,12.593240,0.010329,485.714997
7,ПРОМ. ПОМЕЩЕНИЕ,15,61000.0,80000.0,150000.0,100000.0,2035964.27,15000000.0,24.704706,0.833333,109.489051
11,ФЕРМА,9,63000.0,87284.0,180000.0,385000.0,3800000.00,7160000.0,35.185185,5.500000,82.031071
10,ФАБРИКА/ЗАВОД,6,61000.0,75872.5,136000.0,110000.0,1182780.00,1800000.0,13.041592,1.250000,27.052617
9,СОЛАРЕН ПАРК,5,64496.0,71677.0,717243.0,80000.0,670250.00,2700000.0,10.392117,0.111538,37.668987
8,СКЛАД,4,65455.0,65455.0,83000.0,100000.0,22000000.00,22000000.0,336.108777,1.204819,336.108777
12,ХОТЕЛ,2,73000.0,213099.5,353199.0,5000000.0,5750000.00,6500000.0,51.598711,14.156325,89.041096
0,ВИЛА,2,175000.0,175000.0,175000.0,540000.0,540000.00,540000.0,3.085714,3.085714,3.085714
4,КЪЩА,1,265000.0,265000.0,265000.0,265000.0,265000.00,265000.0,1.000000,1.000000,1.000000
2,ЕТАЖ ОТ КЪЩА,1,120000.0,120000.0,120000.0,85000.0,85000.00,85000.0,0.708333,0.708333,0.708333
1,ВИЛНО СЕЛИЩЕ,1,235000.0,235000.0,235000.0,1635344.0,1635344.00,1635344.0,6.958911,6.958911,6.958911
5,ПАРКОМЯСТО,1,1000000.0,1000000.0,1000000.0,16000.0,16000.00,16000.0,0.016000,0.016000,0.016000

In [31]:
# Drop absurd large-area parking spot
before_rows = len(df_candidate)

drop_mask = df_candidate["ad_id"].eq("1o176373075998653")

dropped_large_parking = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_large_parking[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm_model",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_absurd_large_parking_area",
    "reason": "Manually inspected ПАРКОМЯСТО listing has impossible 1,000,000 sqm area and is not valid for regression training",
    "rows_affected": len(dropped_large_parking),
})

Dropped rows: 1
Candidate rows before: 161364
Candidate rows after: 161363

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm_model,title
120964,1o176373075998653,https://www.imot.bg/obiava-1o176373075998653-p...,ПАРКОМЯСТО,град Варна,"град Варна, Виница",16000.0,1000000.0,0.016,"Продава ПАРКОМЯСТО в град Варна, Виница - 1000..."

In [32]:
df_candidate.head(5)

,ad_id,ad_url,ad_url_path,ad_url_slug,html_path,listing_type,title,deal_raw,property_type_raw,title_city_raw,...,parse_error,area_unit_suspected,area_sqm_corrected,price_per_sqm_corrected,area_sqm_original,price_per_sqm_original,price_per_sqm_recalc,price_per_sqm_diff_abs,price_per_sqm_diff_pct,price_per_sqm_model
0,1a155107752004273,https://www.imot.bg/obiava-1a155107752004273-p...,/obiava-1a155107752004273-prodava-ednostaen-ap...,obiava-1a155107752004273-prodava-ednostaen-apa...,data\raw_listing_html\948e49be77a55a7a.html,single_property_listing,"Продава 1-СТАЕН в област Пазарджик, гр. Велинг...",Продава,1-СТАЕН,област Пазарджик,...,NaN,None,44.0,1297.73,NaN,NaN,1297.727273,0.002727,2.101576e-06,1297.727273
1,1a146979303032401,https://www.imot.bg/obiava-1a146979303032401-p...,/obiava-1a146979303032401-prodava-ednostaen-ap...,obiava-1a146979303032401-prodava-ednostaen-apa...,data\raw_listing_html\9b4948bfbf128a8a.html,single_property_listing,"Продава 1-СТАЕН в град София, Малинова долина ...",Продава,1-СТАЕН,град София,...,NaN,None,36.0,2861.11,NaN,NaN,2861.111111,0.001111,3.883495e-07,2861.111111
2,1a140680337846667,https://www.imot.bg/obiava-1a140680337846667-p...,/obiava-1a140680337846667-prodava-ednostaen-ap...,obiava-1a140680337846667-prodava-ednostaen-apa...,data\raw_listing_html\d014b1815f2f9c9b.html,single_property_listing,"Продава 1-СТАЕН в град Варна, м-т Ален мак - 3...",Продава,1-СТАЕН,град Варна,...,NaN,None,30.0,500.00,NaN,NaN,500.000000,0.000000,0.000000e+00,500.000000
3,1a154997703660554,https://www.imot.bg/obiava-1a154997703660554-p...,/obiava-1a154997703660554-prodava-ednostaen-ap...,obiava-1a154997703660554-prodava-ednostaen-apa...,data\raw_listing_html\6a625253f270be91.html,single_property_listing,"Продава 1-СТАЕН в област Бургас, гр. Свети Вла...",Продава,1-СТАЕН,област Бургас,...,NaN,None,48.0,1533.33,NaN,NaN,1533.333333,0.003333,2.173913e-06,1533.333333
4,1a155107630313014,https://www.imot.bg/obiava-1a155107630313014-p...,/obiava-1a155107630313014-prodava-ednostaen-ap...,obiava-1a155107630313014-prodava-ednostaen-apa...,data\raw_listing_html\a31953e77840ec11.html,single_property_listing,"Продава 1-СТАЕН в област Пазарджик, гр. Велинг...",Продава,1-СТАЕН,област Пазарджик,...,NaN,None,48.0,1087.50,NaN,NaN,1087.500000,0.000000,0.000000e+00,1087.500000

In [33]:
# ------------------------------------------------------------
# Drop irrelevant / raw / debug columns for ML working dataset
# Keep features_pipe for later feature engineering
# ------------------------------------------------------------

before_cols = df_candidate.shape[1]

irrelevant_columns = [
    # identifiers / technical tracking
    "ad_url_path",
    "ad_url_slug",
    "html_path",
    "title_ad_id",
    "parse_error",
    "parsed_at",

    # raw text fields not ready for structured regression
    "title",
    "description_raw",
    "description_clean",
    "features_raw",

    # duplicate / raw fields after structured parsing
    "deal_raw",
    "price_raw",
    "area_raw",
    "floor_raw",
    "construction_raw",

    # redundant price fields
    "title_price_eur",
    "title_price_bgn",

    # not needed after filtering candidate set
    "training_eligible",
]

columns_to_drop = [
    col for col in irrelevant_columns
    if col in df_candidate.columns
]

df_model_base = df_candidate.drop(columns=columns_to_drop).copy()

after_cols = df_model_base.shape[1]

print("Rows:", len(df_model_base))
print("Columns before:", before_cols)
print("Columns dropped:", len(columns_to_drop))
print("Columns after:", after_cols)

print("\nDropped columns:")
print(columns_to_drop)

print("\nRemaining columns:")
print(df_model_base.columns.tolist())

cleanup_actions.append({
    "rule": "drop_irrelevant_raw_debug_columns",
    "reason": "Removed raw parser fields, redundant fields, technical tracking fields, and text columns not yet prepared for structured regression; kept features_pipe for later feature engineering",
    "rows_affected": 0,
    "columns_affected": len(columns_to_drop),
})

Rows: 161363
Columns before: 48
Columns dropped: 17
Columns after: 31

Dropped columns:
['ad_url_path', 'ad_url_slug', 'html_path', 'title_ad_id', 'parse_error', 'title', 'description_raw', 'description_clean', 'features_raw', 'deal_raw', 'price_raw', 'area_raw', 'floor_raw', 'construction_raw', 'title_price_eur', 'title_price_bgn', 'training_eligible']

Remaining columns:
['ad_id', 'ad_url', 'listing_type', 'property_type_raw', 'title_city_raw', 'title_geo_2_raw', 'title_area_sqm', 'seller_name_raw', 'total_price', 'currency', 'vat_status', 'area_sqm', 'price_per_sqm', 'floor', 'total_floors', 'construction_type', 'construction_year', 'location_raw', 'features_pipe', 'features_count', 'published_raw', 'views', 'area_unit_suspected', 'area_sqm_corrected', 'price_per_sqm_corrected', 'area_sqm_original', 'price_per_sqm_original', 'price_per_sqm_recalc', 'price_per_sqm_diff_abs', 'price_per_sqm_diff_pct', 'price_per_sqm_model']

In [34]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 161363 entries, 0 to 164669
Data columns (total 31 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    161363 non-null  object
 1   ad_url                   161363 non-null  object
 2   listing_type             161363 non-null  object
 3   property_type_raw        161363 non-null  object
 4   title_city_raw           161363 non-null  object
 5   title_geo_2_raw          161360 non-null  object
 6   title_area_sqm           159109 non-null  float64
 7   seller_name_raw          151009 non-null  object
 8   total_price              161363 non-null  float64
 9   currency                 161363 non-null  object
 10  vat_status               161363 non-null  object
 11  area_sqm                 161363 non-null  float64
 12  price_per_sqm            161363 non-null  float64
 13  floor                    99857 non-null   float64
 14  total_floors             92202 non-null   float64
 15  construction_type        124084 non-null  object
 16  construction_year        161363 non-null  int64
 17  location_raw             161363 non-null  object
 18  features_pipe            142390 non-null  object
 19  features_count           161363 non-null  int64
 20  published_raw            42672 non-null   object
 21  views                    161363 non-null  float64
 22  area_unit_suspected      180 non-null     object
 23  area_sqm_corrected       161363 non-null  float64
 24  price_per_sqm_corrected  161363 non-null  float64
 25  area_sqm_original        577 non-null     float64
 26  price_per_sqm_original   577 non-null     float64
 27  price_per_sqm_recalc     161363 non-null  float64
 28  price_per_sqm_diff_abs   161363 non-null  float64
 29  price_per_sqm_diff_pct   161363 non-null  float64
 30  price_per_sqm_model      161363 non-null  float64
dtypes: float64(15), int64(2), object(14)
memory usage: 39.4+ MB

In [35]:
# ------------------------------------------------------------
# Finalize corrected area / price fields for ML base dataset
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

# Preserve original scraped values only in df_candidate, not in ML base.
diagnostic_columns = [
    "area_unit_suspected",
    "area_sqm_original",
    "price_per_sqm_original",
    "price_per_sqm_recalc",
    "price_per_sqm_diff_abs",
    "price_per_sqm_diff_pct",
    "price_per_sqm_model",
]

columns_to_drop = [
    col for col in diagnostic_columns
    if col in df_model_base.columns
]

df_model_base = df_model_base.drop(columns=columns_to_drop)

# Replace raw area/price_per_sqm with corrected modeling versions
df_model_base["area_sqm_raw"] = df_model_base["area_sqm"]
df_model_base["price_per_sqm_raw"] = df_model_base["price_per_sqm"]

df_model_base["area_sqm"] = df_model_base["area_sqm_corrected"]
df_model_base["price_per_sqm"] = df_model_base["price_per_sqm_corrected"]

df_model_base = df_model_base.drop(
    columns=[
        "area_sqm_corrected",
        "price_per_sqm_corrected",
    ]
)

print("Rows:", len(df_model_base))
print("Columns:", df_model_base.shape[1])
print("Dropped diagnostic columns:", columns_to_drop)

display(df_model_base.info())

cleanup_actions.append({
    "rule": "finalize_corrected_area_price_fields",
    "reason": "Replaced raw area and price-per-sqm with corrected modeling fields and removed diagnostic cleanup columns",
    "rows_affected": 0,
    "columns_affected": len(columns_to_drop),
})

Rows: 161363
Columns: 24
Dropped diagnostic columns: ['area_unit_suspected', 'area_sqm_original', 'price_per_sqm_original', 'price_per_sqm_recalc', 'price_per_sqm_diff_abs', 'price_per_sqm_diff_pct', 'price_per_sqm_model']
<class 'pandas.core.frame.DataFrame'>
Index: 161363 entries, 0 to 164669
Data columns (total 24 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              161363 non-null  object
 1   ad_url             161363 non-null  object
 2   listing_type       161363 non-null  object
 3   property_type_raw  161363 non-null  object
 4   title_city_raw     161363 non-null  object
 5   title_geo_2_raw    161360 non-null  object
 6   title_area_sqm     159109 non-null  float64
 7   seller_name_raw    151009 non-null  object
 8   total_price        161363 non-null  float64
 9   currency           161363 non-null  object
 10  vat_status         161363 non-null  object
 11  area_sqm           161363 non-null  float64
 12  price_per_sqm      161363 non-null  float64
 13  floor              99857 non-null   float64
 14  total_floors       92202 non-null   float64
 15  construction_type  124084 non-null  object
 16  construction_year  161363 non-null  int64
 17  location_raw       161363 non-null  object
 18  features_pipe      142390 non-null  object
 19  features_count     161363 non-null  int64
 20  published_raw      42672 non-null   object
 21  views              161363 non-null  float64
 22  area_sqm_raw       161363 non-null  float64
 23  price_per_sqm_raw  161363 non-null  float64
dtypes: float64(9), int64(2), object(13)
memory usage: 30.8+ MB

None

In [36]:
df_model_base.title_city_raw.value_counts()

title_city_raw
град София               34392
област Бургас            18177
град Варна               17359
град Пловдив             17136
област Пловдив            7929
област София              5041
град Бургас               4458
област Велико Търново     3965
област Варна              3724
град Стара Загора         3483
област Добрич             3460
град Русе                 3105
град Плевен               2817
област Благоевград        2749
град Шумен                2690
област Стара Загора       2099
град Велико Търново       2049
област Пазарджик          1964
област Габрово            1732
област Ловеч              1636
област Перник             1616
град Кърджали             1317
град Перник               1239
област Шумен              1106
област Русе               1104
област Плевен             1055
град Враца                 992
област Кюстендил           973
област Хасково             854
Гърция                     842
град Благоевград           825
град Габрово               808
град Добрич                804
област Смолян              800
град Пазарджик             793
град Хасково               716
област Враца               588
град Търговище             570
област Кърджали            540
област Монтана             344
град Разград               334
град Монтана               333
град Видин                 312
област Видин               290
град Ловеч                 285
град Сливен                258
област Ямбол               249
област Търговище           241
град Ямбол                 202
област Сливен              202
град Смолян                200
град Кюстендил             191
област Разград             161
област Силистра            157
град Силистра               97
Name: count, dtype: int64

In [37]:
df_model_base.title_geo_2_raw.value_counts()

title_geo_2_raw
Център               10759
к.к. Слънчев бряг     3051
гр. Свети Влас        2533
Христо Смирненски     2386
Малинова долина       2337
                     ...
с. Песочница             1
с. Паисиево              1
с. Балювица              1
с. Тумбалово             1
с. Падеш                 1
Name: count, Length: 3656, dtype: int64

In [38]:
# Inspect current geo fields before any mapping
geo_inspect = df_model_base[
    [
        "title_city_raw",
        "title_geo_2_raw",
        "location_raw",
    ]
].copy()

print("Unique title_city_raw:", geo_inspect["title_city_raw"].nunique(dropna=False))
print("Unique title_geo_2_raw:", geo_inspect["title_geo_2_raw"].nunique(dropna=False))
print("Unique location_raw:", geo_inspect["location_raw"].nunique(dropna=False))

print("\nTop cities:")
display(
    geo_inspect["title_city_raw"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
)

print("\nTop geo_2:")
display(
    geo_inspect["title_geo_2_raw"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("title_geo_2_raw")
    .reset_index(name="rows")
)

print("\nSample location_raw:")
display(
    geo_inspect["location_raw"]
    .dropna()
    .sample(30, random_state=42)
    .reset_index(drop=True)
)

Unique title_city_raw: 55
Unique title_geo_2_raw: 3657
Unique location_raw: 16613

Top cities:

           title_city_raw   rows
0              град София  34392
1           област Бургас  18177
2              град Варна  17359
3            град Пловдив  17136
4          област Пловдив   7929
5            област София   5041
6             град Бургас   4458
7   област Велико Търново   3965
8            област Варна   3724
9       град Стара Загора   3483
10          област Добрич   3460
11              град Русе   3105
12            град Плевен   2817
13     област Благоевград   2749
14             град Шумен   2690
15    област Стара Загора   2099
16    град Велико Търново   2049
17       област Пазарджик   1964
18         област Габрово   1732
19           област Ловеч   1636
20          област Перник   1616
21          град Кърджали   1317
22            град Перник   1239
23           област Шумен   1106
24            област Русе   1104
25          област Плевен   1055
26             град Враца    992
27       област Кюстендил    973
28         област Хасково    854
29                 Гърция    842

Top geo_2:

          title_geo_2_raw   rows
0                  Център  10759
1       к.к. Слънчев бряг   3051
2          гр. Свети Влас   2533
3       Христо Смирненски   2386
4         Малинова долина   2337
5                Кършияка   2314
6                  Тракия   2082
7             гр. Созопол   1837
8               Остромила   1656
9      Манастирски ливади   1631
10            гр. Поморие   1622
11            Кючук Париж   1582
12           Широк център   1428
13                 Виница   1400
14             гр. Банско   1332
15          Кръстова вада   1331
16                 Витоша   1162
17        Промишлена зона   1126
18             Овча купел   1089
19            гр. Несебър   1040
20               с. Равда   1011
21                 Изгрев   1008
22             гр. Балчик    939
23                   Бриз    927
24         Идеален център    904
25                  Бояна    900
26             Беломорски    850
27      Индустриална зона    838
28  Владислав Варненчик 1    815
29               Дружба 1    813
30             с. Марково    812
31               гр. Бяла    796
32               Дружба 2    786
33             гр. Царево    782
34              гр. Банкя    777
35          гр. Приморско    747
36         гр. Асеновград    739
37                Лозенец    737
38       Кайсиева градина    735
39             Аспарухово    718
40        Студентски град    710
41           Меден рудник    683
42             Драгалевци    680
43                  Изток    663
44              Младост 4    657
45              Младост 1    655
46               Сарафово    655
47                   Южен    644
48               с. Лозен    633
49                Гагарин    632

Sample location_raw:

0                               град Варна, Бриз
1                       град Варна, Възраждане 4
2                 град София, Манастирски ливади
3                           град София, Банишора
4     област Велико Търново, гр. Горна Оряховица
5                             град Варна, Галата
6                       град София, Овча купел 1
7                      град София, Хаджи Димитър
8                    област Пловдив, гр. Карлово
9                          град Пловдив, Гагарин
10                      град Русе, Здравец Изток
11             област Стара Загора, с. Козаревец
12          град София, Овча купел, ул. Драгоман
13                град София, Манастирски ливади
14                  град Варна, к.к. Слънчев ден
15                              град Варна, Бриз
16            област Велико Търново, с. Шереметя
17            област Велико Търново, с. Къпиново
18                     град Варна, м-т Ментешето
19              област Бургас, к.к. Слънчев бряг
20                             град Враца, Вежен
21              област Велико Търново, гр. Елена
22                       област Варна, с. Кичево
23                 град Бургас, Братя Миладинови
24                      град Варна, м-т Ален мак
25                     област Добрич, с. Божурец
26                област Стара Загора, с. Шаново
27                   област Пловдив, гр. Карлово
28               област Благоевград, с. Капатово
29                 област Бургас, гр. Свети Влас
Name: location_raw, dtype: object

In [39]:
# ------------------------------------------------------------
# Step: Split location_raw into hierarchical location levels
# No dropping, no bucketing yet
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

location_parts = (
    df_model_base["location_raw"]
    .fillna("")
    .astype(str)
    .str.split(",", expand=True)
)

df_model_base["location_level_1"] = location_parts[0].str.strip()
df_model_base["location_level_2"] = location_parts[1].str.strip() if location_parts.shape[1] > 1 else None
df_model_base["location_level_3"] = location_parts[2].str.strip() if location_parts.shape[1] > 2 else None

for col in ["location_level_1", "location_level_2", "location_level_3"]:
    df_model_base[col] = df_model_base[col].replace({"": None, "nan": None, "None": None})

print("Unique location_level_1:", df_model_base["location_level_1"].nunique(dropna=False))
print("Unique location_level_2:", df_model_base["location_level_2"].nunique(dropna=False))
print("Unique location_level_3:", df_model_base["location_level_3"].nunique(dropna=False))

print("\nTop level 1:")
display(
    df_model_base["location_level_1"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("location_level_1")
    .reset_index(name="rows")
)

print("\nTop level 2:")
display(
    df_model_base["location_level_2"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2")
    .reset_index(name="rows")
)

print("\nTop level 3:")
display(
    df_model_base["location_level_3"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_3")
    .reset_index(name="rows")
)

Unique location_level_1: 271
Unique location_level_2: 3851
Unique location_level_3: 9784

Top level 1:

         location_level_1   rows
0              град София  34340
1           област Бургас  18082
2              град Варна  17322
3            град Пловдив  17131
4          област Пловдив   7921
5            област София   5034
6             град Бургас   4453
7   област Велико Търново   3963
8            област Варна   3720
9           област Добрич   3458
10      град Стара Загора   3415
11              град Русе   3105
12            град Плевен   2817
13     област Благоевград   2746
14             град Шумен   2677
15    област Стара Загора   2089
16    град Велико Търново   2049
17       област Пазарджик   1959
18         област Габрово   1731
19           област Ловеч   1632
20          област Перник   1615
21          град Кърджали   1317
22            град Перник   1239
23            област Русе   1104
24           област Шумен   1103
25          област Плевен   1055
26             град Враца    992
27       област Кюстендил    972
28         област Хасково    853
29                 Гърция    841

Top level 2:

         location_level_2   rows
0                  Център  10735
1       к.к. Слънчев бряг   3023
2          гр. Свети Влас   2506
3       Христо Смирненски   2386
4         Малинова долина   2337
5                Кършияка   2314
6                  Тракия   2082
7             гр. Созопол   1833
8               Остромила   1654
9      Манастирски ливади   1631
10            гр. Поморие   1617
11            Кючук Париж   1582
12           Широк център   1426
13                 Виница   1390
14             гр. Банско   1332
15          Кръстова вада   1330
16                 Витоша   1162
17             Овча купел   1083
18            гр. Несебър   1035
19                 Изгрев   1008
20               с. Равда   1004
21             гр. Балчик    939
22                   Бриз    927
23         Идеален център    902
24                  Бояна    898
25             Беломорски    850
26               Дружба 1    813
27  Владислав Варненчик 1    812
28             с. Марково    810
29               гр. Бяла    796
30               Дружба 2    786
31             гр. Царево    782
32              гр. Банкя    776
33          гр. Приморско    741
34         гр. Асеновград    739
35                Лозенец    735
36       Кайсиева градина    735
37             Аспарухово    718
38        Студентски град    709
39             Драгалевци    680
40                  Изток    663
41              Младост 4    656
42              Младост 1    655
43               Сарафово    655
44                   Южен    643
45                Гагарин    632
46               с. Лозен    632
47               Банишора    617
48          гр. Велинград    602
49            с. Кошарица    586

Top level 3:

             location_level_3    rows
0                        None  136321
1                      Център     493
2                      център     262
3       бул. Симеоновско шосе     149
4                 Гребна база     129
5             бул. Черни връх     123
6                     Гагарин     112
7                        Южен     106
8                      Пощата      96
9        ул. Околовръстен път      93
10              бул. България      87
11                  Остромила      86
12                        ВМИ      86
13                бул. 'Южен'      81
14                      центр      79
15                    ул. Рая      77
16           бул. Иван Иванов      75
17     бул. Ботевградско шосе      75
18            Коматевско шосе      73
19         бул. Цар Борис III      72
20      бул. Ал. Стамболийски      69
21              бул. Сливница      67
22                  бул. Южен      63
23             ул. Монтевидео      62
24           Коматевски възел      61
25                    Кабакум      59
26                бул. Витоша      58
27               ул. Луи Айер      58
28          ул. Димитър Пешев      57
29             Идеален център      57
30               Широк център      54
31                     ЦЕНТЪР      53
32                   Общината      52
33        бул.  3-ти март  54      52
34    бул. Александър Малинов      52
35  бул. Проф. Цветан Лазаров      51
36                     Каваци      50
37             ул. Цар Симеон      49
38            Автогара Родопи      48
39               ул. Обиколна      47
40                бул. Европа      47
41           х-л Ст.Петербург      46
42                Стария град      46
43                  улица Рая      46
44  бул. Св. Климент Охридски      45
45                   Герджика      45
46                     Пазара      45
47          ул. Георги Райчев      44
48                   Новотела      43
49        ул. Тодор Каблешков      43

In [40]:
# ------------------------------------------------------------
# Normalize location levels lightly
# Keep it conservative: strip whitespace and lowercase only for model versions
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

for col in ["location_level_1", "location_level_2", "location_level_3"]:
    model_col = f"{col}_model"
    
    df_model_base[model_col] = (
        df_model_base[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

    df_model_base[model_col] = df_model_base[model_col].replace(
        {
            "": pd.NA,
            "none": pd.NA,
            "nan": pd.NA,
        }
    )

print("Unique location_level_1_model:", df_model_base["location_level_1_model"].nunique(dropna=False))
print("Unique location_level_2_model:", df_model_base["location_level_2_model"].nunique(dropna=False))
print("Unique location_level_3_model:", df_model_base["location_level_3_model"].nunique(dropna=False))

print("\nTop location_level_1_model:")
display(
    df_model_base["location_level_1_model"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("location_level_1_model")
    .reset_index(name="rows")
)

print("\nTop location_level_2_model:")
display(
    df_model_base["location_level_2_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2_model")
    .reset_index(name="rows")
)

Unique location_level_1_model: 269
Unique location_level_2_model: 3848
Unique location_level_3_model: 8941

Top location_level_1_model:

   location_level_1_model   rows
0              град софия  34340
1           област бургас  18082
2              град варна  17322
3            град пловдив  17131
4          област пловдив   7921
5            област софия   5034
6             град бургас   4453
7   област велико търново   3963
8            област варна   3720
9           област добрич   3458
10      град стара загора   3415
11              град русе   3105
12            град плевен   2817
13     област благоевград   2746
14             град шумен   2677
15    област стара загора   2089
16    град велико търново   2049
17       област пазарджик   1959
18         област габрово   1731
19           област ловеч   1632
20          област перник   1615
21          град кърджали   1317
22            град перник   1239
23            област русе   1104
24           област шумен   1103
25          област плевен   1055
26             град враца    992
27       област кюстендил    972
28         област хасково    853
29                 гърция    841

Top location_level_2_model:

   location_level_2_model   rows
0                  център  10735
1       к.к. слънчев бряг   3023
2          гр. свети влас   2506
3       христо смирненски   2386
4         малинова долина   2337
5                кършияка   2314
6                  тракия   2082
7             гр. созопол   1833
8               остромила   1654
9      манастирски ливади   1631
10            гр. поморие   1617
11            кючук париж   1582
12           широк център   1426
13                 виница   1390
14             гр. банско   1332
15          кръстова вада   1330
16                 витоша   1162
17             овча купел   1083
18            гр. несебър   1035
19                 изгрев   1008
20               с. равда   1004
21             гр. балчик    939
22                   бриз    927
23         идеален център    902
24                  бояна    898
25             беломорски    850
26               дружба 1    813
27  владислав варненчик 1    812
28             с. марково    810
29               гр. бяла    796
30               дружба 2    786
31             гр. царево    782
32              гр. банкя    776
33          гр. приморско    741
34         гр. асеновград    739
35       кайсиева градина    735
36                лозенец    735
37             аспарухово    718
38        студентски град    709
39             драгалевци    680
40                  изток    663
41              младост 4    656
42              младост 1    655
43               сарафово    655
44                   южен    643
45               с. лозен    632
46                гагарин    632
47               банишора    617
48          гр. велинград    602
49            с. кошарица    586

In [41]:
# ------------------------------------------------------------
# Create interpretable geo category bucket
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

capital_center_areas = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}

large_regional_cities = {
    "град пловдив",
    "град варна",
    "град бургас",
}

regional_cities = {
    "град русе",
    "град стара загора",
    "град плевен",
    "град велико търново",
    "град шумен",
    "град добрич",
    "град сливен",
    "град хасково",
    "град ямбол",
    "град перник",
    "град благоевград",
    "град пазарджик",
    "град врачa",
    "град враца",
    "град габрово",
    "град кърджали",
    "град кюстендил",
    "град ловеч",
    "град монтана",
    "град разград",
    "град силистра",
    "град смолян",
    "град търговище",
    "град видин",
}

sea_resorts = {
    "свети влас",
    "слънчев бряг",
    "несебър",
    "поморие",
    "равда",
    "созопол",
    "черноморец",
    "приморско",
    "китен",
    "лозенец",
    "царево",
    "ахтопол",
    "обзор",
    "бяла",
    "златни пясъци",
    "св. св. константин и елена",
    "св. константин",
    "кабакум",
    "албена",
    "кранево",
    "балчик",
    "кавaрна",
    "каварна",
    "шкорпиловци",
    "синеморец",
    "дюни",
    "еленѝте",
    "елените",
}

mountain_resorts = {
    "банско",
    "разлог",
    "добринище",
    "боровец",
    "самоков",
    "пампорово",
    "чепеларе",
    "смолян",
    "велинград",
    "сапарева баня",
    "трявна",
    "априлци",
    "троян",
}


def map_geo_category(row):
    level_1 = row.get("location_level_1_model")
    level_2 = row.get("location_level_2_model")

    level_1 = "" if pd.isna(level_1) else str(level_1).strip().lower()
    level_2 = "" if pd.isna(level_2) else str(level_2).strip().lower()

    # 1/2. Sofia split into center vs non-center
    if level_1 == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # 5. Sea resort: check both levels
    if level_1 in sea_resorts or level_2 in sea_resorts:
        return "sea_resort"

    # 6. Mountain resort: check both levels
    if level_1 in mountain_resorts or level_2 in mountain_resorts:
        return "mountain_resort"

    # 3. Large regional city
    if level_1 in large_regional_cities:
        return "large_regional_city"

    # 4. Regional city
    if level_1 in regional_cities:
        return "regional_city"

    # 8. Village / settlement under oblast
    if level_1.startswith("област ") and (
        level_2.startswith("с. ")
        or level_2.startswith("село ")
    ):
        return "village"

    # 7. Smaller city/town under oblast
    if level_1.startswith("област ") and (
        level_2.startswith("гр. ")
        or level_2.startswith("град ")
    ):
        return "small_city"

    # 7. Other city
    if level_1.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nGeo category by property type:")
display(
    pd.crosstab(
        df_model_base["geo_category"],
        df_model_base["property_type_raw"],
        margins=True
    )
)

cleanup_actions.append({
    "rule": "create_geo_category_bucket",
    "reason": "Mapped hierarchical location fields into interpretable market-location buckets for regression modeling",
    "rows_affected": 0,
    "columns_added": 1,
})

Geo category distribution:

          geo_category   rows
0  large_regional_city  38906
1              village  31867
2   capital_non_center  28923
3           small_city  26731
4        regional_city  24236
5       capital_center   5417
6        other_unknown   5187
7      mountain_resort     87
8           sea_resort      9

Geo category by property type:

property_type_raw,1-СТАЕН,2-СТАЕН,3-СТАЕН,4-СТАЕН,АВТОМИВКА,АВТОСЕРВИЗ,АКВАПАРК,АПТЕКА,"АТЕЛИЕ, ТАВАН",БАНКОВ ОФИС,...,СТОМАТОЛОГИЧЕН КАБИНЕТ,ТЪРГОВСКИ КОМПЛЕКС,ФАБРИКА/ЗАВОД,ФЕРМА,ФИТНЕС ЗАЛА,ФОТОГРАФСКО СТУДИО,ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,ХЛАДИЛЕН СКЛАД,ХОТЕЛ,All
geo_category,,,,,,,,,,,,,,,,,,,,,
capital_center,139,1240,1894,475,0,0,0,0,22,3,...,5,10,0,0,8,0,14,0,11,5417
capital_non_center,871,6739,8490,1680,0,10,0,2,56,5,...,6,20,15,3,27,0,17,0,22,28923
large_regional_city,1323,13407,12116,1436,5,5,0,7,25,5,...,9,15,14,1,15,1,27,0,102,38906
mountain_resort,2,13,17,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,87
other_unknown,1003,1320,1122,97,0,0,0,0,4,1,...,0,4,3,0,0,0,0,0,72,5187
regional_city,763,4576,6049,1046,2,36,0,3,70,2,...,9,59,69,5,24,0,33,2,63,24236
sea_resort,0,1,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
small_city,2084,5600,3330,482,3,12,0,3,18,7,...,0,59,100,37,6,0,9,1,435,26731
village,356,977,650,52,0,13,2,1,3,0,...,0,46,50,102,0,0,0,0,294,31867
All,6541,33873,33672,5276,10,76,2,16,198,23,...,29,213,251,148,80,1,100,3,1001,161363

In [42]:
# ------------------------------------------------------------
# Improved geo category mapping with settlement prefix normalization
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

def normalize_settlement_name(value):
    if pd.isna(value):
        return ""

    value = str(value).strip().lower()
    value = value.replace("ё", "е")
    value = value.replace("̀", "")
    value = value.replace("'", "")
    value = value.replace('"', "")
    value = " ".join(value.split())

    prefixes = [
        "гр. ",
        "град ",
        "с. ",
        "село ",
        "к.к. ",
        "кк ",
        "курорт ",
        "в.з. ",
        "м-т ",
        "м. ",
        "местност ",
    ]

    changed = True
    while changed:
        changed = False
        for prefix in prefixes:
            if value.startswith(prefix):
                value = value[len(prefix):].strip()
                changed = True

    return value


df_model_base["location_level_1_norm"] = df_model_base["location_level_1_model"].apply(
    normalize_settlement_name
)

df_model_base["location_level_2_norm"] = df_model_base["location_level_2_model"].apply(
    normalize_settlement_name
)

df_model_base["location_level_3_norm"] = df_model_base["location_level_3_model"].apply(
    normalize_settlement_name
)


capital_center_areas = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}

large_regional_cities = {
    "пловдив",
    "варна",
    "бургас",
}

regional_cities = {
    "русе",
    "стара загора",
    "плевен",
    "велико търново",
    "шумен",
    "добрич",
    "сливен",
    "хасково",
    "ямбол",
    "перник",
    "благоевград",
    "пазарджик",
    "враца",
    "габрово",
    "кърджали",
    "кюстендил",
    "ловеч",
    "монтана",
    "разград",
    "силистра",
    "смолян",
    "търговище",
    "видин",
}

sea_resorts = {
    "свети влас",
    "слънчев бряг",
    "несебър",
    "поморие",
    "равда",
    "созопол",
    "черноморец",
    "приморско",
    "китен",
    "лозенец",
    "царево",
    "ахтопол",
    "обзор",
    "бяла",
    "златни пясъци",
    "св. св. константин и елена",
    "св св константин и елена",
    "св. константин",
    "кабакум",
    "албена",
    "кранево",
    "балчик",
    "каварна",
    "шкорпиловци",
    "синеморец",
    "дюни",
    "елените",
    "аркутино",
    "сарафово",
    "черно море",
}

mountain_resorts = {
    "банско",
    "разлог",
    "добринище",
    "боровец",
    "самоков",
    "пампорово",
    "чепеларе",
    "смолян",
    "велинград",
    "сапарева баня",
    "трявна",
    "априлци",
    "троян",
}


def map_geo_category(row):
    level_1_raw = "" if pd.isna(row.get("location_level_1_model")) else str(row.get("location_level_1_model")).strip().lower()
    level_2_raw = "" if pd.isna(row.get("location_level_2_model")) else str(row.get("location_level_2_model")).strip().lower()

    level_1 = row.get("location_level_1_norm", "")
    level_2 = row.get("location_level_2_norm", "")
    level_3 = row.get("location_level_3_norm", "")

    level_1 = "" if pd.isna(level_1) else str(level_1)
    level_2 = "" if pd.isna(level_2) else str(level_2)
    level_3 = "" if pd.isna(level_3) else str(level_3)

    # Sofia first, because Sofia has "Лозенец", which should not become sea_resort.
    if level_1_raw == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # Resort checks after Sofia exception.
    if level_1 in sea_resorts or level_2 in sea_resorts or level_3 in sea_resorts:
        return "sea_resort"

    if level_1 in mountain_resorts or level_2 in mountain_resorts or level_3 in mountain_resorts:
        return "mountain_resort"

    if level_1 in large_regional_cities:
        return "large_regional_city"

    if level_1 in regional_cities:
        return "regional_city"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("с. ")
        or level_2_raw.startswith("село ")
    ):
        return "village"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("гр. ")
        or level_2_raw.startswith("град ")
    ):
        return "small_city"

    if level_1_raw.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nGeo category by property type:")
display(
    pd.crosstab(
        df_model_base["geo_category"],
        df_model_base["property_type_raw"],
        margins=True
    )
)

print("\nSea resort sample:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("sea_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "sea_resort").sum()),
        random_state=42,
    )
)

print("\nMountain resort sample:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("mountain_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "mountain_resort").sum()),
        random_state=42,
    )
)

Geo category distribution:

          geo_category   rows
0  large_regional_city  37653
1              village  29929
2   capital_non_center  28923
3        regional_city  24035
4           sea_resort  18132
5           small_city  11588
6       capital_center   5417
7      mountain_resort   4086
8        other_unknown   1600

Geo category by property type:

property_type_raw,1-СТАЕН,2-СТАЕН,3-СТАЕН,4-СТАЕН,АВТОМИВКА,АВТОСЕРВИЗ,АКВАПАРК,АПТЕКА,"АТЕЛИЕ, ТАВАН",БАНКОВ ОФИС,...,СТОМАТОЛОГИЧЕН КАБИНЕТ,ТЪРГОВСКИ КОМПЛЕКС,ФАБРИКА/ЗАВОД,ФЕРМА,ФИТНЕС ЗАЛА,ФОТОГРАФСКО СТУДИО,ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,ХЛАДИЛЕН СКЛАД,ХОТЕЛ,All
geo_category,,,,,,,,,,,,,,,,,,,,,
capital_center,139,1240,1894,475,0,0,0,0,22,3,...,5,10,0,0,8,0,14,0,11,5417
capital_non_center,871,6739,8490,1680,0,10,0,2,56,5,...,6,20,15,3,27,0,17,0,22,28923
large_regional_city,1213,12957,11817,1424,5,5,0,7,25,5,...,9,15,14,1,15,1,27,0,79,37653
mountain_resort,450,889,420,61,0,1,0,1,4,1,...,0,8,14,2,3,0,1,0,116,4086
other_unknown,48,182,209,45,0,0,0,0,0,1,...,0,1,2,0,0,0,0,0,30,1600
regional_city,761,4565,6042,1041,2,36,0,3,70,2,...,9,57,67,5,24,0,33,2,59,24035
sea_resort,2815,6119,3585,276,1,3,0,0,17,0,...,0,11,2,1,3,0,5,0,277,18132
small_city,157,837,885,250,2,9,0,2,3,6,...,0,47,87,35,0,0,3,1,154,11588
village,87,345,330,24,0,12,2,1,1,0,...,0,44,50,101,0,0,0,0,253,29929
All,6541,33873,33672,5276,10,76,2,16,198,23,...,29,213,251,148,80,1,100,3,1001,161363

Sea resort sample:

,ad_id,property_type_raw,location_raw,location_level_1_model,location_level_2_model,location_level_2_norm,total_price,area_sqm,price_per_sqm
88815,1i177710523077675,ЕТАЖ ОТ КЪЩА,"област Бургас, гр. Царево",област бургас,гр. царево,царево,319000.0,310.0,1029.03
4896,1a177736899820784,1-СТАЕН,"област Бургас, гр. Приморско",област бургас,гр. приморско,приморско,72300.0,49.0,1475.51
24179,1b177038803489101,2-СТАЕН,"област Бургас, к.к. Слънчев бряг, Пясъците",област бургас,к.к. слънчев бряг,слънчев бряг,85000.0,64.0,1328.12
149644,1r176433180669319,ПАРЦЕЛ,"област Бургас, гр. Приморско, Узунджата",област бургас,гр. приморско,приморско,70000.0,710.0,98.59
9587,1b173239270254887,2-СТАЕН,"област Бургас, гр. Приморско",област бургас,гр. приморско,приморско,56000.0,50.0,1120.00
6413,1a178047718501711,1-СТАЕН,"област Бургас, к.к. Слънчев бряг",област бургас,к.к. слънчев бряг,слънчев бряг,77000.0,37.0,2081.08
8756,1b172310809098334,2-СТАЕН,"област Бургас, к.к. Слънчев бряг",област бургас,к.к. слънчев бряг,слънчев бряг,67500.0,45.0,1500.00
80650,1e173261658667661,МНОГОСТАЕН,"област Бургас, гр. Поморие",област бургас,гр. поморие,поморие,240000.0,280.0,857.14
67433,1c177727411494270,3-СТАЕН,"област Бургас, гр. Созопол",област бургас,гр. созопол,созопол,159800.0,82.0,1948.78
66721,1c177676700907036,3-СТАЕН,"област Бургас, гр. Свети Влас",област бургас,гр. свети влас,свети влас,155000.0,88.0,1761.36
73324,1c178034126988645,3-СТАЕН,"област Бургас, гр. Свети Влас",област бургас,гр. свети влас,свети влас,85000.0,95.0,894.74
33748,1b177762626375918,2-СТАЕН,"област Бургас, гр. Царево",област бургас,гр. царево,царево,87469.0,76.0,1150.91
115705,1l173408006655609,МАГАЗИН,"област Бургас, гр. Свети Влас, Меркурий",област бургас,гр. свети влас,свети влас,41664.0,35.0,1190.40
95221,1j173918570425579,КЪЩА,"област Добрич, гр. Балчик",област добрич,гр. балчик,балчик,400000.0,245.0,1632.65
86967,1g178039920953990,ОФИС,"област Бургас, гр. Несебър",област бургас,гр. несебър,несебър,63000.0,24.0,2625.00
48972,1c175259166935430,3-СТАЕН,"област Бургас, гр. Несебър",област бургас,гр. несебър,несебър,126064.0,84.0,1500.76
9923,1b173695422477556,2-СТАЕН,"област Бургас, к.к. Слънчев бряг",област бургас,к.к. слънчев бряг,слънчев бряг,71000.0,70.0,1014.29
81295,1e175880834752213,МНОГОСТАЕН,"област Бургас, гр. Несебър",област бургас,гр. несебър,несебър,330000.0,330.0,1000.00
14973,1b175681663551521,2-СТАЕН,"област Бургас, гр. Черноморец",област бургас,гр. черноморец,черноморец,115558.0,95.0,1216.40
96028,1j174358304187119,КЪЩА,"област Бургас, с. Лозенец",област бургас,с. лозенец,лозенец,350000.0,142.0,2464.79
18145,1b176235408406891,2-СТАЕН,"област Бургас, гр. Поморие",област бургас,гр. поморие,поморие,99900.0,70.0,1427.14
35432,1b177859418010368,2-СТАЕН,"град Бургас, Сарафово",град бургас,сарафово,сарафово,89900.0,57.0,1577.19
102970,1j176581576526273,КЪЩА,"област Бургас, гр. Свети Влас",област бургас,гр. свети влас,свети влас,450000.0,240.0,1875.00
3575,1a177303960648722,1-СТАЕН,"област Бургас, гр. Китен",област бургас,гр. китен,китен,63000.0,48.0,1312.50
156222,1r177792491346828,ПАРЦЕЛ,"област Бургас, с. Лозенец",област бургас,с. лозенец,лозенец,55000.0,582.0,94.50
48672,1c175157154689870,3-СТАЕН,"област Бургас, гр. Свети Влас",област бургас,гр. свети влас,свети влас,167000.0,112.0,1491.07
124472,1q162203947359524,ХОТЕЛ,"област Бургас, с. Равда",област бургас,с. равда,равда,870000.0,700.0,1242.86
49169,1c175318910204186,3-СТАЕН,"област Бургас, к.к. Слънчев бряг",област бургас,к.к. слънчев бряг,слънчев бряг,210300.0,78.0,2696.15
7124,1b166048210591486,2-СТАЕН,"област Бургас, гр. Обзор",област бургас,гр. обзор,обзор,76000.0,56.0,1357.14
145399,1r175511161960193,ПАРЦЕЛ,"област Бургас, гр. Свети Влас",област бургас,гр. свети влас,свети влас,74000.0,594.0,124.58

Mountain resort sample:

,ad_id,property_type_raw,location_raw,location_level_1_model,location_level_2_model,location_level_2_norm,total_price,area_sqm,price_per_sqm
10467,1b174041697439517,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,104000.00,62.0,1677.42
15054,1b175690508560036,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,89425.00,71.0,1259.51
130162,1r166428708006273,ПАРЦЕЛ,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,120000.00,2100.0,57.14
25946,1b177203531567777,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,118000.00,87.0,1356.32
109984,1j177788531751972,КЪЩА,"област Кюстендил, гр. Сапарева баня",област кюстендил,гр. сапарева баня,сапарева баня,215000.00,302.0,711.92
98288,1j175354519389208,КЪЩА,"област Ловеч, гр. Априлци, Ново Село",област ловеч,гр. априлци,априлци,205000.00,130.0,1576.92
13424,1b175276045221302,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,75000.00,55.0,1363.64
4175,1a177504512328690,1-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,44290.00,40.0,1107.25
2259,1a176475601557631,1-СТАЕН,"област София, к.к. Боровец",област софия,к.к. боровец,боровец,80000.00,38.0,2105.26
26893,1b177306007317194,2-СТАЕН,"област Благоевград, гр. Банско, Грамадето",област благоевград,гр. банско,банско,75000.00,60.0,1250.00
144606,1r175276365255838,ПАРЦЕЛ,"област Габрово, гр. Трявна",област габрово,гр. трявна,трявна,16361.34,1539.0,10.63
20029,1b176485680940476,2-СТАЕН,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,74500.00,72.0,1034.72
1435,1a175690490987605,1-СТАЕН,"област Смолян, к.к. Пампорово",област смолян,к.к. пампорово,пампорово,46750.00,47.0,994.68
80911,1e174784644432158,МНОГОСТАЕН,"област София, гр. Самоков, Център",област софия,гр. самоков,самоков,300000.00,200.0,1500.00
148067,1r176132835808751,ПАРЦЕЛ,"област Ловеч, гр. Троян",област ловеч,гр. троян,троян,9500.00,964.0,9.85
1995,1a176277620581793,1-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,59000.00,49.0,1204.08
49571,1c175420804413689,3-СТАЕН,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,152950.00,161.0,950.00
3780,1a177374189873658,1-СТАЕН,"област Благоевград, гр. Разлог",област благоевград,гр. разлог,разлог,29149.00,38.0,767.08
149342,1r176372276015748,ПАРЦЕЛ,"област Благоевград, гр. Разлог",област благоевград,гр. разлог,разлог,40000.00,615.0,65.04
102422,1j176460639405974,КЪЩА,"област Пазарджик, гр. Велинград, Чепино",област пазарджик,гр. велинград,велинград,55000.00,72.0,763.89
58556,1c176952527428466,3-СТАЕН,"област Благоевград, гр. Банско, ски зона",област благоевград,гр. банско,банско,102999.00,90.0,1144.43
86806,1g177879032592131,ОФИС,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,66000.00,27.0,2444.44
2453,1a176615384295661,1-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,81200.00,47.0,1727.66
414,1a172069498850214,1-СТАЕН,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,51400.00,56.0,917.86
124687,1q171196202193959,ХОТЕЛ,"област Ловеч, гр. Априлци, Скандало",област ловеч,гр. априлци,априлци,285000.00,1500.0,190.00
97347,1j175016013718551,КЪЩА,"област Благоевград, гр. Банско, Банско",област благоевград,гр. банско,банско,300000.00,183.0,1639.34
58952,1c177002648866426,3-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,160000.00,145.0,1103.45
95293,1j173955583170730,КЪЩА,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,320000.00,222.0,1441.44
26742,1b177281283416619,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,94864.00,67.0,1415.88
146616,1r175820120843183,ПАРЦЕЛ,"област Ловеч, гр. Априлци, кв. Зла река",област ловеч,гр. априлци,априлци,25000.00,1500.0,16.67

In [43]:
# ------------------------------------------------------------
# Safer geo category mapping
# Fix false positives like "град Търговище, Боровец"
# ------------------------------------------------------------

def map_geo_category(row):
    level_1_raw = "" if pd.isna(row.get("location_level_1_model")) else str(row.get("location_level_1_model")).strip().lower()
    level_2_raw = "" if pd.isna(row.get("location_level_2_model")) else str(row.get("location_level_2_model")).strip().lower()

    level_1 = row.get("location_level_1_norm", "")
    level_2 = row.get("location_level_2_norm", "")
    level_3 = row.get("location_level_3_norm", "")

    level_1 = "" if pd.isna(level_1) else str(level_1)
    level_2 = "" if pd.isna(level_2) else str(level_2)
    level_3 = "" if pd.isna(level_3) else str(level_3)

    # Sofia first, because Sofia has "Лозенец", which should not become sea_resort.
    if level_1_raw == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # Sea resort:
    # Allow direct city resort, or resort settlement inside oblast.
    if (
        level_1 in sea_resorts
        or (
            level_1_raw.startswith("област ")
            and level_2 in sea_resorts
        )
    ):
        return "sea_resort"

    # Mountain resort:
    # Context-aware to avoid false positives like "град Търговище, Боровец".
    if level_1 in mountain_resorts:
        return "mountain_resort"

    if level_1_raw.startswith("област ") and level_2 in mountain_resorts:
        return "mountain_resort"

    # Special case: Borovets should only be mountain resort if under Sofia/Samokov context.
    if level_2 == "боровец":
        if (
            level_1_raw == "област софия"
            or level_1 == "самоков"
        ):
            return "mountain_resort"

    if level_1 in large_regional_cities:
        return "large_regional_city"

    if level_1 in regional_cities:
        return "regional_city"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("с. ")
        or level_2_raw.startswith("село ")
    ):
        return "village"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("гр. ")
        or level_2_raw.startswith("град ")
        or level_2_raw.startswith("к.к. ")
    ):
        return "small_city"

    if level_1_raw.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nMountain resort sample after fix:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("mountain_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "mountain_resort").sum()),
        random_state=42,
    )
)

Geo category distribution:

          geo_category   rows
0  large_regional_city  38907
1              village  29962
2   capital_non_center  28923
3        regional_city  24126
4           sea_resort  16842
5           small_city  11619
6       capital_center   5417
7      mountain_resort   3992
8        other_unknown   1575

Mountain resort sample after fix:

,ad_id,property_type_raw,location_raw,location_level_1_model,location_level_2_model,location_level_2_norm,total_price,area_sqm,price_per_sqm
50695,1c175690617675250,3-СТАЕН,"област Смолян, к.к. Пампорово",област смолян,к.к. пампорово,пампорово,118833.0,108.0,1100.31
93513,1j172467254257620,КЪЩА,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,252000.0,210.0,1200.00
127968,1r160155474033374,ПАРЦЕЛ,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,516865.0,4550.0,113.60
20613,1b176555203606608,2-СТАЕН,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,77000.0,70.0,1100.00
103412,1j176770085693084,КЪЩА,"област Благоевград, гр. Разлог",област благоевград,гр. разлог,разлог,259950.0,240.0,1083.12
865,1a174620404481572,1-СТАЕН,"област Благоевград, гр. Банско, Свети Иван Рилски",област благоевград,гр. банско,банско,57000.0,40.0,1425.00
92222,1j171025667989089,КЪЩА,"област Габрово, гр. Трявна",област габрово,гр. трявна,трявна,195000.0,516.0,377.91
22567,1b176893030128613,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,56500.0,54.0,1046.30
94952,1j173754010950367,КЪЩА,"област Благоевград, гр. Разлог",област благоевград,гр. разлог,разлог,240000.0,186.0,1290.32
35979,1b177879236344378,2-СТАЕН,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,76160.0,64.0,1190.00
143532,1r174982299220831,ПАРЦЕЛ,"област Габрово, гр. Трявна",област габрово,гр. трявна,трявна,80500.0,4025.0,20.00
133488,1r170438645288325,ПАРЦЕЛ,"област Кюстендил, гр. Сапарева баня",област кюстендил,гр. сапарева баня,сапарева баня,499900.0,2230.0,224.17
91069,1j168805771031573,КЪЩА,"област Пазарджик, гр. Велинград",област пазарджик,гр. велинград,велинград,29900.0,40.0,747.50
125577,1r124231342065003,ПАРЦЕЛ,"град Смолян, Нов център",град смолян,нов център,нов център,839400.0,14000.0,59.96
26234,1b177227287599335,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,75000.0,59.0,1271.19
1437,1a175690550571289,1-СТАЕН,"област София, к.к. Боровец",област софия,к.к. боровец,боровец,196498.0,103.0,1907.75
18081,1b176227208785594,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,132500.0,77.0,1720.78
38382,1b177995888693699,2-СТАЕН,"област София, к.к. Боровец",област софия,к.к. боровец,боровец,116000.0,73.0,1589.04
23527,1b177002189722334,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,95000.0,66.0,1439.39
50134,1c175578278708166,3-СТАЕН,"област Благоевград, гр. Банско, Пирин Лодж",област благоевград,гр. банско,банско,135000.0,105.0,1285.71
151169,1r176821113447741,ПАРЦЕЛ,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,101160.0,1124.0,90.00
49410,1c175386326352089,3-СТАЕН,"област Габрово, гр. Трявна",област габрово,гр. трявна,трявна,95000.0,84.0,1130.95
36085,1b177884192678066,2-СТАЕН,"област Благоевград, гр. Банско, Кабинков лифт",област благоевград,гр. банско,банско,144000.0,80.0,1800.00
40198,1b178058145986620,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,125000.0,84.0,1488.10
48711,1c175187370655061,3-СТАЕН,"област Смолян, к.к. Пампорово",област смолян,к.к. пампорово,пампорово,97500.0,143.0,681.82
129581,1r165218611733947,ПАРЦЕЛ,"област Габрово, гр. Трявна, Божковци",област габрово,гр. трявна,трявна,105000.0,3000.0,35.00
111903,1j177977928862132,КЪЩА,"област Ловеч, гр. Троян",област ловеч,гр. троян,троян,260000.0,165.0,1575.76
135351,1r171662976395350,ПАРЦЕЛ,"област Ловеч, гр. Троян",област ловеч,гр. троян,троян,31500.0,1037.0,30.38
15310,1b175743008380846,2-СТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,105170.0,68.0,1546.62
82352,1e177435757292075,МНОГОСТАЕН,"област Благоевград, гр. Банско",област благоевград,гр. банско,банско,185000.0,127.0,1456.69

In [44]:
# ------------------------------------------------------------
# Inspect rows classified as other_unknown
# ------------------------------------------------------------

other_unknown_geo = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("other_unknown rows:", len(other_unknown_geo))
print("Share of df_model_base:", round(len(other_unknown_geo) / len(df_model_base) * 100, 2), "%")

print("\nTop location_level_1_model in other_unknown:")
display(
    other_unknown_geo["location_level_1_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_1_model")
    .reset_index(name="rows")
)

print("\nTop location_level_2_model in other_unknown:")
display(
    other_unknown_geo["location_level_2_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2_model")
    .reset_index(name="rows")
)

print("\nTop normalized level 1 / level 2 combos:")
display(
    other_unknown_geo
    .groupby(["location_level_1_model", "location_level_2_model"], dropna=False)
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample other_unknown rows:")
display(
    other_unknown_geo[
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sample(min(50, len(other_unknown_geo)), random_state=42)
)

other_unknown rows: 1575
Share of df_model_base: 0.98 %

Top location_level_1_model in other_unknown:

                               location_level_1_model  rows
0                                              гърция   841
1                                    област пазарджик   195
2                                        област софия    54
3                                      област пловдив    52
4                                       област перник    20
5                             апартамент с три спални    20
6                                 област стара загора    15
7   комплекс sun city apartments е позициониран в ...    13
8   тристайния апартамент е разположен в северната...    12
9                                     област кърджали    11
10                                       област ловеч     8
11  комплесът се намира в непосредствена близост д...     8
12  имотът е разположен в престижната част на идеа...     7
13                                      област плевен     7
14  сградата е разположена на изключително комуник...     7
15                              област велико търново     7
16  слънчев бряг е един от най-големите семейни ку...     6
17  курортът свети влас (свети влас) българия е ма...     6
18                                        област русе     6
19                                     област хасково     6
20              в околността има изобилие от магазини     6
21                                 област благоевград     5
22                                двустаен апартамент     5
23                                 нов жилищен проект     5
24                                      област бургас     4
25                                             ахелой     3
26  - комплексът се намира само на 200 м от брегов...     3
27                                       област варна     3
28                                   + кв. овча купел     3
29                   приморско е малък български град     3
30  апартаментът се намира в тихата и предпочитана...     3
31  кв.владислав варненчик е най-големия в гр.варн...     3
32  свети влас е уникално място в природата-благод...     3
33  апартаментът е в един от най- предпочитаните р...     3
34  свети влас е уникално по своята природа място ...     3
35  един от най-предпочитаните райони на града в н...     2
36                           + бул. цар борис iii 160     2
37                       равда е морски курортен град     2
38                             в близост има: училища     2
39  имотът се намира в предпочитан и добре устроен...     2
40         апартаментът се намира в местност ален мак     2
41  курортът свети влас (свети влас) българия е ма...     2
42                              комуникативна локация     2
43  комплексът се намира в западната част на слънч...     2
44  село хърсово се намира в санданско-петричката ...     2
45                         подходящ за строеж на къща     2
46   имотът е с атрактивно местоположение - в бли...     2
47                                   област кюстендил     2
48                                     област габрово     2
49   вилна зона побит камък е на 3км от село нови хан     2

Top location_level_2_model in other_unknown:

                               location_level_2_model  rows
0                                           халкидики   300
1                                               солун   203
2                                              кавала   170
3                                      м-т цигов чарк   123
4                                   магистрала тракия    61
5                                                <NA>    61
6                                           яз. батак    55
7                                              ксанти    27
8                                           в.з.ярема    26
9                                              пиерия    26
10                                                сяр    22
11                                              тасос    20
12     разположен в северната част на гр.стара загора    20
13                                       хижа здравец    19
14                                     главен път е85    17
15  в непосредствена близост до к.к. св.св. конста...    13
16                                     главен път е79    13
17  на тихо и спокойно място за живеене в близост ...    12
18                                           закинтос    11
19                                        яз. пчелина    11
20                                       яз. кърджали    10
21                                      гара лакатник    10
22                                            училища     9
23                                          заведения     8
24                                           гара бов     8
25                                              евбея     7
26                                              еврос     7
27                                            локация     7
28                                     главен път е83     7
29                                              атина     6
30                                        м-т мечката     6
31                                             родопи     6
32  а северната му част е затворена от стара плани...     6
33                                             лесбос     5
34                                            циклади     5
35  разположен в предпочитания район болница в шум...     5
36              в северната част на град стара загора     5
37                                      източна атика     5
38                                  магистрала марица     5
39                   в близост до хранителни магазини     4
40                                          яз. сопот     4
41                                   магистрала хемус     4
42                               яз. ал. стамболийски     4
43                                     детски градини     4
44                                      м-т яз. искър     3
45                                             лариса     3
46                                         додеканези     3
47                                   магистрала люлин     3
48  много популярен сред туристите. намира се в юг...     3
49  планински и горски курорт има специален микрок...     3

Top normalized level 1 / level 2 combos:

,location_level_1_model,location_level_2_model,rows
73,гърция,халкидики,300
70,гърция,солун,203
56,гърция,кавала,170
167,област пазарджик,м-т цигов чарк,123
169,област пазарджик,яз. батак,55
...,...,...,...
248,слънчев бряг е един от най-големите семейни ку...,а северната му част покрива стара планина-всич...,1
251,слънчев бряг е най-големият български курорт,разположен в красив залив във формата на полум...,1
252,спокойна и живописна местност в полите на родо...,заобиколена от борова гора. идеално място за п...,1
253,срещу частна немска детска градина германи'. п...,ринг мол и херитидж парк. тих,1
254,старозагорските бани е желано място за отдих,спа,1

Sample other_unknown rows:

,ad_id,property_type_raw,location_raw,location_level_1_model,location_level_2_model,location_level_1_norm,location_level_2_norm,total_price,area_sqm,price_per_sqm
129908,1r165841033746317,ПАРЦЕЛ,"област Пазарджик, м-т Цигов чарк",област пазарджик,м-т цигов чарк,област пазарджик,цигов чарк,260000.0,4000.0,65.00
101050,1j176164448147614,КЪЩА,"Гърция, Кавала, Паралия Офриниу",гърция,кавала,гърция,кавала,234000.0,81.0,2888.89
126870,1r152981671922709,ПАРЦЕЛ,"област Хасково, магистрала Марица, Капитан Анд...",област хасково,магистрала марица,област хасково,магистрала марица,36000.0,3000.0,12.00
83983,1f176598443092697,МЕЗОНЕТ,"Гърция, Еврос, Александруполис",гърция,еврос,гърция,еврос,950000.0,342.0,2777.78
83604,1f174654954940124,МЕЗОНЕТ,"Гърция, Ксанти, Порто Лагос",гърция,ксанти,гърция,ксанти,175000.0,136.0,1286.76
156526,1r177831975183091,ПАРЦЕЛ,"област Пазарджик, яз. Батак, м-ст 'Кънева Борика'",област пазарджик,яз. батак,област пазарджик,яз. батак,100000.0,4000.0,25.00
83827,1f175947821536216,МЕЗОНЕТ,"Гърция, Сяр, Логари, Неа Кердилия",гърция,сяр,гърция,сяр,168000.0,66.0,2545.45
44931,1c173531283585130,3-СТАЕН,Апартаментът се намира в новопостроена бутиков...,апартаментът се намира в новопостроена бутиков...,в непосредствена близост до парк артилерийски,апартаментът се намира в новопостроена бутиков...,в непосредствена близост до парк артилерийски,166000.0,102.0,1627.45
81349,1e175949754817789,МНОГОСТАЕН,"Гърция, Кавала, Керамоти",гърция,кавала,гърция,кавала,485000.0,320.0,1515.62
7839,1b170229904985603,2-СТАЕН,"Гърция, Солун, Солун",гърция,солун,гърция,солун,75000.0,37.0,2027.03
92796,1j171697280223988,КЪЩА,"Гърция, Халкидики, Вурвуру",гърция,халкидики,гърция,халкидики,300000.0,89.0,3370.79
113434,1j178090563299443,КЪЩА,"Гърция, Сяр",гърция,сяр,гърция,сяр,230000.0,60.0,3833.33
95759,1j174238354729197,КЪЩА,"Гърция, Халкидики, Каландра (Касандра)",гърция,халкидики,гърция,халкидики,123000.0,73.0,1684.93
99433,1j175706980840164,КЪЩА,"Гърция, Халкидики",гърция,халкидики,гърция,халкидики,490000.0,130.0,3769.23
113710,1k171984513198914,ВИЛА,"Гърция, Халкидики",гърция,халкидики,гърция,халкидики,400000.0,400.0,1000.00
92241,1j171095037235268,КЪЩА,"Гърция, Халкидики, Ситония",гърция,халкидики,гърция,халкидики,225000.0,80.0,2812.50
58886,1c176978463971098,3-СТАЕН,"В околността има изобилие от магазини, училища...",в околността има изобилие от магазини,училища,в околността има изобилие от магазини,училища,197374.0,96.0,2055.98
149562,1r176417281582241,ПАРЦЕЛ,ПОЗЕМЛЕН имот находящ се в урбанизирана терито...,поземлен имот находящ се в урбанизирана терито...,<NA>,поземлен имот находящ се в урбанизирана терито...,,66000.0,513.0,128.65
4072,1a177460516798536,1-СТАЕН,"Гърция, Кавала, Нае Перамос",гърция,кавала,гърция,кавала,105000.0,38.0,2763.16
4091,1a177462266332415,1-СТАЕН,Свети Влас е уникално място в природата-благод...,свети влас е уникално място в природата-благод...,планински и горски курорт има специален микрок...,свети влас е уникално място в природата-благод...,планински и горски курорт има специален микрок...,68900.0,44.0,1565.91
158886,1r178049242203470,ПАРЦЕЛ,"област Пазарджик, яз. Батак, м-ст 'Божанова къ...",област пазарджик,яз. батак,област пазарджик,яз. батак,31067.0,661.0,47.00
163868,1t175940442737606,ВИЛНО СЕЛИЩЕ,"област Пловдив, хижа Здравец",област пловдив,хижа здравец,област пловдив,хижа здравец,650000.0,5300.0,122.64
83932,1f176376220316355,МЕЗОНЕТ,"Гърция, Халкидики, Posidi Halkidiki",гърция,халкидики,гърция,халкидики,450000.0,140.0,3214.29
91889,1j170586194943228,КЪЩА,Селото Гюльовца се намира от южната страна на ...,селото гюльовца се намира от южната страна на ...,в долината на река хаджийска. през селото мина...,селото гюльовца се намира от южната страна на ...,в долината на река хаджийска. през селото мина...,48572.0,68.0,714.29
156597,1r177848956219387,ПАРЦЕЛ,"област Пазарджик, м-т Цигов чарк",област пазарджик,м-т цигов чарк,област пазарджик,цигов чарк,18500.0,650.0,28.46
101354,1j176233325583951,КЪЩА,"Гърция, Коринтия",гърция,коринтия,гърция,коринтия,350000.0,200.0,1750.00
113722,1k171983805922413,ВИЛА,"Гърция, Закинтос",гърция,закинтос,гърция,закинтос,850000.0,200.0,4250.00
52962,1c176121616090766,3-СТАЕН,"Гърция, Ксанти, Маггана",гърция,ксанти,гърция,ксанти,140000.0,136.0,1029.41
143201,1r174889191199680,ПАРЦЕЛ,"област Пазарджик, м-т Цигов чарк",област пазарджик,м-т цигов чарк,област пазарджик,цигов чарк,30000.0,2000.0,15.00
89555,1j160517663324542,КЪЩА,"Гърция, Корфу",гърция,корфу,гърция,корфу,390000.0,90.0,4333.33
7601,1b169114971299767,2-СТАЕН,"ДВУСТАЕН апартамент, в северната част на град...",двустаен апартамент,в северната част на град стара загора,двустаен апартамент,в северната част на град стара загора,139989.0,67.0,2089.39
126701,1r151454439494464,ПАРЦЕЛ,"област Бургас, магистрала Тракия",област бургас,магистрала тракия,област бургас,магистрала тракия,280000.0,20000.0,14.00
94568,1j173348800356355,КЪЩА,"Гърция, Халкидики, Сикия",гърция,халкидики,гърция,халкидики,270000.0,90.0,3000.00
101353,1j176234114465141,КЪЩА,"Село Дебелт, само на 17 км от гр. Бургас спо...",село дебелт,само на 17 км от гр. бургас спокойно и добре р...,дебелт,само на 17 км от гр. бургас спокойно и добре р...,35000.0,105.0,333.33
99621,1j175775055135874,КЪЩА,"Гърция, Солун, Неа Кердилия",гърция,солун,гърция,солун,75000.0,90.0,833.33
94734,1j173589149509344,КЪЩА,"Гърция, Солун",гърция,солун,гърция,солун,520000.0,321.0,1619.94
105358,1j177141843947141,КЪЩА,"Гърция, Солун, Панорама",гърция,солун,гърция,солун,550000.0,300.0,1833.33
90305,1j166505844153148,КЪЩА,"Гърция, Кавала, Паралия Врасна",гърция,кавала,гърция,кавала,400000.0,110.0,3636.36
82330,1e177435451217052,МНОГОСТАЕН,Апартаментът е в един от най- предпочитаните р...,апартаментът е в един от най- предпочитаните р...,на минути пешеходно от пешеходната зона,апартаментът е в един от най- предпочитаните р...,на минути пешеходно от пешеходната зона,215000.0,106.0,2028.30
3021,1a177019072489151,1-СТАЕН,Слънчев бряг е един от най-големите семейни ку...,слънчев бряг е един от най-големите семейни ку...,а северната му част е затворена стара планина-...,слънчев бряг е един от най-големите семейни ку...,а северната му част е затворена стара планина-...,45000.0,29.0,1551.72
61569,1c177260646448101,3-СТАЕН,Слънчев бряг е един от най-големите семейни ку...,слънчев бряг е един от най-големите семейни ку...,а северната му част е затворена от стара плани...,слънчев бряг е един от най-големите семейни ку...,а северната му част е затворена от стара плани...,119500.0,88.0,1357.95
4371,1a177571870417510,1-СТАЕН,"Гърция, Солун, Каламария",гърция,солун,гърция,солун,180000.0,30.0,6000.00
110482,1j177849695719077,КЪЩА,"Гърция, Солун, Неа Врасна",гърция,солун,гърция,солун,165000.0,53.0,3113.21
135209,1r171615112361263,ПАРЦЕЛ,"област София, в.з.Ярема",област софия,в.з.ярема,област софия,в.з.ярема,189900.0,750.0,253.20
90105,1j165728029199484,КЪЩА,"Гърция, Пиерия, Олимпийска ривиера",гърция,пиерия,гърция,пиерия,350000.0,340.0,1029.41
113725,1k171984478560831,ВИЛА,"Гърция, Халкидики",гърция,халкидики,гърция,халкидики,2280000.0,189.0,12063.49
99523,1j175750347941007,КЪЩА,"Гърция, Халкидики, Офриньо",гърция,халкидики,гърция,халкидики,250000.0,150.0,1666.67
57743,1c176873541098526,3-СТАЕН,Сградата се намира в най-хубавата част на кв. ...,сградата се намира в най-хубавата част на кв. ...,<NA>,сградата се намира в най-хубавата част на кв. ...,,299876.0,105.0,2855.96
125048,1q176458749473774,ХОТЕЛ,"Гърция, Халкидики, Криопиги",гърция,халкидики,гърция,халкидики,1340000.0,700.0,1914.29
125154,1q177236103322226,ХОТЕЛ,"Гърция, Лесбос",гърция,лесбос,гърция,лесбос,490000.0,530.0,924.53

In [45]:
# ------------------------------------------------------------
# Geo cleanup: drop Greece and reclassify oblast unknowns
# ------------------------------------------------------------

before_rows = len(df_model_base)

# 1. Drop Greece / foreign Greece listings
drop_greece_mask = (
    df_model_base["location_level_1_model"]
    .astype("string")
    .str.lower()
    .eq("гърция")
)

dropped_greece = df_model_base.loc[drop_greece_mask].copy()

df_model_base = df_model_base.loc[~drop_greece_mask].copy()

after_greece_rows = len(df_model_base)

print("Dropped Greece rows:", before_rows - after_greece_rows)


# 2. Reclassify other_unknown rows that start with "област" as small_city
reclass_oblast_unknown_mask = (
    df_model_base["geo_category"].eq("other_unknown")
    & df_model_base["location_level_1_model"].astype("string").str.startswith("област", na=False)
)

reclassified_oblast_unknown = df_model_base.loc[reclass_oblast_unknown_mask].copy()

df_model_base.loc[reclass_oblast_unknown_mask, "geo_category"] = "small_city"

print("Reclassified oblast other_unknown rows:", len(reclassified_oblast_unknown))
print("Rows before:", before_rows)
print("Rows after:", len(df_model_base))


# 3. Inspect updated geo distribution
print("\nUpdated geo_category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)


# 4. Inspect remaining other_unknown
remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("\nRemaining other_unknown rows:", len(remaining_other_unknown))

display(
    remaining_other_unknown[
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)


# 5. Log cleanup actions
cleanup_actions.append({
    "rule": "drop_greece_listings",
    "reason": "Greece listings are outside the target Bulgarian real estate market and irrelevant for the planned regression model",
    "rows_affected": len(dropped_greece),
})

cleanup_actions.append({
    "rule": "reclassify_oblast_other_unknown_to_small_city",
    "reason": "Rows classified as other_unknown but starting with oblast are Bulgarian regional listings and should be treated as small_city for coarse geo bucketing",
    "rows_affected": len(reclassified_oblast_unknown),
})

Dropped Greece rows: 841
Reclassified oblast other_unknown rows: 400
Rows before: 161363
Rows after: 160522

Updated geo_category distribution:

          geo_category   rows
0  large_regional_city  38907
1              village  29962
2   capital_non_center  28923
3        regional_city  24126
4           sea_resort  16842
5           small_city  12019
6       capital_center   5417
7      mountain_resort   3992
8        other_unknown    334

Remaining other_unknown rows: 334

,ad_id,property_type_raw,location_raw,location_level_1_model,location_level_2_model,location_level_1_norm,location_level_2_norm,total_price,area_sqm,price_per_sqm
1316,1a175559624267113,1-СТАЕН,Комплекс SUN CITY APARTMENTS е позициониран ...,комплекс sun city apartments е позициониран в ...,в непосредствена близост до к.к. св.св. конста...,комплекс sun city apartments е позициониран в ...,в непосредствена близост до к.к. св.св. конста...,99900.0,47.0,2125.53
1751,1a176068114364174,1-СТАЕН,Слънчев бряг е един от най-големите семейни ку...,слънчев бряг е един от най-големите семейни ку...,а северната част на стара планина-ярко осветен...,слънчев бряг е един от най-големите семейни ку...,а северната част на стара планина-ярко осветен...,59000.0,36.0,1638.89
1961,1a176251323867030,1-СТАЕН,Само 100 метра от супермаркет Меркурий и спи...,само 100 метра от супермаркет меркурий и спирк...,<NA>,само 100 метра от супермаркет меркурий и спирк...,,59500.0,36.0,1652.78
2086,1a176311612121480,1-СТАЕН,кв.Владислав Варненчик е най-големия в гр.Варн...,кв.владислав варненчик е най-големия в гр.варн...,стадион,кв.владислав варненчик е най-големия в гр.варн...,стадион,58450.0,42.0,1391.67
2235,1a176437367602476,1-СТАЕН,Комплексът се намира на идеално място-между ти...,комплексът се намира на идеално място-между ти...,само на 200 метра от златистия плаж и на 300 м...,комплексът се намира на идеално място-между ти...,само на 200 метра от златистия плаж и на 300 м...,58000.0,31.0,1870.97
...,...,...,...,...,...,...,...,...,...,...
40136,1b178057454873181,2-СТАЕН,Свети Влас е уникален по своята природа благод...,свети влас е уникален по своята природа благод...,планински и горски въздух с преобладаване на с...,свети влас е уникален по своята природа благод...,планински и горски въздух с преобладаване на с...,110000.0,55.0,2000.00
40793,1b178091605006158,2-СТАЕН,"Апартаментът се намира в гр. Поморие, на 5-ти ...",апартаментът се намира в гр. поморие,на 5-ти етаж от 6-етажна тухлена сграда,апартаментът се намира в гр. поморие,на 5-ти етаж от 6-етажна тухлена сграда,120176.0,55.0,2185.02
41206,1c163531906748487,3-СТАЕН,Курортът Свети Влас (Свети Влас) България е ма...,курортът свети влас (свети влас) българия е ма...,<NA>,курортът свети влас (свети влас) българия е ма...,,152052.0,198.0,767.94
41245,1c163673363507961,3-СТАЕН,Курортът Свети Влас (Свети Влас) България е ма...,курортът свети влас (свети влас) българия е ма...,<NA>,курортът свети влас (свети влас) българия е ма...,,127535.0,166.0,768.28
41664,1c167476341703614,3-СТАЕН,Свети Влас е уникално по своята природа място ...,свети влас е уникално по своята природа място ...,планински и горски въздух в курорта преобладав...,свети влас е уникално по своята природа място ...,планински и горски въздух в курорта преобладав...,170000.0,150.0,1133.33

In [46]:
# ------------------------------------------------------------
# Inspect remaining other_unknown by title_city_raw
# ------------------------------------------------------------

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("Remaining other_unknown rows:", len(remaining_other_unknown))

print("\nTop title_city_raw values:")
display(
    remaining_other_unknown["title_city_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTitle city + location level combo:")
display(
    remaining_other_unknown
    .groupby(
        [
            "title_city_raw",
            "location_level_1_model",
            "location_level_2_model",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample remaining other_unknown:")
display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["title_city_raw", "property_type_raw", "price_per_sqm"])
    .head(100)
)

Remaining other_unknown rows: 334

Top title_city_raw values:

           title_city_raw  rows
0           област Бургас    89
1       град Стара Загора    68
2              град София    52
3              град Варна    36
4              град Шумен    13
5     област Стара Загора    10
6          област Пловдив     8
7            област София     7
8          град Пазарджик     6
9             град Бургас     5
10       област Пазарджик     5
11           град Пловдив     5
12     област Благоевград     3
13           област Ловеч     3
14           град Хасково     3
15       град Благоевград     3
16           област Варна     3
17           област Шумен     3
18          област Добрич     2
19  област Велико Търново     2
20             град Ямбол     1
21          област Смолян     1
22       област Търговище     1
23       област Кюстендил     1
24          област Перник     1
25         област Габрово     1
26                 Гърция     1
27         област Хасково     1

Title city + location level combo:

,title_city_raw,location_level_1_model,location_level_2_model,rows
61,град Стара Загора,апартамент с три спални,разположен в северната част на гр.стара загора,20
15,град Варна,комплекс sun city apartments е позициониран в ...,в непосредствена близост до к.к. св.св. конста...,13
90,град Стара Загора,тристайния апартамент е разположен в северната...,на тихо и спокойно място за живеене в близост ...,12
16,град Варна,комплесът се намира в непосредствена близост д...,заведения,8
95,град Шумен,имотът е разположен в престижната част на идеа...,локация,7
...,...,...,...,...
71,град Стара Загора,етаж от къща в широкия център на град стара за...,в близост до v оу,1
69,град Стара Загора,двустаен апартамент в един от най- предпочитан...,парк 'зелен клин'. тихо и спокойно място на ми...,1
70,град Стара Загора,етаж от къща в центъра на град стара загора,срещу градината с паметника на васил левски.,1
68,град Стара Загора,двустаен апартамент в един от най- бързо разви...,денонощни магазини,1
67,град Стара Загора,двустаен апартамент в близост до бул. патриарх...,осигурява бърз достъп до централната част на г...,1

Sample remaining other_unknown:

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,location_level_1_model,location_level_2_model,location_level_1_norm,location_level_2_norm,total_price,area_sqm,price_per_sqm
147632,1r176062111749471,https://www.imot.bg/obiava-1r176062111749471-p...,ПАРЦЕЛ,Гърция,"На уникално място, само на една крачка от прис...",на уникално място,само на една крачка от пристанището (както се ...,на уникално място,само на една крачка от пристанището (както се ...,480000.0,4957.0,96.83
48606,1c175144452019710,https://www.imot.bg/obiava-1c175144452019710-p...,3-СТАЕН,град Благоевград,Апартаментът се намира в нова сграда с АКТ 15 ...,апартаментът се намира в нова сграда с акт 15 ...,детска градина,апартаментът се намира в нова сграда с акт 15 ...,детска градина,111300.0,86.0,1294.19
63915,1c177442836123156,https://www.imot.bg/obiava-1c177442836123156-p...,3-СТАЕН,град Благоевград,Апартаментът се намира в нова сграда с АКТ 15 ...,апартаментът се намира в нова сграда с акт 15 ...,детска градина,апартаментът се намира в нова сграда с акт 15 ...,детска градина,142038.0,109.0,1303.10
82368,1e177445296590308,https://www.imot.bg/obiava-1e177445296590308-p...,МНОГОСТАЕН,град Благоевград,"Намира се в началото на кв. Струмско, в близос...",намира се в началото на кв. струмско,в близост до училище,намира се в началото на кв. струмско,в близост до училище,110000.0,96.0,1145.83
36663,1b177918076115026,https://www.imot.bg/obiava-1b177918076115026-p...,2-СТАЕН,град Бургас,Кварталът се отличава с отлична инфраструктура...,кварталът се отличава с отлична инфраструктура,спокойствие и бърз достъп до всички удобства.,кварталът се отличава с отлична инфраструктура,спокойствие и бърз достъп до всички удобства.,76500.0,60.0,1275.00
...,...,...,...,...,...,...,...,...,...,...,...,...
91136,1j168932865793206,https://www.imot.bg/obiava-1j168932865793206-p...,КЪЩА,град София,- на 15 км от центъра на София;,- на 15 км от центъра на софия;,<NA>,- на 15 км от центъра на софия;,,546580.0,253.0,2160.40
91101,1j168890765808833,https://www.imot.bg/obiava-1j168890765808833-p...,КЪЩА,град София,- на 15 км от центъра на София;,- на 15 км от центъра на софия;,<NA>,- на 15 км от центъра на софия;,,576400.0,261.0,2208.43
96176,1j174446717390386,https://www.imot.bg/obiava-1j174446717390386-p...,КЪЩА,град София,Срещу частна немска детска градина Германи'. ...,срещу частна немска детска градина германи'. п...,ринг мол и херитидж парк. тих,срещу частна немска детска градина германи. пе...,ринг мол и херитидж парк. тих,1050000.0,400.0,2625.00
93086,1j172000134531750,https://www.imot.bg/obiava-1j172000134531750-p...,КЪЩА,град София,Намира се в кв. Бояна(Гърдова глава),намира се в кв. бояна(гърдова глава),<NA>,намира се в кв. бояна(гърдова глава),,470000.0,82.0,5731.71
116499,1l176157096171387,https://www.imot.bg/obiava-1l176157096171387-p...,МАГАЗИН,град София,ул.'Арх. Петър Загорски' в близост до ул. 'Про...,ул.'арх. петър загорски' в близост до ул. 'про...,<NA>,ул.арх. петър загорски в близост до ул. проф. ...,,239000.0,94.0,2542.55

In [47]:
# ------------------------------------------------------------
# Re-inspect remaining other_unknown using title_city_raw + title_geo_2_raw
# No mutation
# ------------------------------------------------------------

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

# Normalize for inspection only
remaining_other_unknown["title_city_model_inspect"] = (
    remaining_other_unknown["title_city_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

remaining_other_unknown["title_geo_2_model_inspect"] = (
    remaining_other_unknown["title_geo_2_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

print("Remaining other_unknown rows:", len(remaining_other_unknown))

print("\nTop title_city_raw:")
display(
    remaining_other_unknown["title_city_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTop title_geo_2_raw:")
display(
    remaining_other_unknown["title_geo_2_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_geo_2_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTop title_city_raw + title_geo_2_raw combos:")
display(
    remaining_other_unknown
    .groupby(
        [
            "title_city_raw",
            "title_geo_2_raw",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample rows:")
display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "title_geo_2_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["title_city_raw", "title_geo_2_raw", "property_type_raw"])
    .head(150)
)

Remaining other_unknown rows: 334

Top title_city_raw:

           title_city_raw  rows
0           област Бургас    89
1       град Стара Загора    68
2              град София    52
3              град Варна    36
4              град Шумен    13
5     област Стара Загора    10
6          област Пловдив     8
7            област София     7
8          град Пазарджик     6
9             град Бургас     5
10       област Пазарджик     5
11           град Пловдив     5
12     област Благоевград     3
13           област Ловеч     3
14           град Хасково     3
15       град Благоевград     3
16           област Варна     3
17           област Шумен     3
18          област Добрич     2
19  област Велико Търново     2
20             град Ямбол     1
21          област Смолян     1
22       област Търговище     1
23       област Кюстендил     1
24          област Перник     1
25         област Габрово     1
26                 Гърция     1
27         област Хасково     1

Top title_geo_2_raw:

      title_geo_2_raw  rows
0             Аязмото    39
1      гр. Свети Влас    27
2   к.к. Слънчев бряг    24
3              Център    24
4              Виница     9
..                ...   ...
95      с. Три могили     1
96         с. Бойково     1
97      с. Поцърненци     1
98     с. Малка Верея     1
99          гр. Обзор     1

[100 rows x 2 columns]

Top title_city_raw + title_geo_2_raw combos:

        title_city_raw    title_geo_2_raw  rows
52   град Стара Загора            Аязмото    39
76       област Бургас     гр. Свети Влас    27
79       област Бургас  к.к. Слънчев бряг    24
61   град Стара Загора             Център    11
6           град Варна             Виница     9
..                 ...                ...   ...
70  област Благоевград          с. Обидим     1
66          град Шумен  Боян Българанов 1     1
68          град Ямбол      Граф Игнатиев     1
97        област Ловеч          с. Орешак     1
96        област Ловеч        гр. Априлци     1

[100 rows x 3 columns]

Sample rows:

,ad_id,ad_url,property_type_raw,title_city_raw,title_geo_2_raw,location_raw,location_level_1_model,location_level_2_model,location_level_1_norm,location_level_2_norm,total_price,area_sqm,price_per_sqm
147632,1r176062111749471,https://www.imot.bg/obiava-1r176062111749471-p...,ПАРЦЕЛ,Гърция,Ксанти,"На уникално място, само на една крачка от прис...",на уникално място,само на една крачка от пристанището (както се ...,на уникално място,само на една крачка от пристанището (както се ...,480000.0,4957.0,96.83
82368,1e177445296590308,https://www.imot.bg/obiava-1e177445296590308-p...,МНОГОСТАЕН,град Благоевград,Струмско,"Намира се в началото на кв. Струмско, в близос...",намира се в началото на кв. струмско,в близост до училище,намира се в началото на кв. струмско,в близост до училище,110000.0,96.0,1145.83
48606,1c175144452019710,https://www.imot.bg/obiava-1c175144452019710-p...,3-СТАЕН,град Благоевград,Широк център,Апартаментът се намира в нова сграда с АКТ 15 ...,апартаментът се намира в нова сграда с акт 15 ...,детска градина,апартаментът се намира в нова сграда с акт 15 ...,детска градина,111300.0,86.0,1294.19
63915,1c177442836123156,https://www.imot.bg/obiava-1c177442836123156-p...,3-СТАЕН,град Благоевград,Широк център,Апартаментът се намира в нова сграда с АКТ 15 ...,апартаментът се намира в нова сграда с акт 15 ...,детска градина,апартаментът се намира в нова сграда с акт 15 ...,детска градина,142038.0,109.0,1303.10
36663,1b177918076115026,https://www.imot.bg/obiava-1b177918076115026-p...,2-СТАЕН,град Бургас,Крайморие,Кварталът се отличава с отлична инфраструктура...,кварталът се отличава с отлична инфраструктура,спокойствие и бърз достъп до всички удобства.,кварталът се отличава с отлична инфраструктура,спокойствие и бърз достъп до всички удобства.,76500.0,60.0,1275.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80333,1e169115535787570,https://www.imot.bg/obiava-1e169115535787570-p...,МНОГОСТАЕН,град Стара Загора,Аязмото,"АПАРТАМЕНТ с ТРИ СПАЛНИ, разположен в севернат...",апартамент с три спални,разположен в северната част на гр.стара загора,апартамент с три спални,разположен в северната част на гр.стара загора,180000.0,152.0,1184.21
82330,1e177435451217052,https://www.imot.bg/obiava-1e177435451217052-p...,МНОГОСТАЕН,град Стара Загора,Аязмото,Апартаментът е в един от най- предпочитаните р...,апартаментът е в един от най- предпочитаните р...,на минути пешеходно от пешеходната зона,апартаментът е в един от най- предпочитаните р...,на минути пешеходно от пешеходната зона,215000.0,106.0,2028.30
23532,1b177002271655032,https://www.imot.bg/obiava-1b177002271655032-p...,2-СТАЕН,град Стара Загора,Железник,Двустаен апартамент в един от най- бързо разви...,двустаен апартамент в един от най- бързо разви...,денонощни магазини,двустаен апартамент в един от най- бързо разви...,денонощни магазини,118500.0,70.0,1692.86
50110,1c175577014970919,https://www.imot.bg/obiava-1c175577014970919-p...,3-СТАЕН,град Стара Загора,Железник,кв. Железник изток предпочитан заради сп...,кв. железник изток предпочитан заради спокойна...,<NA>,кв. железник изток предпочитан заради спокойна...,,97900.0,89.0,1100.00
50276,1c175619625640256,https://www.imot.bg/obiava-1c175619625640256-p...,3-СТАЕН,град Стара Загора,Железник,кв. Железник изток предпочитан заради сп...,кв. железник изток предпочитан заради спокойна...,<NA>,кв. железник изток предпочитан заради спокойна...,,109900.0,99.0,1110.10

In [48]:
# ------------------------------------------------------------
# Better fix for remaining other_unknown using title_city_raw + title_geo_2_raw
# No blanket "oblast -> small_city"
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

# Normalize title fields
df_model_base["title_city_model"] = (
    df_model_base["title_city_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

df_model_base["title_geo_2_model"] = (
    df_model_base["title_geo_2_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

# Drop Greece based on title_city_raw
before_rows = len(df_model_base)

drop_greece_mask = df_model_base["title_city_model"].eq("гърция")

dropped_greece_title_city = df_model_base.loc[drop_greece_mask].copy()
df_model_base = df_model_base.loc[~drop_greece_mask].copy()

print("Dropped Greece rows:", len(dropped_greece_title_city))


large_regional_city_titles = {
    "град пловдив",
    "град варна",
    "град бургас",
}

regional_city_titles = {
    "град русе",
    "град стара загора",
    "град плевен",
    "град велико търново",
    "град шумен",
    "град добрич",
    "град сливен",
    "град хасково",
    "град ямбол",
    "град перник",
    "град благоевград",
    "град пазарджик",
    "град враца",
    "град габрово",
    "град кърджали",
    "град кюстендил",
    "град ловеч",
    "град монтана",
    "град разград",
    "град силистра",
    "град смолян",
    "град търговище",
    "град видин",
}

capital_center_areas_from_title = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}


def map_unknown_from_title_city_geo(row):
    title_city = row.get("title_city_model")
    title_geo_2 = row.get("title_geo_2_model")

    title_city = "" if pd.isna(title_city) else str(title_city).strip().lower()
    title_geo_2 = "" if pd.isna(title_geo_2) else str(title_geo_2).strip().lower()

    # Sofia: use title_geo_2 to split center vs non-center
    if title_city == "град софия":
        if title_geo_2 in capital_center_areas_from_title:
            return "capital_center"
        return "capital_non_center"

    # Villages under oblast
    if title_city.startswith("област ") and (
        title_geo_2.startswith("с. ")
        or title_geo_2.startswith("село ")
    ):
        return "village"

    # Towns under oblast
    if title_city.startswith("област ") and (
        title_geo_2.startswith("гр. ")
        or title_geo_2.startswith("град ")
        or title_geo_2.startswith("к.к. ")
    ):
        return "small_city"

    # Large regional city direct
    if title_city in large_regional_city_titles:
        return "large_regional_city"

    # Regional city direct
    if title_city in regional_city_titles:
        return "regional_city"

    # Other direct city
    if title_city.startswith("град "):
        return "small_city"

    # Region without usable settlement detail
    if title_city.startswith("област "):
        return "small_city"

    return "other_unknown"


# Reclassify only remaining other_unknown
remaining_unknown_mask = df_model_base["geo_category"].eq("other_unknown")

reclassified_from_title_fields = df_model_base.loc[remaining_unknown_mask].copy()

df_model_base.loc[remaining_unknown_mask, "geo_category"] = (
    df_model_base.loc[remaining_unknown_mask]
    .apply(map_unknown_from_title_city_geo, axis=1)
)

print("Rows before:", before_rows)
print("Rows after:", len(df_model_base))
print("Rows reclassified from title fields:", len(reclassified_from_title_fields))

print("\nUpdated geo_category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("\nRemaining other_unknown rows:", len(remaining_other_unknown))

display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "title_geo_2_raw",
            "location_raw",
            "title_city_model",
            "title_geo_2_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)

cleanup_actions.append({
    "rule": "drop_greece_by_title_city",
    "reason": "Greece listings are outside the Bulgarian target market; title_city_raw is the reliable field when location_raw is corrupted",
    "rows_affected": len(dropped_greece_title_city),
})

cleanup_actions.append({
    "rule": "reclassify_other_unknown_using_title_city_and_geo_2",
    "reason": "Rows with corrupted location_raw were reclassified using title_city_raw and title_geo_2_raw, preserving village vs small-city distinction",
    "rows_affected": len(reclassified_from_title_fields),
})

Dropped Greece rows: 1
Rows before: 160522
Rows after: 160521
Rows reclassified from title fields: 333

Updated geo_category distribution:

          geo_category   rows
0  large_regional_city  38953
1              village  30014
2   capital_non_center  28960
3        regional_city  24220
4           sea_resort  16842
5           small_city  12108
6       capital_center   5432
7      mountain_resort   3992

Remaining other_unknown rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_raw, title_geo_2_raw, location_raw, title_city_model, title_geo_2_model, total_price, area_sqm, price_per_sqm]
Index: []

In [49]:
# ------------------------------------------------------------
# Normalize title_city_raw and title_geo_2_raw
# - lowercase
# - trim whitespace
# - remove settlement prefixes from title_geo_2
# ------------------------------------------------------------

df_model_base = df_model_base.copy()


def normalize_bg_text(value):
    if pd.isna(value):
        return pd.NA

    value = str(value).strip().lower()
    value = value.replace("ё", "е")
    value = value.replace("̀", "")
    value = value.replace("'", "")
    value = value.replace('"', "")
    value = " ".join(value.split())

    if value in {"", "none", "nan", "<na>"}:
        return pd.NA

    return value


def remove_geo_prefix(value):
    if pd.isna(value):
        return pd.NA

    value = normalize_bg_text(value)

    if pd.isna(value):
        return pd.NA

    prefixes = [
        "гр. ",
        "град ",
        "с. ",
        "село ",
        "к.к. ",
        "кк ",
        "курорт ",
        "ж.к. ",
        "кв. ",
        "м-т ",
        "м. ",
        "местност ",
        "в.з. ",
        "с.о. ",
        "п.к. ",
    ]

    changed = True
    while changed:
        changed = False

        for prefix in prefixes:
            if value.startswith(prefix):
                value = value[len(prefix):].strip()
                changed = True

    return value if value else pd.NA


# Normalized city field
df_model_base["title_city_model"] = (
    df_model_base["title_city_raw"]
    .apply(normalize_bg_text)
)

# Normalized geo_2 field, with prefix removed
df_model_base["title_geo_2_model"] = (
    df_model_base["title_geo_2_raw"]
    .apply(remove_geo_prefix)
)


print("Unique title_city_raw:", df_model_base["title_city_raw"].nunique(dropna=False))
print("Unique title_city_model:", df_model_base["title_city_model"].nunique(dropna=False))

print("Unique title_geo_2_raw:", df_model_base["title_geo_2_raw"].nunique(dropna=False))
print("Unique title_geo_2_model:", df_model_base["title_geo_2_model"].nunique(dropna=False))


print("\nTop title_city_model:")
display(
    df_model_base["title_city_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("title_city_model")
    .reset_index(name="rows")
)

print("\nTop title_geo_2_model:")
display(
    df_model_base["title_geo_2_model"]
    .value_counts(dropna=False)
    .head(100)
    .rename_axis("title_geo_2_model")
    .reset_index(name="rows")
)


cleanup_actions.append({
    "rule": "normalize_title_city_and_geo_2",
    "reason": "Created lowercase normalized location fields and removed settlement/location prefixes from title_geo_2 for cleaner geo mapping",
    "rows_affected": 0,
    "columns_added": 2,
})

Unique title_city_raw: 54
Unique title_city_model: 54
Unique title_geo_2_raw: 3629
Unique title_geo_2_model: 3499

Top title_city_model:

         title_city_model   rows
0              град софия  34392
1           област бургас  18177
2              град варна  17359
3            град пловдив  17136
4          област пловдив   7929
5            област софия   5041
6             град бургас   4458
7   област велико търново   3965
8            област варна   3724
9       град стара загора   3483
10          област добрич   3460
11              град русе   3105
12            град плевен   2817
13     област благоевград   2749
14             град шумен   2690
15    област стара загора   2099
16    град велико търново   2049
17       област пазарджик   1964
18         област габрово   1732
19           област ловеч   1636
20          област перник   1616
21          град кърджали   1317
22            град перник   1239
23           област шумен   1106
24            област русе   1104
25          област плевен   1055
26             град враца    992
27       област кюстендил    973
28         област хасково    854
29       град благоевград    825
30           град габрово    808
31            град добрич    804
32          област смолян    800
33         град пазарджик    793
34           град хасково    716
35           област враца    588
36         град търговище    570
37        област кърджали    540
38         област монтана    344
39           град разград    334
40           град монтана    333
41             град видин    312
42           област видин    290
43             град ловеч    285
44            град сливен    258
45           област ямбол    249
46       област търговище    241
47             град ямбол    202
48          област сливен    202
49            град смолян    200

Top title_geo_2_model:

    title_geo_2_model   rows
0              център  10759
1        слънчев бряг   3051
2          свети влас   2533
3   христо смирненски   2386
4     малинова долина   2337
..                ...    ...
95       въстанически    299
96         костинброд    299
97           брестник    298
98           казанлък    292
99      хаджи димитър    289

[100 rows x 2 columns]

In [50]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160521 entries, 0 to 164669
Data columns (total 36 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ad_id                   160521 non-null  object
 1   ad_url                  160521 non-null  object
 2   listing_type            160521 non-null  object
 3   property_type_raw       160521 non-null  object
 4   title_city_raw          160521 non-null  object
 5   title_geo_2_raw         160518 non-null  object
 6   title_area_sqm          158267 non-null  float64
 7   seller_name_raw         150250 non-null  object
 8   total_price             160521 non-null  float64
 9   currency                160521 non-null  object
 10  vat_status              160521 non-null  object
 11  area_sqm                160521 non-null  float64
 12  price_per_sqm           160521 non-null  float64
 13  floor                   99341 non-null   float64
 14  total_floors            91848 non-null   float64
 15  construction_type       123328 non-null  object
 16  construction_year       160521 non-null  int64
 17  location_raw            160521 non-null  object
 18  features_pipe           141589 non-null  object
 19  features_count          160521 non-null  int64
 20  published_raw           42330 non-null   object
 21  views                   160521 non-null  float64
 22  area_sqm_raw            160521 non-null  float64
 23  price_per_sqm_raw       160521 non-null  float64
 24  location_level_1        160521 non-null  object
 25  location_level_2        160456 non-null  object
 26  location_level_3        24465 non-null   object
 27  location_level_1_model  160521 non-null  string
 28  location_level_2_model  160456 non-null  string
 29  location_level_3_model  24465 non-null   string
 30  geo_category            160521 non-null  object
 31  location_level_1_norm   160521 non-null  object
 32  location_level_2_norm   160521 non-null  object
 33  location_level_3_norm   160521 non-null  object
 34  title_city_model        160521 non-null  object
 35  title_geo_2_model       160518 non-null  object
dtypes: float64(9), int64(2), object(22), string(3)
memory usage: 45.3+ MB

In [51]:
# ------------------------------------------------------------
# Keep only useful columns and overwrite df_model_base
# ------------------------------------------------------------

useful_columns = [
    # Traceability
    "ad_id",
    "ad_url",

    # Core listing attributes
    "listing_type",
    "property_type_raw",

    # Target / price
    "total_price",
    "currency",
    "vat_status",
    "area_sqm",
    "price_per_sqm",

    # Building / physical features
    "floor",
    "total_floors",
    "construction_type",
    "construction_year",

    # Clean geo features
    "title_city_model",
    "title_geo_2_model",
    "geo_category",

    # Feature engineering inputs
    "features_pipe",
    "features_count",

    # Listing metadata
    "views",
]

df_model_base = df_model_base[useful_columns].copy()

print("Rows:", len(df_model_base))
print("Columns:", df_model_base.shape[1])

display(df_model_base.info())

Rows: 160521
Columns: 19
<class 'pandas.core.frame.DataFrame'>
Index: 160521 entries, 0 to 164669
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              160521 non-null  object
 1   ad_url             160521 non-null  object
 2   listing_type       160521 non-null  object
 3   property_type_raw  160521 non-null  object
 4   total_price        160521 non-null  float64
 5   currency           160521 non-null  object
 6   vat_status         160521 non-null  object
 7   area_sqm           160521 non-null  float64
 8   price_per_sqm      160521 non-null  float64
 9   floor              99341 non-null   float64
 10  total_floors       91848 non-null   float64
 11  construction_type  123328 non-null  object
 12  construction_year  160521 non-null  int64
 13  title_city_model   160521 non-null  object
 14  title_geo_2_model  160518 non-null  object
 15  geo_category       160521 non-null  object
 16  features_pipe      141589 non-null  object
 17  features_count     160521 non-null  int64
 18  views              160521 non-null  float64
dtypes: float64(6), int64(2), object(11)
memory usage: 24.5+ MB

None

In [52]:
# ------------------------------------------------------------
# Explore construction_type and construction_year
# ------------------------------------------------------------

print("Rows:", len(df_model_base))

print("\nconstruction_type missing:")
print(df_model_base["construction_type"].isna().sum())
print(round(df_model_base["construction_type"].isna().mean() * 100, 2), "%")

print("\nconstruction_type distribution:")
display(
    df_model_base["construction_type"]
    .value_counts(dropna=False)
    .rename_axis("construction_type")
    .reset_index(name="rows")
)

print("\nconstruction_year summary:")
display(
    df_model_base["construction_year"]
    .describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999])
)

Rows: 160521

construction_type missing:
37193
23.17 %

construction_type distribution:

       construction_type    rows
0                  Тухла  109362
1                   None   37193
2                  Панел    7471
3               Гредоред    3281
4                    ЕПК    1907
5  Сглобяема конструкция     648
6      Ново строителство     464
7                Монолит     146
8           Стоманобетон      41
9     Старо строителство       8

construction_year summary:

count    160521.000000
mean       2017.496477
std          17.148408
min        1950.000000
0.1%       1950.000000
0.5%       1950.000000
1%         1960.000000
5%         1980.000000
50%        2026.000000
95%        2027.000000
99%        2028.000000
99.5%      2029.000000
99.9%      2030.000000
max        2049.000000
Name: construction_year, dtype: float64

In [53]:
# ------------------------------------------------------------
# Inspect suspicious construction_year values
# ------------------------------------------------------------

suspicious_years = df_model_base.loc[
    (df_model_base["construction_year"] <= 1800)
    | (df_model_base["construction_year"] > 2035)
].copy()

print("Suspicious construction_year rows:", len(suspicious_years))

display(
    suspicious_years[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_year",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values("construction_year")
    .head(100)
)

Suspicious construction_year rows: 82

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type,construction_year,total_price,area_sqm,price_per_sqm
126102,1r141093463707645,https://www.imot.bg/obiava-1r141093463707645-p...,ПАРЦЕЛ,област плевен,ясен,village,None,2036,14000.0,2036.0,6.88
126545,1r149211805106805,https://www.imot.bg/obiava-1r149211805106805-p...,ПАРЦЕЛ,град софия,люлин 5,capital_non_center,None,2036,420000.0,2036.0,206.29
107724,1j177503553254998,https://www.imot.bg/obiava-1j177503553254998-p...,КЪЩА,област стара загора,старозагорски бани,village,Тухла,2036,295000.0,300.0,983.33
133347,1r170239284876614,https://www.imot.bg/obiava-1r170239284876614-p...,ПАРЦЕЛ,град софия,лозен,capital_non_center,None,2036,244400.0,2036.0,120.04
144600,1r175275665954514,https://www.imot.bg/obiava-1r175275665954514-p...,ПАРЦЕЛ,област перник,магистрала люлин,small_city,None,2036,420000.0,2036.0,206.29
...,...,...,...,...,...,...,...,...,...,...,...
152398,1r177002934856978,https://www.imot.bg/obiava-1r177002934856978-p...,ПАРЦЕЛ,град пловдив,индустриална зона,large_regional_city,None,2048,103000.0,2048.0,50.29
152394,1r177002923787020,https://www.imot.bg/obiava-1r177002923787020-p...,ПАРЦЕЛ,град пловдив,индустриална зона,large_regional_city,None,2048,103000.0,2048.0,50.29
129710,1r165451031003426,https://www.imot.bg/obiava-1r165451031003426-p...,ПАРЦЕЛ,град софия,бусманци,capital_non_center,None,2049,160000.0,2049.0,78.09
149959,1r176485620257607,https://www.imot.bg/obiava-1r176485620257607-p...,ПАРЦЕЛ,област стара загора,ново село,village,None,2049,20000.0,2049.0,9.76
153875,1r177221122834853,https://www.imot.bg/obiava-1r177221122834853-p...,ПАРЦЕЛ,град русе,дружба 3,regional_city,None,2049,80000.0,2049.0,39.04

In [54]:
# ------------------------------------------------------------
# construction_type x construction_year profile
# ------------------------------------------------------------

construction_profile = (
    df_model_base
    .groupby("construction_type", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_year=("construction_year", "min"),
        p05_year=("construction_year", lambda s: s.quantile(0.05)),
        median_year=("construction_year", "median"),
        p95_year=("construction_year", lambda s: s.quantile(0.95)),
        max_year=("construction_year", "max"),
        median_price=("total_price", "median"),
        median_ppsqm=("price_per_sqm", "median"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(construction_profile)

,construction_type,rows,min_year,p05_year,median_year,p95_year,max_year,median_price,median_ppsqm
8,Тухла,109362,1950,1970.0,2026.0,2028.0,2048,150000.00,1555.480
9,NaN,37193,1950,2022.0,2026.0,2026.0,2049,71580.00,47.370
4,Панел,7471,1950,1970.0,1990.0,2026.0,2040,121000.00,1616.280
0,Гредоред,3281,1950,1950.0,2026.0,2026.0,2026,43500.00,437.500
1,ЕПК,1907,1950,1970.0,1990.0,2026.0,2028,148000.00,1904.760
5,Сглобяема конструкция,648,1960,1990.0,2026.0,2026.0,2028,115000.00,700.000
3,Ново строителство,464,1953,2023.0,2026.0,2026.0,2026,66546.47,140.030
2,Монолит,146,1980,2000.0,2026.0,2026.0,2026,45000.00,93.745
7,Стоманобетон,41,1970,2009.0,2026.0,2026.0,2027,290000.00,97.360
6,Старо строителство,8,2026,2026.0,2026.0,2026.0,2026,14500.00,694.445

In [55]:
# ------------------------------------------------------------
# Inspect land-related listings vs missing construction fields
# ------------------------------------------------------------

land_property_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

df_land_check = df_model_base.copy()

df_land_check["is_land_related"] = df_land_check["property_type_raw"].isin(land_property_types)

# 1. Count land vs non-land
print("Land-related rows:")
display(
    df_land_check["is_land_related"]
    .value_counts(dropna=False)
    .rename_axis("is_land_related")
    .reset_index(name="rows")
)

# 2. Property type distribution for land-related candidates
print("\nLand-related property_type_raw distribution:")
display(
    df_land_check.loc[df_land_check["is_land_related"], "property_type_raw"]
    .value_counts(dropna=False)
    .rename_axis("property_type_raw")
    .reset_index(name="rows")
)

# 3. Compare missing construction_type by land flag
print("\nMissing construction_type by land flag:")
display(
    df_land_check
    .assign(construction_type_missing=df_land_check["construction_type"].isna())
    .groupby("is_land_related")
    .agg(
        rows=("ad_id", "count"),
        missing_construction_type=("construction_type_missing", "sum"),
        missing_construction_type_pct=("construction_type_missing", lambda s: round(s.mean() * 100, 2)),
        non_missing_construction_type=("construction_type", lambda s: s.notna().sum()),
    )
    .reset_index()
)

# 4. Construction year completeness by land flag
print("\nConstruction year check by land flag:")
display(
    df_land_check
    .assign(
        construction_year_missing=df_land_check["construction_year"].isna(),
        construction_year_zero=df_land_check["construction_year"].eq(0),
        construction_year_positive=df_land_check["construction_year"].gt(0),
    )
    .groupby("is_land_related")
    .agg(
        rows=("ad_id", "count"),
        missing_year=("construction_year_missing", "sum"),
        zero_year=("construction_year_zero", "sum"),
        positive_year=("construction_year_positive", "sum"),
        min_year=("construction_year", "min"),
        median_year=("construction_year", "median"),
        max_year=("construction_year", "max"),
    )
    .reset_index()
)

# 5. Cross-tab: land-related vs construction_type
print("\nconstruction_type distribution for land-related rows:")
display(
    df_land_check.loc[df_land_check["is_land_related"], "construction_type"]
    .value_counts(dropna=False)
    .rename_axis("construction_type")
    .reset_index(name="rows")
)

# 6. Land rows with non-null construction_type
print("\nLand rows with non-null construction_type:")
land_with_construction_type = df_land_check.loc[
    df_land_check["is_land_related"]
    & df_land_check["construction_type"].notna()
].copy()

print("Rows:", len(land_with_construction_type))

display(
    land_with_construction_type[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_year",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)

Land-related rows:

   is_land_related    rows
0            False  124906
1             True   35615

Land-related property_type_raw distribution:

  property_type_raw   rows
0            ПАРЦЕЛ  33361
1   ЗЕМЕДЕЛСКА ЗЕМЯ   2254

Missing construction_type by land flag:

,is_land_related,rows,missing_construction_type,missing_construction_type_pct,non_missing_construction_type
0,False,124906,2229,1.78,122677
1,True,35615,34964,98.17,651

Construction year check by land flag:

,is_land_related,rows,missing_year,zero_year,positive_year,min_year,median_year,max_year
0,False,124906,0,0,124906,1950,2026.0,2048
1,True,35615,0,0,35615,1950,2026.0,2049

construction_type distribution for land-related rows:

       construction_type   rows
0                   None  34964
1      Ново строителство    330
2                  Панел    146
3                Монолит     97
4           Стоманобетон     25
5               Гредоред     18
6  Сглобяема конструкция     16
7                  Тухла     16
8     Старо строителство      2
9                    ЕПК      1

Land rows with non-null construction_type:
Rows: 651

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type,construction_year,total_price,area_sqm,price_per_sqm
125386,1r117222015891705,https://www.imot.bg/obiava-1r117222015891705-p...,ПАРЦЕЛ,област софия,хераково,village,Ново строителство,2026,54825.00,731.0,75.00
125451,1r121939503137224,https://www.imot.bg/obiava-1r121939503137224-p...,ПАРЦЕЛ,град габрово,център,regional_city,Монолит,2000,90000.00,2000.0,45.00
125458,1r122156113495258,https://www.imot.bg/obiava-1r122156113495258-p...,ПАРЦЕЛ,област софия,хераково,village,Ново строителство,2026,106650.00,1422.0,75.00
125466,1r121939266470060,https://www.imot.bg/obiava-1r121939266470060-p...,ПАРЦЕЛ,град габрово,център,regional_city,Монолит,2026,133680.00,3342.0,40.00
125475,1r121939276274603,https://www.imot.bg/obiava-1r121939276274603-p...,ПАРЦЕЛ,област габрово,кметовци,village,Монолит,2026,15338.76,854.0,17.96
...,...,...,...,...,...,...,...,...,...,...,...
132322,1r169234995761783,https://www.imot.bg/obiava-1r169234995761783-p...,ПАРЦЕЛ,област пазарджик,жребичко,village,Монолит,2026,45000.00,346.0,130.06
132587,1r169527548628957,https://www.imot.bg/obiava-1r169527548628957-p...,ПАРЦЕЛ,град софия,горни богров,capital_non_center,Панел,2026,500000.00,6831.0,73.20
132637,1r169563809121530,https://www.imot.bg/obiava-1r169563809121530-p...,ПАРЦЕЛ,град варна,прибой,large_regional_city,Ново строителство,2026,621000.00,5400.0,115.00
132707,1r169649977154545,https://www.imot.bg/obiava-1r169649977154545-p...,ПАРЦЕЛ,област велико търново,орловец,village,Монолит,2025,5112.92,1680.0,3.04
132731,1r169657894043471,https://www.imot.bg/obiava-1r169657894043471-p...,ПАРЦЕЛ,област шумен,велики преслав,small_city,Панел,2026,41000.00,3499.0,11.72

In [56]:
# ------------------------------------------------------------
# Clean construction fields for land-related property types
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

land_property_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

is_land_related = df_model_base["property_type_raw"].isin(land_property_types)

# Create model-safe construction fields
df_model_base["construction_type_model"] = df_model_base["construction_type"]
df_model_base["construction_year_model"] = df_model_base["construction_year"].astype("float")

# For land, construction fields are not applicable
df_model_base.loc[is_land_related, "construction_type_model"] = "not_applicable_land"
df_model_base.loc[is_land_related, "construction_year_model"] = pd.NA

print("Land-related rows:", is_land_related.sum())

print("\nconstruction_type_model distribution:")
display(
    df_model_base["construction_type_model"]
    .value_counts(dropna=False)
    .rename_axis("construction_type_model")
    .reset_index(name="rows")
)

print("\nconstruction_year_model summary, non-land only:")
display(
    df_model_base.loc[~is_land_related, "construction_year_model"]
    .describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999])
)

cleanup_actions.append({
    "rule": "set_construction_fields_not_applicable_for_land",
    "reason": "Land listings had nonsensical construction_type/construction_year values such as Панел, Монолит, and Ново строителство; these fields are not applicable to land",
    "rows_affected": int(is_land_related.sum()),
})

Land-related rows: 35615

construction_type_model distribution:

   construction_type_model    rows
0                    Тухла  109346
1      not_applicable_land   35615
2                    Панел    7325
3                 Гредоред    3263
4                     None    2229
5                      ЕПК    1906
6    Сглобяема конструкция     632
7        Ново строителство     134
8                  Монолит      49
9             Стоманобетон      16
10      Старо строителство       6

construction_year_model summary, non-land only:

count    124906.000000
mean       2015.399428
std          18.709195
min        1950.000000
0.1%       1950.000000
0.5%       1950.000000
1%         1960.000000
5%         1970.000000
50%        2026.000000
95%        2028.000000
99%        2028.000000
99.5%      2029.000000
99.9%      2030.000000
max        2048.000000
Name: construction_year_model, dtype: float64

In [57]:
# ------------------------------------------------------------
# Inspect suspicious construction years for non-land buildings only
# ------------------------------------------------------------

non_land = ~df_model_base["property_type_raw"].isin(land_property_types)

suspicious_building_years = df_model_base.loc[
    non_land
    & (
        df_model_base["construction_year_model"].isna()
        | df_model_base["construction_year_model"].le(1800)
        | df_model_base["construction_year_model"].gt(2035)
    )
].copy()

print("Suspicious non-land construction_year rows:", len(suspicious_building_years))

display(
    suspicious_building_years[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_type_model",
            "construction_year",
            "construction_year_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["construction_year_model", "property_type_raw"], na_position="first")
    .head(100)
)

Suspicious non-land construction_year rows: 26

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type,construction_type_model,construction_year,construction_year_model,total_price,area_sqm,price_per_sqm
107724,1j177503553254998,https://www.imot.bg/obiava-1j177503553254998-p...,КЪЩА,област стара загора,старозагорски бани,village,Тухла,Тухла,2036,2036.0,295000.0,300.0,983.33
16392,1b175939463648337,https://www.imot.bg/obiava-1b175939463648337-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16434,1b175942646181887,https://www.imot.bg/obiava-1b175942646181887-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16440,1b175942336350299,https://www.imot.bg/obiava-1b175942336350299-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16443,1b175942739693686,https://www.imot.bg/obiava-1b175942739693686-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16449,1b175947094326386,https://www.imot.bg/obiava-1b175947094326386-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16452,1b175947177600145,https://www.imot.bg/obiava-1b175947177600145-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16455,1b175947149899002,https://www.imot.bg/obiava-1b175947149899002-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16460,1b175947246966478,https://www.imot.bg/obiava-1b175947246966478-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,85200.0,71.0,1200.00
51942,1c175939413046355,https://www.imot.bg/obiava-1c175939413046355-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,157300.0,121.0,1300.00
51952,1c175942704703701,https://www.imot.bg/obiava-1c175942704703701-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,149500.0,115.0,1300.00
51964,1c175947323261485,https://www.imot.bg/obiava-1c175947323261485-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2040,2040.0,136500.0,105.0,1300.00
51965,1c175947210627923,https://www.imot.bg/obiava-1c175947210627923-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,143000.0,110.0,1300.00
51966,1c175947126668213,https://www.imot.bg/obiava-1c175947126668213-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,148200.0,114.0,1300.00
51967,1c175947380590029,https://www.imot.bg/obiava-1c175947380590029-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2040,2040.0,154700.0,119.0,1300.00
51971,1c175942595661197,https://www.imot.bg/obiava-1c175942595661197-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,157300.0,121.0,1300.00
51976,1c175942777587753,https://www.imot.bg/obiava-1c175942777587753-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,149500.0,115.0,1300.00
70843,1c177918478616510,https://www.imot.bg/obiava-1c177918478616510-p...,3-СТАЕН,град пловдив,гагарин,large_regional_city,Тухла,Тухла,2040,2040.0,175000.0,120.0,1458.33
83453,1f172961668221214,https://www.imot.bg/obiava-1f172961668221214-p...,МЕЗОНЕТ,град софия,гоце делчев,capital_non_center,Тухла,Тухла,2040,2040.0,340000.0,200.0,1700.00
123462,1p174833764685538,https://www.imot.bg/obiava-1p174833764685538-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,обеля,capital_non_center,Панел,Панел,2040,2040.0,2550000.0,2040.0,1250.00
123562,1p175338395348022,https://www.imot.bg/obiava-1p175338395348022-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,волуяк,capital_non_center,Панел,Панел,2040,2040.0,2448000.0,2040.0,1200.00
119552,1n175471955713641,https://www.imot.bg/obiava-1n175471955713641-p...,СКЛАД,град софия,връбница 2,capital_non_center,Панел,Панел,2040,2040.0,2550000.0,2040.0,1250.00
123210,1p173338715705181,https://www.imot.bg/obiava-1p173338715705181-p...,ПРОМ. ПОМЕЩЕНИЕ,град пловдив,индустриална зона,large_regional_city,Тухла,Тухла,2042,2042.0,2500000.0,2042.0,1224.29
123153,1p172588346121420,https://www.imot.bg/obiava-1p172588346121420-p...,ПРОМ. ПОМЕЩЕНИЕ,област добрич,победа,village,Тухла,Тухла,2046,2046.0,435000.0,2046.0,212.61
163971,1t176354667650491,https://www.imot.bg/obiava-1t176354667650491-p...,САМОСТОЯТЕЛНА СГРАДА,град плевен,индустриална зона,regional_city,Тухла,Тухла,2047,2047.0,700000.0,2047.0,341.96
123123,1p172440864698814,https://www.imot.bg/obiava-1p172440864698814-p...,ПРОМ. ПОМЕЩЕНИЕ,град сливен,център,regional_city,Тухла,Тухла,2048,2048.0,1300000.0,2048.0,634.77

In [58]:
# ------------------------------------------------------------
# Manually correct confirmed construction_year parser errors
# ------------------------------------------------------------

manual_year_corrections = {
    # Previously confirmed
    "1t176354667650491": 1970,
    "1p172440864698814": 1970,

    # Newly confirmed
    "1p172588346121420": 1980,
    "1j177343897083535": 1960,  # true unknown, pragmatic proxy
    "1p173338715705181": 2023,
    "1n175471955713641": 2025,
    "1p175338395348022": 2016,
    "1p174833764685538": 2025,
    "1f172961668221214": 2020,  # true unknown, pragmatic proxy

    # All of these should be 2026
    "1j177503553254998": 2026,
    "1b175939463648337": 2026,
    "1b175942336350299": 2026,
    "1b175942646181887": 2026,
    "1b175942739693686": 2026,
    "1b175947149899002": 2026,
    "1b175947246966478": 2026,
    "1b175947177600145": 2026,
    "1b175947094326386": 2026,
    "1c175939413046355": 2026,
    "1c175942595661197": 2026,
    "1c175942704703701": 2026,
    "1c175947126668213": 2026,
    "1c175947210627923": 2026,
    "1c175947323261485": 2026,
    "1c175947380590029": 2026,
    "1c175942777587753": 2026,
}

# Check whether all provided ad_ids exist
provided_ids = set(manual_year_corrections.keys())
existing_ids = set(df_model_base["ad_id"])

missing_ids = sorted(provided_ids - existing_ids)

if missing_ids:
    print("WARNING - these ad_ids were not found in df_model_base:")
    print(missing_ids)

before_values = df_model_base.loc[
    df_model_base["ad_id"].isin(provided_ids),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type",
        "construction_type_model",
        "construction_year",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

for ad_id, corrected_year in manual_year_corrections.items():
    mask = df_model_base["ad_id"].eq(ad_id)

    df_model_base.loc[mask, "construction_year"] = corrected_year
    df_model_base.loc[mask, "construction_year_model"] = corrected_year

after_values = df_model_base.loc[
    df_model_base["ad_id"].isin(provided_ids),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type",
        "construction_type_model",
        "construction_year",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

print("Provided correction IDs:", len(provided_ids))
print("Corrected rows found:", len(after_values))
print("Missing IDs:", len(missing_ids))

print("\nBefore:")
display(before_values.sort_values("ad_id"))

print("\nAfter:")
display(after_values.sort_values("ad_id"))

cleanup_actions.append({
    "rule": "manual_correct_future_construction_years_extended",
    "reason": "Confirmed parser errors in future construction years; manually corrected based on listing inspection",
    "rows_affected": len(after_values),
})

WARNING - these ad_ids were not found in df_model_base:
['1j177343897083535']
Provided correction IDs: 26
Corrected rows found: 25
Missing IDs: 1

Before:

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type,construction_type_model,construction_year,construction_year_model,total_price,area_sqm,price_per_sqm
16392,1b175939463648337,https://www.imot.bg/obiava-1b175939463648337-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16440,1b175942336350299,https://www.imot.bg/obiava-1b175942336350299-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16434,1b175942646181887,https://www.imot.bg/obiava-1b175942646181887-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16443,1b175942739693686,https://www.imot.bg/obiava-1b175942739693686-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16449,1b175947094326386,https://www.imot.bg/obiava-1b175947094326386-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16455,1b175947149899002,https://www.imot.bg/obiava-1b175947149899002-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16452,1b175947177600145,https://www.imot.bg/obiava-1b175947177600145-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,93600.0,72.0,1300.00
16460,1b175947246966478,https://www.imot.bg/obiava-1b175947246966478-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,85200.0,71.0,1200.00
51942,1c175939413046355,https://www.imot.bg/obiava-1c175939413046355-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,157300.0,121.0,1300.00
51971,1c175942595661197,https://www.imot.bg/obiava-1c175942595661197-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,157300.0,121.0,1300.00
51952,1c175942704703701,https://www.imot.bg/obiava-1c175942704703701-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,149500.0,115.0,1300.00
51976,1c175942777587753,https://www.imot.bg/obiava-1c175942777587753-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,149500.0,115.0,1300.00
51966,1c175947126668213,https://www.imot.bg/obiava-1c175947126668213-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,148200.0,114.0,1300.00
51965,1c175947210627923,https://www.imot.bg/obiava-1c175947210627923-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2040,2040.0,143000.0,110.0,1300.00
51964,1c175947323261485,https://www.imot.bg/obiava-1c175947323261485-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2040,2040.0,136500.0,105.0,1300.00
51967,1c175947380590029,https://www.imot.bg/obiava-1c175947380590029-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2040,2040.0,154700.0,119.0,1300.00
83453,1f172961668221214,https://www.imot.bg/obiava-1f172961668221214-p...,МЕЗОНЕТ,град софия,гоце делчев,capital_non_center,Тухла,Тухла,2040,2040.0,340000.0,200.0,1700.00
107724,1j177503553254998,https://www.imot.bg/obiava-1j177503553254998-p...,КЪЩА,област стара загора,старозагорски бани,village,Тухла,Тухла,2036,2036.0,295000.0,300.0,983.33
119552,1n175471955713641,https://www.imot.bg/obiava-1n175471955713641-p...,СКЛАД,град софия,връбница 2,capital_non_center,Панел,Панел,2040,2040.0,2550000.0,2040.0,1250.00
123123,1p172440864698814,https://www.imot.bg/obiava-1p172440864698814-p...,ПРОМ. ПОМЕЩЕНИЕ,град сливен,център,regional_city,Тухла,Тухла,2048,2048.0,1300000.0,2048.0,634.77
123153,1p172588346121420,https://www.imot.bg/obiava-1p172588346121420-p...,ПРОМ. ПОМЕЩЕНИЕ,област добрич,победа,village,Тухла,Тухла,2046,2046.0,435000.0,2046.0,212.61
123210,1p173338715705181,https://www.imot.bg/obiava-1p173338715705181-p...,ПРОМ. ПОМЕЩЕНИЕ,град пловдив,индустриална зона,large_regional_city,Тухла,Тухла,2042,2042.0,2500000.0,2042.0,1224.29
123462,1p174833764685538,https://www.imot.bg/obiava-1p174833764685538-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,обеля,capital_non_center,Панел,Панел,2040,2040.0,2550000.0,2040.0,1250.00
123562,1p175338395348022,https://www.imot.bg/obiava-1p175338395348022-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,волуяк,capital_non_center,Панел,Панел,2040,2040.0,2448000.0,2040.0,1200.00
163971,1t176354667650491,https://www.imot.bg/obiava-1t176354667650491-p...,САМОСТОЯТЕЛНА СГРАДА,град плевен,индустриална зона,regional_city,Тухла,Тухла,2047,2047.0,700000.0,2047.0,341.96

After:

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type,construction_type_model,construction_year,construction_year_model,total_price,area_sqm,price_per_sqm
16392,1b175939463648337,https://www.imot.bg/obiava-1b175939463648337-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16440,1b175942336350299,https://www.imot.bg/obiava-1b175942336350299-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16434,1b175942646181887,https://www.imot.bg/obiava-1b175942646181887-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16443,1b175942739693686,https://www.imot.bg/obiava-1b175942739693686-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16449,1b175947094326386,https://www.imot.bg/obiava-1b175947094326386-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16455,1b175947149899002,https://www.imot.bg/obiava-1b175947149899002-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16452,1b175947177600145,https://www.imot.bg/obiava-1b175947177600145-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,93600.0,72.0,1300.00
16460,1b175947246966478,https://www.imot.bg/obiava-1b175947246966478-p...,2-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,85200.0,71.0,1200.00
51942,1c175939413046355,https://www.imot.bg/obiava-1c175939413046355-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,157300.0,121.0,1300.00
51971,1c175942595661197,https://www.imot.bg/obiava-1c175942595661197-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,157300.0,121.0,1300.00
51952,1c175942704703701,https://www.imot.bg/obiava-1c175942704703701-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,149500.0,115.0,1300.00
51976,1c175942777587753,https://www.imot.bg/obiava-1c175942777587753-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,149500.0,115.0,1300.00
51966,1c175947126668213,https://www.imot.bg/obiava-1c175947126668213-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,148200.0,114.0,1300.00
51965,1c175947210627923,https://www.imot.bg/obiava-1c175947210627923-p...,3-СТАЕН,град пловдив,коматевско шосе,large_regional_city,Тухла,Тухла,2026,2026.0,143000.0,110.0,1300.00
51964,1c175947323261485,https://www.imot.bg/obiava-1c175947323261485-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2026,2026.0,136500.0,105.0,1300.00
51967,1c175947380590029,https://www.imot.bg/obiava-1c175947380590029-p...,3-СТАЕН,град пловдив,прослав,large_regional_city,Тухла,Тухла,2026,2026.0,154700.0,119.0,1300.00
83453,1f172961668221214,https://www.imot.bg/obiava-1f172961668221214-p...,МЕЗОНЕТ,град софия,гоце делчев,capital_non_center,Тухла,Тухла,2020,2020.0,340000.0,200.0,1700.00
107724,1j177503553254998,https://www.imot.bg/obiava-1j177503553254998-p...,КЪЩА,област стара загора,старозагорски бани,village,Тухла,Тухла,2026,2026.0,295000.0,300.0,983.33
119552,1n175471955713641,https://www.imot.bg/obiava-1n175471955713641-p...,СКЛАД,град софия,връбница 2,capital_non_center,Панел,Панел,2025,2025.0,2550000.0,2040.0,1250.00
123123,1p172440864698814,https://www.imot.bg/obiava-1p172440864698814-p...,ПРОМ. ПОМЕЩЕНИЕ,град сливен,център,regional_city,Тухла,Тухла,1970,1970.0,1300000.0,2048.0,634.77
123153,1p172588346121420,https://www.imot.bg/obiava-1p172588346121420-p...,ПРОМ. ПОМЕЩЕНИЕ,област добрич,победа,village,Тухла,Тухла,1980,1980.0,435000.0,2046.0,212.61
123210,1p173338715705181,https://www.imot.bg/obiava-1p173338715705181-p...,ПРОМ. ПОМЕЩЕНИЕ,град пловдив,индустриална зона,large_regional_city,Тухла,Тухла,2023,2023.0,2500000.0,2042.0,1224.29
123462,1p174833764685538,https://www.imot.bg/obiava-1p174833764685538-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,обеля,capital_non_center,Панел,Панел,2025,2025.0,2550000.0,2040.0,1250.00
123562,1p175338395348022,https://www.imot.bg/obiava-1p175338395348022-p...,ПРОМ. ПОМЕЩЕНИЕ,град софия,волуяк,capital_non_center,Панел,Панел,2016,2016.0,2448000.0,2040.0,1200.00
163971,1t176354667650491,https://www.imot.bg/obiava-1t176354667650491-p...,САМОСТОЯТЕЛНА СГРАДА,град плевен,индустриална зона,regional_city,Тухла,Тухла,1970,1970.0,700000.0,2047.0,341.96

In [59]:
# ------------------------------------------------------------
# Recheck future construction years after manual corrections
# ------------------------------------------------------------

future_years = df_model_base.loc[
    df_model_base["construction_year_model"].gt(2035),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type_model",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

print("Remaining future construction_year_model rows:", len(future_years))

display(
    future_years
    .sort_values("construction_year_model", ascending=False)
    .head(100)
)

Remaining future construction_year_model rows: 1

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,construction_type_model,construction_year_model,total_price,area_sqm,price_per_sqm
70843,1c177918478616510,https://www.imot.bg/obiava-1c177918478616510-p...,3-СТАЕН,град пловдив,гагарин,large_regional_city,Тухла,2040.0,175000.0,120.0,1458.33

In [60]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160521 entries, 0 to 164669
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    160521 non-null  object
 1   ad_url                   160521 non-null  object
 2   listing_type             160521 non-null  object
 3   property_type_raw        160521 non-null  object
 4   total_price              160521 non-null  float64
 5   currency                 160521 non-null  object
 6   vat_status               160521 non-null  object
 7   area_sqm                 160521 non-null  float64
 8   price_per_sqm            160521 non-null  float64
 9   floor                    99341 non-null   float64
 10  total_floors             91848 non-null   float64
 11  construction_type        123328 non-null  object
 12  construction_year        160521 non-null  int64
 13  title_city_model         160521 non-null  object
 14  title_geo_2_model        160518 non-null  object
 15  geo_category             160521 non-null  object
 16  features_pipe            141589 non-null  object
 17  features_count           160521 non-null  int64
 18  views                    160521 non-null  float64
 19  construction_type_model  158292 non-null  object
 20  construction_year_model  124906 non-null  float64
dtypes: float64(7), int64(2), object(12)
memory usage: 26.9+ MB

In [61]:
# ------------------------------------------------------------
# Inspect non-building property types with floor data
# ------------------------------------------------------------

floor_not_applicable_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
    "СОЛАРЕН ПАРК",
}

non_building_with_floor = df_model_base.loc[
    df_model_base["property_type_raw"].isin(floor_not_applicable_types)
    & (
        df_model_base["floor"].notna()
        | df_model_base["total_floors"].notna()
    )
].copy()

print("Non-building rows with floor/total_floors populated:", len(non_building_with_floor))

display(
    non_building_with_floor[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor", "total_floors"])
    .head(100)
)

Non-building rows with floor/total_floors populated: 10

,ad_id,ad_url,property_type_raw,title_city_model,title_geo_2_model,geo_category,floor,total_floors,total_price,area_sqm,price_per_sqm
163062,1t169269241339101,https://www.imot.bg/obiava-1t169269241339101-p...,СОЛАРЕН ПАРК,област шумен,новосел,village,0.0,1.0,76693.78,663.0,115.68
163726,1t175342694532880,https://www.imot.bg/obiava-1t175342694532880-p...,СОЛАРЕН ПАРК,град русе,образцов чифлик,regional_city,0.0,1.0,6250000.00,53670.0,116.45
164151,1t177028156147273,https://www.imot.bg/obiava-1t177028156147273-p...,СОЛАРЕН ПАРК,град враца,дъбника,regional_city,0.0,1.0,989000.00,23000.0,43.00
164360,1t177461364893028,https://www.imot.bg/obiava-1t177461364893028-p...,СОЛАРЕН ПАРК,област пловдив,асеновград,small_city,0.0,1.0,799000.00,15527.0,51.46
164400,1t177591914946249,https://www.imot.bg/obiava-1t177591914946249-p...,СОЛАРЕН ПАРК,област русе,глоджево,small_city,0.0,1.0,64000.00,2000.0,32.00
164522,1t177910743210389,https://www.imot.bg/obiava-1t177910743210389-p...,СОЛАРЕН ПАРК,област русе,глоджево,small_city,0.0,1.0,192000.00,3500.0,54.86
163576,1t174472037331298,https://www.imot.bg/obiava-1t174472037331298-p...,СОЛАРЕН ПАРК,област шумен,средня,village,1.0,1.0,76700.00,1501.0,51.10
163632,1t174945852611903,https://www.imot.bg/obiava-1t174945852611903-p...,СОЛАРЕН ПАРК,област добрич,дончево,village,1.0,1.0,6267500.00,26133.0,239.83
164559,1t177988109109028,https://www.imot.bg/obiava-1t177988109109028-p...,СОЛАРЕН ПАРК,област русе,писанец,village,1.0,1.0,100000.00,1257.0,79.55
164282,1t177340724318112,https://www.imot.bg/obiava-1t177340724318112-p...,СОЛАРЕН ПАРК,област русе,табачка,village,2.0,2.0,60000.00,2200.0,27.27

In [62]:
# ------------------------------------------------------------
# Create model-safe floor fields and mark non-building floors as N/A
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

floor_not_applicable_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
    "СОЛАРЕН ПАРК",
}

is_floor_not_applicable = df_model_base["property_type_raw"].isin(floor_not_applicable_types)

df_model_base["floor_model"] = df_model_base["floor"].astype("float")
df_model_base["total_floors_model"] = df_model_base["total_floors"].astype("float")

df_model_base["floor_applicability"] = "applicable"
df_model_base.loc[is_floor_not_applicable, "floor_applicability"] = "not_applicable_non_building"

df_model_base.loc[is_floor_not_applicable, "floor_model"] = pd.NA
df_model_base.loc[is_floor_not_applicable, "total_floors_model"] = pd.NA

print("Rows marked floor not applicable:", int(is_floor_not_applicable.sum()))

display(
    df_model_base["floor_applicability"]
    .value_counts(dropna=False)
    .rename_axis("floor_applicability")
    .reset_index(name="rows")
)

cleanup_actions.append({
    "rule": "set_floor_fields_not_applicable_for_non_building_types",
    "reason": "Floor and total_floors are not meaningful for land, parking-only, and solar park listings",
    "rows_affected": int(is_floor_not_applicable.sum()),
})

Rows marked floor not applicable: 35679

           floor_applicability    rows
0                   applicable  124842
1  not_applicable_non_building   35679

In [63]:
# ------------------------------------------------------------
# Inspect suspicious floor values for floor-applicable listings
# ------------------------------------------------------------

floor_applicable = df_model_base["floor_applicability"].eq("applicable")

suspicious_floor_rows = df_model_base.loc[
    floor_applicable
    & (
        df_model_base["floor_model"].lt(-5)
        | df_model_base["floor_model"].gt(60)
        | df_model_base["total_floors_model"].gt(80)
        | (
            df_model_base["floor_model"].notna()
            & df_model_base["total_floors_model"].notna()
            & df_model_base["floor_model"].gt(df_model_base["total_floors_model"] + 2)
        )
    )
].copy()

print("Suspicious floor rows:", len(suspicious_floor_rows))

display(
    suspicious_floor_rows[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "floor_model",
            "total_floors_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor_model", "total_floors_model"])
    .head(100)
)

Suspicious floor rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_model, title_geo_2_model, geo_category, floor, total_floors, floor_model, total_floors_model, total_price, area_sqm, price_per_sqm]
Index: []

In [64]:
# ------------------------------------------------------------
# Inspect suspicious floor values for floor-applicable listings
# ------------------------------------------------------------

floor_applicable = df_model_base["floor_applicability"].eq("applicable")

suspicious_floor_rows = df_model_base.loc[
    floor_applicable
    & (
        df_model_base["floor_model"].lt(-5)
        | df_model_base["floor_model"].gt(60)
        | df_model_base["total_floors_model"].gt(80)
        | (
            df_model_base["floor_model"].notna()
            & df_model_base["total_floors_model"].notna()
            & df_model_base["floor_model"].gt(df_model_base["total_floors_model"] + 2)
        )
    )
].copy()

print("Suspicious floor rows:", len(suspicious_floor_rows))

display(
    suspicious_floor_rows[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "floor_model",
            "total_floors_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor_model", "total_floors_model"])
    .head(100)
)

Suspicious floor rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_model, title_geo_2_model, geo_category, floor, total_floors, floor_model, total_floors_model, total_price, area_sqm, price_per_sqm]
Index: []

In [74]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    159466 non-null  object
 1   ad_url                   159466 non-null  object
 2   listing_type             159466 non-null  object
 3   property_type_raw        159466 non-null  object
 4   total_price              159466 non-null  float64
 5   currency                 159466 non-null  object
 6   vat_status               159466 non-null  object
 7   area_sqm                 159466 non-null  float64
 8   price_per_sqm            159466 non-null  float64
 9   floor                    97454 non-null   float64
 10  total_floors             90480 non-null   float64
 11  construction_type        120724 non-null  object
 12  construction_year        159466 non-null  int64
 13  title_city_model         159466 non-null  object
 14  title_geo_2_model        159463 non-null  object
 15  geo_category             159466 non-null  object
 16  features_pipe            139702 non-null  object
 17  features_count           159466 non-null  int64
 18  views                    159466 non-null  float64
 19  construction_type_model  157277 non-null  object
 20  construction_year_model  122212 non-null  float64
 21  floor_model              97446 non-null   float64
 22  total_floors_model       90472 non-null   float64
 23  floor_applicability      159466 non-null  object
dtypes: float64(9), int64(2), object(13)
memory usage: 30.4+ MB

In [65]:
# ------------------------------------------------------------
# Final cleanup: create ML-ready dataset and save to Parquet
# ------------------------------------------------------------

# Choose your output path
ML_OUTPUT_PATH = PARSED_DATA_DIR / LATEST_RUN / "imot_ml_ready.parquet"

df_ml_ready = df_model_base.copy()

# ------------------------------------------------------------
# 1. Keep only model-useful columns
# ------------------------------------------------------------

ml_ready_columns = [
    # Traceability - keep for audit, drop before fitting if needed
    "ad_id",
    "ad_url",

    # Core categorical features
    "listing_type",
    "property_type_raw",
    "currency",
    "vat_status",
    "title_city_model",
    "title_geo_2_model",
    "geo_category",

    # Numeric target / features
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "views",
    "features_count",

    # Cleaned construction features
    "construction_type_model",
    "construction_year_model",

    # Cleaned floor features
    "floor_model",
    "total_floors_model",
    "floor_applicability",

    # Feature engineering input
    "features_pipe",
]

ml_ready_columns = [
    col for col in ml_ready_columns
    if col in df_ml_ready.columns
]

df_ml_ready = df_ml_ready[ml_ready_columns].copy()


# ------------------------------------------------------------
# 2. Standardize missing categorical values
# ------------------------------------------------------------

categorical_cols = [
    "listing_type",
    "property_type_raw",
    "currency",
    "vat_status",
    "title_city_model",
    "title_geo_2_model",
    "geo_category",
    "construction_type_model",
    "floor_applicability",
    "features_pipe",
]

for col in categorical_cols:
    if col in df_ml_ready.columns:
        df_ml_ready[col] = (
            df_ml_ready[col]
            .astype("string")
            .str.strip()
        )
        df_ml_ready[col] = df_ml_ready[col].fillna("unknown")


# ------------------------------------------------------------
# 3. Ensure numeric columns are numeric
# ------------------------------------------------------------

numeric_cols = [
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "views",
    "features_count",
    "construction_year_model",
    "floor_model",
    "total_floors_model",
]

for col in numeric_cols:
    if col in df_ml_ready.columns:
        df_ml_ready[col] = pd.to_numeric(df_ml_ready[col], errors="coerce")


# ------------------------------------------------------------
# 4. Final sanity checks
# ------------------------------------------------------------

print("ML-ready rows:", len(df_ml_ready))
print("ML-ready columns:", df_ml_ready.shape[1])

print("\nColumns:")
print(df_ml_ready.columns.tolist())

print("\nMissing values:")
display(
    df_ml_ready
    .isna()
    .sum()
    .rename("missing")
    .reset_index()
    .rename(columns={"index": "column"})
    .sort_values("missing", ascending=False)
)

print("\nInfo:")
display(df_ml_ready.info())


# ------------------------------------------------------------
# 5. Save to Parquet
# ------------------------------------------------------------

ML_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

df_ml_ready.to_parquet(
    ML_OUTPUT_PATH,
    index=False,
)

print(f"\nSaved ML-ready dataset to: {ML_OUTPUT_PATH}")
print("Saved rows:", len(df_ml_ready))
print("Saved columns:", df_ml_ready.shape[1])


# ------------------------------------------------------------
# 6. Optional: verify reload
# ------------------------------------------------------------

df_ml_ready_check = pd.read_parquet(ML_OUTPUT_PATH)

print("\nReload check:")
print("Rows:", len(df_ml_ready_check))
print("Columns:", df_ml_ready_check.shape[1])

display(df_ml_ready_check.head())

ML-ready rows: 160521
ML-ready columns: 20

Columns:
['ad_id', 'ad_url', 'listing_type', 'property_type_raw', 'currency', 'vat_status', 'title_city_model', 'title_geo_2_model', 'geo_category', 'total_price', 'area_sqm', 'price_per_sqm', 'views', 'features_count', 'construction_type_model', 'construction_year_model', 'floor_model', 'total_floors_model', 'floor_applicability', 'features_pipe']

Missing values:

                     column  missing
17       total_floors_model    68683
16              floor_model    61190
15  construction_year_model    35615
0                     ad_id        0
3         property_type_raw        0
2              listing_type        0
1                    ad_url        0
4                  currency        0
8              geo_category        0
5                vat_status        0
6          title_city_model        0
7         title_geo_2_model        0
11            price_per_sqm        0
10                 area_sqm        0
9               total_price        0
12                    views        0
14  construction_type_model        0
13           features_count        0
18      floor_applicability        0
19            features_pipe        0

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 160521 entries, 0 to 164669
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    160521 non-null  object
 1   ad_url                   160521 non-null  object
 2   listing_type             160521 non-null  string
 3   property_type_raw        160521 non-null  string
 4   currency                 160521 non-null  string
 5   vat_status               160521 non-null  string
 6   title_city_model         160521 non-null  string
 7   title_geo_2_model        160521 non-null  string
 8   geo_category             160521 non-null  string
 9   total_price              160521 non-null  float64
 10  area_sqm                 160521 non-null  float64
 11  price_per_sqm            160521 non-null  float64
 12  views                    160521 non-null  float64
 13  features_count           160521 non-null  int64
 14  construction_type_model  160521 non-null  string
 15  construction_year_model  124906 non-null  float64
 16  floor_model              99331 non-null   float64
 17  total_floors_model       91838 non-null   float64
 18  floor_applicability      160521 non-null  string
 19  features_pipe            160521 non-null  string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 25.7+ MB

None

Saved ML-ready dataset to: D:\users\kamen.dimitrov\desktop\SOFTUNI\AI_and_ML_upskill_program\machine_learning\08_final_project_1\data\parsed_sales_runs\parsed_sales_full_20260608_081646\imot_ml_ready.parquet
Saved rows: 160521
Saved columns: 20

Reload check:
Rows: 160521
Columns: 20

,ad_id,ad_url,listing_type,property_type_raw,currency,vat_status,title_city_model,title_geo_2_model,geo_category,total_price,area_sqm,price_per_sqm,views,features_count,construction_type_model,construction_year_model,floor_model,total_floors_model,floor_applicability,features_pipe
0,1a155107752004273,https://www.imot.bg/obiava-1a155107752004273-p...,single_property_listing,1-СТАЕН,EUR,with_vat,област пазарджик,велинград,mountain_resort,57100.0,44.0,1297.73,9.0,5,Тухла,2026.0,1.0,4.0,applicable,Тухла|Асансьор|С гараж|С паркинг|Лизинг
1,1a146979303032401,https://www.imot.bg/obiava-1a146979303032401-p...,single_property_listing,1-СТАЕН,EUR,with_vat,град софия,малинова долина,capital_non_center,103000.0,36.0,2861.11,734.0,1,Тухла,2027.0,2.0,4.0,applicable,Тухла
2,1a140680337846667,https://www.imot.bg/obiava-1a140680337846667-p...,single_property_listing,1-СТАЕН,EUR,unknown,град варна,ален мак,large_regional_city,15000.0,30.0,500.00,13987.0,3,Тухла,2014.0,0.0,3.0,applicable,Тухла|Лизинг|Бартер
3,1a154997703660554,https://www.imot.bg/obiava-1a154997703660554-p...,single_property_listing,1-СТАЕН,EUR,no_vat,област бургас,свети влас,sea_resort,73600.0,48.0,1533.33,24930.0,11,Тухла,2015.0,1.0,5.0,applicable,Тухла|Асансьор|С паркинг|Лизинг|Интернет връзк...
4,1a155107630313014,https://www.imot.bg/obiava-1a155107630313014-p...,single_property_listing,1-СТАЕН,EUR,with_vat,област пазарджик,велинград,mountain_resort,52200.0,48.0,1087.50,4.0,7,Тухла,2027.0,0.0,2.0,applicable,Тухла|Асансьор|С гараж|С паркинг|Лизинг|Интерн...