In [1]:
%matplotlib inline

In [2]:
#Import Libraries here

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
from pathlib import Path
from IPython.display import display

In [3]:
#Import your modules here
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
PARSED_DATA_DIR = PROJECT_ROOT / "data" / "parsed_sales_full"

In [4]:
parsed_df = pd.read_parquet(PARSED_DATA_DIR / "parsed_listings.parquet")
parsed_df

,ad_id,ad_url,ad_url_path,ad_url_slug,html_path,listing_type,title,deal_raw,property_type_raw,title_city_raw,...,description_raw,description_clean,features_raw,features_pipe,features_count,published_raw,views,training_eligible,parse_error,parsed_at
0,1a129794411209548,https://www.imot.bg/obiava-1a129794411209548-p...,/obiava-1a129794411209548-prodava-ednostaen-ap...,obiava-1a129794411209548-prodava-ednostaen-apa...,data\raw_listing_html\2caac228937b3b30.html,single_property_listing,"Продава 1-СТАЕН в област Благоевград, гр. Банс...",Продава,1-СТАЕН,област Благоевград,...,Предлагаме студио 32 кв.м в сграда Никмар на ...,Предлагаме студио 32 кв.м в сграда Никмар на ...,Тухла\nОбзаведен\nКонтрол на достъпа,Тухла|Обзаведен|Контрол на достъпа,3,None,5834.0,True,NaN,2026-05-16T13:50:20.885206+00:00
1,1a127539284802892,https://www.imot.bg/obiava-1a127539284802892-p...,/obiava-1a127539284802892-prodava-ednostaen-ap...,obiava-1a127539284802892-prodava-ednostaen-apa...,data\raw_listing_html\857c7fd39ad302de.html,single_property_listing,"Продава 1-СТАЕН в област Добрич, гр. Балчик - ...",Продава,1-СТАЕН,област Добрич,...,"Балчик, комплекс 'Марина Сити'- луксозни апарт...","Балчик, комплекс 'Марина Сити'- луксозни апарт...",Тухла\nАсансьор\nИнтернет връзка\nОбзаведен\nВ...,Тухла|Асансьор|Интернет връзка|Обзаведен|Видео...,8,None,2391.0,True,NaN,2026-05-16T13:50:20.903929+00:00
2,1a126881929164804,https://www.imot.bg/obiava-1a126881929164804-p...,/obiava-1a126881929164804-prodava-ednostaen-ap...,obiava-1a126881929164804-prodava-ednostaen-apa...,data\raw_listing_html\9208ce061d053c01.html,single_property_listing,"Продава 1-СТАЕН в град Плевен, Дружба 1 - 40 к...",Продава,1-СТАЕН,град Плевен,...,"Продава гарсониера след ремонт- стая, кухня, б...","Продава гарсониера след ремонт- стая, кухня, б...",Панел,Панел,1,None,6579.0,True,NaN,2026-05-16T13:50:21.030575+00:00
3,1a130799086731769,https://www.imot.bg/obiava-1a130799086731769-p...,/obiava-1a130799086731769-prodava-ednostaen-ap...,obiava-1a130799086731769-prodava-ednostaen-apa...,data\raw_listing_html\ad1172ee3bcfaaed.html,single_property_listing,"Продава 1-СТАЕН в град Плевен, Дружба 4 - 40 к...",Продава,1-СТАЕН,град Плевен,...,"Продава гарсониера след ремонт, с ПВС дограма,...","Продава гарсониера след ремонт, с ПВС дограма,...",Панел\nАсансьор,Панел|Асансьор,2,None,4282.0,True,NaN,2026-05-16T13:50:21.051889+00:00
4,1a140309247069043,https://www.imot.bg/obiava-1a140309247069043-p...,/obiava-1a140309247069043-prodava-ednostaen-ap...,obiava-1a140309247069043-prodava-ednostaen-apa...,data\raw_listing_html\733a85c00c43835a.html,single_property_listing,"Продава 1-СТАЕН в област Велико Търново, гр. Г...",Продава,1-СТАЕН,област Велико Търново,...,ПАНЕЛНА ГАСОНИЕРА---КУПУВАМЕ СПЕШНО.ПЛАЩТАНЕ В...,ПАНЕЛНА ГАСОНИЕРА---КУПУВАМЕ СПЕШНО.ПЛАЩТАНЕ В...,Панел\nС преход\nАсансьор\nС гараж\nС паркинг\...,Панел|С преход|Асансьор|С гараж|С паркинг|Лизи...,14,None,3.0,True,NaN,2026-05-16T13:50:24.307483+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164068,8633,https://www.imot.bg/obiava-8633-zhilishtna-sgr...,/obiava-8633-zhilishtna-sgrada-grad-sofiya-geo...,obiava-8633-zhilishtna-sgrada-grad-sofiya-geo-...,data\raw_listing_html\dd0b17ff74a93d61.html,new_building_project,"Жилищна сграда в град София, Гео Милев :: imot...",None,None,None,...,ПОСТОЯНСТВО модерен дом с характер в кв. Гео...,ПОСТОЯНСТВО модерен дом с характер в кв. Гео...,None,None,0,"Публикувана в 11:51 на 12 май, 2026 год.",3573.0,False,NaN,None
164069,8704,https://www.imot.bg/obiava-8704-zhilishtna-sgr...,/obiava-8704-zhilishtna-sgrada-grad-ruse-charo...,obiava-8704-zhilishtna-sgrada-grad-ruse-charod...,data\raw_listing_html\25229bcec7aa7ad1.html,new_building_project,"Жилищна сграда в град Русе, Чародейка - Юг :: ...",None,None,None,...,НОВО СТРОИТЕЛСТВО В РУСЕ В Ж.К. ЧАРОДЕЙКА ЮГ |...,НОВО СТРОИТЕЛСТВО В РУСЕ В Ж.К. ЧАРОДЕЙКА ЮГ |...,None,None,0,"Публикувана в 9:57 на 12 май, 2026 год.",61.0,False,NaN,None
164070,8711,https://www.imot.bg/obiava-8711-zhilishtna-sgr...,/obiava-8711-zhilishtna-sgrada-grad-plovdiv-ky...,obiava-8711-zhilishtna-sgrada-grad-plovdiv-kyu...,data\raw_listing_html\d29c4c72a8c8cbb9.html,new_building_project,"Жилищна сграда в град Пловдив, Кючук Париж :: ...",None,None,None,...,"🌐 Локация: Кючук Париж, пресечка на бул. Никол...","🌐 Локация: Кючук Париж, пресечка на бул. Никол...",None,None,0,"Публикувана в 18:32 на 14 май, 2026 год.",44.0,False,NaN,None
164071,8712,https://www.imot.bg/obiava-8712-zhilishtna-sgr...,/obiava-8712-zhilishtna-sgrada-oblast-varna-gr...,obiava-8712-zhilishtna-sgrada-oblast-varna-gr-...,data\raw_listing_html\30397e8b238929dd.html,new_building_project,"Жилищна сграда в област Варна, гр. Бяла :: imo...",None,None,None,...,"Комплекс Панорама гр. Бяла\nМясто, където мо...","Комплекс Панорама гр. Бяла Място, където мор...",None,None,0,"Публикувана в 6:09 на 15 май, 2026 год.",97.0,False,NaN,None
164072,8619,https://www.imot.bg/obiava-8619-kashta-oblast-...,/obiava-8619-kashta-oblast-varna-gr-valchi-dol...,obiava-8619-kashta-oblast-varna-gr-valchi-dol-...,data\raw_listing_html\a9144301a51ccb84.html,new_building_project,"Къща в област Варна, гр. Вълчи дол :: imot.bg ...",None,None,None,...,Описание на имота:\n🏡 СОБСТВЕНИК продава напъл...,Описание на имота: 🏡 СОБСТВЕНИК продава напълн...,None,None,0,"Публикувана в 6:44 на 14 май, 2026 год.",746.0,False,NaN,None

In [5]:
parsed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164073 entries, 0 to 164072
Data columns (total 40 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              164073 non-null  object
 1   ad_url             164073 non-null  object
 2   ad_url_path        164073 non-null  object
 3   ad_url_slug        164073 non-null  object
 4   html_path          164073 non-null  object
 5   listing_type       164073 non-null  object
 6   title              164073 non-null  object
 7   deal_raw           163808 non-null  object
 8   property_type_raw  163808 non-null  object
 9   title_city_raw     163808 non-null  object
 10  title_geo_2_raw    163805 non-null  object
 11  title_area_sqm     160360 non-null  float64
 12  title_price_eur    160128 non-null  float64
 13  title_price_bgn    160128 non-null  float64
 14  seller_name_raw    152396 non-null  object
 15  title_ad_id        164062 non-null  float64
 16  total_price        163807 non-null  float64
 17  currency           163808 non-null  object
 18  price_raw          163808 non-null  object
 19  vat_status         164073 non-null  object
 20  area_sqm           162755 non-null  float64
 21  area_raw           162755 non-null  object
 22  price_per_sqm      162596 non-null  float64
 23  floor              99033 non-null   float64
 24  total_floors       91825 non-null   float64
 25  floor_raw          99033 non-null   object
 26  construction_raw   164073 non-null  object
 27  construction_type  123351 non-null  object
 28  construction_year  164073 non-null  int64
 29  location_raw       164062 non-null  object
 30  description_raw    162528 non-null  object
 31  description_clean  162528 non-null  object
 32  features_raw       142956 non-null  object
 33  features_pipe      142956 non-null  object
 34  features_count     164073 non-null  int64
 35  published_raw      43334 non-null   object
 36  views              164062 non-null  float64
 37  training_eligible  164073 non-null  bool
 38  parse_error        0 non-null       float64
 39  parsed_at          1509 non-null    object
dtypes: bool(1), float64(11), int64(2), object(26)
memory usage: 49.0+ MB

In [6]:
audit_summary = pd.DataFrame({
    "column": parsed_df.columns,
    "dtype": parsed_df.dtypes.astype(str).values,
    "non_null": parsed_df.notna().sum().values,
    "missing": parsed_df.isna().sum().values,
    "missing_pct": (parsed_df.isna().mean() * 100).round(2).values,
    "n_unique": parsed_df.nunique(dropna=True).values,
})

audit_summary.sort_values("missing_pct", ascending=False)
audit_summary

               column    dtype  non_null  missing  missing_pct  n_unique
0               ad_id   object    164073        0         0.00    164070
1              ad_url   object    164073        0         0.00    164073
2         ad_url_path   object    164073        0         0.00    164073
3         ad_url_slug   object    164073        0         0.00    164073
4           html_path   object    164073        0         0.00    164073
5        listing_type   object    164073        0         0.00         3
6               title   object    164073        0         0.00    164065
7            deal_raw   object    163808      265         0.16         1
8   property_type_raw   object    163808      265         0.16        44
9      title_city_raw   object    163808      265         0.16        55
10    title_geo_2_raw   object    163805      268         0.16      3680
11     title_area_sqm  float64    160360     3713         2.26      8256
12    title_price_eur  float64    160128     3945         2.40     25998
13    title_price_bgn  float64    160128     3945         2.40     25999
14    seller_name_raw   object    152396    11677         7.12      3688
15        title_ad_id  float64    164062       11         0.01    151275
16        total_price  float64    163807      266         0.16     26038
17           currency   object    163808      265         0.16         2
18          price_raw   object    163808      265         0.16     26079
19         vat_status   object    164073        0         0.00         4
20           area_sqm  float64    162755     1318         0.80      8518
21           area_raw   object    162755     1318         0.80      9514
22      price_per_sqm  float64    162596     1477         0.90     56487
23              floor  float64     99033    65040        39.64        26
24       total_floors  float64     91825    72248        44.03        30
25          floor_raw   object     99033    65040        39.64       367
26   construction_raw   object    164073        0         0.00       371
27  construction_type   object    123351    40722        24.82         9
28  construction_year    int64    164073        0         0.00        97
29       location_raw   object    164062       11         0.01     17117
30    description_raw   object    162528     1545         0.94    157220
31  description_clean   object    162528     1545         0.94    157196
32       features_raw   object    142956    21117        12.87      6409
33      features_pipe   object    142956    21117        12.87      6409
34     features_count    int64    164073        0         0.00        27
35      published_raw   object     43334   120739        73.59     30932
36              views  float64    164062       11         0.01      9876
37  training_eligible     bool    164073        0         0.00         2
38        parse_error  float64         0   164073       100.00         0
39          parsed_at   object      1509   162564        99.08      1509

In [7]:
parsed_df.listing_type.value_counts()

listing_type
single_property_listing    161683
unknown                      1533
new_building_project          857
Name: count, dtype: int64

In [8]:
parsed_df.deal_raw.value_counts()

deal_raw
Продава    163808
Name: count, dtype: int64

In [9]:
# ------------------------------------------------------------
# STEP 2 — Row-level validity checks
# ------------------------------------------------------------
print("Rows:", len(parsed_df))
print("Columns:", len(parsed_df.columns))

# 1. Listing type distribution
print("\nlisting_type distribution:")
display(
    parsed_df["listing_type"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 2. Training eligibility distribution
print("\ntraining_eligible distribution:")
display(
    parsed_df["training_eligible"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 3. Deal type distribution
print("\ndeal_raw distribution:")
display(
    parsed_df["deal_raw"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 4. Currency distribution
print("\ncurrency distribution:")
display(
    parsed_df["currency"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 5. VAT status distribution
print("\nvat_status distribution:")
display(
    parsed_df["vat_status"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(parsed_df) * 100).round(2))
)

# 6. Duplicate checks
duplicate_summary = {
    "duplicate_ad_url_rows": parsed_df.duplicated("ad_url").sum(),
    "duplicate_ad_id_rows": parsed_df.duplicated("ad_id").sum(),
    "duplicate_title_rows": parsed_df.duplicated("title").sum(),
    "duplicate_html_path_rows": parsed_df.duplicated("html_path").sum(),
}

print("\nDuplicate summary:")
display(pd.DataFrame([duplicate_summary]))

# 7. Inspect duplicated ad_id rows
dup_ad_ids = parsed_df.loc[parsed_df.duplicated("ad_id", keep=False), [
    "ad_id",
    "ad_url",
    "title",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "location_raw",
]]

print("\nDuplicated ad_id rows:")
display(dup_ad_ids.sort_values("ad_id"))

# 8. Core ML validity flags
validity = pd.DataFrame({
    "has_deal": parsed_df["deal_raw"].notna(),
    "has_property_type": parsed_df["property_type_raw"].notna(),
    "has_city": parsed_df["title_city_raw"].notna(),
    "has_area": parsed_df["area_sqm"].notna(),
    "has_total_price": parsed_df["total_price"].notna(),
    "has_price_per_sqm": parsed_df["price_per_sqm"].notna(),
    "positive_area": parsed_df["area_sqm"].gt(0),
    "positive_total_price": parsed_df["total_price"].gt(0),
    "positive_price_per_sqm": parsed_df["price_per_sqm"].gt(0),
    "training_eligible": parsed_df["training_eligible"].eq(True),
})

validity_summary = (
    validity
    .sum()
    .to_frame("valid_count")
    .assign(
        invalid_count=lambda x: len(parsed_df) - x["valid_count"],
        valid_pct=lambda x: (x["valid_count"] / len(parsed_df) * 100).round(2)
    )
)

print("\nValidity summary:")
display(validity_summary)

# 9. First strict candidate rows for regression
df_candidate = parsed_df[
    parsed_df["training_eligible"].eq(True)
    & parsed_df["deal_raw"].notna()
    & parsed_df["property_type_raw"].notna()
    & parsed_df["title_city_raw"].notna()
    & parsed_df["area_sqm"].gt(0)
    & parsed_df["total_price"].gt(0)
    & parsed_df["price_per_sqm"].gt(0)
].copy()

print("\nFirst-pass ML candidate rows:", len(df_candidate))
print("Share of dataset:", round(len(df_candidate) / len(parsed_df) * 100, 2), "%")

# 10. Candidate property type distribution
print("\nCandidate property_type_raw distribution:")
display(
    df_candidate["property_type_raw"]
    .value_counts(dropna=False)
    .to_frame("count")
    .assign(pct=lambda x: (x["count"] / len(df_candidate) * 100).round(2))
    .head(50)
)

Rows: 164073
Columns: 40

listing_type distribution:

                          count    pct
listing_type
single_property_listing  161683  98.54
unknown                    1533   0.93
new_building_project        857   0.52

training_eligible distribution:

                    count   pct
training_eligible
True               160621  97.9
False                3452   2.1

deal_raw distribution:

           count    pct
deal_raw
Продава   163808  99.84
None         265   0.16

currency distribution:

           count    pct
currency
EUR       163799  99.83
None         265   0.16
BGN            9   0.01

vat_status distribution:

             count    pct
vat_status
no_vat       89192  54.36
with_vat     57918  35.30
without_vat  10114   6.16
unknown       6849   4.17

Duplicate summary:

,duplicate_ad_url_rows,duplicate_ad_id_rows,duplicate_title_rows,duplicate_html_path_rows
0,0,3,8,0

Duplicated ad_id rows:

,ad_id,ad_url,title,total_price,area_sqm,price_per_sqm,location_raw
110478,1j177874171211621,https://www.imot.bg/obiava-1j177874171211621-p...,"Продава КЪЩА в област Силистра, с. Старо село ...",21500.0,220.0,97.73,"област Силистра, с. Старо село"
110483,1j177874171211621,https://www.imot.bg/obiava-1j177874171211621-p...,"Продава КЪЩА в област Силистра, с. Старо село ...",21500.0,220.0,97.73,"област Силистра, с. Старо село"
157481,1r177805588600613,https://www.imot.bg/obiava-1r177805588600613-p...,"Продава ПАРЦЕЛ в град София, Подуяне - 887 кв....",1000.0,887.0,1.13,"град София, Подуяне, бул. Ботевградско шосе"
157482,1r177805588600613,https://www.imot.bg/obiava-1r177805588600613-p...,"Продава ПАРЦЕЛ в град София, Подуяне - 887 кв....",1000.0,887.0,1.13,"град София, Подуяне, бул. Ботевградско шосе"
163896,7788,https://www.imot.bg/obiava-7788-zhilishten-kom...,"Жилищен комплекс в област София, гр. Самоков :...",NaN,NaN,NaN,"област София, гр. Самоков"
163898,7788,https://www.imot.bg/obiava-7788-zhilishtna-sgr...,"Жилищен комплекс в област София, гр. Самоков :...",NaN,NaN,NaN,"област София, гр. Самоков"

Validity summary:

                        valid_count  invalid_count  valid_pct
has_deal                     163808            265      99.84
has_property_type            163808            265      99.84
has_city                     163808            265      99.84
has_area                     162755           1318      99.20
has_total_price              163807            266      99.84
has_price_per_sqm            162596           1477      99.10
positive_area                162703           1370      99.17
positive_total_price         163806            267      99.84
positive_price_per_sqm       162594           1479      99.10
training_eligible            160621           3452      97.90

First-pass ML candidate rows: 160569
Share of dataset: 97.86 %

Candidate property_type_raw distribution:

                             count    pct
property_type_raw
ПАРЦЕЛ                       35240  21.95
2-СТАЕН                      33693  20.98
3-СТАЕН                      33445  20.83
КЪЩА                         22190  13.82
1-СТАЕН                       6021   3.75
4-СТАЕН                       5258   3.27
МАГАЗИН                       3434   2.14
МНОГОСТАЕН                    3074   1.91
ОФИС                          2380   1.48
ЗЕМЕДЕЛСКА ЗЕМЯ               2235   1.39
ПРОМ. ПОМЕЩЕНИЕ               1978   1.23
ЕТАЖ ОТ КЪЩА                  1851   1.15
ГАРАЖ                         1505   0.94
МЕЗОНЕТ                       1382   0.86
ВИЛА                          1191   0.74
ЗАВЕДЕНИЕ                     1082   0.67
ХОТЕЛ                          992   0.62
СКЛАД                          767   0.48
ПАРКОМЯСТО                     759   0.47
САМОСТОЯТЕЛНА СГРАДА           461   0.29
ФАБРИКА/ЗАВОД                  249   0.16
ТЪРГОВСКИ КОМПЛЕКС             211   0.13
АТЕЛИЕ, ТАВАН                  188   0.12
ФЕРМА                          143   0.09
ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН     99   0.06
ВИЛНО СЕЛИЩЕ                    93   0.06
ФИТНЕС ЗАЛА                     78   0.05
АВТОСЕРВИЗ                      76   0.05
КЛИНИКА                         70   0.04
СОЛАРЕН ПАРК                    62   0.04
ЛЕКАРСКИ КАБИНЕТ                61   0.04
СПА/СОЛАРНО СТУДИО              43   0.03
БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ       42   0.03
ГАРАЖ, ПАРКОМЯСТО               39   0.02
ДЕТСКИ ЦЕНТЪР                   31   0.02
ДОМ ЗА ВЪЗРАСТНИ ХОРА           30   0.02
СТОМАТОЛОГИЧЕН КАБИНЕТ          27   0.02
БАНКОВ ОФИС                     24   0.01
АПТЕКА                          22   0.01
ПАРКИНГ                         18   0.01
АВТОМИВКА                       11   0.01
АКВАПАРК                         9   0.01
ХЛАДИЛЕН СКЛАД                   4   0.00
ФОТОГРАФСКО СТУДИО               1   0.00

In [10]:
df_ml_base = df_candidate.copy()

print("Rows in df_candidate:", len(df_candidate))
print("Rows in df_ml_base:", len(df_ml_base))

# ------------------------------------------------------------
# Step 2: Target and numeric variable audit
# Uses existing df_candidate from Step 1
# ------------------------------------------------------------



# ------------------------------------------------------------
# Overall numeric distribution
# ------------------------------------------------------------

numeric_cols = [
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title_price_eur",
    "title_area_sqm",
    "views",
    "floor",
    "total_floors",
    "construction_year",
    "features_count",
]

available_numeric_cols = [
    col for col in numeric_cols
    if col in df_ml_base.columns
]

overall_numeric_summary = (
    df_ml_base[available_numeric_cols]
    .describe(percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])
    .T
)

display(overall_numeric_summary)

# ------------------------------------------------------------
# Target distribution by property type
# ------------------------------------------------------------

target_by_property_type = (
    df_ml_base
    .groupby("property_type_raw")
    .agg(
        count=("ad_id", "count"),
        price_median=("total_price", "median"),
        price_p01=("total_price", lambda x: x.quantile(0.01)),
        price_p05=("total_price", lambda x: x.quantile(0.05)),
        price_p95=("total_price", lambda x: x.quantile(0.95)),
        price_p99=("total_price", lambda x: x.quantile(0.99)),
        area_median=("area_sqm", "median"),
        area_p01=("area_sqm", lambda x: x.quantile(0.01)),
        area_p99=("area_sqm", lambda x: x.quantile(0.99)),
        ppm_median=("price_per_sqm", "median"),
        ppm_p01=("price_per_sqm", lambda x: x.quantile(0.01)),
        ppm_p99=("price_per_sqm", lambda x: x.quantile(0.99)),
    )
    .sort_values("count", ascending=False)
)

display(target_by_property_type)

# ------------------------------------------------------------
# Target distribution by city
# ------------------------------------------------------------

target_by_city = (
    df_ml_base
    .groupby("title_city_raw")
    .agg(
        count=("ad_id", "count"),
        price_median=("total_price", "median"),
        price_p05=("total_price", lambda x: x.quantile(0.05)),
        price_p95=("total_price", lambda x: x.quantile(0.95)),
        area_median=("area_sqm", "median"),
        ppm_median=("price_per_sqm", "median"),
        ppm_p05=("price_per_sqm", lambda x: x.quantile(0.05)),
        ppm_p95=("price_per_sqm", lambda x: x.quantile(0.95)),
    )
    .sort_values("count", ascending=False)
)

display(target_by_city.head(30))

# ------------------------------------------------------------
# Suspicious low / high values
# ------------------------------------------------------------

review_cols = [
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]

suspicious_low_price = df_ml_base[
    df_ml_base["total_price"] <= df_ml_base["total_price"].quantile(0.001)
][review_cols]

suspicious_high_price = df_ml_base[
    df_ml_base["total_price"] >= df_ml_base["total_price"].quantile(0.999)
][review_cols]

suspicious_low_ppm = df_ml_base[
    df_ml_base["price_per_sqm"] <= df_ml_base["price_per_sqm"].quantile(0.001)
][review_cols]

suspicious_high_ppm = df_ml_base[
    df_ml_base["price_per_sqm"] >= df_ml_base["price_per_sqm"].quantile(0.999)
][review_cols]

print("Suspicious low price rows:", len(suspicious_low_price))
display(suspicious_low_price.head(20))

print("Suspicious high price rows:", len(suspicious_high_price))
display(suspicious_high_price.head(20))

print("Suspicious low price_per_sqm rows:", len(suspicious_low_ppm))
display(suspicious_low_ppm.head(20))

print("Suspicious high price_per_sqm rows:", len(suspicious_high_ppm))
display(suspicious_high_ppm.head(20))

Rows in df_candidate: 160569
Rows in df_ml_base: 160569

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
total_price,160569.0,253700.499129,2.068018e+06,31.00,8180.67,20451.68,75800.0,135000.00,240000.00,680000.00,2024228.320,4.711950e+08
area_sqm,160569.0,1487.231387,1.911446e+04,0.26,20.00,43.00,73.0,113.00,500.00,5612.00,20000.000,4.854710e+06
price_per_sqm,160569.0,1387.571661,4.952991e+03,0.01,3.73,15.00,287.0,1291.67,1983.08,3200.00,4700.272,1.140908e+06
title_price_eur,157117.0,250848.357525,2.078686e+06,500.00,8200.00,20499.80,75650.0,134900.00,240000.00,670000.00,2000000.000,4.711950e+08
title_area_sqm,158334.0,1437.864874,1.910530e+04,1.00,20.00,43.00,73.0,112.00,466.00,5436.35,19600.000,4.854710e+06
views,160569.0,1577.804134,2.448352e+03,1.00,15.00,47.00,330.0,953.00,1970.00,4951.60,10606.960,1.345020e+05
floor,97938.0,3.192397,2.556188e+00,0.00,0.00,0.00,1.0,3.00,4.00,8.00,12.000,2.500000e+01
total_floors,90820.0,6.098194,3.063337e+00,1.00,1.00,2.00,4.0,6.00,7.00,12.00,18.000,4.000000e+01
construction_year,160569.0,2017.740124,1.683958e+01,1950.00,1960.00,1980.00,2020.0,2026.00,2026.00,2027.00,2028.000,2.049000e+03
features_count,160569.0,2.656534,2.393012e+00,0.00,0.00,0.00,1.0,2.00,4.00,8.00,10.000,3.900000e+01

,count,price_median,price_p01,price_p05,price_p95,price_p99,area_median,area_p01,area_p99,ppm_median,ppm_p01,ppm_p99
property_type_raw,,,,,,,,,,,,
ПАРЦЕЛ,35240,80000.00,4900.0000,10737.1300,1016695.000,3009302.50,1879.0,276.3900,50000.00,45.000,1.5000,1000.0000
2-СТАЕН,33693,115000.00,48096.9152,64500.0000,239900.000,320553.44,68.0,41.0000,124.00,1686.670,739.9848,4416.6700
3-СТАЕН,33445,180000.00,66000.0000,89900.0000,412000.000,610000.00,103.0,60.0000,218.00,1774.770,690.1492,4944.4400
КЪЩА,22190,138048.81,9000.0000,17900.0000,730000.000,1600000.00,150.0,40.0000,1000.00,967.740,65.7290,4500.0000
1-СТАЕН,6021,66000.00,28500.0000,35820.0000,145000.000,193812.20,43.0,21.0000,86.00,1564.150,702.1520,4134.1120
4-СТАЕН,5258,279000.00,69295.4920,99800.0000,752000.000,1250000.00,141.0,79.0000,361.00,1951.285,598.8237,6135.1628
МАГАЗИН,3434,154820.00,14066.0000,32000.0000,850000.000,2242875.30,94.0,14.0000,1289.77,1700.000,147.6051,7500.0000
МНОГОСТАЕН,3074,290000.00,60989.1719,100000.0000,997700.000,1550000.00,157.0,81.7300,538.27,1800.000,475.9524,6147.7697
ОФИС,2380,200000.00,18000.0000,35000.0000,1330000.000,4047995.50,108.0,15.0000,2315.00,1804.760,139.8507,5548.8908
ЗЕМЕДЕЛСКА ЗЕМЯ,2235,50000.00,1333.8000,4500.0000,480989.700,6817422.66,1528.0,4.1394,41543.78,28.410,0.3868,43300.0000
ПРОМ. ПОМЕЩЕНИЕ,1978,300000.00,18000.0000,44000.0000,2800000.000,6461000.00,1080.0,55.7700,54070.61,322.315,9.3639,3050.4502
ЕТАЖ ОТ КЪЩА,1851,130379.43,25564.5900,46016.2700,347650.000,590000.00,105.0,44.0000,328.00,1198.340,244.6800,3800.8350
ГАРАЖ,1505,30000.00,8181.4432,13599.3840,79774.000,189800.00,21.0,12.0000,268.20,1304.350,256.2492,3750.0000
МЕЗОНЕТ,1382,276000.00,68544.7640,99000.0000,804499.200,1419000.00,156.0,50.0000,502.00,1765.010,594.0527,5264.5141
ВИЛА,1191,59000.00,7491.3730,12135.5050,1000000.000,2820000.00,75.0,15.0000,1100.00,929.410,41.5210,9549.2380
ЗАВЕДЕНИЕ,1082,225000.00,15254.9825,46045.4565,1200000.000,2031370.00,200.5,29.2400,2035.72,1184.700,90.3571,6000.0000
ХОТЕЛ,992,805000.00,39999.9100,176678.6880,3750610.000,7017910.00,1000.0,152.7300,20426.40,806.125,33.3195,4496.9870
СКЛАД,767,299000.00,7670.2000,25000.0000,4000000.000,7500000.00,650.0,8.0000,50997.70,571.430,11.4652,2112.5774
ПАРКОМЯСТО,759,23000.00,7200.0000,10000.0000,65200.000,160000.00,16.0,11.0000,330.00,1272.730,346.0596,3487.5758
САМОСТОЯТЕЛНА СГРАДА,461,430000.00,17700.0000,50050.0000,4000000.000,7122000.00,864.0,40.6000,9638.20,625.670,11.7600,4466.6640
ФАБРИКА/ЗАВОД,249,770000.00,31954.6928,131887.8220,4003000.000,7488000.00,3245.0,223.5600,76245.92,206.260,11.1316,2667.3572
ТЪРГОВСКИ КОМПЛЕКС,211,466000.00,15400.0000,50599.5000,5954000.000,10700000.00,740.0,41.0000,29250.00,619.830,20.6250,5057.6960
"АТЕЛИЕ, ТАВАН",188,86500.00,20392.9616,27315.0000,233305.700,298544.40,50.5,14.4800,195.17,1670.415,551.5920,4278.4911
ФЕРМА,143,240000.00,20881.1636,38100.0000,3726775.129,6785150.00,5215.0,133.1800,108000.00,49.770,3.9468,2362.1960
ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН,99,117597.13,23990.0000,40903.3500,585500.000,1480100.00,60.0,19.9800,412.30,1723.790,463.4138,5224.9896
ВИЛНО СЕЛИЩЕ,93,428276.00,34200.0000,71666.4000,2320000.000,6021400.00,2000.0,87.5200,72160.00,235.510,7.1164,3541.2396
ФИТНЕС ЗАЛА,78,234750.00,29907.0000,41274.1500,1250000.000,2590000.00,242.5,79.5400,1633.64,924.090,104.4664,4802.0730
АВТОСЕРВИЗ,76,276500.00,35892.6900,48400.0000,1300000.000,2050000.00,377.5,52.0000,47512.75,707.540,12.8225,5081.9275
КЛИНИКА,70,612892.50,65000.0000,108000.0000,2036500.000,3485560.00,382.5,63.8000,4951.25,1944.445,50.6155,8250.0033
СОЛАРЕН ПАРК,62,134000.00,25454.9614,29000.0000,1580000.000,6256825.00,3195.0,123.8000,110476.88,43.920,6.6822,666.1753
ЛЕКАРСКИ КАБИНЕТ,61,180000.00,25600.0000,40903.3500,950000.000,1379000.00,90.0,24.6000,862.00,1702.700,474.1460,4664.4440
СПА/СОЛАРНО СТУДИО,43,278868.00,33520.0000,46283.7000,1485800.100,1895800.00,365.0,45.8800,18027.48,945.120,51.6994,2883.3118
БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ,42,275000.00,19858.5000,35250.0000,1190250.000,4913590.00,1835.0,138.7000,7447.09,198.150,8.0120,2969.1819
"ГАРАЖ, ПАРКОМЯСТО",39,16361.34,8763.5444,11095.0330,114950.000,213640.00,20.0,11.3800,2626.00,809.520,105.7268,2045.1784
ДЕТСКИ ЦЕНТЪР,31,255000.00,17470.0000,48450.0000,3635000.000,5200000.00,285.0,56.5000,3580.00,1642.250,22.6760,3020.6090
ДОМ ЗА ВЪЗРАСТНИ ХОРА,30,602500.00,93050.0000,140750.0000,2050500.000,3236000.00,1675.0,290.5800,9773.25,317.290,36.2931,2880.0009
СТОМАТОЛОГИЧЕН КАБИНЕТ,27,208185.00,68874.0000,81997.0000,950000.000,2171000.00,130.0,25.1200,1701.00,1833.330,422.3460,9430.4646
БАНКОВ ОФИС,24,510000.00,70393.5922,108247.6315,2745500.000,2780000.00,456.5,71.1500,1300.00,1784.195,104.6115,6773.5214
АПТЕКА,22,198995.00,69000.0000,69227.4000,408550.000,1863390.00,79.0,40.8400,301.81,2190.175,427.4044,30678.3075
ПАРКИНГ,18,390000.00,17821.9623,45109.8115,3462890.000,3732578.00,5076.0,434.0000,31142.98,123.975,8.2556,901.8339
АВТОМИВКА,11,290000.00,28000.0000,40000.0000,850000.000,890000.00,400.0,182.9000,3304.00,557.140,43.0030,1970.0000
АКВАПАРК,9,1900000.00,474000.0000,970000.0000,6832408.000,9463025.60,15000.0,3585.9200,15000.00,126.670,97.1564,2613.8900
ХЛАДИЛЕН СКЛАД,4,408126.00,224231.5000,241157.5000,542240.300,554528.06,715.5,280.8500,7985.74,510.030,78.8675,1277.4721
ФОТОГРАФСКО СТУДИО,1,148900.00,148900.0000,148900.0000,148900.000,148900.00,123.0,123.0000,123.00,1210.570,1210.5700,1210.5700

,count,price_median,price_p05,price_p95,area_median,ppm_median,ppm_p05,ppm_p95
title_city_raw,,,,,,,,
град София,34462,260000.000,79984.3000,1.200000e+06,116.0,2324.220,70.0000,4392.8600
област Бургас,17876,98000.000,28662.0000,4.800000e+05,88.0,1255.590,13.3550,2295.0750
град Варна,17607,156000.000,51300.0000,5.700000e+05,90.0,1800.900,83.3570,3250.0000
град Пловдив,17162,137403.500,66752.0000,4.743000e+05,93.0,1452.645,150.0840,2599.9995
област Пловдив,7794,99925.000,16500.0000,5.415730e+05,680.0,102.835,7.9630,1704.7985
област София,5025,112500.000,20000.0000,8.992000e+05,800.0,100.000,10.0000,2057.8620
град Бургас,4486,145604.000,30000.0000,5.000000e+05,97.0,1547.765,15.0000,2889.5500
област Велико Търново,3822,46500.000,7700.0000,3.695250e+05,161.5,236.985,5.1610,1261.0980
област Варна,3743,80000.000,15014.8000,5.200000e+05,610.0,110.000,6.5000,1695.8210
област Добрич,3444,80657.500,10903.0000,4.900000e+05,175.0,568.580,6.2500,1666.6700
град Стара Загора,3386,120000.000,28737.5000,3.737500e+05,100.0,1206.480,28.0000,2000.0000
град Русе,3118,110000.000,15338.7600,4.300000e+05,90.5,1239.405,20.1270,2200.5880
град Плевен,2761,119900.000,23000.0000,3.483480e+05,92.0,1300.000,26.7700,2342.0000
град Шумен,2760,115000.000,29652.1835,2.601500e+05,85.0,1440.000,30.9560,2154.0520
област Благоевград,2658,88429.000,24000.0000,5.413826e+05,119.0,914.760,16.5885,1876.4730
област Стара Загора,2053,61355.030,10000.0000,4.200000e+05,470.0,197.700,5.4160,1526.6740
град Велико Търново,2030,135000.000,27000.0000,4.643250e+05,100.5,1313.395,53.6140,2252.9865
област Пазарджик,1965,80000.000,16000.0000,5.770000e+05,374.0,352.380,10.0000,1562.5000
област Перник,1638,65152.000,15273.0000,4.330400e+05,436.0,220.245,10.0000,2002.4570
област Габрово,1620,45252.490,7795.0000,3.003388e+05,220.0,259.085,4.9500,1315.8295
област Ловеч,1619,40000.000,6045.0000,3.808900e+05,819.0,52.980,2.5800,1236.9420
град Кърджали,1274,92950.000,16361.3400,3.000000e+05,109.0,920.250,32.5790,1756.1880
град Перник,1259,119907.000,38680.0000,5.504000e+05,105.0,1199.220,34.8240,2135.6330
област Шумен,1124,40901.420,8500.0000,3.057589e+05,289.5,187.095,5.5690,1236.3120
Гърция,1075,275535.000,78500.0000,1.964700e+06,142.0,2357.140,40.2060,5722.9750
област Русе,1055,41000.000,7654.0410,3.290000e+05,205.0,225.000,6.3270,1434.4300
област Плевен,1026,39995.000,7000.0000,3.287500e+05,188.5,175.735,3.8075,1268.5900
град Враца,962,115270.335,20000.0000,5.095000e+05,100.0,1176.110,12.5710,2301.2160
област Кюстендил,883,68000.000,12320.0000,5.475000e+05,300.0,243.830,10.2620,1384.6390
област Хасково,853,61303.900,12900.0000,5.000000e+05,150.0,402.440,7.4920,1377.0660

Suspicious low price rows: 163

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
9459,1b173616280291614,https://www.imot.bg/obiava-1b173616280291614-p...,2-СТАЕН,град Монтана,"град Монтана, в.з. Запад, язовир ,, Огоста''",1400.00,85.0,16.47,"Продава 2-СТАЕН в град Монтана, в.з. Запад - 8..."
81038,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.00,1.0,950.00,"Продава МНОГОСТАЕН в град Кърджали, Център - 1..."
91609,1j171319088818131,https://www.imot.bg/obiava-1j171319088818131-p...,КЪЩА,област Добрич,"област Добрич, с. Краище",2300.81,70.0,32.87,"Продава КЪЩА в област Добрич, с. Краище - 70 к..."
101124,1j176510235621725,https://www.imot.bg/obiava-1j176510235621725-p...,КЪЩА,област Добрич,"област Добрич, гр. Балчик",1199.00,211.0,5.68,"Продава КЪЩА в област Добрич, гр. Балчик - 211..."
107479,1j177567892491721,https://www.imot.bg/obiava-1j177567892491721-p...,КЪЩА,област Ловеч,"област Ловеч, с. Черни Вит",1000.00,40.0,25.00,"Продава КЪЩА в област Ловеч, с. Черни Вит - 40..."
122811,1r119770677083487,https://www.imot.bg/obiava-1r119770677083487-p...,ПАРЦЕЛ,област Плевен,"област Плевен, с. Ореховица",2045.17,1060.0,1.93,"Продава ПАРЦЕЛ в област Плевен, с. Ореховица -..."
123104,1r129836973937027,https://www.imot.bg/obiava-1r129836973937027-p...,ПАРЦЕЛ,град София,"град София, Бъкстон",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м ..."
123105,1r129837036109746,https://www.imot.bg/obiava-1r129837036109746-p...,ПАРЦЕЛ,град София,"град София, Павлово",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м ..."
123106,1r129837027077889,https://www.imot.bg/obiava-1r129837027077889-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
123107,1r129837078094806,https://www.imot.bg/obiava-1r129837078094806-p...,ПАРЦЕЛ,град София,"град София, Борово",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
123138,1r129836999298495,https://www.imot.bg/obiava-1r129836999298495-p...,ПАРЦЕЛ,град София,"град София, Манастирски ливади",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Манастирски ливад..."
123141,1r129837016910336,https://www.imot.bg/obiava-1r129837016910336-p...,ПАРЦЕЛ,град София,"град София, Изток",2000.00,1.0,2000.00,"Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / ..."
123474,1r140187131835609,https://www.imot.bg/obiava-1r140187131835609-p...,ПАРЦЕЛ,град София,"град София, Редута",1000.00,400.0,2.50,"Продава ПАРЦЕЛ в град София, Редута - 400 кв.м..."
124091,1r151023473457367,https://www.imot.bg/obiava-1r151023473457367-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, с. Пчелище",2300.81,4420.0,0.52,"Продава ПАРЦЕЛ в област Велико Търново, с. Пче..."
124488,1r154462348986606,https://www.imot.bg/obiava-1r154462348986606-p...,ПАРЦЕЛ,град Велико Търново,"град Велико Търново, Промишлена зона - Запад",1234.00,3000.0,0.41,"Продава ПАРЦЕЛ в град Велико Търново, Промишле..."
124627,1r155661113661224,https://www.imot.bg/obiava-1r155661113661224-p...,ПАРЦЕЛ,област Силистра,"област Силистра, с. Каменци",2300.81,2600.0,0.88,"Продава ПАРЦЕЛ в област Силистра, с. Каменци -..."
124885,1r157469288353220,https://www.imot.bg/obiava-1r157469288353220-p...,ПАРЦЕЛ,град Ямбол,"град Ямбол, Изток",1700.00,58767.0,0.03,"Продава ПАРЦЕЛ в град Ямбол, Изток - 58767 кв...."
125506,1r160526162464092,https://www.imot.bg/obiava-1r160526162464092-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Бежаново",2200.00,618.0,3.56,"Продава ПАРЦЕЛ в област Ловеч, с. Бежаново - 6..."
126744,1r164614155136903,https://www.imot.bg/obiava-1r164614155136903-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1500.00,5000.0,0.30,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."
126745,1r164613796043510,https://www.imot.bg/obiava-1r164613796043510-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Тепава",2556.46,10005.0,0.26,"Продава ПАРЦЕЛ в област Ловеч, с. Тепава - 100..."

Suspicious high price rows: 165

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
84279,1g173470575981747,https://www.imot.bg/obiava-1g173470575981747-p...,ОФИС,град София,"град София, Гоце Делчев",15000000.0,9000.0,1666.67,"Продава ОФИС в град София, Гоце Делчев - 9000 ..."
84497,1g174699117198253,https://www.imot.bg/obiava-1g174699117198253-p...,ОФИС,град София,"град София, Център",16800000.0,6000.0,2800.00,"Продава ОФИС в град София, Център - 6000 кв.м ..."
84500,1g174699202740588,https://www.imot.bg/obiava-1g174699202740588-p...,ОФИС,град София,"град София, Център",16800000.0,6000.0,2800.00,"Продава ОФИС в град София, Център - 6000 кв.м ..."
84509,1g174776979932737,https://www.imot.bg/obiava-1g174776979932737-p...,ОФИС,град София,"град София, Център, бул. Витоша",8500000.0,3200.0,2656.25,"Продава ОФИС в град София, Център - 3200 кв.м ..."
85397,1g177133995357205,https://www.imot.bg/obiava-1g177133995357205-p...,ОФИС,град София,"град София, Център, бул. Тодор Александров",10500000.0,6500.0,1615.38,"Продава ОФИС в град София, Център - 6500 кв.м ..."
91380,1j171086779696897,https://www.imot.bg/obiava-1j171086779696897-p...,КЪЩА,град София,"град София, Бояна",8000000.0,1040.0,7692.31,"Продава КЪЩА в град София, Бояна - 1040 кв.м /..."
94778,1j174048031872635,https://www.imot.bg/obiava-1j174048031872635-p...,КЪЩА,град София,"град София, Манастирски ливади",7100000.0,4300.0,1651.16,"Продава КЪЩА в град София, Манастирски ливади ..."
97247,1j175630317787949,https://www.imot.bg/obiava-1j175630317787949-p...,КЪЩА,област Бургас,"област Бургас, с. Равда",10000000.0,1000.0,10000.00,"Продава КЪЩА в област Бургас, с. Равда - 1000 ..."
98684,1j176009601438654,https://www.imot.bg/obiava-1j176009601438654-p...,КЪЩА,град София,"град София, 7-ми 11-ти километър",7608000.0,1059.0,7184.14,"Продава КЪЩА в град София, 7-ми 11-ти километъ..."
102821,1j176941336469721,https://www.imot.bg/obiava-1j176941336469721-p...,КЪЩА,град София,"град София, м-т Камбаните",15500000.0,2000.0,7750.00,"Продава КЪЩА в град София, м-т Камбаните - 200..."
102884,1j176949856360345,https://www.imot.bg/obiava-1j176949856360345-p...,КЪЩА,град София,"град София, гр. Банкя",22995000.0,5199.0,4422.97,"Продава КЪЩА в град София, гр. Банкя - 5199 кв..."
111036,1k171984522416868,https://www.imot.bg/obiava-1k171984522416868-p...,ВИЛА,Гърция,"Гърция, Халкидики",17500000.0,1000.0,17500.00,"Продава ВИЛА в Гърция, Халкидики - 1000 кв.м /..."
111040,1k171984525859775,https://www.imot.bg/obiava-1k171984525859775-p...,ВИЛА,Гърция,"Гърция, Халкидики",12000000.0,1000.0,12000.00,"Продава ВИЛА в Гърция, Халкидики - 1000 кв.м /..."
111083,1k171990343933829,https://www.imot.bg/obiava-1k171990343933829-p...,ВИЛА,Гърция,"Гърция, Халкидики",12000000.0,1000.0,12000.00,"Продава ВИЛА в Гърция, Халкидики - 1000 кв.м /..."
112028,1l141050030858795,https://www.imot.bg/obiava-1l141050030858795-p...,МАГАЗИН,град Ловеч,"град Ловеч, Център",12500000.0,2500.0,5000.00,"Продава МАГАЗИН в град Ловеч, Център - 2500 кв..."
116686,1n168233966358888,https://www.imot.bg/obiava-1n168233966358888-p...,СКЛАД,област София,"област София, гр. Елин Пелин",8850000.0,8450.0,1047.34,"Продава СКЛАД в област София, гр. Елин Пелин -..."
116721,1n170480055370411,https://www.imot.bg/obiava-1n170480055370411-p...,СКЛАД,град София,"град София, Център, пл. Сточна гара",12000000.0,7373.0,1627.56,"Продава СКЛАД в град София, Център - 7373 кв.м..."
116887,1n173815085615503,https://www.imot.bg/obiava-1n173815085615503-p...,СКЛАД,град Русе,"град Русе, Промишлена зона - Запад",7500000.0,31200.0,240.38,"Продава СКЛАД в град Русе, Промишлена зона - З..."
116914,1n174297984628158,https://www.imot.bg/obiava-1n174297984628158-p...,СКЛАД,област София,"област София, с. Столник",22000000.0,65455.0,336.11,"Продава СКЛАД в област София, с. Столник - 654..."
117067,1n176107936962495,https://www.imot.bg/obiava-1n176107936962495-p...,СКЛАД,град Русе,"град Русе, Промишлена зона - Изток",7500000.0,31000.0,241.94,"Продава СКЛАД в град Русе, Промишлена зона - И..."

Suspicious low price_per_sqm rows: 162

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
118483,1o176373075998653,https://www.imot.bg/obiava-1o176373075998653-p...,ПАРКОМЯСТО,град Варна,"град Варна, Виница",16000.00,1000000.0,0.02,"Продава ПАРКОМЯСТО в град Варна, Виница - 1000..."
124091,1r151023473457367,https://www.imot.bg/obiava-1r151023473457367-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, с. Пчелище",2300.81,4420.0,0.52,"Продава ПАРЦЕЛ в област Велико Търново, с. Пче..."
124101,1r151066590726245,https://www.imot.bg/obiava-1r151066590726245-p...,ПАРЦЕЛ,област София,"област София, гр. Елин Пелин, м. Соленико",150000.00,1031000.0,0.15,"Продава ПАРЦЕЛ в област София, гр. Елин Пелин ..."
124113,1r151197862312006,https://www.imot.bg/obiava-1r151197862312006-p...,ПАРЦЕЛ,област Враца,"област Враца, гр. Бяла Слатина",35000.00,91000.0,0.38,"Продава ПАРЦЕЛ в област Враца, гр. Бяла Слатин..."
124120,1r151119773445530,https://www.imot.bg/obiava-1r151119773445530-p...,ПАРЦЕЛ,област София,"област София, с. Караполци, м. Копанината",59999.00,345732.0,0.17,"Продава ПАРЦЕЛ в област София, с. Караполци - ..."
124224,1r152276705539618,https://www.imot.bg/obiava-1r152276705539618-p...,ПАРЦЕЛ,град Ловеч,"град Ловеч, Промишлена зона, Баховско шосе",11000.00,30000.0,0.37,"Продава ПАРЦЕЛ в град Ловеч, Промишлена зона -..."
124430,1r153992249301189,https://www.imot.bg/obiava-1r153992249301189-p...,ПАРЦЕЛ,област Ямбол,"област Ямбол, с. Савино",8500.00,20850.0,0.41,"Продава ПАРЦЕЛ в област Ямбол, с. Савино - 208..."
124488,1r154462348986606,https://www.imot.bg/obiava-1r154462348986606-p...,ПАРЦЕЛ,град Велико Търново,"град Велико Търново, Промишлена зона - Запад",1234.00,3000.0,0.41,"Продава ПАРЦЕЛ в град Велико Търново, Промишле..."
124798,1r156829059149246,https://www.imot.bg/obiava-1r156829059149246-p...,ПАРЦЕЛ,област Добрич,"област Добрич, гр. Балчик, фиш-фиш",40900.00,94000.0,0.44,"Продава ПАРЦЕЛ в област Добрич, гр. Балчик - 9..."
124885,1r157469288353220,https://www.imot.bg/obiava-1r157469288353220-p...,ПАРЦЕЛ,град Ямбол,"град Ямбол, Изток",1700.00,58767.0,0.03,"Продава ПАРЦЕЛ в град Ямбол, Изток - 58767 кв...."
125508,1r160639737234969,https://www.imot.bg/obiava-1r160639737234969-p...,ПАРЦЕЛ,област Добрич,"област Добрич, гр. Каварна, С.Божурец",23000.00,68116.0,0.34,"Продава ПАРЦЕЛ в област Добрич, гр. Каварна - ..."
126067,1r162728761839736,https://www.imot.bg/obiava-1r162728761839736-p...,ПАРЦЕЛ,област Хасково,"област Хасково, гр. Любимец, Йерусалимово",15000.00,25000.0,0.60,"Продава ПАРЦЕЛ в област Хасково, гр. Любимец -..."
126663,1r164457233746463,https://www.imot.bg/obiava-1r164457233746463-p...,ПАРЦЕЛ,област Русе,"област Русе, с. Иваново, Стрелбище",6500.00,9500.0,0.68,"Продава ПАРЦЕЛ в област Русе, с. Иваново - 950..."
126672,1r164466204982974,https://www.imot.bg/obiava-1r164466204982974-p...,ПАРЦЕЛ,област Габрово,"област Габрово, гр. Дряново",17500.00,83935.0,0.21,"Продава ПАРЦЕЛ в област Габрово, гр. Дряново -..."
126744,1r164614155136903,https://www.imot.bg/obiava-1r164614155136903-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1500.00,5000.0,0.30,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."
126745,1r164613796043510,https://www.imot.bg/obiava-1r164613796043510-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Тепава",2556.46,10005.0,0.26,"Продава ПАРЦЕЛ в област Ловеч, с. Тепава - 100..."
126747,1r164614174065380,https://www.imot.bg/obiava-1r164614174065380-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Казачево",1600.00,5600.0,0.29,"Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5..."
126758,1r164614436553901,https://www.imot.bg/obiava-1r164614436553901-p...,ПАРЦЕЛ,област Ловеч,"област Ловеч, с. Кърпачево",1000.00,1500.0,0.67,"Продава ПАРЦЕЛ в област Ловеч, с. Кърпачево - ..."
126769,1r164614607487020,https://www.imot.bg/obiava-1r164614607487020-p...,ПАРЦЕЛ,област Плевен,"област Плевен, с. Николаево",3000.00,6000.0,0.50,"Продава ПАРЦЕЛ в област Плевен, с. Николаево -..."
126981,1r165022219714888,https://www.imot.bg/obiava-1r165022219714888-p...,ПАРЦЕЛ,област Враца,"област Враца, с. Габаре, Усоето",8500.00,18500.0,0.46,"Продава ПАРЦЕЛ в област Враца, с. Габаре - 185..."

Suspicious high price_per_sqm rows: 161

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.0,1.0,35000.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
4937,1a177675907072610,https://www.imot.bg/obiava-1a177675907072610-p...,1-СТАЕН,град Русе,"град Русе, Здравец, Олимпа",51900.0,2.0,25950.00,"Продава 1-СТАЕН в град Русе, Здравец - 2 кв.м ..."
7246,1b169623222441373,https://www.imot.bg/obiava-1b169623222441373-p...,2-СТАЕН,град София,"град София, Център, ул. Московска",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
30069,1b177384841782593,https://www.imot.bg/obiava-1b177384841782593-p...,2-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
30576,1b177426474262322,https://www.imot.bg/obiava-1b177426474262322-p...,2-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 2-СТАЕН в град София, Център - 80 кв.м..."
44911,1c173834640237899,https://www.imot.bg/obiava-1c173834640237899-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
45794,1c174196381828349,https://www.imot.bg/obiava-1c174196381828349-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",97000.0,1.0,97000.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
56467,1c176537220648919,https://www.imot.bg/obiava-1c176537220648919-p...,3-СТАЕН,град София,"град София, Център",1300000.0,120.0,10833.33,"Продава 3-СТАЕН в град София, Център - 120 кв...."
57381,1c176762421595765,https://www.imot.bg/obiava-1c176762421595765-p...,3-СТАЕН,град София,"град София, Център",990000.0,93.0,10645.16,"Продава 3-СТАЕН в град София, Център - 93 кв.м..."
60408,1c177029736377902,https://www.imot.bg/obiava-1c177029736377902-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
61306,1c177114417060072,https://www.imot.bg/obiava-1c177114417060072-p...,3-СТАЕН,град София,"град София, Докторски паметник",749000.0,80.0,9362.50,"Продава 3-СТАЕН в град София, Докторски паметн..."
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.0,1.0,100000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
64098,1c177332627033073,https://www.imot.bg/obiava-1c177332627033073-p...,3-СТАЕН,град София,"град София, Център, ул. Съборна",970000.0,95.0,10210.53,"Продава 3-СТАЕН в град София, Център - 95 кв.м..."
72653,1c177858126583960,https://www.imot.bg/obiava-1c177858126583960-p...,3-СТАЕН,град София,"град София, Център",750000.0,80.0,9375.00,"Продава 3-СТАЕН в град София, Център - 80 кв.м..."
77061,1d176959981300701,https://www.imot.bg/obiava-1d176959981300701-p...,4-СТАЕН,град София,"град София, Център",1900000.0,200.0,9500.00,"Продава 4-СТАЕН в град София, Център - 200 кв...."
77541,1d177244143665522,https://www.imot.bg/obiava-1d177244143665522-p...,4-СТАЕН,град София,"град София, Център",2460000.0,239.0,10292.89,"Продава 4-СТАЕН в град София, Център - 239 кв...."
81034,1e176876794712573,https://www.imot.bg/obiava-1e176876794712573-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Гледка",58450.0,1.0,58450.00,"Продава МНОГОСТАЕН в град Кърджали, Гледка - 1..."
81938,1e177722363417683,https://www.imot.bg/obiava-1e177722363417683-p...,МНОГОСТАЕН,Гърция,"Гърция, Солун",1900000.0,165.0,11515.15,"Продава МНОГОСТАЕН в Гърция, Солун - 165 кв.м ..."

In [11]:
MIN_AREA_BY_PROPERTY_TYPE = {
    "1-СТАЕН": 15,
    "2-СТАЕН": 25,
    "3-СТАЕН": 35,
    "4-СТАЕН": 45,
    "МНОГОСТАЕН": 50,
    "МЕЗОНЕТ": 40,
    "АТЕЛИЕ, ТАВАН": 10,
    "КЪЩА": 25,
    "ЕТАЖ ОТ КЪЩА": 25,
    "ВИЛА": 20,
    "ГАРАЖ": 8,
    "ПАРКОМЯСТО": 8,
    "МАГАЗИН": 5,
    "ОФИС": 5,
    "СКЛАД": 5,
    "ПАРЦЕЛ": 50,
    "ЗЕМЕДЕЛСКА ЗЕМЯ": 100,
}

df_ml_base["min_reasonable_area"] = (
    df_ml_base["property_type_raw"]
    .map(MIN_AREA_BY_PROPERTY_TYPE)
)

df_ml_base["suspicious_area_too_small"] = (
    df_ml_base["min_reasonable_area"].notna()
    & (df_ml_base["area_sqm"] < df_ml_base["min_reasonable_area"])
)

small_area_review = df_ml_base[
    df_ml_base["suspicious_area_too_small"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(["property_type_raw", "area_sqm"])

print("Suspicious too-small area rows:", len(small_area_review))
display(small_area_review.head(50))

Suspicious too-small area rows: 338

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.00,1.0,35000.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
4937,1a177675907072610,https://www.imot.bg/obiava-1a177675907072610-p...,1-СТАЕН,град Русе,"град Русе, Здравец, Олимпа",51900.00,2.0,25950.00,"Продава 1-СТАЕН в град Русе, Здравец - 2 кв.м ..."
914,1a174617120400088,https://www.imot.bg/obiava-1a174617120400088-p...,1-СТАЕН,град Варна,"град Варна, Център",39500.00,10.0,3950.00,"Продава 1-СТАЕН в град Варна, Център - 10 кв.м..."
937,1a174720940537891,https://www.imot.bg/obiava-1a174720940537891-p...,1-СТАЕН,град Варна,"град Варна, Гръцка махала, ФК",31490.00,10.0,3149.00,"Продава 1-СТАЕН в град Варна, Гръцка махала - ..."
5386,1a177762750182371,https://www.imot.bg/obiava-1a177762750182371-p...,1-СТАЕН,град Варна,"град Варна, Левски 2, ул.Емануил Манолов",34900.00,10.0,3490.00,"Продава 1-СТАЕН в град Варна, Левски 2 - 10 кв..."
5409,1a177762783253610,https://www.imot.bg/obiava-1a177762783253610-p...,1-СТАЕН,град Варна,"град Варна, Христо Ботев, ул.Тодор Влайков",29900.00,10.0,2990.00,"Продава 1-СТАЕН в град Варна, Христо Ботев - 1..."
5612,1a177822677766997,https://www.imot.bg/obiava-1a177822677766997-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар",23000.00,11.0,2090.91,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
2957,1a176952090948960,https://www.imot.bg/obiava-1a176952090948960-p...,1-СТАЕН,област Бургас,"област Бургас, к.к. Слънчев бряг",24000.00,12.0,2000.00,"Продава 1-СТАЕН в област Бургас, к.к. Слънчев ..."
5045,1a177685873409268,https://www.imot.bg/obiava-1a177685873409268-p...,1-СТАЕН,град Бургас,"град Бургас, Възраждане",30000.00,12.0,2500.00,"Продава 1-СТАЕН в град Бургас, Възраждане - 12..."
5384,1a177762644247321,https://www.imot.bg/obiava-1a177762644247321-p...,1-СТАЕН,град Варна,"град Варна, Колхозен пазар, ул.Стоенчо Хаджи И...",34900.00,12.0,2908.33,"Продава 1-СТАЕН в град Варна, Колхозен пазар -..."
4871,1a177667102639011,https://www.imot.bg/obiava-1a177667102639011-p...,1-СТАЕН,град София,"град София, Стрелбище",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Стрелбище - 13 к..."
4873,1a177667142731690,https://www.imot.bg/obiava-1a177667142731690-p...,1-СТАЕН,град София,"град София, Иван Вазов",82000.00,13.0,6307.69,"Продава 1-СТАЕН в град София, Иван Вазов - 13 ..."
11541,1b174712395287055,https://www.imot.bg/obiava-1b174712395287055-p...,2-СТАЕН,град Бургас,"град Бургас, Център",16500.00,14.0,1178.57,"Продава 2-СТАЕН в град Бургас, Център - 14 кв...."
29854,1b177381801540774,https://www.imot.bg/obiava-1b177381801540774-p...,2-СТАЕН,град Варна,"град Варна, Бриз, Паркмарт",87500.00,20.0,4375.00,"Продава 2-СТАЕН в град Варна, Бриз - 20 кв.м /..."
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",97000.00,1.0,97000.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.00,1.0,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.00,1.0,100000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
111497,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.00,1.0,310000.00,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
111994,1k177830949732411,https://www.imot.bg/obiava-1k177830949732411-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",27000.00,9.0,3000.00,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
111277,1k174238436132860,https://www.imot.bg/obiava-1k174238436132860-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",11248.42,10.0,1124.84,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
111300,1k174589655796135,https://www.imot.bg/obiava-1k174589655796135-p...,ВИЛА,град Русе,"град Русе, в.з. Кулата",14900.00,10.0,1490.00,"Продава ВИЛА в град Русе, в.з. Кулата - 10 кв...."
110941,1k170487729767222,https://www.imot.bg/obiava-1k170487729767222-p...,ВИЛА,област Габрово,"област Габрово, с. Борики",9700.00,12.0,808.33,"Продава ВИЛА в област Габрово, с. Борики - 12 ..."
111988,1k177874594569087,https://www.imot.bg/obiava-1k177874594569087-p...,ВИЛА,област Хасково,"област Хасково, с. Минерални бани",38000.00,12.0,3166.67,"Продава ВИЛА в област Хасково, с. Минерални ба..."
111694,1k176790178804201,https://www.imot.bg/obiava-1k176790178804201-p...,ВИЛА,град Шумен,"град Шумен, м-т Под Манастира",28000.00,13.0,2153.85,"Продава ВИЛА в град Шумен, м-т Под Манастира -..."
110796,1k159187372423967,https://www.imot.bg/obiava-1k159187372423967-p...,ВИЛА,град Добрич,"град Добрич, в.з. Лозята",9714.55,14.0,693.90,"Продава ВИЛА в град Добрич, в.з. Лозята - 14 к..."
111194,1k173381990962779,https://www.imot.bg/obiava-1k173381990962779-p...,ВИЛА,град Търговище,"град Търговище, Вилна зона, Чокя",15338.76,14.0,1095.63,"Продава ВИЛА в град Търговище, Вилна зона - 14..."
111656,1k176608838752786,https://www.imot.bg/obiava-1k176608838752786-p...,ВИЛА,град Добрич,"град Добрич, м-т Газибаба, алмалии",9200.00,14.0,657.14,"Продава ВИЛА в град Добрич, м-т Газибаба - 14 ..."
110878,1k166902483080379,https://www.imot.bg/obiava-1k166902483080379-p...,ВИЛА,град Русе,"град Русе, Долапите",5880.00,15.0,392.00,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
110953,1k170238482982981,https://www.imot.bg/obiava-1k170238482982981-p...,ВИЛА,град Русе,"град Русе, Долапите, 10-ти км",6391.15,15.0,426.08,"Продава ВИЛА в град Русе, Долапите - 15 кв.м /..."
110978,1k171153091465916,https://www.imot.bg/obiava-1k171153091465916-p...,ВИЛА,област Варна,"област Варна, с. Осеново",35000.00,15.0,2333.33,"Продава ВИЛА в област Варна, с. Осеново - 15 к..."
111204,1k173617831600509,https://www.imot.bg/obiava-1k173617831600509-p...,ВИЛА,град Плевен,"град Плевен, м-т Мъртва долина",5624.21,15.0,374.95,"Продава ВИЛА в град Плевен, м-т Мъртва долина ..."
111215,1k173771669891059,https://www.imot.bg/obiava-1k173771669891059-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",28990.25,15.0,1932.68,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
111258,1k174285800592432,https://www.imot.bg/obiava-1k174285800592432-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",22000.00,15.0,1466.67,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
111274,1k174360336907458,https://www.imot.bg/obiava-1k174360336907458-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",21500.00,15.0,1433.33,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
111327,1k174697906929015,https://www.imot.bg/obiava-1k174697906929015-p...,ВИЛА,област Бургас,"област Бургас, с. Росен",26000.00,15.0,1733.33,"Продава ВИЛА в област Бургас, с. Росен - 15 кв..."
111394,1k175206432515505,https://www.imot.bg/obiava-1k175206432515505-p...,ВИЛА,област Русе,"област Русе, с. Пиргово",32000.00,15.0,2133.33,"Продава ВИЛА в област Русе, с. Пиргово - 15 кв..."
111714,1k177089513661784,https://www.imot.bg/obiava-1k177089513661784-p...,ВИЛА,област Търговище,"област Търговище, с. Разбойна, Серсема",33233.00,15.0,2215.53,"Продава ВИЛА в област Търговище, с. Разбойна -..."
111771,1k177306035384054,https://www.imot.bg/obiava-1k177306035384054-p...,ВИЛА,област Габрово,"област Габрово, с. Чукилите",14000.00,15.0,933.33,"Продава ВИЛА в област Габрово, с. Чукилите - 1..."
110848,1k165349073718160,https://www.imot.bg/obiava-1k165349073718160-p...,ВИЛА,област София,"област София, с. Свидня",14000.00,16.0,875.00,"Продава ВИЛА в област София, с. Свидня - 16 кв..."
110899,1k168630218456890,https://www.imot.bg/obiava-1k168630218456890-p...,ВИЛА,град Русе,"град Русе, в.з. Касева Чешма",31000.00,16.0,1937.50,"Продава ВИЛА в град Русе, в.з. Касева Чешма - ..."
111170,1k173131358442876,https://www.imot.bg/obiava-1k173131358442876-p...,ВИЛА,град Русе,"град Русе, в.з. Липака",10225.84,16.0,639.12,"Продава ВИЛА в град Русе, в.з. Липака - 16 кв...."
111202,1k173131452046414,https://www.imot.bg/obiava-1k173131452046414-p...,ВИЛА,област Русе,"област Русе, с. Николово",10225.84,16.0,639.12,"Продава ВИЛА в област Русе, с. Николово - 16 к..."
111787,1k177304552236782,https://www.imot.bg/obiava-1k177304552236782-p...,ВИЛА,област Пазарджик,"област Пазарджик, м-т Цигов чарк",32000.00,16.0,2000.00,"Продава ВИЛА в област Пазарджик, м-т Цигов чар..."
111285,1k174471450262174,https://www.imot.bg/obiava-1k174471450262174-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Крушевски баир",12271.01,17.0,721.82,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
111876,1k177592015889825,https://www.imot.bg/obiava-1k177592015889825-p...,ВИЛА,град Враца,"град Враца, Студентски град, Врачански лозя",17000.00,17.0,1000.00,"Продава ВИЛА в град Враца, Студентски град - 1..."
110826,1k163422905045659,https://www.imot.bg/obiava-1k163422905045659-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",10225.84,18.0,568.10,"Продава ВИЛА в град Разград, Промишлена зона -..."
110880,1k166936354732929,https://www.imot.bg/obiava-1k166936354732929-p...,ВИЛА,област Габрово,"област Габрово, гр. Севлиево, Севлиевски лозя",10225.84,18.0,568.10,"Продава ВИЛА в област Габрово, гр. Севлиево - ..."
110936,1k169877165462335,https://www.imot.bg/obiava-1k169877165462335-p...,ВИЛА,област София,"област София, с. Владо Тричков, Ромча",18000.00,18.0,1000.00,"Продава ВИЛА в област София, с. Владо Тричков ..."
111529,1k175922288191828,https://www.imot.bg/obiava-1k175922288191828-p...,ВИЛА,град Разград,"град Разград, Промишлена зона - Запад",42437.23,18.0,2357.62,"Продава ВИЛА в град Разград, Промишлена зона -..."
111745,1k177194253564731,https://www.imot.bg/obiava-1k177194253564731-p...,ВИЛА,град Враца,"град Враца, Студентски град, м-ст Череша",9000.00,18.0,500.00,"Продава ВИЛА в град Враца, Студентски град - 1..."

In [12]:
# ------------------------------------------------------------
# Step 2B: Further filter the 338 suspicious area candidates
# using price_per_sqm
# ------------------------------------------------------------

# Replace this with the actual name of your 338-row dataframe if different
area_suspicious_df = small_area_review.copy()

print("Starting suspicious area candidates:", len(area_suspicious_df))


# ------------------------------------------------------------
# 1. Add a practical top price-per-sqm flag
# ------------------------------------------------------------

# These are review thresholds, not final ML rules.
# Keep them intentionally simple for now.

area_suspicious_df["very_high_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 10_000
)

area_suspicious_df["extreme_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 25_000
)

area_suspicious_df["absurd_price_per_sqm"] = (
    area_suspicious_df["price_per_sqm"] >= 50_000
)


# ------------------------------------------------------------
# 2. Add combined drop candidate logic
# ------------------------------------------------------------

area_suspicious_df["likely_bad_area_or_price"] = (
    (area_suspicious_df["area_sqm"] <= 2)
    | (
        (area_suspicious_df["area_sqm"] <= 10)
        & (area_suspicious_df["price_per_sqm"] >= 10_000)
    )
    | (area_suspicious_df["price_per_sqm"] >= 50_000)
)


# ------------------------------------------------------------
# 3. Inspect the strongest drop candidates first
# ------------------------------------------------------------

drop_review = area_suspicious_df[
    area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["price_per_sqm", "area_sqm"],
    ascending=[False, True]
)

print("Likely bad rows from the 338 candidates:", len(drop_review))
display(drop_review.head(100))


# ------------------------------------------------------------
# 4. Inspect borderline candidates separately
# ------------------------------------------------------------

borderline_review = area_suspicious_df[
    ~area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["area_sqm", "price_per_sqm"],
    ascending=[True, False]
)

print("Borderline rows still needing manual review:", len(borderline_review))
display(borderline_review.head(100))

Starting suspicious area candidates: 338
Likely bad rows from the 338 candidates: 55

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
161031,1s176771053368590,https://www.imot.bg/obiava-1s176771053368590-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, гр. Кюстендил, Въртешево",48000000.00,66.000,727272.73,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр..."
111497,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.00,1.000,310000.00,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
160182,1s174472213814965,https://www.imot.bg/obiava-1s174472213814965-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Баня",300000.00,1.000,300000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
160844,1s176287027588136,https://www.imot.bg/obiava-1s176287027588136-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костинброд, С. Безден",72000.00,0.260,276923.08,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.00,1.000,210000.00,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
159726,1s173082154774113,https://www.imot.bg/obiava-1s173082154774113-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Войводиново",140000.00,1.000,140000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. В..."
128912,1r168321569073352,https://www.imot.bg/obiava-1r168321569073352-p...,ПАРЦЕЛ,област Пловдив,"област Пловдив, гр. Карлово",120000.00,1.000,120000.00,"Продава ПАРЦЕЛ в област Пловдив, гр. Карлово -..."
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.00,1.000,100000.00,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
160192,1s174472241896851,https://www.imot.bg/obiava-1s174472241896851-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Резово",500000.00,5.139,97295.19,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ре..."
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",97000.00,1.000,97000.00,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
159708,1s172983627962992,https://www.imot.bg/obiava-1s172983627962992-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Банско, 'Овиначе'",521280.00,6.516,80000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
161547,1s177486195173601,https://www.imot.bg/obiava-1s177486195173601-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Сандански, Долна Граде...",1616000.00,24.327,66428.25,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
81034,1e176876794712573,https://www.imot.bg/obiava-1e176876794712573-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Гледка",58450.00,1.000,58450.00,"Продава МНОГОСТАЕН в град Кърджали, Гледка - 1..."
93241,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-p...,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",55000.00,1.000,55000.00,"Продава КЪЩА в област Пазарджик, гр. Септември..."
160464,1s175169149080295,https://www.imot.bg/obiava-1s175169149080295-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, гр. Лъки",5112918.81,94.000,54392.75,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, гр. ..."
159025,1s168018942420237,https://www.imot.bg/obiava-1s168018942420237-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Добрич,"област Добрич, с. Ваклино",195000.00,4.000,48750.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, с. Ва..."
160625,1s175750711879706,https://www.imot.bg/obiava-1s175750711879706-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Брестник",129500.00,2.699,47980.73,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
161278,1s177149004657663,https://www.imot.bg/obiava-1s177149004657663-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Трояново",95700.00,2.000,47850.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Тр..."
161910,1s177867171514004,https://www.imot.bg/obiava-1s177867171514004-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, с. Мусачево",270000.00,6.000,45000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Мус..."
160189,1s174472234785072,https://www.imot.bg/obiava-1s174472234785072-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Поморие",156280.00,3.907,40000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. П..."
132664,1r171576942411245,https://www.imot.bg/obiava-1r171576942411245-p...,ПАРЦЕЛ,област Благоевград,"област Благоевград, гр. Гоце Делчев, Местност ...",35500.00,1.000,35500.00,"Продава ПАРЦЕЛ в област Благоевград, гр. Гоце ..."
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.00,1.000,35000.00,"Продава 1-СТАЕН в град Велико Търново, Център ..."
160283,1s174703244961240,https://www.imot.bg/obiava-1s174703244961240-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костинброд",35000.00,1.000,35000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
150068,1r176876865288529,https://www.imot.bg/obiava-1r176876865288529-p...,ПАРЦЕЛ,област Кърджали,"област Кърджали, с. Глухар",28200.00,1.000,28200.00,"Продава ПАРЦЕЛ в област Кърджали, с. Глухар - ..."
4937,1a177675907072610,https://www.imot.bg/obiava-1a177675907072610-p...,1-СТАЕН,град Русе,"град Русе, Здравец, Олимпа",51900.00,2.000,25950.00,"Продава 1-СТАЕН в град Русе, Здравец - 2 кв.м ..."
158868,1s165779817079118,https://www.imot.bg/obiava-1s165779817079118-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Елин Пелин",131250.00,5.250,25000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ел..."
160400,1s175007382745819,https://www.imot.bg/obiava-1s175007382745819-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, с. Маринка",24500.00,1.000,24500.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ма..."
160187,1s174472219289049,https://www.imot.bg/obiava-1s174472219289049-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Жиленци",24000.00,1.000,24000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
160274,1s174677671762908,https://www.imot.bg/obiava-1s174677671762908-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, гр. Разлог",49500.00,2.302,21503.04,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
161690,1s177685190752057,https://www.imot.bg/obiava-1s177685190752057-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Перник,"област Перник, с. Стефаново",43000.00,2.000,21500.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Перник, с. Ст..."
160431,1s175074737372727,https://www.imot.bg/obiava-1s175074737372727-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Първенец",88200.00,4.410,20000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. П..."
161272,1s177151989937075,https://www.imot.bg/obiava-1s177151989937075-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Калековец",119000.00,6.000,19833.33,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. К..."
159871,1s173601633745814,https://www.imot.bg/obiava-1s173601633745814-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Ресилово",30000.00,1.900,15789.47,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
160796,1s176156957009387,https://www.imot.bg/obiava-1s176156957009387-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Несебър, к.к. Слънчев Бряг",117900.00,8.000,14737.50,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Н..."
160581,1s175620144557357,https://www.imot.bg/obiava-1s175620144557357-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Черноморец",95000.00,7.000,13571.43,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Ч..."
118935,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-p...,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градск...",12000.00,1.000,12000.00,"Продава ГАРАЖ в област Пазарджик, гр. Пещера -..."
158724,1s162142678282599,https://www.imot.bg/obiava-1s162142678282599-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, с. Николичевци",84363.00,7.500,11248.40,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с...."
160190,1s174472238104460,https://www.imot.bg/obiava-1s174472238104460-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костенец",37708.00,3.428,11000.00,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
160537,1s175439501862736,https://www.imot.bg/obiava-1s175439501862736-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Варна,"област Варна, гр. Игнатиево",9000.00,0.880,10227.27,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Варна, гр. Иг..."
160130,1s174443975664895,https://www.imot.bg/obiava-1s174443975664895-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Ловеч,"област Ловеч, с. Голяма Желязна",25462.34,2.497,10197.17,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Ловеч, с. Гол..."
154767,1r177502554613617,https://www.imot.bg/obiava-1r177502554613617-p...,ПАРЦЕЛ,област Бургас,"област Бургас, гр. Каблешково",13000.00,2.000,6500.00,"Продава ПАРЦЕЛ в област Бургас, гр. Каблешково..."
146598,1r176181905920944,https://www.imot.bg/obiava-1r176181905920944-p...,ПАРЦЕЛ,град София,"град София, Борово",5000.00,1.000,5000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
160066,1s174241970465675,https://www.imot.bg/obiava-1s174241970465675-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Варна,"област Варна, с. Припек",2300.81,0.580,3966.91,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Варна, с. При..."
136384,1r173210500743400,https://www.imot.bg/obiava-1r173210500743400-p...,ПАРЦЕЛ,град София,"град София, Лозенец",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м ..."
136400,1r173210674853219,https://www.imot.bg/obiava-1r173210674853219-p...,ПАРЦЕЛ,град София,"град София, Оборище",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м ..."
136403,1r173210689382131,https://www.imot.bg/obiava-1r173210689382131-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",3000.00,1.000,3000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
123104,1r129836973937027,https://www.imot.bg/obiava-1r129836973937027-p...,ПАРЦЕЛ,град София,"град София, Бъкстон",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м ..."
123105,1r129837036109746,https://www.imot.bg/obiava-1r129837036109746-p...,ПАРЦЕЛ,град София,"град София, Павлово",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м ..."
123106,1r129837027077889,https://www.imot.bg/obiava-1r129837027077889-p...,ПАРЦЕЛ,град София,"град София, Гео Милев",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв...."
123107,1r129837078094806,https://www.imot.bg/obiava-1r129837078094806-p...,ПАРЦЕЛ,град София,"град София, Борово",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Борово - 1 кв.м /..."
123138,1r129836999298495,https://www.imot.bg/obiava-1r129836999298495-p...,ПАРЦЕЛ,град София,"град София, Манастирски ливади",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Манастирски ливад..."
123141,1r129837016910336,https://www.imot.bg/obiava-1r129837016910336-p...,ПАРЦЕЛ,град София,"град София, Изток",2000.00,1.000,2000.00,"Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / ..."
138009,1r173831670876756,https://www.imot.bg/obiava-1r173831670876756-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Дебелец",1111.00,1.000,1111.00,"Продава ПАРЦЕЛ в област Велико Търново, гр. Де..."
81038,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.00,1.000,950.00,"Продава МНОГОСТАЕН в град Кърджали, Център - 1..."
158536,1s148066780877500,https://www.imot.bg/obiava-1s148066780877500-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Климент",1073.00,1.310,819.08,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. К..."

Borderline rows still needing manual review: 283

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
159291,1s170435725629856,https://www.imot.bg/obiava-1s170435725629856-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Велико Търново,"област Велико Търново, с. Самоводене",22000.00,2.595,8477.84,Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Велико Търнов...
117235,1n177322468553738,https://www.imot.bg/obiava-1n177322468553738-p...,СКЛАД,град София,"град София, Кръстова вада, Ул. Ген. Иван Колев",5000.00,3.000,1666.67,"Продава СКЛАД в град София, Кръстова вада - 3 ..."
116787,1n171187720586372,https://www.imot.bg/obiava-1n171187720586372-p...,СКЛАД,град София,"град София, Връбница 2, бул. Ломско шосе",2700.00,3.000,900.00,"Продава СКЛАД в град София, Връбница 2 - 3 кв...."
160102,1s174443985769114,https://www.imot.bg/obiava-1s174443985769114-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Ловеч,"област Ловеч, с. Голяма Желязна",30012.83,3.086,9725.48,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Ловеч, с. Гол..."
158777,1s162982497186752,https://www.imot.bg/obiava-1s162982497186752-p...,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Богдан",4218.16,3.303,1277.07,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Б..."
...,...,...,...,...,...,...,...,...,...
107252,1j177554821671263,https://www.imot.bg/obiava-1j177554821671263-p...,КЪЩА,област Варна,"област Варна, с. Доброглед",49900.00,20.000,2495.00,"Продава КЪЩА в област Варна, с. Доброглед - 20..."
107812,1j177625871240095,https://www.imot.bg/obiava-1j177625871240095-p...,КЪЩА,град Бургас,"град Бургас, гр. Българово, Лозницата",35000.00,20.000,1750.00,"Продава КЪЩА в град Бургас, гр. Българово - 20..."
145544,1r175992199900650,https://www.imot.bg/obiava-1r175992199900650-p...,ПАРЦЕЛ,област Велико Търново,"област Велико Търново, гр. Горна Оряховица",33000.00,20.000,1650.00,"Продава ПАРЦЕЛ в област Велико Търново, гр. Го..."
154775,1r177503028161354,https://www.imot.bg/obiava-1r177503028161354-p...,ПАРЦЕЛ,град Бургас,"град Бургас, Банево, с.о. Острицата-2",32000.00,20.000,1600.00,"Продава ПАРЦЕЛ в град Бургас, Банево - 20 кв.м..."
97859,1j175802706863343,https://www.imot.bg/obiava-1j175802706863343-p...,КЪЩА,област Кюстендил,"област Кюстендил, с. Горно Уйно",28000.00,20.000,1400.00,"Продава КЪЩА в област Кюстендил, с. Горно Уйно..."

In [13]:
# ------------------------------------------------------------
# Step 2D: Detect likely decare-parsed-as-sqm issue
# ------------------------------------------------------------

LAND_DECARE_LIKELY_TYPES = {
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

df_candidate = df_candidate.copy()

df_candidate["area_unit_suspected"] = None
df_candidate["area_sqm_corrected"] = df_candidate["area_sqm"]
df_candidate["price_per_sqm_corrected"] = df_candidate["price_per_sqm"]

likely_decare_mask = (
    df_candidate["property_type_raw"].isin(LAND_DECARE_LIKELY_TYPES)
    & df_candidate["area_sqm"].between(0.1, 100)
    & (df_candidate["price_per_sqm"] > 500)
)

df_candidate.loc[likely_decare_mask, "area_unit_suspected"] = "decare_parsed_as_sqm"

df_candidate.loc[likely_decare_mask, "area_sqm_corrected"] = (
    df_candidate.loc[likely_decare_mask, "area_sqm"] * 1000
)

df_candidate.loc[likely_decare_mask, "price_per_sqm_corrected"] = (
    df_candidate.loc[likely_decare_mask, "total_price"]
    / df_candidate.loc[likely_decare_mask, "area_sqm_corrected"]
)

print("Likely decare correction rows:", likely_decare_mask.sum())

display(
    df_candidate.loc[
        likely_decare_mask,
        [
            "ad_id",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "area_sqm_corrected",
            "price_per_sqm",
            "price_per_sqm_corrected",
            "title",
        ],
    ]
    .sort_values("price_per_sqm", ascending=False)
    .head(100)
)

Likely decare correction rows: 176

,ad_id,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,area_sqm_corrected,price_per_sqm,price_per_sqm_corrected,title
160926,1s176468771852693,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Първенец",78400000.0,100.00,100000.0,784000.00,784.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. П..."
161031,1s176771053368590,ЗЕМЕДЕЛСКА ЗЕМЯ,област Кюстендил,"област Кюстендил, гр. Кюстендил, Въртешево",48000000.0,66.00,66000.0,727272.73,727.272727,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр..."
160182,1s174472213814965,ЗЕМЕДЕЛСКА ЗЕМЯ,област Благоевград,"област Благоевград, с. Баня",300000.0,1.00,1000.0,300000.00,300.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, ..."
160844,1s176287027588136,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, гр. Костинброд, С. Безден",72000.0,0.26,260.0,276923.08,276.923077,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Ко..."
159726,1s173082154774113,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Войводиново",140000.0,1.00,1000.0,140000.00,140.000000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. В..."
...,...,...,...,...,...,...,...,...,...,...
161009,1s176616240629088,ЗЕМЕДЕЛСКА ЗЕМЯ,област Бургас,"област Бургас, гр. Каблешково",134000.0,61.00,61000.0,2196.72,2.196721,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. К..."
161187,1s177028180046425,ЗЕМЕДЕЛСКА ЗЕМЯ,област София,"област София, с. Клисура",108000.0,50.00,50000.0,2160.00,2.160000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Кли..."
161707,1s177695084461169,ЗЕМЕДЕЛСКА ЗЕМЯ,област Стара Загора,"област Стара Загора, с. Богомилово, местност У...",83000.0,39.00,39000.0,2128.21,2.128205,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора,..."
160447,1s175103495952700,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Костиево",200000.0,94.00,94000.0,2127.66,2.127660,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. К..."
161702,1s177694053564815,ЗЕМЕДЕЛСКА ЗЕМЯ,област Пловдив,"област Пловдив, с. Добралък",202500.0,100.00,100000.0,2025.00,2.025000,"Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Д..."

In [14]:
suspect_338 = small_area_review.copy()

# If your 338 dataframe has a different name, replace suspicious_candidates above.

suspect_338["suspect_group"] = "other_suspicious"

# 1. Agricultural land likely parsed in decares
suspect_338.loc[
    suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] < 200),
    "suspect_group"
] = "agricultural_land_likely_decares"

# 2. Very small residential/commercial areas
suspect_338.loc[
    ~suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] <= 20),
    "suspect_group"
] = "non_land_tiny_area"

# 3. High price per sqm but normal-ish area
suspect_338.loc[
    ~suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & (suspect_338["area_sqm"] > 20)
    & (suspect_338["price_per_sqm"] >= 9000),
    "suspect_group"
] = "non_land_high_price_per_sqm"

# 4. Agricultural land still expensive even after correction
if "price_per_sqm_corrected" in suspect_338.columns:
    suspect_338.loc[
        suspect_338["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
        & (suspect_338["price_per_sqm_corrected"] > 100),
        "suspect_group"
    ] = "agricultural_land_extreme_even_after_correction"


suspect_summary = (
    suspect_338["suspect_group"]
    .value_counts()
    .rename_axis("suspect_group")
    .reset_index(name="rows")
)

suspect_summary["pct_of_338"] = (
    suspect_summary["rows"] / len(suspect_338) * 100
).round(2)

display(suspect_summary)

                      suspect_group  rows  pct_of_338
0  agricultural_land_likely_decares   213       63.02
1                non_land_tiny_area   103       30.47
2                  other_suspicious    22        6.51

In [15]:
tiny_non_land = suspect_338[
    suspect_338["suspect_group"].eq("non_land_tiny_area")
].copy()

tiny_non_land_summary = (
    tiny_non_land
    .groupby("property_type_raw")
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        median_area=("area_sqm", "median"),
        max_area=("area_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
        median_price_per_sqm=("price_per_sqm", "median"),
    )
    .sort_values("rows", ascending=False)
    .reset_index()
)

display(tiny_non_land_summary)

,property_type_raw,rows,min_area,median_area,max_area,min_price,median_price,max_price,median_price_per_sqm
0,ВИЛА,36,1.0,15.0,19.0,5624.21,15669.38,310000.0,1047.815
1,КЪЩА,23,1.0,20.0,20.0,5700.00,35000.00,140000.0,1750.000
2,ПАРЦЕЛ,20,1.0,1.0,20.0,1111.00,4000.00,120000.0,2000.000
3,1-СТАЕН,12,1.0,10.5,13.0,23000.00,34900.00,82000.0,3319.500
4,3-СТАЕН,3,1.0,1.0,1.0,97000.00,100000.00,210000.0,100000.000
5,ГАРАЖ,3,1.0,5.0,7.0,10000.00,12000.00,22000.0,3142.860
6,2-СТАЕН,2,14.0,17.0,20.0,16500.00,52000.00,87500.0,2776.785
7,МНОГОСТАЕН,2,1.0,1.0,1.0,950.00,29700.00,58450.0,29700.000
8,СКЛАД,2,3.0,3.0,3.0,2700.00,3850.00,5000.0,1283.335

In [16]:
multiroom_tiny = df_candidate[
    df_candidate["property_type_raw"].eq("МНОГОСТАЕН")
    & df_candidate["area_sqm"].lt(20)
].copy()

cols_to_review = [
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "floor",
    "total_floors",
    "construction_type",
    "construction_year",
    "features_count",
    "views",
    "title",
    "description_clean",
]

multiroom_tiny[cols_to_review]

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,floor,total_floors,construction_type,construction_year,features_count,views,title,description_clean
81034,1e176876794712573,https://www.imot.bg/obiava-1e176876794712573-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Гледка",58450.0,1.0,58450.0,NaN,NaN,Тухла,2028,5,813.0,"Продава МНОГОСТАЕН в град Кърджали, Гледка - 1...",Реф. : 54 Имоти България предлага за продажба...
81038,1e176876835043438,https://www.imot.bg/obiava-1e176876835043438-p...,МНОГОСТАЕН,град Кърджали,"град Кърджали, Център",950.0,1.0,950.0,NaN,NaN,Тухла,2026,5,788.0,"Продава МНОГОСТАЕН в град Кърджали, Център - 1...",Реф. : 55 Имоти България предлага за продажба...

In [17]:
# Drop the 2 suspicious МНОГОСТАЕН rows with tiny area
before_rows = len(df_candidate)

drop_mask = (
    df_candidate["property_type_raw"].eq("МНОГОСТАЕН")
    & df_candidate["area_sqm"].lt(20)
)

dropped_multiroom_tiny = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

dropped_multiroom_tiny[
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_raw",
        "location_raw",
        "total_price",
        "area_sqm",
        "price_per_sqm",
        "title",
    ]
]

cleanup_actions = []

cleanup_actions.append({
    "rule": "drop_multiroom_tiny_area",
    "reason": "МНОГОСТАЕН listings below 20 sqm are structurally implausible for regression training",
    "rows_affected": len(dropped_multiroom_tiny),
})

Dropped rows: 2
Candidate rows before: 160569
Candidate rows after: 160567

In [18]:
types_to_check = [
    "1-СТАЕН",
    "3-СТАЕН",
    "КЪЩА",
    "ВИЛА",
    "ГАРАЖ",
]

manual_check_df = (
    small_area_review
    .loc[small_area_review["property_type_raw"].isin(types_to_check)
        & (small_area_review["area_sqm"] == 1)]
    .sort_values(
        ["property_type_raw", "area_sqm", "price_per_sqm"],
        ascending=[True, True, False],
    )
    .copy()
)

print("Rows to manually inspect:", len(manual_check_df))

manual_check_df[
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_raw",
        "location_raw",
        "total_price",
        "area_sqm",
        "price_per_sqm",
        "title",
    ]
]

with pd.option_context("display.max_colwidth", None):
    display(manual_check_df[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ])

Rows to manually inspect: 7

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-prodava-ednostaen-apartament-grad-veliko-tarnovo-tsentar,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.0,1.0,35000.0,"Продава 1-СТАЕН в град Велико Търново, Център - 1 кв.м / При запитване, СЕНТЧЪРИ ХОУМС :: imot.bg Обява 915894"
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-prodava-tristaen-apartament-oblast-kardzhali-gr-momchilgrad,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.0,"Продава 3-СТАЕН в област Кърджали, гр. Момчилград - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 045818"
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-prodava-tristaen-apartament-grad-kardzhali-tsentar,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.0,1.0,100000.0,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 848711"
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-prodava-tristaen-apartament-grad-dobrich-tsentar,3-СТАЕН,град Добрич,"град Добрич, Център",97000.0,1.0,97000.0,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м / При запитване, АДРЕС НЕДВИЖИМИ ИМОТИ - ДОБРИЧ :: imot.bg Обява 054878"
111497,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-prodava-vila-gartsiya-halkidiki,ВИЛА,Гърция,"Гърция, Халкидики",310000.0,1.0,310000.0,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 310 000 € » 606 307.30 лв., БРЕЙН ТРЪСТ :: imot.bg Обява 713961"
118935,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-prodava-garazh-parkomyasto-oblast-pazardzhik-gr-peshtera-tsentralna-gradska-chast,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градска част",12000.0,1.0,12000.0,"Продава ГАРАЖ в област Пазарджик, гр. Пещера - 1 кв.м / При запитване, ИМОТИ К1 :: imot.bg Обява 800843"
93241,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-prodava-kashta-oblast-pazardzhik-gr-septemvri-septemvri,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",55000.0,1.0,55000.0,"Продава КЪЩА в област Пазарджик, гр. Септември - 1 кв.м / При запитване :: imot.bg Обява 853529"

In [19]:
# Drop manually inspected 1 sqm suspicious rows
before_rows = len(df_candidate)

manual_drop_ad_ids = [
    "1a164924469915894",  # 1-СТАЕН, 1 sqm
    "1c177331151045818",  # 3-СТАЕН, 1 sqm
    "1c177331172848711",  # 3-СТАЕН, 1 sqm
    "1c175085717054878",  # 3-СТАЕН, 1 sqm
    "1k175862421713961",  # ВИЛА, 1 sqm
    "1o177179195800843",  # ГАРАЖ, 1 sqm
    "1j172909262853529",  # КЪЩА, 1 sqm
]

drop_mask = df_candidate["ad_id"].isin(manual_drop_ad_ids)

dropped_manual_1sqm = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_manual_1sqm[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_manual_1sqm_suspicious_rows",
    "reason": "Manually inspected 1 sqm listings with implausible area/price_per_sqm combinations; likely parsing or source-entry errors",
    "rows_affected": len(dropped_manual_1sqm),
})

Dropped rows: 7
Candidate rows before: 160567
Candidate rows after: 160560

,ad_id,ad_url,property_type_raw,title_city_raw,location_raw,total_price,area_sqm,price_per_sqm,title
76,1a164924469915894,https://www.imot.bg/obiava-1a164924469915894-p...,1-СТАЕН,град Велико Търново,"град Велико Търново, Център",35000.0,1.0,35000.0,"Продава 1-СТАЕН в град Велико Търново, Център ..."
48264,1c175085717054878,https://www.imot.bg/obiava-1c175085717054878-p...,3-СТАЕН,град Добрич,"град Добрич, Център",97000.0,1.0,97000.0,"Продава 3-СТАЕН в град Добрич, Център - 1 кв.м..."
64012,1c177331151045818,https://www.imot.bg/obiava-1c177331151045818-p...,3-СТАЕН,област Кърджали,"област Кърджали, гр. Момчилград",210000.0,1.0,210000.0,"Продава 3-СТАЕН в област Кърджали, гр. Момчилг..."
64014,1c177331172848711,https://www.imot.bg/obiava-1c177331172848711-p...,3-СТАЕН,град Кърджали,"град Кърджали, Център",100000.0,1.0,100000.0,"Продава 3-СТАЕН в град Кърджали, Център - 1 кв..."
93241,1j172909262853529,https://www.imot.bg/obiava-1j172909262853529-p...,КЪЩА,област Пазарджик,"област Пазарджик, гр. Септември, Септември",55000.0,1.0,55000.0,"Продава КЪЩА в област Пазарджик, гр. Септември..."
111497,1k175862421713961,https://www.imot.bg/obiava-1k175862421713961-p...,ВИЛА,Гърция,"Гърция, Халкидики",310000.0,1.0,310000.0,"Продава ВИЛА в Гърция, Халкидики - 1 кв.м / 31..."
118935,1o177179195800843,https://www.imot.bg/obiava-1o177179195800843-p...,ГАРАЖ,област Пазарджик,"област Пазарджик, гр. Пещера, централна градск...",12000.0,1.0,12000.0,"Продава ГАРАЖ в област Пазарджик, гр. Пещера -..."

In [20]:
# Show full URL/title text in notebook output
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)

parcel_tiny_area_inspect = (
    df_candidate.loc[
        df_candidate["property_type_raw"].eq("ПАРЦЕЛ")
        & df_candidate["area_sqm"].lt(20)
    ]
    .sort_values(["area_sqm", "price_per_sqm"], ascending=[True, False])
    .copy()
)

print("Rows to manually inspect:", len(parcel_tiny_area_inspect))

display(
    parcel_tiny_area_inspect[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

Rows to manually inspect: 18

                    ad_id                                                                                                             ad_url property_type_raw         title_city_raw                                          location_raw  total_price  area_sqm  price_per_sqm                                                                                                                          title
128912  1r168321569073352                             https://www.imot.bg/obiava-1r168321569073352-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0       1.0      120000.00            Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 1 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 073352
132664  1r171576942411245  https://www.imot.bg/obiava-1r171576942411245-prodava-partsel-oblast-blagoevgrad-gr-gotse-delchev-mestnost-mochura            ПАРЦЕЛ     област Благоевград  област Благоевград, гр. Гоце Делчев, Местност Мочура      35500.0       1.0       35500.00                     Продава ПАРЦЕЛ в област Благоевград, гр. Гоце Делчев - 1 кв.м / При запитване, БКС :: imot.bg Обява 411245
150068  1r176876865288529                             https://www.imot.bg/obiava-1r176876865288529-prodava-partsel-oblast-kardzhali-s-gluhar            ПАРЦЕЛ        област Кърджали                            област Кърджали, с. Глухар      28200.0       1.0       28200.00            Продава ПАРЦЕЛ в област Кърджали, с. Глухар - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 288529
146598  1r176181905920944                                    https://www.imot.bg/obiava-1r176181905920944-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       5000.0       1.0        5000.00            Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 5 000 € » 9 779.15 лв., БМБ КОНСТРАКШЪН ЕООД :: imot.bg Обява 920944
136384  1r173210500743400                                  https://www.imot.bg/obiava-1r173210500743400-prodava-partsel-grad-sofiya-lozenets            ПАРЦЕЛ             град София                                   град София, Лозенец       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 743400
136400  1r173210674853219                                 https://www.imot.bg/obiava-1r173210674853219-prodava-partsel-grad-sofiya-oborishte            ПАРЦЕЛ             град София                                   град София, Оборище       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 853219
136403  1r173210689382131                                 https://www.imot.bg/obiava-1r173210689382131-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       3000.0       1.0        3000.00       Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 382131
123104  1r129836973937027                                   https://www.imot.bg/obiava-1r129836973937027-prodava-partsel-grad-sofiya-bakston            ПАРЦЕЛ             град София                                   град София, Бъкстон       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 937027
123105  1r129837036109746                                   https://www.imot.bg/obiava-1r129837036109746-prodava-partsel-grad-sofiya-pavlovo            ПАРЦЕЛ             град София                                   град София, Павлово       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 109746
123106  1r129837027077889                                 https://www.imot.bg/obiava-1r129837027077889-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       2000.0       1.0        2000.00           Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 077889
123107  1r129837078094806                                    https://www.imot.bg/obiava-1r129837078094806-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       2000.0       1.0        2000.00              Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 094806
123138  1r129836999298495                        https://www.imot.bg/obiava-1r129836999298495-prodava-partsel-grad-sofiya-manastirski-livadi            ПАРЦЕЛ             град София                        град София, Манастирски ливади       2000.0       1.0        2000.00  Продава ПАРЦЕЛ в град София, Манастирски ливади - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 298495
123141  1r129837016910336                                     https://www.imot.bg/obiava-1r129837016910336-prodava-partsel-grad-sofiya-iztok            ПАРЦЕЛ             град София                                     град София, Изток       2000.0       1.0        2000.00               Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 910336
138009  1r173831670876756                     https://www.imot.bg/obiava-1r173831670876756-prodava-partsel-oblast-veliko-tarnovo-gr-debelets            ПАРЦЕЛ  област Велико Търново                    област Велико Търново, гр. Дебелец       1111.0       1.0        1111.00    Продава ПАРЦЕЛ в област Велико Търново, гр. Дебелец - 1 кв.м / При запитване, АДРЕС НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 876756
154767  1r177502554613617                          https://www.imot.bg/obiava-1r177502554613617-prodava-partsel-oblast-burgas-gr-kableshkovo            ПАРЦЕЛ          област Бургас                         област Бургас, гр. Каблешково      13000.0       2.0        6500.00            Продава ПАРЦЕЛ в област Бургас, гр. Каблешково - 2 кв.м / При запитване, ЕКС НВД БУРГАС ООД :: imot.bg Обява 613617
138040  1r173850696242512          https://www.imot.bg/obiava-1r173850696242512-prodava-partsel-oblast-varna-s-zdravets-m-st-kurdzhieva-niva            ПАРЦЕЛ           област Варна         област Варна, с. Здравец, М-ст Курджиева нива      13000.0      10.0        1300.00         Продава ПАРЦЕЛ в област Варна, с. Здравец - 10 кв.м / 13 000 € » 25 425.79 лв., ДИМИТРОВ ИМОТИ :: imot.bg Обява 242512
134097  1r172269115424343                             https://www.imot.bg/obiava-1r172269115424343-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0      11.0       10909.09           Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 11 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 424343
153188  1r177330658387954                                   https://www.imot.bg/obiava-1r177330658387954-prodava-partsel-grad-ruse-druzhba-3            ПАРЦЕЛ              град Русе                                   град Русе, Дружба 3      17000.0      19.0         894.74              Продава ПАРЦЕЛ в град Русе, Дружба 3 - 19 кв.м / 17 000 € » 33 249.11 лв., ДУНАВСКИ ИМОТИ :: imot.bg Обява 387954

In [21]:
# Drop suspicious/fake ПАРЦЕЛ rows with tiny area
before_rows = len(df_candidate)

drop_mask = (
    df_candidate["property_type_raw"].eq("ПАРЦЕЛ")
    & df_candidate["area_sqm"].lt(20)
)

dropped_parcel_tiny_fake = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_parcel_tiny_fake[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_parcel_tiny_fake_ads",
    "reason": "ПАРЦЕЛ listings below 20 sqm appear to be fake/placeholder ads and are not valid regression training observations",
    "rows_affected": len(dropped_parcel_tiny_fake),
})

Dropped rows: 18
Candidate rows before: 160560
Candidate rows after: 160542

                    ad_id                                                                                                             ad_url property_type_raw         title_city_raw                                          location_raw  total_price  area_sqm  price_per_sqm                                                                                                                          title
123104  1r129836973937027                                   https://www.imot.bg/obiava-1r129836973937027-prodava-partsel-grad-sofiya-bakston            ПАРЦЕЛ             град София                                   град София, Бъкстон       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Бъкстон - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 937027
123105  1r129837036109746                                   https://www.imot.bg/obiava-1r129837036109746-prodava-partsel-grad-sofiya-pavlovo            ПАРЦЕЛ             град София                                   град София, Павлово       2000.0       1.0        2000.00             Продава ПАРЦЕЛ в град София, Павлово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 109746
123106  1r129837027077889                                 https://www.imot.bg/obiava-1r129837027077889-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       2000.0       1.0        2000.00           Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 077889
123107  1r129837078094806                                    https://www.imot.bg/obiava-1r129837078094806-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       2000.0       1.0        2000.00              Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 094806
123138  1r129836999298495                        https://www.imot.bg/obiava-1r129836999298495-prodava-partsel-grad-sofiya-manastirski-livadi            ПАРЦЕЛ             град София                        град София, Манастирски ливади       2000.0       1.0        2000.00  Продава ПАРЦЕЛ в град София, Манастирски ливади - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 298495
123141  1r129837016910336                                     https://www.imot.bg/obiava-1r129837016910336-prodava-partsel-grad-sofiya-iztok            ПАРЦЕЛ             град София                                     град София, Изток       2000.0       1.0        2000.00               Продава ПАРЦЕЛ в град София, Изток - 1 кв.м / 2 000 € » 3 911.66 лв., ПЛАНЕКС ИНЖЕНЕРИНГ :: imot.bg Обява 910336
128912  1r168321569073352                             https://www.imot.bg/obiava-1r168321569073352-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0       1.0      120000.00            Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 1 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 073352
132664  1r171576942411245  https://www.imot.bg/obiava-1r171576942411245-prodava-partsel-oblast-blagoevgrad-gr-gotse-delchev-mestnost-mochura            ПАРЦЕЛ     област Благоевград  област Благоевград, гр. Гоце Делчев, Местност Мочура      35500.0       1.0       35500.00                     Продава ПАРЦЕЛ в област Благоевград, гр. Гоце Делчев - 1 кв.м / При запитване, БКС :: imot.bg Обява 411245
134097  1r172269115424343                             https://www.imot.bg/obiava-1r172269115424343-prodava-partsel-oblast-plovdiv-gr-karlovo            ПАРЦЕЛ         област Пловдив                           област Пловдив, гр. Карлово     120000.0      11.0       10909.09           Продава ПАРЦЕЛ в област Пловдив, гр. Карлово - 11 кв.м / При запитване, НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 424343
136384  1r173210500743400                                  https://www.imot.bg/obiava-1r173210500743400-prodava-partsel-grad-sofiya-lozenets            ПАРЦЕЛ             град София                                   град София, Лозенец       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Лозенец - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 743400
136400  1r173210674853219                                 https://www.imot.bg/obiava-1r173210674853219-prodava-partsel-grad-sofiya-oborishte            ПАРЦЕЛ             град София                                   град София, Оборище       3000.0       1.0        3000.00         Продава ПАРЦЕЛ в град София, Оборище - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 853219
136403  1r173210689382131                                 https://www.imot.bg/obiava-1r173210689382131-prodava-partsel-grad-sofiya-geo-milev            ПАРЦЕЛ             град София                                 град София, Гео Милев       3000.0       1.0        3000.00       Продава ПАРЦЕЛ в град София, Гео Милев - 1 кв.м / 3 000 € » 5 867.49 лв., ИНФИНИТИ ПРОПЪРТИ EООД :: imot.bg Обява 382131
138009  1r173831670876756                     https://www.imot.bg/obiava-1r173831670876756-prodava-partsel-oblast-veliko-tarnovo-gr-debelets            ПАРЦЕЛ  област Велико Търново                    област Велико Търново, гр. Дебелец       1111.0       1.0        1111.00    Продава ПАРЦЕЛ в област Велико Търново, гр. Дебелец - 1 кв.м / При запитване, АДРЕС НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 876756
138040  1r173850696242512          https://www.imot.bg/obiava-1r173850696242512-prodava-partsel-oblast-varna-s-zdravets-m-st-kurdzhieva-niva            ПАРЦЕЛ           област Варна         област Варна, с. Здравец, М-ст Курджиева нива      13000.0      10.0        1300.00         Продава ПАРЦЕЛ в област Варна, с. Здравец - 10 кв.м / 13 000 € » 25 425.79 лв., ДИМИТРОВ ИМОТИ :: imot.bg Обява 242512
146598  1r176181905920944                                    https://www.imot.bg/obiava-1r176181905920944-prodava-partsel-grad-sofiya-borovo            ПАРЦЕЛ             град София                                    град София, Борово       5000.0       1.0        5000.00            Продава ПАРЦЕЛ в град София, Борово - 1 кв.м / 5 000 € » 9 779.15 лв., БМБ КОНСТРАКШЪН ЕООД :: imot.bg Обява 920944
150068  1r176876865288529                             https://www.imot.bg/obiava-1r176876865288529-prodava-partsel-oblast-kardzhali-s-gluhar            ПАРЦЕЛ        област Кърджали                            област Кърджали, с. Глухар      28200.0       1.0       28200.00            Продава ПАРЦЕЛ в област Кърджали, с. Глухар - 1 кв.м / При запитване, ИМОТИБЪЛГАРИЯКЪРДЖАЛИ :: imot.bg Обява 288529
153188  1r177330658387954                                   https://www.imot.bg/obiava-1r177330658387954-prodava-partsel-grad-ruse-druzhba-3            ПАРЦЕЛ              град Русе                                   град Русе, Дружба 3      17000.0      19.0         894.74              Продава ПАРЦЕЛ в град Русе, Дружба 3 - 19 кв.м / 17 000 € » 33 249.11 лв., ДУНАВСКИ ИМОТИ :: imot.bg Обява 387954
154767  1r177502554613617                          https://www.imot.bg/obiava-1r177502554613617-prodava-partsel-oblast-burgas-gr-kableshkovo            ПАРЦЕЛ          област Бургас                         област Бургас, гр. Каблешково      13000.0       2.0        6500.00            Продава ПАРЦЕЛ в област Бургас, гр. Каблешково - 2 кв.м / При запитване, ЕКС НВД БУРГАС ООД :: imot.bg Обява 613617

In [22]:
# Correct agricultural land area values that appear to be entered in decares
before_rows = len(df_candidate)

agri_mask = (
    df_candidate["property_type_raw"].eq("ЗЕМЕДЕЛСКА ЗЕМЯ")
    & df_candidate["area_sqm"].notna()
    & df_candidate["total_price"].notna()
    & df_candidate["area_sqm"].between(0.01, 500)  # likely decares, not sqm
)

corrected_agri_land_decares = df_candidate.loc[agri_mask].copy()

df_candidate.loc[agri_mask, "area_sqm_original"] = df_candidate.loc[agri_mask, "area_sqm"]
df_candidate.loc[agri_mask, "price_per_sqm_original"] = df_candidate.loc[agri_mask, "price_per_sqm"]

df_candidate.loc[agri_mask, "area_sqm"] = (
    df_candidate.loc[agri_mask, "area_sqm"] * 1000
)

df_candidate.loc[agri_mask, "price_per_sqm"] = (
    df_candidate.loc[agri_mask, "total_price"] / df_candidate.loc[agri_mask, "area_sqm"]
)

after_rows = len(df_candidate)

print("Corrected agricultural land rows:", len(corrected_agri_land_decares))
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    df_candidate.loc[
        agri_mask,
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm_original",
            "area_sqm",
            "price_per_sqm_original",
            "price_per_sqm",
            "title",
        ]
    ].sort_values("price_per_sqm", ascending=False).head(100)
)

cleanup_actions.append({
    "rule": "correct_agricultural_land_decares_to_sqm",
    "reason": "ЗЕМЕДЕЛСКА ЗЕМЯ listings with very small area values are likely expressed in decares; converted area to sqm and recalculated price_per_sqm",
    "rows_affected": len(corrected_agri_land_decares),
})

Corrected agricultural land rows: 561
Candidate rows before: 160542
Candidate rows after: 160542

                    ad_id                                                                                                            ad_url property_type_raw       title_city_raw                                   location_raw   total_price  area_sqm_original  area_sqm  price_per_sqm_original  price_per_sqm                                                                                                                                                   title
161321  1s177261153256353         https://www.imot.bg/obiava-1s177261153256353-prodava-zemedelska-zemya-oblast-blagoevgrad-s-novo-konomladi   ЗЕМЕДЕЛСКА ЗЕМЯ   област Благоевград          област Благоевград, с. Ново Кономлади  4.711950e+08              413.0  413000.0              1140907.99    1140.907990  Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Благоевград, с. Ново Кономлади - 31413 дка / 471 195 000 € » 921 577 316.85 лв., ИМОТИ ШОПОВА :: imot.bg Обява 256353
160926  1s176468771852693                  https://www.imot.bg/obiava-1s176468771852693-prodava-zemedelska-zemya-oblast-plovdiv-s-parvenets   ЗЕМЕДЕЛСКА ЗЕМЯ       област Пловдив                    област Пловдив, с. Първенец  7.840000e+07              100.0  100000.0               784000.00     784.000000                  Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Първенец - 15680 дка / 78 400 000 € » 153 337 072.00 лв., КРИСТАЛ :: imot.bg Обява 852693
161031  1s176771053368590  https://www.imot.bg/obiava-1s176771053368590-prodava-zemedelska-zemya-oblast-kyustendil-gr-kyustendil-varteshevo   ЗЕМЕДЕЛСКА ЗЕМЯ     област Кюстендил     област Кюстендил, гр. Кюстендил, Въртешево  4.800000e+07               66.0   66000.0               727272.73     727.272727                 Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, гр. Кюстендил - 6000 дка / 48 000 000 € » 93 879 840.00 лв., СЕТИВА :: imot.bg Обява 368590
159910  1s173709460066839                    https://www.imot.bg/obiava-1s173709460066839-prodava-zemedelska-zemya-oblast-dobrich-gr-shabla   ЗЕМЕДЕЛСКА ЗЕМЯ        област Добрич                       област Добрич, гр. Шабла  4.666050e+07              122.0  122000.0               382463.09     382.463091        Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Добрич, гр. Шабла - 23400 дка / 46 660 497.08 € » 91 260 000 лв., НЕДВИЖИМИ ИМОТИ ШАБЛА :: imot.bg Обява 066839
158734  1s162618938090814   https://www.imot.bg/obiava-1s162618938090814-prodava-zemedelska-zemya-oblast-plovdiv-s-drangovo-mestnost-izlata   ЗЕМЕДЕЛСКА ЗЕМЯ       област Пловдив  област Пловдив, с. Дрангово, Местност  Излъта  5.112919e+07              150.0  150000.0               340861.25     340.861254        Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Дрангово - 10000 дка / 51 129 188.12 € » 100 000 000 лв., КОСТАДИНОВ ИМОТИ  :: imot.bg Обява 090814
...                   ...                                                                                                               ...               ...                  ...                                            ...           ...                ...       ...                     ...            ...                                                                                                                                                     ...
159698  1s172924783379667                    https://www.imot.bg/obiava-1s172924783379667-prodava-zemedelska-zemya-oblast-burgas-s-stratsin   ЗЕМЕДЕЛСКА ЗЕМЯ        област Бургас                      област Бургас, с. Страцин  7.600000e+04               26.0   26000.0                 2923.08       2.923077                        Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Страцин - 38 дка / 76 000 € » 148 643.08 лв., ПЕТРАКИЕВИ ООД :: imot.bg Обява 379667
160801  1s176183294684950      https://www.imot.bg/obiava-1s176183294684950-prodava-zemedelska-zemya-oblast-sofiya-gr-elin-pelin-s-novi-han   ЗЕМЕДЕЛСКА ЗЕМЯ         област София       област София, гр. Елин Пелин, с.Нови Хан  2.000000e+05               70.0   70000.0                 2857.14       2.857143                   Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, гр. Елин Пелин - 3.87 дка / 200 000 € » 391 166.00 лв., МАКС СЪЛУШЪНС :: imot.bg Обява 684950
160632  1s175777352640762  https://www.imot.bg/obiava-1s175777352640762-prodava-zemedelska-zemya-oblast-stara-zagora-gr-stara-zagora-gerena   ЗЕМЕДЕЛСКА ЗЕМЯ  област Стара Загора  област Стара Загора, гр. Стара Загора, Герена  5.000000e+05              179.0  179000.0                 2793.30       2.793296                            Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора, гр. Стара Загора - 5 дка / 500 000 € » 977 915.00 лв. :: imot.bg Обява 640762
161137  1s176943330656975                https://www.imot.bg/obiava-1s176943330656975-prodava-zemedelska-zemya-oblast-pazardzhik-s-apriltsi   ЗЕМЕДЕЛСКА ЗЕМЯ     област Пазарджик                   област Пазарджик, с. Априлци  4.353700e+05              158.0  158000.0                 2755.51       2.755506                     Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пазарджик, с. Априлци - 217.685 дка / 435 370 € » 851 509.71 лв., ХОУМЛЕНД :: imot.bg Обява 656975
160144  1s174472124611946                     https://www.imot.bg/obiava-1s174472124611946-prodava-zemedelska-zemya-oblast-burgas-s-tankovo   ЗЕМЕДЕЛСКА ЗЕМЯ        област Бургас                      област Бургас, с. Тънково  1.099900e+04                4.0    4000.0                 2749.75       2.749750                    Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Тънково - 4 дка / 10 999 € » 21 512.17 лв., БЪЛГЕРИАН ПРОПЕРТИС  :: imot.bg Обява 611946

[100 rows x 11 columns]

In [23]:
drop_review = area_suspicious_df[
    area_suspicious_df["likely_bad_area_or_price"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(
    ["price_per_sqm", "area_sqm"],
    ascending=[False, True]
)

drop_review.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 161031 to 158536
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ad_id              55 non-null     object
 1   ad_url             55 non-null     object
 2   property_type_raw  55 non-null     object
 3   title_city_raw     55 non-null     object
 4   location_raw       55 non-null     object
 5   total_price        55 non-null     float64
 6   area_sqm           55 non-null     float64
 7   price_per_sqm      55 non-null     float64
 8   title              55 non-null     object
dtypes: float64(3), object(6)
memory usage: 4.3+ KB

In [24]:
df_ml_base = df_candidate.copy()

print("Rows in df_candidate:", len(df_candidate))
print("Rows in df_ml_base:", len(df_ml_base))

df_ml_base["min_reasonable_area"] = (
    df_ml_base["property_type_raw"]
    .map(MIN_AREA_BY_PROPERTY_TYPE)
)

df_ml_base["suspicious_area_too_small"] = (
    df_ml_base["min_reasonable_area"].notna()
    & (df_ml_base["area_sqm"] < df_ml_base["min_reasonable_area"])
)

small_area_review = df_ml_base[
    df_ml_base["suspicious_area_too_small"]
][[
    "ad_id",
    "ad_url",
    "property_type_raw",
    "title_city_raw",
    "location_raw",
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "title",
]].sort_values(["property_type_raw", "area_sqm"])

print("Suspicious too-small area rows:", len(small_area_review))
display(small_area_review.head(50))

Rows in df_candidate: 160542
Rows in df_ml_base: 160542
Suspicious too-small area rows: 98

                    ad_id                                                                                                                         ad_url property_type_raw    title_city_raw                                         location_raw  total_price  area_sqm  price_per_sqm                                                                                                                                             title
4937    1a177675907072610                            https://www.imot.bg/obiava-1a177675907072610-prodava-ednostaen-apartament-grad-ruse-zdravets-olimpa           1-СТАЕН         град Русе                           град Русе, Здравец, Олимпа     51900.00       2.0       25950.00                        Продава 1-СТАЕН в град Русе, Здравец - 2 кв.м / При запитване, ВАЛЕНТИНА ПЕТРОВА - НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 072610
914     1a174617120400088                                   https://www.imot.bg/obiava-1a174617120400088-prodava-ednostaen-apartament-grad-varna-tsentar           1-СТАЕН        град Варна                                   град Варна, Център     39500.00      10.0        3950.00                                   Продава 1-СТАЕН в град Варна, Център - 10 кв.м / 39 500 € » 77 255.29 лв., ЕКС НВД  ООД :: imot.bg Обява 400088
937     1a174720940537891                         https://www.imot.bg/obiava-1a174720940537891-prodava-ednostaen-apartament-grad-varna-gratska-mahala-fk           1-СТАЕН        град Варна                        град Варна, Гръцка махала, ФК     31490.00      10.0        3149.00                   Продава 1-СТАЕН в град Варна, Гръцка махала - 10 кв.м / 31 490 € » 61 589.09 лв., ПАЛАД НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 537891
5386    1a177762750182371               https://www.imot.bg/obiava-1a177762750182371-prodava-ednostaen-apartament-grad-varna-levski-2-ul-emanuil-manolov           1-СТАЕН        град Варна             град Варна, Левски 2, ул.Емануил Манолов     34900.00      10.0        3490.00                                 Продава 1-СТАЕН в град Варна, Левски 2 - 10 кв.м / 34 900 € » 68 258.47 лв., РЕМАКС-ИДЕАЛ :: imot.bg Обява 182371
5409    1a177762783253610             https://www.imot.bg/obiava-1a177762783253610-prodava-ednostaen-apartament-grad-varna-hristo-botev-ul-todor-vlaykov           1-СТАЕН        град Варна           град Варна, Христо Ботев, ул.Тодор Влайков     29900.00      10.0        2990.00                             Продава 1-СТАЕН в град Варна, Христо Ботев - 10 кв.м / 29 900 € » 58 479.32 лв., РЕМАКС-ИДЕАЛ :: imot.bg Обява 253610
5612    1a177822677766997                            https://www.imot.bg/obiava-1a177822677766997-prodava-ednostaen-apartament-grad-varna-kolhozen-pazar           1-СТАЕН        град Варна                           град Варна, Колхозен пазар     23000.00      11.0        2090.91                               Продава 1-СТАЕН в град Варна, Колхозен пазар - 11 кв.м / 23 000 € » 44 984.09 лв., РУДИ КЕЙ :: imot.bg Обява 766997
2957    1a176952090948960                     https://www.imot.bg/obiava-1a176952090948960-prodava-ednostaen-apartament-oblast-burgas-k-k-slanchev-bryag           1-СТАЕН     област Бургас                     област Бургас, к.к. Слънчев бряг     24000.00      12.0        2000.00                    Продава 1-СТАЕН в област Бургас, к.к. Слънчев бряг - 12 кв.м / 24 000 € » 46 939.92 лв., МАКСИМА ИМОТИ :: imot.bg Обява 948960
5045    1a177685873409268                              https://www.imot.bg/obiava-1a177685873409268-prodava-ednostaen-apartament-grad-burgas-vazrazhdane           1-СТАЕН       град Бургас                              град Бургас, Възраждане     30000.00      12.0        2500.00                Продава 1-СТАЕН в град Бургас, Възраждане - 12 кв.м / 30 000 € » 58 674.90 лв., ТИТАН ПРОПЪРТИС РЕНТ-ИЗТОК :: imot.bg Обява 409268
5384    1a177762644247321  https://www.imot.bg/obiava-1a177762644247321-prodava-ednostaen-apartament-grad-varna-kolhozen-pazar-ul-stoencho-hadzhi-ivanov           1-СТАЕН        град Варна  град Варна, Колхозен пазар, ул.Стоенчо Хаджи Иванов     34900.00      12.0        2908.33                           Продава 1-СТАЕН в град Варна, Колхозен пазар - 12 кв.м / 34 900 € » 68 258.47 лв., РЕМАКС-ИДЕАЛ :: imot.bg Обява 247321
4871    1a177667102639011                              https://www.imot.bg/obiava-1a177667102639011-prodava-ednostaen-apartament-grad-sofiya-strelbishte           1-СТАЕН        град София                                град София, Стрелбище     82000.00      13.0        6307.69                              Продава 1-СТАЕН в град София, Стрелбище - 13 кв.м / 82 000 € » 160 378.06 лв., ЦИТАДЕЛА ГРУП :: imot.bg Обява 639011
4873    1a177667142731690                               https://www.imot.bg/obiava-1a177667142731690-prodava-ednostaen-apartament-grad-sofiya-ivan-vazov           1-СТАЕН        град София                               град София, Иван Вазов     82000.00      13.0        6307.69                             Продава 1-СТАЕН в град София, Иван Вазов - 13 кв.м / 82 000 € » 160 378.06 лв., ЦИТАДЕЛА ГРУП :: imot.bg Обява 731690
11541   1b174712395287055                                   https://www.imot.bg/obiava-1b174712395287055-prodava-dvustaen-apartament-grad-burgas-tsentar           2-СТАЕН       град Бургас                                  град Бургас, Център     16500.00      14.0        1178.57                                   Продава 2-СТАЕН в град Бургас, Център - 14 кв.м / 16 500 € » 32 271.20 лв., ЛЕВ ЕСТЕЙТС :: imot.bg Обява 287055
29854   1b177381801540774                              https://www.imot.bg/obiava-1b177381801540774-prodava-dvustaen-apartament-grad-varna-briz-parkmart           2-СТАЕН        град Варна                           град Варна, Бриз, Паркмарт     87500.00      20.0        4375.00                                        Продава 2-СТАЕН в град Варна, Бриз - 20 кв.м / 87 500 € » 171 135.13 лв., БУЛ ИМОТ :: imot.bg Обява 540774
111994  1k177830949732411                                         https://www.imot.bg/obiava-1k177830949732411-prodava-vila-grad-ruse-v-z-kaseva-cheshma              ВИЛА         град Русе                         град Русе, в.з. Касева Чешма     27000.00       9.0        3000.00                            Продава ВИЛА в град Русе, в.з. Касева Чешма - 9 кв.м / 27 000 € » 52 807.41 лв., АГЕНЦИЯ БРИКС :: imot.bg Обява 732411
111277  1k174238436132860                                        https://www.imot.bg/obiava-1k174238436132860-prodava-vila-grad-shumen-m-t-pod-manastira              ВИЛА        град Шумен                        град Шумен, м-т Под Манастира     11248.42      10.0        1124.84  Продава ВИЛА в град Шумен, м-т Под Манастира - 10 кв.м / 11 248.42 € » 22 000 лв., АДРЕС НЕДВИЖИМИ ИМОТИ - КАНТОРА ШУМЕН :: imot.bg Обява 132860
111300  1k174589655796135                                                 https://www.imot.bg/obiava-1k174589655796135-prodava-vila-grad-ruse-v-z-kulata              ВИЛА         град Русе                               град Русе, в.з. Кулата     14900.00      10.0        1490.00                                                Продава ВИЛА в град Русе, в.з. Кулата - 10 кв.м / 14 900 € » 29 141.87 лв. :: imot.bg Обява 796135
110941  1k170487729767222                                              https://www.imot.bg/obiava-1k170487729767222-prodava-vila-oblast-gabrovo-s-boriki              ВИЛА    област Габрово                            област Габрово, с. Борики      9700.00      12.0         808.33                                  Продава ВИЛА в област Габрово, с. Борики - 12 кв.м / 9 700 € » 18 971.55 лв., ТОП ЕСТЕЙТ :: imot.bg Обява 767222
111988  1k177874594569087                                      https://www.imot.bg/obiava-1k177874594569087-prodava-vila-oblast-haskovo-s-mineralni-bani              ВИЛА    област Хасково                    област Хасково, с. Минерални бани     38000.00      12.0        3166.67                         Продава ВИЛА в област Хасково, с. Минерални бани - 12 кв.м / 38 000 € » 74 321.54 лв., ИМОТИ-МИРА :: imot.bg Обява 569087
111694  1k176790178804201                                        https://www.imot.bg/obiava-1k176790178804201-prodava-vila-grad-shumen-m-t-pod-manastira              ВИЛА        град Шумен                        град Шумен, м-т Под Манастира     28000.00      13.0        2153.85                           Продава ВИЛА в град Шумен, м-т Под Манастира - 13 кв.м / При запитване, ФАВОРИТ НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 804201
110796  1k159187372423967                                             https://www.imot.bg/obiava-1k159187372423967-prodava-vila-grad-dobrich-v-z-lozyata              ВИЛА       град Добрич                             град Добрич, в.з. Лозята      9714.55      14.0         693.90                      Продава ВИЛА в град Добрич, в.з. Лозята - 14 кв.м / 9 714.55 € » 19 000 лв., ЕДИВАР - КАНТОРА ДОБРИЧ :: imot.bg Обява 423967
111194  1k173381990962779                                   https://www.imot.bg/obiava-1k173381990962779-prodava-vila-grad-targovishte-vilna-zona-chokya              ВИЛА    град Търговище                     град Търговище, Вилна зона, Чокя     15338.76      14.0        1095.63                                      Продава ВИЛА в град Търговище, Вилна зона - 14 кв.м / 15 338.76 € » 30 000 лв., КСЕН :: imot.bg Обява 962779
111656  1k176608838752786                                    https://www.imot.bg/obiava-1k176608838752786-prodava-vila-grad-dobrich-m-t-gazibaba-almalii              ВИЛА       град Добрич                   град Добрич, м-т Газибаба, алмалии      9200.00      14.0         657.14                             Продава ВИЛА в град Добрич, м-т Газибаба - 14 кв.м / 9 200 € » 17 993.64 лв., ДОБРИЧ ИМОТИ 21 :: imot.bg Обява 752786
110878  1k166902483080379                                                   https://www.imot.bg/obiava-1k166902483080379-prodava-vila-grad-ruse-dolapite              ВИЛА         град Русе                                  град Русе, Долапите      5880.00      15.0         392.00                                     Продава ВИЛА в град Русе, Долапите - 15 кв.м / 5 880 € » 11 500.28 лв., РЕАЛ БЪЛГАРИЯ :: imot.bg Обява 080379
110953  1k170238482982981                                          https://www.imot.bg/obiava-1k170238482982981-prodava-vila-grad-ruse-dolapite-10-ti-km              ВИЛА         град Русе                        град Русе, Долапите, 10-ти км      6391.15      15.0         426.08                                        Продава ВИЛА в град Русе, Долапите - 15 кв.м / 6 391.15 € » 12 500 лв., КОМОР ЕООД :: imot.bg Обява 982981
110978  1k171153091465916                                               https://www.imot.bg/obiava-1k171153091465916-prodava-vila-oblast-varna-s-osenovo              ВИЛА      област Варна                             област Варна, с. Осеново     35000.00      15.0        2333.33                               Продава ВИЛА в област Варна, с. Осеново - 15 кв.м / 35 000 € » 68 454.05 лв., ИМОТИ ПРЕМИЕР :: imot.bg Обява 465916
111204  1k173617831600509                                        https://www.imot.bg/obiava-1k173617831600509-prodava-vila-grad-pleven-m-t-martva-dolina              ВИЛА       град Плевен                       град Плевен, м-т Мъртва долина      5624.21      15.0         374.95                    Продава ВИЛА в град Плевен, м-т Мъртва долина - 15 кв.м / 5 624.21 € » 11 000 лв., ФОР СЕЛ РЕАЛ ЕСТЕЙТ :: imot.bg Обява 600509
111215  1k173771669891059                                         https://www.imot.bg/obiava-1k173771669891059-prodava-vila-grad-ruse-v-z-kaseva-cheshma              ВИЛА         град Русе                         град Русе, в.з. Касева Чешма     28990.25      15.0        1932.68                          Продава ВИЛА в град Русе, в.з. Касева Чешма - 15 кв.м / 28 990.25 € » 56 700 лв., СТОЛИЦА ИНВЕСТ :: imot.bg Обява 891059
111258  1k174285800592432                                         https://www.imot.bg/obiava-1k174285800592432-prodava-vila-grad-ruse-v-z-kaseva-cheshma              ВИЛА         град Русе                         град Русе, в.з. Касева Чешма     22000.00      15.0        1466.67                       Продава ВИЛА в град Русе, в.з. Касева Чешма - 15 кв.м / 22 000 € » 43 028.26 лв., АЛЕКС ЕСТЕЙТ - БД :: imot.bg Обява 592432
111274  1k174360336907458                                         https://www.imot.bg/obiava-1k174360336907458-prodava-vila-grad-ruse-v-z-kaseva-cheshma              ВИЛА         град Русе                         град Русе, в.з. Касева Чешма     21500.00      15.0        1433.33                            Продава ВИЛА в град Русе, в.з. Касева Чешма - 15 кв.м / 21 500 € » 42 050.35 лв., АДРЕС - РУСЕ :: imot.bg Обява 907458
111327  1k174697906929015                                                https://www.imot.bg/obiava-1k174697906929015-prodava-vila-oblast-burgas-s-rosen              ВИЛА     област Бургас                              област Бургас, с. Росен     26000.00      15.0        1733.33                                               Продава ВИЛА в област Бургас, с. Росен - 15 кв.м / 26 000 € » 50 851.58 лв. :: imot.bg Обява 929015
111394  1k175206432515505                                                https://www.imot.bg/obiava-1k175206432515505-prodava-vila-oblast-ruse-s-pirgovo              ВИЛА       област Русе                              област Русе, с. Пиргово     32000.00      15.0        2133.33                                Продава ВИЛА в област Русе, с. Пиргово - 15 кв.м / 32 000 € » 62 586.56 лв., АГЕНЦИЯ БРИКС :: imot.bg Обява 515505
111714  1k177089513661784                                https://www.imot.bg/obiava-1k177089513661784-prodava-vila-oblast-targovishte-s-razboyna-sersema              ВИЛА  област Търговище               област Търговище, с. Разбойна, Серсема     33233.00      15.0        2215.53                                   Продава ВИЛА в област Търговище, с. Разбойна - 15 кв.м / 33 233 € » 64 998.10 лв., КСЕН :: imot.bg Обява 661784
111771  1k177306035384054                                           https://www.imot.bg/obiava-1k177306035384054-prodava-vila-oblast-gabrovo-s-chukilite              ВИЛА    област Габрово                          област Габрово, с. Чукилите     14000.00      15.0         933.33                                   Продава ВИЛА в област Габрово, с. Чукилите - 15 кв.м / 14 000 € » 27 381.62 лв., РЕГЕНТ :: imot.bg Обява 384054
110848  1k165349073718160                                              https://www.imot.bg/obiava-1k165349073718160-prodava-vila-oblast-sofiya-s-svidnya              ВИЛА      област София                              област София, с. Свидня     14000.00      16.0         875.00                                      Продава ВИЛА в област София, с. Свидня - 16 кв.м / 14 000 € » 27 381.62 лв., МАРКОНИ :: imot.bg Обява 718160
110899  1k168630218456890                                         https://www.imot.bg/obiava-1k168630218456890-prodava-vila-grad-ruse-v-z-kaseva-cheshma              ВИЛА         град Русе                         град Русе, в.з. Касева Чешма     31000.00      16.0        1937.50                                    Продава ВИЛА в град Русе, в.з. Касева Чешма - 16 кв.м / 31 000 € » 60 630.73 лв., ДЕСИ :: imot.bg Обява 456890
111170  1k173131358442876                                                 https://www.imot.bg/obiava-1k173131358442876-prodava-vila-grad-ruse-v-z-lipaka              ВИЛА         град Русе                               град Русе, в.з. Липака     10225.84      16.0         639.12                                        Продава ВИЛА в град Русе, в.з. Липака - 16 кв.м / 10 225.84 € » 20 000 лв., НЕЛИНИ :: imot.bg Обява 442876
111202  1k173131452046414                                               https://www.imot.bg/obiava-1k173131452046414-prodava-vila-oblast-ruse-s-nikolovo              ВИЛА       област Русе                             област Русе, с. Николово     10225.84      16.0         639.12                                      Продава ВИЛА в област Русе, с. Николово - 16 кв.м / 10 225.84 € » 20 000 лв., НЕЛИНИ :: imot.bg Обява 046414
111787  1k177304552236782                                   https://www.imot.bg/obiava-1k177304552236782-prodava-vila-oblast-pazardzhik-m-t-tsigov-chark              ВИЛА  област Пазарджик                     област Пазарджик, м-т Цигов чарк     32000.00      16.0        2000.00                                      Продава ВИЛА в област Пазарджик, м-т Цигов чарк - 16 кв.м / 32 000 € » 62 586.56 лв. :: imot.bg Обява 236782
111285  1k174471450262174                           https://www.imot.bg/obiava-1k174471450262174-prodava-vila-oblast-gabrovo-gr-sevlievo-krushevski-bair              ВИЛА    област Габрово         област Габрово, гр. Севлиево, Крушевски баир     12271.01      17.0         721.82                  Продава ВИЛА в област Габрово, гр. Севлиево - 17 кв.м / 12 271.01 € » 24 000 лв., АДРЕС НЕДВИЖИМИ ИМОТИ  :: imot.bg Обява 262174
111876  1k177592015889825                         https://www.imot.bg/obiava-1k177592015889825-prodava-vila-grad-vratsa-studentski-grad-vrachanski-lozya              ВИЛА        град Враца          град Враца, Студентски град, Врачански лозя     17000.00      17.0        1000.00                                 Продава ВИЛА в град Враца, Студентски град - 17 кв.м / 17 000 € » 33 249.11 лв., АГРО-ЕМ  :: imot.bg Обява 889825
110826  1k163422905045659                                  https://www.imot.bg/obiava-1k163422905045659-prodava-vila-grad-razgrad-promishlena-zona-zapad              ВИЛА      град Разград                град Разград, Промишлена зона - Запад     10225.84      18.0         568.10           Продава ВИЛА в град Разград, Промишлена зона - Запад - 18 кв.м / 10 225.84 € » 20 000 лв., РОС -НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 045659
110880  1k166936354732929                          https://www.imot.bg/obiava-1k166936354732929-prodava-vila-oblast-gabrovo-gr-sevlievo-sevlievski-lozya              ВИЛА    област Габрово        област Габрово, гр. Севлиево, Севлиевски лозя     10225.84      18.0         568.10                                  Продава ВИЛА в област Габрово, гр. Севлиево - 18 кв.м / 10 225.84 € » 20 000 лв., РЕГЕНТ :: imot.bg Обява 732929
110936  1k169877165462335                                https://www.imot.bg/obiava-1k169877165462335-prodava-vila-oblast-sofiya-s-vlado-trichkov-romcha              ВИЛА      област София                област София, с. Владо Тричков, Ромча     18000.00      18.0        1000.00                            Продава ВИЛА в област София, с. Владо Тричков - 18 кв.м / 18 000 € » 35 204.94 лв., ТЕМЕНУГА64 :: imot.bg Обява 462335
111529  1k175922288191828                                  https://www.imot.bg/obiava-1k175922288191828-prodava-vila-grad-razgrad-promishlena-zona-zapad              ВИЛА      град Разград                град Разград, Промишлена зона - Запад     42437.23      18.0        2357.62           Продава ВИЛА в град Разград, Промишлена зона - Запад - 18 кв.м / 42 437.23 € » 83 000 лв., РОС -НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 191828
111745  1k177194253564731                            https://www.imot.bg/obiava-1k177194253564731-prodava-vila-grad-vratsa-studentski-grad-m-st-cheresha              ВИЛА        град Враца            град Враца, Студентски град,  м-ст Череша      9000.00      18.0         500.00                           Продава ВИЛА в град Враца, Студентски град - 18 кв.м / 9 000 € » 17 602.47 лв., БОРСА ИМОТИ ООД :: imot.bg Обява 564731

In [25]:
# Drop final manually inspected suspicious listing
before_rows = len(df_candidate)

drop_ad_ids = {
    "1a177675907072610",
}

drop_mask = df_candidate["ad_id"].isin(drop_ad_ids)

dropped_final_manual = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_final_manual[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_manual_fake_tiny_area_single_room",
    "reason": "Manually inspected listing 1a177675907072610 has implausible 2 sqm area for a 1-СТАЕН listing and should not be used for regression training",
    "rows_affected": len(dropped_final_manual),
})

Dropped rows: 1
Candidate rows before: 160542
Candidate rows after: 160541

                  ad_id                                                                                               ad_url property_type_raw title_city_raw                location_raw  total_price  area_sqm  price_per_sqm                                                                                                                       title
4937  1a177675907072610  https://www.imot.bg/obiava-1a177675907072610-prodava-ednostaen-apartament-grad-ruse-zdravets-olimpa           1-СТАЕН      град Русе  град Русе, Здравец, Олимпа      51900.0       2.0        25950.0  Продава 1-СТАЕН в град Русе, Здравец - 2 кв.м / При запитване, ВАЛЕНТИНА ПЕТРОВА - НЕДВИЖИМИ ИМОТИ :: imot.bg Обява 072610

In [26]:
price_summary = df_candidate[
    [
        "total_price",
        "title_price_eur",
        "title_price_bgn",
        "area_sqm",
        "price_per_sqm",
    ]
].describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999]).T

display(price_summary)

print("Rows:", len(df_candidate))
print("Missing total_price:", df_candidate["total_price"].isna().sum())
print("Missing price_per_sqm:", df_candidate["price_per_sqm"].isna().sum())
print("Non-positive total_price:", (df_candidate["total_price"] <= 0).sum())
print("Non-positive price_per_sqm:", (df_candidate["price_per_sqm"] <= 0).sum())

                    count           mean           std         min         0.1%      0.5%          1%        5%        50%         95%          99%        99.5%         99.9%           max
total_price      160541.0  253736.623876  2.068196e+06   31.000000  2600.000000   6000.00   8200.0000  20453.00  135000.00   680000.00  2025369.600  3135276.200  7.100000e+06  4.711950e+08
title_price_eur  157104.0  250866.784991  2.078771e+06  500.000000  2882.060000   6000.00   8400.6000  20500.00  134900.00   670000.00  2000000.000  3000000.000  6.984953e+06  4.711950e+08
title_price_bgn  157104.0  490652.784446  4.065722e+06  977.920000  5636.819360  11734.98  16430.1436  40094.52  263841.47  1310406.10  3911660.000  5867490.000  1.366138e+07  9.215773e+08
area_sqm         160541.0    2114.391355  2.345064e+04    3.000000    12.000000     17.00     20.0000     43.00     114.00     6000.00    26236.400    60000.000  3.000000e+05  4.854710e+06
price_per_sqm    160541.0    1344.451663  2.255529e+03    0.000304     0.174916      1.33      2.8400     14.29    1289.20     3191.49     4636.384     5414.487  7.975082e+03  5.794038e+05

Rows: 160541
Missing total_price: 0
Missing price_per_sqm: 0
Non-positive total_price: 0
Non-positive price_per_sqm: 0

In [27]:
df_candidate["price_per_sqm_recalc"] = (
    df_candidate["total_price"] / df_candidate["area_sqm"]
)

df_candidate["price_per_sqm_diff_abs"] = (
    df_candidate["price_per_sqm"] - df_candidate["price_per_sqm_recalc"]
).abs()

df_candidate["price_per_sqm_diff_pct"] = (
    df_candidate["price_per_sqm_diff_abs"] / df_candidate["price_per_sqm_recalc"]
)

price_mismatch = df_candidate.loc[
    df_candidate["price_per_sqm_diff_pct"].gt(0.01)
].copy()

print("Price-per-sqm mismatch rows > 1%:", len(price_mismatch))

display(
    price_mismatch[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm",
            "price_per_sqm_recalc",
            "price_per_sqm_diff_pct",
            "price_raw",
            "title",
        ]
    ]
    .sort_values("price_per_sqm_diff_pct", ascending=False)
    .head(50)
)

Price-per-sqm mismatch rows > 1%: 29

                    ad_id                                                                                                                   ad_url property_type_raw         title_city_raw                                         location_raw  total_price   area_sqm  price_per_sqm  price_per_sqm_recalc  price_per_sqm_diff_pct    price_raw                                                                                                                                            title
118483  1o176373075998653                               https://www.imot.bg/obiava-1o176373075998653-prodava-garazh-parkomyasto-grad-varna-vinitsa        ПАРКОМЯСТО             град Варна                                   град Варна, Виница     16000.00  1000000.0           0.02              0.016000                0.250000     16 000 €                         Продава ПАРКОМЯСТО в град Варна, Виница - 1000000 кв.м / 16 000 € » 31 293.28 лв., ХОЛДИНГ ГРУП  :: imot.bg Обява 998653
161150  1s176978940485838                           https://www.imot.bg/obiava-1s176978940485838-prodava-zemedelska-zemya-oblast-pleven-s-todorovo   ЗЕМЕДЕЛСКА ЗЕМЯ          област Плевен                           област Плевен, с. Тодорово     14000.00   189550.0           0.07              0.073859                0.052250     14 000 €        Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Плевен, с. Тодорово - 12 дка / 14 000 € » 27 381.62 лв., АДРЕС - ФРАНЧАЙЗ ПЛЕВЕН :: imot.bg Обява 485838
158520  1s144766083882107     https://www.imot.bg/obiava-1s144766083882107-prodava-zemedelska-zemya-oblast-sofiya-s-herakovo-mestnostta-buli-valog   ЗЕМЕДЕЛСКА ЗЕМЯ           област София   област София, с. Хераково, местността 'Були валог'       511.00     8199.0           0.06              0.062325                0.037299        511 €                                     Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Хераково - 8 дка / При запитване, АНГЕЛОВ :: imot.bg Обява 882107
124885  1r157469288353220                                           https://www.imot.bg/obiava-1r157469288353220-prodava-partsel-grad-yambol-iztok            ПАРЦЕЛ             град Ямбол                                    град Ямбол, Изток      1700.00    58767.0           0.03              0.028928                0.037065      1 700 €                                             Продава ПАРЦЕЛ в град Ямбол, Изток - 58767 кв.м / При запитване, ТОП ИМОТ БГ :: imot.bg Обява 353220
146376  1r176155521345093                        https://www.imot.bg/obiava-1r176155521345093-prodava-partsel-oblast-pernik-gr-tran-selo-turkovtsi            ПАРЦЕЛ          област Перник               област Перник, гр. Трън, Село Турковци     40903.35  3959900.0           0.01              0.010329                0.031889  40 903.35 €                 Продава ПАРЦЕЛ в област Перник, гр. Трън - 3959900 кв.м / 40 903.35 € » 80 000 лв., БЛЕК ЕНД УАЙТ РИЪЛТИ :: imot.bg Обява 345093
124101  1r151066590726245                      https://www.imot.bg/obiava-1r151066590726245-prodava-partsel-oblast-sofiya-gr-elin-pelin-m-soleniko            ПАРЦЕЛ           област София            област София, гр. Елин Пелин, м. Соленико    150000.00  1031000.0           0.15              0.145490                0.031000    150 000 €                                Продава ПАРЦЕЛ в област София, гр. Елин Пелин - 1031000 кв.м / При запитване, РЕНЕСАНС АД :: imot.bg Обява 726245
160644  1s175819638805908  https://www.imot.bg/obiava-1s175819638805908-prodava-zemedelska-zemya-oblast-stara-zagora-s-kirilovo-mestnost-valkovets   ЗЕМЕДЕЛСКА ЗЕМЯ    област Стара Загора  област Стара Загора, с. Кирилово, местност ВЪЛКОВЕЦ       205.00     1240.0           0.17              0.165323                0.028293        205 €                      Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора, с. Кирилово - 3701 дка / При запитване, ТЕРЗИЕВА ООД :: imot.bg Обява 805908
160647  1s175819656276128  https://www.imot.bg/obiava-1s175819656276128-prodava-zemedelska-zemya-oblast-stara-zagora-s-kirilovo-mestnost-marashite   ЗЕМЕДЕЛСКА ЗЕМЯ    област Стара Загора  област Стара Загора, с. Кирилово, местност МАРАШИТЕ       205.00     1240.0           0.17              0.165323                0.028293        205 €                      Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Стара Загора, с. Кирилово - 3401 дка / При запитване, ТЕРЗИЕВА ООД :: imot.bg Обява 276128
161511  1s177462535055312         https://www.imot.bg/obiava-1s177462535055312-prodava-zemedelska-zemya-oblast-burgas-s-yasna-polyana-trite-krushi   ЗЕМЕДЕЛСКА ЗЕМЯ          област Бургас           област Бургас, с. Ясна поляна, Трите круши       643.00     5999.0           0.11              0.107185                0.026267        643 €                 Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Ясна поляна - 5.999 дка / 643 € » 1 257.60 лв., КОИН КОНСУЛТ :: imot.bg Обява 055312
135487  1r172899850546229                                   https://www.imot.bg/obiava-1r172899850546229-prodava-partsel-oblast-lovech-s-kazachevo            ПАРЦЕЛ           област Ловеч                            област Ловеч, с. Казачево      1500.00     8598.0           0.17              0.174459                0.025560      1 500 €                                Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 8598 кв.м / При запитване, ЛОВЕЧ КОНСУЛТ ООД :: imot.bg Обява 546229
133756  1r172080513548610                           https://www.imot.bg/obiava-1r172080513548610-prodava-partsel-oblast-veliko-tarnovo-gr-debelets            ПАРЦЕЛ  област Велико Търново                   област Велико Търново, гр. Дебелец      1111.00     6700.0           0.17              0.165821                0.025203      1 111 €                                 Продава ПАРЦЕЛ в област Велико Търново, гр. Дебелец - 6700 кв.м / 1 111 € » 2 172.93 лв. :: imot.bg Обява 548610
154955  1r177514396184479                                https://www.imot.bg/obiava-1r177514396184479-prodava-partsel-oblast-plovdiv-gr-asenovgrad            ПАРЦЕЛ         област Пловдив                       област Пловдив, гр. Асеновград    120000.00   650100.0           0.18              0.184587                0.024850    120 000 €          Продава ПАРЦЕЛ в област Пловдив, гр. Асеновград - 650100 кв.м / 120 000 € » 234 699.60 лв., ЕКС НВД ПЛОВДИВ ООД :: imot.bg Обява 184479
159161  1s169095777444571                            https://www.imot.bg/obiava-1s169095777444571-prodava-zemedelska-zemya-oblast-plovdiv-s-prolom   ЗЕМЕДЕЛСКА ЗЕМЯ         област Пловдив                            област Пловдив, с. Пролом      1789.52    20369.0           0.09              0.087855                0.024414   1 789.52 €           Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, с. Пролом - 2.546 дка / 1 789.52 € » 3 500 лв., НЕДВИЖИМИ ИМОТИ ВАНЯ :: imot.bg Обява 444571
130049  1r169571092600853                                  https://www.imot.bg/obiava-1r169571092600853-prodava-partsel-oblast-burgas-gr-primorsko            ПАРЦЕЛ          област Бургас                         област Бургас, гр. Приморско      4000.00    21500.0           0.19              0.186047                0.021250      4 000 €                                      Продава ПАРЦЕЛ в област Бургас, гр. Приморско - 21500 кв.м / 4 000 € » 7 823.32 лв. :: imot.bg Обява 600853
160983  1s176537514767590                       https://www.imot.bg/obiava-1s176537514767590-prodava-zemedelska-zemya-oblast-pleven-s-kartozhabene   ЗЕМЕДЕЛСКА ЗЕМЯ          област Плевен                        област Плевен, с. Къртожабене     13000.00   189550.0           0.07              0.068583                0.020654     13 000 €      Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Плевен, с. Къртожабене - 4 дка / 13 000 € » 25 425.79 лв., АДРЕС - ФРАНЧАЙЗ ПЛЕВЕН :: imot.bg Обява 767590
124120  1r151119773445530                     https://www.imot.bg/obiava-1r151119773445530-prodava-partsel-oblast-sofiya-s-karapoltsi-m-kopaninata            ПАРЦЕЛ           област София            област София, с. Караполци, м. Копанината     59999.00   345732.0           0.17              0.173542                0.020410     59 999 €                                   Продава ПАРЦЕЛ в област София, с. Караполци - 345732 кв.м / При запитване, РЕНЕСАНС АД :: imot.bg Обява 445530
140319  1r174644643585476                                   https://www.imot.bg/obiava-1r174644643585476-prodava-partsel-oblast-burgas-gr-karnobat            ПАРЦЕЛ          област Бургас                          област Бургас, гр. Карнобат     49000.00   300000.0           0.16              0.163333                0.020408     49 000 €                                      Продава ПАРЦЕЛ в област Бургас, гр. Карнобат - 300000 кв.м / При запитване, АТЛАНТА :: imot.bg Обява 585476
158993  1s167640946582265            https://www.imot.bg/obiava-1s167640946582265-prodava-zemedelska-zemya-oblast-burgas-gr-chernomorets-izkupuvam   ЗЕМЕДЕЛСКА ЗЕМЯ          област Бургас             област Бургас, гр. Черноморец, Изкупувам      1000.00     6999.0           0.14              0.142878                0.020140      1 000 €          Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Черноморец - 1 дка / 1 000 € » 1 955.83 лв., НЕУСТОИМИ ПРЕДЛОЖЕНИЯ :: imot.bg Обява 582265
126745  1r164613796043510                                      https://www.imot.bg/obiava-1r164613796043510-prodava-partsel-oblast-lovech-s-tepava            ПАРЦЕЛ           област Ловеч                              област Ловеч, с. Тепава      2556.46    10005.0           0.26              0.255518                0.017540   2 556.46 €                        Продава ПАРЦЕЛ в област Ловеч, с. Тепава - 10005 кв.м / 2 556.46 € » 5 000 лв., ЛОВЕЧ КОНСУЛТ ООД :: imot.bg Обява 043510
160419  1s175033738856789                            https://www.imot.bg/obiava-1s175033738856789-prodava-zemedelska-zemya-oblast-sofiya-s-pchelin   ЗЕМЕДЕЛСКА ЗЕМЯ           област София                              област София, с. Пчелин     95000.00   345732.0           0.27              0.274779                0.017393     95 000 €                                   Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област София, с. Пчелин - 4 дка / При запитване, РЕНЕСАНС АД :: imot.bg Обява 856789
152458  1r177219597450837                                     https://www.imot.bg/obiava-1r177219597450837-prodava-partsel-oblast-dobrich-s-topola            ПАРЦЕЛ          област Добрич                             област Добрич, с. Топола     17900.00   125771.0           0.14              0.142322                0.016316     17 900 €                            Продава ПАРЦЕЛ в област Добрич, с. Топола - 125771 кв.м / При запитване, БЪЛГЕРИАН ПРОПЕРТИС  :: imot.bg Обява 450837
126747  1r164614174065380                                   https://www.imot.bg/obiava-1r164614174065380-prodava-partsel-oblast-lovech-s-kazachevo            ПАРЦЕЛ           област Ловеч                            област Ловеч, с. Казачево      1600.00     5600.0           0.29              0.285714                0.015000      1 600 €                       Продава ПАРЦЕЛ в област Ловеч, с. Казачево - 5600 кв.м / 1 600 € » 3 129.33 лв., ЛОВЕЧ КОНСУЛТ ООД :: imot.bg Обява 065380
160284  1s174582430797703               https://www.imot.bg/obiava-1s174582430797703-prodava-zemedelska-zemya-oblast-kyustendil-s-gorna-grashtitsa   ЗЕМЕДЕЛСКА ЗЕМЯ       област Кюстендил                   област Кюстендил, с. Горна Гращица      1380.00     8500.0           0.16              0.162353                0.014493      1 380 €  Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с. Горна Гращица - 2.3 дка / 1 380 € » 2 699.05 лв., КОНТРАКТ ПРОПЪРТИ ЕООД :: imot.bg Обява 797703
160312  1s174739413061650                      https://www.imot.bg/obiava-1s174739413061650-prodava-zemedelska-zemya-oblast-targovishte-s-davidovo   ЗЕМЕДЕЛСКА ЗЕМЯ       област Търговище                        област Търговище, с. Давидово      1500.00     4000.0           0.38              0.375000                0.013333      1 500 €                                 Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Търговище, с. Давидово - 4000 дка / При запитване, КСЕН :: imot.bg Обява 061650
132535  1r171516251050830                         https://www.imot.bg/obiava-1r171516251050830-prodava-partsel-oblast-veliko-tarnovo-gr-strazhitsa            ПАРЦЕЛ  област Велико Търново                  област Велико Търново, гр. Стражица      3000.00     7998.0           0.38              0.375094                0.013080      3 000 €                 Продава ПАРЦЕЛ в област Велико Търново, гр. Стражица - 7998 кв.м / 3 000 € » 5 867.49 лв., МАЙХОУМС ЕООД :: imot.bg Обява 050830
124113  1r151197862312006                              https://www.imot.bg/obiava-1r151197862312006-prodava-partsel-oblast-vratsa-gr-byala-slatina            ПАРЦЕЛ           област Враца                       област Враца, гр. Бяла Слатина     35000.00    91000.0           0.38              0.384615                0.012000     35 000 €                           Продава ПАРЦЕЛ в област Враца, гр. Бяла Слатина - 91000 кв.м / При запитване, АТИКАНТЕ ЕСТЕЙТС :: imot.bg Обява 312006
124798  1r156829059149246                         https://www.imot.bg/obiava-1r156829059149246-prodava-partsel-oblast-dobrich-gr-balchik-fish-fish            ПАРЦЕЛ          област Добрич                   област Добрич, гр. Балчик, фиш-фиш     40900.00    94000.0           0.44              0.435106                0.011247     40 900 €                        Продава ПАРЦЕЛ в област Добрич, гр. Балчик - 94000 кв.м / При запитване, СЕВЕРОИЗТОЧНИ ИМОТИ ЕООД :: imot.bg Обява 149246
131955  1r171153791512892                          https://www.imot.bg/obiava-1r171153791512892-prodava-partsel-oblast-pazardzhik-m-t-tsigov-chark            ПАРЦЕЛ       област Пазарджик                     област Пазарджик, м-т Цигов чарк      1111.00     2616.0           0.42              0.424694                0.011053      1 111 €                    Продава ПАРЦЕЛ в област Пазарджик, м-т Цигов чарк - 2616 кв.м / 1 111 € » 2 172.93 лв., ТОНИКО ИМОТИ  :: imot.bg Обява 512892
136380  1r173210477949657                                    https://www.imot.bg/obiava-1r173210477949657-prodava-partsel-oblast-pleven-s-grivitsa            ПАРЦЕЛ          област Плевен                            област Плевен, с. Гривица     30000.00   189550.0           0.16              0.158270                0.010933     30 000 €                        Продава ПАРЦЕЛ в област Плевен, с. Гривица - 189550 кв.м / При запитване, АДРЕС - ФРАНЧАЙЗ ПЛЕВЕН :: imot.bg Обява 949657

In [28]:
price_psqm_by_type = (
    df_candidate
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_ppsqm=("price_per_sqm", "min"),
        p01_ppsqm=("price_per_sqm", lambda s: s.quantile(0.01)),
        median_ppsqm=("price_per_sqm", "median"),
        p99_ppsqm=("price_per_sqm", lambda s: s.quantile(0.99)),
        max_ppsqm=("price_per_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(price_psqm_by_type)

              property_type_raw   rows    min_ppsqm    p01_ppsqm  median_ppsqm   p99_ppsqm  max_ppsqm  min_price  median_price    max_price
29                       ПАРЦЕЛ  35222     0.010000     1.500000        44.990    986.6773   11363.64     250.00      80000.00   40000000.0
1                       2-СТАЕН  33693    16.470000   739.984800      1686.670   4416.6700    9375.00    1400.00     115000.00    1200000.0
2                       3-СТАЕН  33442    76.130000   690.143800      1774.290   4919.2210   10833.33    7500.00     180000.00    2190000.0
21                         КЪЩА  22189     1.000000    65.728000       967.740   4500.0000   19179.89    1000.00     138048.81   22995000.0
0                       1-СТАЕН   6019   124.330000   702.127800      1563.340   4106.4758    6307.69   12271.01      66000.00     305258.0
3                       4-СТАЕН   5258    91.630000   598.823700      1951.285   6135.1628   10292.89   20451.68     279000.00    2460000.0
23                      МАГАЗИН   3434     9.400000   147.605100      1700.000   7500.0000   20450.00    3323.40     154820.00   12500000.0
25                   МНОГОСТАЕН   3072   104.760000   475.934800      1800.000   6138.5600   11515.15   22000.00     290000.00    5000000.0
26                         ОФИС   2380    16.660000   139.850700      1804.760   5548.8908   12163.33    4857.27     200000.00   16800000.0
19              ЗЕМЕДЕЛСКА ЗЕМЯ   2235     0.000304     0.016072        10.000   1373.4644  579403.85      31.00      50000.00  471195000.0
30              ПРОМ. ПОМЕЩЕНИЕ   1978     0.810000     9.363900       322.315   3050.4502   31666.67    3000.00     300000.00   15000000.0
17                 ЕТАЖ ОТ КЪЩА   1851    36.590000   244.680000      1198.340   3800.8350    8241.76    4464.00     130379.43    1500000.0
13                        ГАРАЖ   1504    68.510000   256.156900      1302.175   3750.0000   20000.00    3500.00      30000.00     792000.0
24                      МЕЗОНЕТ   1382   373.680000   594.052700      1765.010   5264.5141   13750.00   54908.00     276000.00    2750000.0
11                         ВИЛА   1190     3.090000    41.520100       928.990   9504.9995   26666.67    4100.00      58950.00   17500000.0
18                    ЗАВЕДЕНИЕ   1082    12.680000    90.357100      1184.700   6000.0000   18796.99    8700.00     225000.00    4900000.0
43                        ХОТЕЛ    992     1.900000    33.319500       806.125   4496.9870   11428.57   18000.00     805000.00   12000000.0
32                        СКЛАД    767     0.840000    11.465200       571.430   2112.5774    6875.00    2700.00     299000.00   22000000.0
28                   ПАРКОМЯСТО    759     0.020000   346.059600      1272.730   3487.5758    6666.67    2750.00      23000.00     309000.0
31         САМОСТОЯТЕЛНА СГРАДА    461     5.180000    11.760000       625.670   4466.6640    6591.34    7000.00     430000.00   23267500.0
37                ФАБРИКА/ЗАВОД    249     5.010000    11.131600       206.260   2667.3572    5000.00   20000.00     770000.00   12500000.0
36           ТЪРГОВСКИ КОМПЛЕКС    211     7.610000    20.625000       619.830   5057.6960  120000.00    9714.55     466000.00   12500000.0
8                 АТЕЛИЕ, ТАВАН    188   266.670000   551.592000      1670.415   4278.4911    4500.00   10740.00      86500.00     319000.0
38                        ФЕРМА    143     1.070000     3.946800        49.770   2362.1960    4285.71    8691.96     240000.00    7500000.0
41  ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН     99   395.000000   463.413800      1723.790   5224.9896   11162.79   23500.00     117597.13    1730000.0
12                 ВИЛНО СЕЛИЩЕ     93     6.960000     7.116400       235.510   3541.2396    5932.20   25000.00     428276.00    6267500.0
39                  ФИТНЕС ЗАЛА     78    57.250000   104.466400       924.090   4802.0730    7755.10   22900.00     234750.00    4900000.0
5                    АВТОСЕРВИЗ     76     5.270000    12.822500       707.540   5081.9275    5627.71   13191.33     276500.00    2800000.0
20                      КЛИНИКА     70    23.050000    50.615500      1944.445   8250.0033   10714.29   65000.00     612892.50    3676000.0
33                 СОЛАРЕН ПАРК     62     6.670000     6.682200        43.920    666.1753     832.26   21474.26     134000.00    6267500.0
22             ЛЕКАРСКИ КАБИНЕТ     61   431.210000   474.146000      1702.700   4664.4440    4825.40   22000.00     180000.00    1760000.0
34           СПА/СОЛАРНО СТУДИО     43    25.000000    51.699400       945.120   2883.3118    3225.49   31000.00     278868.00    1900000.0
10    БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ     42     3.830000     8.012000       198.150   2969.1819    3102.19   19100.00     275000.00    6800000.0
14            ГАРАЖ, ПАРКОМЯСТО     39    57.140000   105.726800       809.520   2045.1784    2272.73    8180.67      16361.34     222000.0
15                ДЕТСКИ ЦЕНТЪР     31    21.440000    22.676000      1642.250   3020.6090    3072.92   10000.00     255000.00    5200000.0
16        ДОМ ЗА ВЪЗРАСТНИ ХОРА     30    31.250000    36.293100       317.290   2880.0009    3000.00   80000.00     602500.00    3700000.0
35       СТОМАТОЛОГИЧЕН КАБИНЕТ     27   375.000000   422.346000      1833.330   9430.4646   11162.79   65000.00     208185.00    2600000.0
9                   БАНКОВ ОФИС     24    91.950000   104.611500      1784.195   6773.5214    7142.86   59309.86     510000.00    2780000.0
7                        АПТЕКА     22   328.360000   427.404400      2190.175  30678.3075   37500.00   69000.00     198995.00    2250000.0
27                      ПАРКИНГ     18     7.970000     8.255600       123.975    901.8339     950.00   11000.00     390000.00    3800000.0
4                     АВТОМИВКА     11    41.670000    43.003000       557.140   1970.0000    2000.00   25000.00     290000.00     900000.0
6                      АКВАПАРК      9    94.590000    97.156400       126.670   2613.8900    2830.17  350000.00    1900000.00   10120680.0
42               ХЛАДИЛЕН СКЛАД      4    68.000000    78.867500       510.030   1277.4721    1298.74  220000.00     408126.00     557600.0
40           ФОТОГРАФСКО СТУДИО      1  1210.570000  1210.570000      1210.570   1210.5700    1210.57  148900.00     148900.00     148900.0

In [30]:
df_candidate["price_per_sqm_model"] = (
    df_candidate["total_price"] / df_candidate["area_sqm"]
)

In [31]:
# ------------------------------------------------------------
# Step 3A: Inspect extreme area values by property type
# ------------------------------------------------------------

area_by_type = (
    df_candidate
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        p01_area=("area_sqm", lambda s: s.quantile(0.01)),
        median_area=("area_sqm", "median"),
        p95_area=("area_sqm", lambda s: s.quantile(0.95)),
        p99_area=("area_sqm", lambda s: s.quantile(0.99)),
        max_area=("area_sqm", "max"),
        median_price=("total_price", "median"),
        median_ppsqm=("price_per_sqm_model", "median"),
    )
    .reset_index()
    .sort_values("max_area", ascending=False)
)

display(area_by_type)

              property_type_raw   rows  min_area  p01_area  median_area   p95_area   p99_area   max_area  median_price  median_ppsqm
29                       ПАРЦЕЛ  35222      20.0    280.00       1880.5   16604.75   50000.00  4854710.0      80000.00     44.992269
28                   ПАРКОМЯСТО    759       8.0     11.00         16.0      42.10     330.00  1000000.0      23000.00   1272.727273
19              ЗЕМЕДЕЛСКА ЗЕМЯ   2235     260.0    550.00       4410.0  322100.00  496320.00   587623.0      50000.00     10.000000
43                        ХОТЕЛ    992       9.0    152.73       1000.0    8000.00   20426.40   500000.0     805000.00    806.125629
21                         КЪЩА  22189      15.0     40.00        150.0     500.00    1000.00   265000.0     138048.81    967.741935
12                 ВИЛНО СЕЛИЩЕ     93      59.0     87.52       2000.0   25878.40   72160.00   235000.0     428276.00    235.507246
38                        ФЕРМА    143      20.0    133.18       5215.0   63900.00  108000.00   180000.0     240000.00     49.773756
11                         ВИЛА   1190       9.0     15.00         75.0     465.00    1100.00   175000.0      58950.00    928.991597
30              ПРОМ. ПОМЕЩЕНИЕ   1978       6.0     55.77       1080.0   15000.00   54070.61   150000.0     300000.00    322.314270
33                 СОЛАРЕН ПАРК     62      75.0    123.80       3195.0   66581.45  110476.88   150000.0     134000.00     43.919414
37                ФАБРИКА/ЗАВОД    249      67.0    223.56       3245.0   42420.00   76245.92   136000.0     770000.00    206.258890
5                    АВТОСЕРВИЗ     76      52.0     52.00        377.5    5127.75   47512.75    97000.0     276500.00    707.542909
32                        СКЛАД    767       3.0      8.00        650.0   10752.00   50997.70    83000.0     299000.00    571.428571
36           ТЪРГОВСКИ КОМПЛЕКС    211      15.0     41.00        740.0   10958.50   29250.00    46000.0     466000.00    619.834711
27                      ПАРКИНГ     18     400.0    434.00       5076.0   19578.90   31142.98    34034.0     390000.00    123.972963
34           СПА/СОЛАРНО СТУДИО     43      40.0     45.88        365.0     984.00   18027.48    30000.0     278868.00    945.121951
31         САМОСТОЯТЕЛНА СГРАДА    461      22.0     40.60        864.0    6565.00    9638.20    19636.0     430000.00    625.674218
6                      АКВАПАРК      9    3576.0   3585.92      15000.0   15000.00   15000.00    15000.0    1900000.00    126.666667
18                    ЗАВЕДЕНИЕ   1082      10.0     29.24        200.5     760.00    2035.72    10405.0     225000.00   1184.697856
16        ДОМ ЗА ВЪЗРАСТНИ ХОРА     30     290.0    290.58       1675.0    8282.90    9773.25    10375.0     602500.00    317.287234
20                      КЛИНИКА     70      50.0     63.80        382.5    1927.10    4951.25     9695.0     612892.50   1944.444444
26                         ОФИС   2380      10.0     15.00        108.0     753.25    2315.00     9000.0     200000.00   1804.761290
42               ХЛАДИЛЕН СКЛАД      4     278.0    280.85        715.5    7128.70    7985.74     8200.0     408126.00    510.029985
10    БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ     42     110.0    138.70       1835.0    5858.60    7447.09     8001.0     275000.00    198.150339
23                      МАГАЗИН   3434       5.0     14.00         94.0     564.35    1289.77     5895.0     154820.00   1700.000000
15                ДЕТСКИ ЦЕНТЪР     31      55.0     56.50        285.0    2600.00    3580.00     4000.0     255000.00   1642.247863
1                       2-СТАЕН  33693      14.0     41.00         68.0      95.00     124.00     4000.0     115000.00   1686.666667
14            ГАРАЖ, ПАРКОМЯСТО     39      11.0     11.38         20.0     181.20    2626.00     3500.0      16361.34    809.523810
4                     АВТОМИВКА     11     182.0    182.90        400.0    2600.00    3304.00     3480.0     290000.00    557.142857
39                  ФИТНЕС ЗАЛА     78      78.0     79.54        242.5     851.25    1633.64     2918.0     234750.00    924.089394
35       СТОМАТОЛОГИЧЕН КАБИНЕТ     27      22.0     25.12        130.0     850.00    1701.00     2000.0     208185.00   1833.333333
25                   МНОГОСТАЕН   3072      49.0     82.00        157.0     354.45     538.29     1930.0     290000.00   1800.000000
2                       3-СТАЕН  33442      35.0     60.00        103.0     155.00     218.00     1450.0     180000.00   1774.291896
17                 ЕТАЖ ОТ КЪЩА   1851      22.0     44.00        105.0     220.00     328.00     1365.0     130379.43   1198.340312
9                   БАНКОВ ОФИС     24      70.0     71.15        456.5    1285.00    1300.00     1300.0     510000.00   1784.198399
13                        ГАРАЖ   1504       5.0     12.00         21.0      53.85     268.65     1200.0      30000.00   1302.173913
0                       1-СТАЕН   6019      10.0     21.00         43.0      64.00      86.00     1127.0      66000.00   1563.340000
3                       4-СТАЕН   5258      53.0     79.00        141.0     262.00     361.00     1000.0     279000.00   1951.287175
22             ЛЕКАРСКИ КАБИНЕТ     61      21.0     24.60         90.0     812.00     862.00      880.0     180000.00   1702.702703
24                      МЕЗОНЕТ   1382      22.0     50.00        156.0     350.00     502.00      850.0     276000.00   1765.006002
41  ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН     99      19.0     19.98         60.0     315.90     412.30      721.0     117597.13   1723.793103
8                 АТЕЛИЕ, ТАВАН    188      10.0     14.48         50.5     140.00     195.17      312.0      86500.00   1670.414082
7                        АПТЕКА     22      40.0     40.84         79.0     270.85     301.81      310.0     198995.00   2190.174782
40           ФОТОГРАФСКО СТУДИО      1     123.0    123.00        123.0     123.00     123.00      123.0     148900.00   1210.569106

In [32]:
# ------------------------------------------------------------
# Step 3B: Manually inspect largest-area listings
# ------------------------------------------------------------

large_area_candidates = df_candidate.loc[
    df_candidate["area_sqm"].gt(df_candidate["area_sqm"].quantile(0.995))
].copy()

print("Large area candidates:", len(large_area_candidates))

display(
    large_area_candidates[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm_model",
            "price_raw",
            "title",
        ]
    ]
    .sort_values("area_sqm", ascending=False)
    .head(100)
)

Large area candidates: 786

                    ad_id                                                                                                                   ad_url property_type_raw    title_city_raw                                          location_raw  total_price   area_sqm  price_per_sqm_model     price_raw                                                                                                                                              title
129963  1r169452337555022                                      https://www.imot.bg/obiava-1r169452337555022-prodava-partsel-oblast-sofiya-gr-svoge            ПАРЦЕЛ      област София                               област София, гр. Своге   7282065.00  4854710.0             1.500000   7 282 065 €       Продава ПАРЦЕЛ в област София, гр. Своге - 4854710 кв.м / 7 282 065 € » 14 242 481.19 лв., ПРОПЪРТИ ГРУП ИНВЕСТМЪНТС :: imot.bg Обява 555022
146376  1r176155521345093                        https://www.imot.bg/obiava-1r176155521345093-prodava-partsel-oblast-pernik-gr-tran-selo-turkovtsi            ПАРЦЕЛ     област Перник                област Перник, гр. Трън, Село Турковци     40903.35  3959900.0             0.010329   40 903.35 €                   Продава ПАРЦЕЛ в област Перник, гр. Трън - 3959900 кв.м / 40 903.35 € » 80 000 лв., БЛЕК ЕНД УАЙТ РИЪЛТИ :: imot.bg Обява 345093
126832  1r164760333818070                                 https://www.imot.bg/obiava-1r164760333818070-prodava-partsel-oblast-sofiya-gr-kostinbrod            ПАРЦЕЛ      област София                          област София, гр. Костинброд  30000000.00  1200000.0            25.000000  30 000 000 €                    Продава ПАРЦЕЛ в област София, гр. Костинброд - 1200000 кв.м / 30 000 000 € » 58 674 900.00 лв., РЕГЕНТ :: imot.bg Обява 818070
124101  1r151066590726245                      https://www.imot.bg/obiava-1r151066590726245-prodava-partsel-oblast-sofiya-gr-elin-pelin-m-soleniko            ПАРЦЕЛ      област София             област София, гр. Елин Пелин, м. Соленико    150000.00  1031000.0             0.145490     150 000 €                                  Продава ПАРЦЕЛ в област София, гр. Елин Пелин - 1031000 кв.м / При запитване, РЕНЕСАНС АД :: imot.bg Обява 726245
124596  1r155299501444798                                    https://www.imot.bg/obiava-1r155299501444798-prodava-partsel-oblast-sofiya-s-opitsvet            ПАРЦЕЛ      област София                              област София, с. Опицвет  29500000.00  1020000.0            28.921569  29 500 000 €                 Продава ПАРЦЕЛ в област София, с. Опицвет - 1020000 кв.м / 29 500 000 € » 57 696 985.00 лв., БГ-ИММОБИЛИЕН :: imot.bg Обява 444798
...                   ...                                                                                                                      ...               ...               ...                                                   ...          ...        ...                  ...           ...                                                                                                                                                ...
161305  1s177220205302669  https://www.imot.bg/obiava-1s177220205302669-prodava-zemedelska-zemya-oblast-plovdiv-gr-plovdiv-industrialna-zona-sever   ЗЕМЕДЕЛСКА ЗЕМЯ    област Пловдив  област Пловдив, гр. Пловдив, Индустриална зона Север    648000.00   400000.0             1.620000     648 000 €              Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Пловдив, гр. Пловдив - 14.4 дка / 648 000 € » 1 267 377.84 лв., АРИС БРОКЕР  :: imot.bg Обява 302669
159779  1s173220317960948                            https://www.imot.bg/obiava-1s173220317960948-prodava-zemedelska-zemya-oblast-burgas-s-ravnets   ЗЕМЕДЕЛСКА ЗЕМЯ     област Бургас                              област Бургас, с. Равнец     35000.00   400000.0             0.087500      35 000 €                             Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, с. Равнец - 10 дка / 35 000 € » 68 454.05 лв., АСАВИЯ :: imot.bg Обява 960948
159031  1s168130131217651                      https://www.imot.bg/obiava-1s168130131217651-prodava-zemedelska-zemya-oblast-burgas-gr-chernomorets   ЗЕМЕДЕЛСКА ЗЕМЯ     област Бургас                         област Бургас, гр. Черноморец    127500.00   400000.0             0.318750     127 500 €  Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Черноморец - 4 дка / 127 500 € » 249 368.33 лв., ХОУМ ЕНД БИЗНЕС КОНСУЛТ ООД :: imot.bg Обява 217651
159021  1s168061196976997                  https://www.imot.bg/obiava-1s168061196976997-prodava-zemedelska-zemya-oblast-burgas-gr-aheloy-m-bryasta   ЗЕМЕДЕЛСКА ЗЕМЯ     област Бургас                  област Бургас, гр. Ахелой, м. Бряста     13000.00   400000.0             0.032500      13 000 €                             Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Бургас, гр. Ахелой - 1 дка / 13 000 € » 25 425.79 лв., АСАВИЯ :: imot.bg Обява 976997
159051  1s168087671851211         https://www.imot.bg/obiava-1s168087671851211-prodava-zemedelska-zemya-oblast-kyustendil-s-bersin-aladzhin-mozhst   ЗЕМЕДЕЛСКА ЗЕМЯ  област Кюстендил            област Кюстендил, с. Берсин, Аладжин можст      8700.00   400000.0             0.021750       8 700 €                           Продава ЗЕМЕДЕЛСКА ЗЕМЯ в област Кюстендил, с. Берсин - 5.6 дка / 8 700 € » 17 015.72 лв., КАДЕМ :: imot.bg Обява 851211

[100 rows x 10 columns]

In [33]:
# ------------------------------------------------------------
# Step 3C: Segment large-area candidates by property type
# ------------------------------------------------------------

large_area_summary = (
    large_area_candidates
    .groupby("property_type_raw", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_area=("area_sqm", "min"),
        median_area=("area_sqm", "median"),
        max_area=("area_sqm", "max"),
        min_price=("total_price", "min"),
        median_price=("total_price", "median"),
        max_price=("total_price", "max"),
        median_ppsqm=("price_per_sqm_model", "median"),
        min_ppsqm=("price_per_sqm_model", "min"),
        max_ppsqm=("price_per_sqm_model", "max"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(large_area_summary)

   property_type_raw  rows   min_area  median_area   max_area   min_price  median_price    max_price  median_ppsqm  min_ppsqm    max_ppsqm
3    ЗЕМЕДЕЛСКА ЗЕМЯ   462    61000.0     180000.0   587623.0       31.00       66535.5  471195000.0      0.393501   0.000304  1140.907990
6             ПАРЦЕЛ   270    60006.0      89835.0  4854710.0     8691.96     1499992.5   40000000.0     13.195000   0.010329   485.714997
7    ПРОМ. ПОМЕЩЕНИЕ    17    61000.0      80000.0   150000.0    65000.00     1250000.0   15000000.0     18.939394   0.812500   109.489051
11             ФЕРМА     9    63000.0      87284.0   180000.0   385000.00     3800000.0    7160000.0     35.185185   5.500000    82.031071
8              СКЛАД     8    61000.0      63227.5    83000.0    70000.00     6000000.0   22000000.0     98.360656   0.843373   336.108777
10     ФАБРИКА/ЗАВОД     7    61000.0      66537.0   136000.0   820000.00     1200000.0    6000000.0     14.705882  12.000000    98.360656
9       СОЛАРЕН ПАРК     4    67261.0      78442.5   150000.0   450000.00      740000.0    1200000.0      6.693532   6.666667    14.083185
12             ХОТЕЛ     3    73000.0     353199.0   500000.0   950000.00     5000000.0    6500000.0     14.156325   1.900000    89.041096
1               ВИЛА     2   175000.0     175000.0   175000.0   540000.00      540000.0     540000.0      3.085714   3.085714     3.085714
4               КЪЩА     1   265000.0     265000.0   265000.0   265000.00      265000.0     265000.0      1.000000   1.000000     1.000000
2       ВИЛНО СЕЛИЩЕ     1   235000.0     235000.0   235000.0  1635344.00     1635344.0    1635344.0      6.958911   6.958911     6.958911
0         АВТОСЕРВИЗ     1    97000.0      97000.0    97000.0   511000.00      511000.0     511000.0      5.268041   5.268041     5.268041
5         ПАРКОМЯСТО     1  1000000.0    1000000.0  1000000.0    16000.00       16000.0      16000.0      0.016000   0.016000     0.016000

In [34]:
# Drop absurd large-area parking spot
before_rows = len(df_candidate)

drop_mask = df_candidate["ad_id"].eq("1o176373075998653")

dropped_large_parking = df_candidate.loc[drop_mask].copy()

df_candidate = df_candidate.loc[~drop_mask].copy()

after_rows = len(df_candidate)

print("Dropped rows:", before_rows - after_rows)
print("Candidate rows before:", before_rows)
print("Candidate rows after:", after_rows)

display(
    dropped_large_parking[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "total_price",
            "area_sqm",
            "price_per_sqm_model",
            "title",
        ]
    ]
)

cleanup_actions.append({
    "rule": "drop_absurd_large_parking_area",
    "reason": "Manually inspected ПАРКОМЯСТО listing has impossible 1,000,000 sqm area and is not valid for regression training",
    "rows_affected": len(dropped_large_parking),
})

Dropped rows: 1
Candidate rows before: 160541
Candidate rows after: 160540

                    ad_id                                                                                      ad_url property_type_raw title_city_raw        location_raw  total_price   area_sqm  price_per_sqm_model                                                                                                                     title
118483  1o176373075998653  https://www.imot.bg/obiava-1o176373075998653-prodava-garazh-parkomyasto-grad-varna-vinitsa        ПАРКОМЯСТО     град Варна  град Варна, Виница      16000.0  1000000.0                0.016  Продава ПАРКОМЯСТО в град Варна, Виница - 1000000 кв.м / 16 000 € » 31 293.28 лв., ХОЛДИНГ ГРУП  :: imot.bg Обява 998653

In [36]:
df_candidate.head(5)

,ad_id,ad_url,ad_url_path,ad_url_slug,html_path,listing_type,title,deal_raw,property_type_raw,title_city_raw,title_geo_2_raw,title_area_sqm,title_price_eur,title_price_bgn,seller_name_raw,title_ad_id,total_price,currency,price_raw,vat_status,area_sqm,area_raw,price_per_sqm,floor,total_floors,floor_raw,construction_raw,construction_type,construction_year,location_raw,description_raw,description_clean,features_raw,features_pipe,features_count,published_raw,views,training_eligible,parse_error,parsed_at,area_unit_suspected,area_sqm_corrected,price_per_sqm_corrected,area_sqm_original,price_per_sqm_original,price_per_sqm_recalc,price_per_sqm_diff_abs,price_per_sqm_diff_pct,price_per_sqm_model
0,1a129794411209548,https://www.imot.bg/obiava-1a129794411209548-prodava-ednostaen-apartament-oblast-blagoevgrad-gr-bansko,/obiava-1a129794411209548-prodava-ednostaen-apartament-oblast-blagoevgrad-gr-bansko,obiava-1a129794411209548-prodava-ednostaen-apartament-oblast-blagoevgrad-gr-bansko,data\raw_listing_html\2caac228937b3b30.html,single_property_listing,"Продава 1-СТАЕН в област Благоевград, гр. Банско - 35 кв.м / 36 000 € » 70 409.88 лв., ФОРОС-НАЦИОНАЛНА КОМПАНИЯ НЕДВИЖИМИ ИМОТИ-БАНСКО :: imot.bg Обява 209548",Продава,1-СТАЕН,област Благоевград,гр. Банско,35.0,36000.0,70409.88,ФОРОС-НАЦИОНАЛНА КОМПАНИЯ НЕДВИЖИМИ ИМОТИ-БАНСКО,209548.0,36000.0,EUR,36 000 €,no_vat,35.0,35 кв.м,1028.57,3.0,5.0,3-ти от 5,"Тухла, 2010",Тухла,2010,"област Благоевград, гр. Банско","Предлагаме студио 32 кв.м в сграда Никмар на ул. Явор. Разположено е на трети етаж. Състои се от дневна, баня с тоалетна и гардеробно помещение. Разположен на трети жилищен етаж. Студиото е обзаведено, не е поставен кухненски бокс, но има всички комуникации.\nСградата е много добре поддържана. Има асансьор.\nТакса поддръжка 250 евро/година.","Предлагаме студио 32 кв.м в сграда Никмар на ул. Явор. Разположено е на трети етаж. Състои се от дневна, баня с тоалетна и гардеробно помещение. Разположен на трети жилищен етаж. Студиото е обзаведено, не е поставен кухненски бокс, но има всички комуникации. Сградата е много добре поддържана. Има асансьор. Такса поддръжка 250 евро/година.",Тухла\nОбзаведен\nКонтрол на достъпа,Тухла|Обзаведен|Контрол на достъпа,3,None,5834.0,True,NaN,2026-05-16T13:50:20.885206+00:00,None,35.0,1028.57,NaN,NaN,1028.571429,0.001429,1.388889e-06,1028.571429
1,1a127539284802892,https://www.imot.bg/obiava-1a127539284802892-prodava-ednostaen-apartament-oblast-dobrich-gr-balchik,/obiava-1a127539284802892-prodava-ednostaen-apartament-oblast-dobrich-gr-balchik,obiava-1a127539284802892-prodava-ednostaen-apartament-oblast-dobrich-gr-balchik,data\raw_listing_html\857c7fd39ad302de.html,single_property_listing,"Продава 1-СТАЕН в област Добрич, гр. Балчик - 51 кв.м / 75 000 € » 146 687.25 лв., ВАРНА НОФ ПРОПЪРТИС :: imot.bg Обява 802892",Продава,1-СТАЕН,област Добрич,гр. Балчик,51.0,75000.0,146687.25,ВАРНА НОФ ПРОПЪРТИС,802892.0,75000.0,EUR,75 000 €,no_vat,51.0,51 кв.м,1470.59,3.0,5.0,3-ти от 5,"Тухла, 2008",Тухла,2008,"област Добрич, гр. Балчик","Балчик, комплекс 'Марина Сити'- луксозни апартаменти на брега на морето Прекрасно студио ситуирано на 4 етаж в комплекс 'Марина сити'. Състои се от една голяма стая, където е кухнята и спалнята, тераса с частичен изглед към морето. Баня с душ. Комплекс МАРИНА СИТИ се намира на 38 км северно от морската столица на България Варна. Морският климат предлага топло слънчево лято със свежи прохладни вечери, което продължава чак до края на септември. Перфектното местоположение на комплекса го прави лесен за достигане, както по земя и по вода, така и по въздух.","Балчик, комплекс 'Марина Сити'- луксозни апартаменти на брега на морето Прекрасно студио ситуирано на 4 етаж в комплекс 'Марина сити'. Състои се от една голяма стая, където е кухнята и спалнята, тераса с частичен изглед към морето. Баня с душ. Комплекс МАРИНА СИТИ се намира на 38 км северно от морската столица на България Варна. Морският климат предлага топло слънчево лято със свежи прохладни вечери, което продължава чак до края на септември. Перфектното местоположение на комплекса го прави лесен за достигане, както по земя и по вода, така и по въздух.",Тухла\nАсансьор\nИнтернет връзка\nОбзаведен\nВидео наблюдение\nКонтрол на достъпа\nОхрана\nВ затворен комплекс,Тухла|Асансьор|Интернет връзка|Обзаведен|Видео наблюдение|Контрол на достъпа|Охрана|В затворен комплекс,8,None,2391.0,True,NaN,2026-05-16T13:50:20.903929+00:00,None,51.0,1470.59,NaN,NaN,1470.588235,0.001765,1.200000e-06,1470.588235
2,1a126881929164804,https://www.imot.bg/obiava-1a126881929164804-prodava-ednostaen-apartament-grad-pleven-druzhba-1-bivshiyat-bikarnik,/obiava-1a126881929164804-prodava-ednostaen-apartament-grad-pleven-druzhba-1-bivshiyat-bikarnik,obiava-1a126881929164804-prodava-ednostaen-apartament-grad-pleven-druzhba-1-bivshiyat-bikarnik,data\raw_listing_html\9208ce061d053c01.html,single_property_listing,"Продава 1-СТАЕН в град Плевен, Дружба 1 - 40 кв.м / 53 500 € » 104 636.91 лв., САНЯ :: imot.bg Обява 164804",Продава,1-СТАЕН,град Плевен,Дружба 1,40.0,53500.0,104636.91,САНЯ,164804.0,53500.0,EUR,53 500 €,no_vat,40.0,40 кв.м,1337.50,4.0,8.0,4-ти от 8,"Панел, 2026",Панел,2026,"град Плевен, Дружба 1, Бившият Бикарник","Продава гарсониера след ремонт- стая, кухня, баня с тоалетна и тераса.Стаите са на паркет, коридор и кухня - теракота,сменена дограма,нова баня-0878836233","Продава гарсониера след ремонт- стая, кухня, баня с тоалетна и тераса.Стаите са на паркет, коридор и кухня - теракота,сменена дограма,нова баня-0878836233",Панел,Панел,1,None,6579.0,True,NaN,2026-05-16T13:50:21.030575+00:00,None,40.0,1337.50,NaN,NaN,1337.500000,0.000000,0.000000e+00,1337.500000
3,1a130799086731769,https://www.imot.bg/obiava-1a130799086731769-prodava-ednostaen-apartament-grad-pleven-druzhba-4,/obiava-1a130799086731769-prodava-ednostaen-apartament-grad-pleven-druzhba-4,obiava-1a130799086731769-prodava-ednostaen-apartament-grad-pleven-druzhba-4,data\raw_listing_html\ad1172ee3bcfaaed.html,single_property_listing,"Продава 1-СТАЕН в град Плевен, Дружба 4 - 40 кв.м / 52 000 € » 101 703.16 лв., САНЯ :: imot.bg Обява 731769",Продава,1-СТАЕН,град Плевен,Дружба 4,40.0,52000.0,101703.16,САНЯ,731769.0,52000.0,EUR,52 000 €,no_vat,40.0,40 кв.м,1300.00,8.0,8.0,8-ми от 8,"Панел, 1970",Панел,1970,"град Плевен, Дружба 4","Продава гарсониера след ремонт, с ПВС дограма, ламинат в много добро състояние.За оглед- 0878836233","Продава гарсониера след ремонт, с ПВС дограма, ламинат в много добро състояние.За оглед- 0878836233",Панел\nАсансьор,Панел|Асансьор,2,None,4282.0,True,NaN,2026-05-16T13:50:21.051889+00:00,None,40.0,1300.00,NaN,NaN,1300.000000,0.000000,0.000000e+00,1300.000000
4,1a140309247069043,https://www.imot.bg/obiava-1a140309247069043-prodava-ednostaen-apartament-oblast-veliko-tarnovo-gr-gorna-oryahovitsa-kv-prolet,/obiava-1a140309247069043-prodava-ednostaen-apartament-oblast-veliko-tarnovo-gr-gorna-oryahovitsa-kv-prolet,obiava-1a140309247069043-prodava-ednostaen-apartament-oblast-veliko-tarnovo-gr-gorna-oryahovitsa-kv-prolet,data\raw_listing_html\733a85c00c43835a.html,single_property_listing,"Продава 1-СТАЕН в област Велико Търново, гр. Горна Оряховица - 42 кв.м / При запитване, ТАРА КОНСУЛТ :: imot.bg Обява 069043",Продава,1-СТАЕН,област Велико Търново,гр. Горна Оряховица,42.0,NaN,NaN,None,69043.0,49450.0,EUR,49 450 €,unknown,42.0,42 кв.м,1177.38,1.0,6.0,1-ви от 6,"Панел, 2026",Панел,2026,"област Велико Търново, гр. Горна Оряховица, кв.Пролет",ПАНЕЛНА ГАСОНИЕРА---КУПУВАМЕ СПЕШНО.ПЛАЩТАНЕ В БРОЙ.,ПАНЕЛНА ГАСОНИЕРА---КУПУВАМЕ СПЕШНО.ПЛАЩТАНЕ В БРОЙ.,Панел\nС преход\nАсансьор\nС гараж\nС паркинг\nЛизинг\nБартер\nИнтернет връзка\nС действащ бизнес\nОбзаведен\nВидео наблюдение\nКонтрол на достъпа\nОхрана\nСаниран,Панел|С преход|Асансьор|С гараж|С паркинг|Лизинг|Бартер|Интернет връзка|С действащ бизнес|Обзаведен|Видео наблюдение|Контрол на достъпа|Охрана|Саниран,14,None,3.0,True,NaN,2026-05-16T13:50:24.307483+00:00,None,42.0,1177.38,NaN,NaN,1177.380952,0.000952,8.088979e-07,1177.380952

In [37]:
# ------------------------------------------------------------
# Drop irrelevant / raw / debug columns for ML working dataset
# Keep features_pipe for later feature engineering
# ------------------------------------------------------------

before_cols = df_candidate.shape[1]

irrelevant_columns = [
    # identifiers / technical tracking
    "ad_url_path",
    "ad_url_slug",
    "html_path",
    "title_ad_id",
    "parse_error",
    "parsed_at",

    # raw text fields not ready for structured regression
    "title",
    "description_raw",
    "description_clean",
    "features_raw",

    # duplicate / raw fields after structured parsing
    "deal_raw",
    "price_raw",
    "area_raw",
    "floor_raw",
    "construction_raw",

    # redundant price fields
    "title_price_eur",
    "title_price_bgn",

    # not needed after filtering candidate set
    "training_eligible",
]

columns_to_drop = [
    col for col in irrelevant_columns
    if col in df_candidate.columns
]

df_model_base = df_candidate.drop(columns=columns_to_drop).copy()

after_cols = df_model_base.shape[1]

print("Rows:", len(df_model_base))
print("Columns before:", before_cols)
print("Columns dropped:", len(columns_to_drop))
print("Columns after:", after_cols)

print("\nDropped columns:")
print(columns_to_drop)

print("\nRemaining columns:")
print(df_model_base.columns.tolist())

cleanup_actions.append({
    "rule": "drop_irrelevant_raw_debug_columns",
    "reason": "Removed raw parser fields, redundant fields, technical tracking fields, and text columns not yet prepared for structured regression; kept features_pipe for later feature engineering",
    "rows_affected": 0,
    "columns_affected": len(columns_to_drop),
})

Rows: 160540
Columns before: 49
Columns dropped: 18
Columns after: 31

Dropped columns:
['ad_url_path', 'ad_url_slug', 'html_path', 'title_ad_id', 'parse_error', 'parsed_at', 'title', 'description_raw', 'description_clean', 'features_raw', 'deal_raw', 'price_raw', 'area_raw', 'floor_raw', 'construction_raw', 'title_price_eur', 'title_price_bgn', 'training_eligible']

Remaining columns:
['ad_id', 'ad_url', 'listing_type', 'property_type_raw', 'title_city_raw', 'title_geo_2_raw', 'title_area_sqm', 'seller_name_raw', 'total_price', 'currency', 'vat_status', 'area_sqm', 'price_per_sqm', 'floor', 'total_floors', 'construction_type', 'construction_year', 'location_raw', 'features_pipe', 'features_count', 'published_raw', 'views', 'area_unit_suspected', 'area_sqm_corrected', 'price_per_sqm_corrected', 'area_sqm_original', 'price_per_sqm_original', 'price_per_sqm_recalc', 'price_per_sqm_diff_abs', 'price_per_sqm_diff_pct', 'price_per_sqm_model']

In [39]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160540 entries, 0 to 163846
Data columns (total 31 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    160540 non-null  object
 1   ad_url                   160540 non-null  object
 2   listing_type             160540 non-null  object
 3   property_type_raw        160540 non-null  object
 4   title_city_raw           160540 non-null  object
 5   title_geo_2_raw          160537 non-null  object
 6   title_area_sqm           158305 non-null  float64
 7   seller_name_raw          150524 non-null  object
 8   total_price              160540 non-null  float64
 9   currency                 160540 non-null  object
 10  vat_status               160540 non-null  object
 11  area_sqm                 160540 non-null  float64
 12  price_per_sqm            160540 non-null  float64
 13  floor                    97936 non-null   float64
 14  total_floors             90818 non-null   float64
 15  construction_type        121597 non-null  object
 16  construction_year        160540 non-null  int64
 17  location_raw             160540 non-null  object
 18  features_pipe            140622 non-null  object
 19  features_count           160540 non-null  int64
 20  published_raw            42521 non-null   object
 21  views                    160540 non-null  float64
 22  area_unit_suspected      176 non-null     object
 23  area_sqm_corrected       160540 non-null  float64
 24  price_per_sqm_corrected  160540 non-null  float64
 25  area_sqm_original        561 non-null     float64
 26  price_per_sqm_original   561 non-null     float64
 27  price_per_sqm_recalc     160540 non-null  float64
 28  price_per_sqm_diff_abs   160540 non-null  float64
 29  price_per_sqm_diff_pct   160540 non-null  float64
 30  price_per_sqm_model      160540 non-null  float64
dtypes: float64(15), int64(2), object(14)
memory usage: 39.2+ MB

In [40]:
# ------------------------------------------------------------
# Finalize corrected area / price fields for ML base dataset
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

# Preserve original scraped values only in df_candidate, not in ML base.
diagnostic_columns = [
    "area_unit_suspected",
    "area_sqm_original",
    "price_per_sqm_original",
    "price_per_sqm_recalc",
    "price_per_sqm_diff_abs",
    "price_per_sqm_diff_pct",
    "price_per_sqm_model",
]

columns_to_drop = [
    col for col in diagnostic_columns
    if col in df_model_base.columns
]

df_model_base = df_model_base.drop(columns=columns_to_drop)

# Replace raw area/price_per_sqm with corrected modeling versions
df_model_base["area_sqm_raw"] = df_model_base["area_sqm"]
df_model_base["price_per_sqm_raw"] = df_model_base["price_per_sqm"]

df_model_base["area_sqm"] = df_model_base["area_sqm_corrected"]
df_model_base["price_per_sqm"] = df_model_base["price_per_sqm_corrected"]

df_model_base = df_model_base.drop(
    columns=[
        "area_sqm_corrected",
        "price_per_sqm_corrected",
    ]
)

print("Rows:", len(df_model_base))
print("Columns:", df_model_base.shape[1])
print("Dropped diagnostic columns:", columns_to_drop)

display(df_model_base.info())

cleanup_actions.append({
    "rule": "finalize_corrected_area_price_fields",
    "reason": "Replaced raw area and price-per-sqm with corrected modeling fields and removed diagnostic cleanup columns",
    "rows_affected": 0,
    "columns_affected": len(columns_to_drop),
})

Rows: 160540
Columns: 24
Dropped diagnostic columns: ['area_unit_suspected', 'area_sqm_original', 'price_per_sqm_original', 'price_per_sqm_recalc', 'price_per_sqm_diff_abs', 'price_per_sqm_diff_pct', 'price_per_sqm_model']
<class 'pandas.core.frame.DataFrame'>
Index: 160540 entries, 0 to 163846
Data columns (total 24 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              160540 non-null  object
 1   ad_url             160540 non-null  object
 2   listing_type       160540 non-null  object
 3   property_type_raw  160540 non-null  object
 4   title_city_raw     160540 non-null  object
 5   title_geo_2_raw    160537 non-null  object
 6   title_area_sqm     158305 non-null  float64
 7   seller_name_raw    150524 non-null  object
 8   total_price        160540 non-null  float64
 9   currency           160540 non-null  object
 10  vat_status         160540 non-null  object
 11  area_sqm           160540 non-null  float64
 12  price_per_sqm      160540 non-null  float64
 13  floor              97936 non-null   float64
 14  total_floors       90818 non-null   float64
 15  construction_type  121597 non-null  object
 16  construction_year  160540 non-null  int64
 17  location_raw       160540 non-null  object
 18  features_pipe      140622 non-null  object
 19  features_count     160540 non-null  int64
 20  published_raw      42521 non-null   object
 21  views              160540 non-null  float64
 22  area_sqm_raw       160540 non-null  float64
 23  price_per_sqm_raw  160540 non-null  float64
dtypes: float64(9), int64(2), object(13)
memory usage: 30.6+ MB

None

In [41]:
df_model_base.title_city_raw.value_counts()

title_city_raw
град София               34452
област Бургас            17875
град Варна               17606
град Пловдив             17162
област Пловдив            7792
област София              5025
град Бургас               4486
област Велико Търново     3821
област Варна              3742
област Добрич             3444
град Стара Загора         3386
град Русе                 3116
град Плевен               2761
град Шумен                2760
област Благоевград        2657
област Стара Загора       2053
град Велико Търново       2029
област Пазарджик          1963
област Перник             1638
област Габрово            1620
област Ловеч              1619
град Кърджали             1271
град Перник               1259
област Шумен              1124
Гърция                    1074
област Русе               1055
област Плевен             1026
град Враца                 962
област Кюстендил           883
област Хасково             853
град Пазарджик             832
област Смолян              804
град Габрово               778
град Благоевград           746
град Добрич                725
град Хасково               705
град Търговище             584
област Враца               539
област Кърджали            537
област Монтана             342
град Разград               332
град Монтана               324
град Видин                 298
град Ловеч                 280
град Сливен                264
област Видин               259
област Търговище           238
област Ямбол               229
град Ямбол                 207
област Сливен              201
град Смолян                199
град Кюстендил             193
област Разград             159
област Силистра            154
град Силистра               97
Name: count, dtype: int64

In [42]:
df_model_base.title_geo_2_raw.value_counts()

title_geo_2_raw
Център               10676
к.к. Слънчев бряг     2936
гр. Свети Влас        2525
Христо Смирненски     2386
Малинова долина       2276
                     ...
гр. Сливен               1
с. Вельово               1
с. Шишковица             1
с. Кавракирово           1
с. Паисиево              1
Name: count, Length: 3620, dtype: int64

In [43]:
# Inspect current geo fields before any mapping
geo_inspect = df_model_base[
    [
        "title_city_raw",
        "title_geo_2_raw",
        "location_raw",
    ]
].copy()

print("Unique title_city_raw:", geo_inspect["title_city_raw"].nunique(dropna=False))
print("Unique title_geo_2_raw:", geo_inspect["title_geo_2_raw"].nunique(dropna=False))
print("Unique location_raw:", geo_inspect["location_raw"].nunique(dropna=False))

print("\nTop cities:")
display(
    geo_inspect["title_city_raw"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
)

print("\nTop geo_2:")
display(
    geo_inspect["title_geo_2_raw"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("title_geo_2_raw")
    .reset_index(name="rows")
)

print("\nSample location_raw:")
display(
    geo_inspect["location_raw"]
    .dropna()
    .sample(30, random_state=42)
    .reset_index(drop=True)
)

Unique title_city_raw: 55
Unique title_geo_2_raw: 3621
Unique location_raw: 16552

Top cities:

           title_city_raw   rows
0              град София  34452
1           област Бургас  17875
2              град Варна  17606
3            град Пловдив  17162
4          област Пловдив   7792
5            област София   5025
6             град Бургас   4486
7   област Велико Търново   3821
8            област Варна   3742
9           област Добрич   3444
10      град Стара Загора   3386
11              град Русе   3116
12            град Плевен   2761
13             град Шумен   2760
14     област Благоевград   2657
15    област Стара Загора   2053
16    град Велико Търново   2029
17       област Пазарджик   1963
18          област Перник   1638
19         област Габрово   1620
20           област Ловеч   1619
21          град Кърджали   1271
22            град Перник   1259
23           област Шумен   1124
24                 Гърция   1074
25            област Русе   1055
26          област Плевен   1026
27             град Враца    962
28       област Кюстендил    883
29         област Хасково    853

Top geo_2:

          title_geo_2_raw   rows
0                  Център  10676
1       к.к. Слънчев бряг   2936
2          гр. Свети Влас   2525
3       Христо Смирненски   2386
4         Малинова долина   2276
5                Кършияка   2271
6                  Тракия   2155
7             гр. Созопол   1842
8               Остромила   1684
9      Манастирски ливади   1605
10            Кючук Париж   1567
11            гр. Поморие   1553
12                 Виница   1378
13           Широк център   1363
14          Кръстова вада   1358
15             гр. Банско   1299
16                 Витоша   1205
17        Промишлена зона   1128
18             Овча купел   1077
19            гр. Несебър    982
20                 Изгрев    977
21               с. Равда    975
22                  Бояна    960
23             гр. Балчик    931
24                   Бриз    929
25             Беломорски    878
26         Идеален център    874
27      Индустриална зона    866
28              гр. Банкя    834
29  Владислав Варненчик 1    808
30               гр. Бяла    796
31             с. Марково    784
32             гр. Царево    772
33               Дружба 2    752
34                Лозенец    746
35          гр. Приморско    728
36       Кайсиева градина    725
37             Аспарухово    723
38         гр. Асеновград    717
39             Драгалевци    714
40        Студентски град    711
41           Меден рудник    704
42              Младост 4    672
43               с. Лозен    655
44                   Южен    654
45               Дружба 1    653
46                  Изток    648
47               Сарафово    641
48              Младост 1    639
49                Гагарин    616

Sample location_raw:

0                      град София, Малинова долина
1                        град Шумен, Томбул джамия
2                    област Бургас, гр. Свети Влас
3                     област Пловдив, с. Калояново
4                              град Добрич, Център
5     град София, Манастирски ливади, ул. Луи Айер
6                              град София, Люлин 3
7                      град Ямбол, Промишлена зона
8                              град София, Оборище
9                  град Стара Загора, Кольо Ганчев
10                             град Бургас, Център
11                         град София, Гевгелийски
12              област Велико Търново, с. Кесарево
13                       град София, м-т Камбаните
14                   град Велико Търново, Бузлуджа
15                         област Русе, с. Иваново
16                             град София, Люлин 8
17                   град Шумен, Боян Българанов 2
18          град София, Гоце Делчев, бул. България
19                       област Габрово, с. Шумата
20                      град Варна, Цветен квартал
21                       област Добрич, с. Кранево
22             град Видин, Промишлена зона - Запад
23       област Плевен, гр. Долни Дъбник, Брестака
24                        област София, гр. Правец
25                         град Варна, м-т Пчелина
26                      област Бургас, гр. Поморие
27                              град Варна, Център
28                          град София, Орландовци
29                            град София, Дружба 2
Name: location_raw, dtype: object

In [44]:
# ------------------------------------------------------------
# Step: Split location_raw into hierarchical location levels
# No dropping, no bucketing yet
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

location_parts = (
    df_model_base["location_raw"]
    .fillna("")
    .astype(str)
    .str.split(",", expand=True)
)

df_model_base["location_level_1"] = location_parts[0].str.strip()
df_model_base["location_level_2"] = location_parts[1].str.strip() if location_parts.shape[1] > 1 else None
df_model_base["location_level_3"] = location_parts[2].str.strip() if location_parts.shape[1] > 2 else None

for col in ["location_level_1", "location_level_2", "location_level_3"]:
    df_model_base[col] = df_model_base[col].replace({"": None, "nan": None, "None": None})

print("Unique location_level_1:", df_model_base["location_level_1"].nunique(dropna=False))
print("Unique location_level_2:", df_model_base["location_level_2"].nunique(dropna=False))
print("Unique location_level_3:", df_model_base["location_level_3"].nunique(dropna=False))

print("\nTop level 1:")
display(
    df_model_base["location_level_1"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("location_level_1")
    .reset_index(name="rows")
)

print("\nTop level 2:")
display(
    df_model_base["location_level_2"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2")
    .reset_index(name="rows")
)

print("\nTop level 3:")
display(
    df_model_base["location_level_3"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_3")
    .reset_index(name="rows")
)

Unique location_level_1: 262
Unique location_level_2: 3806
Unique location_level_3: 9777

Top level 1:

         location_level_1   rows
0              град София  34409
1           област Бургас  17790
2              град Варна  17578
3            град Пловдив  17158
4          област Пловдив   7785
5            област София   5017
6             град Бургас   4482
7   област Велико Търново   3819
8            област Варна   3737
9           област Добрич   3443
10      град Стара Загора   3319
11              град Русе   3116
12            град Плевен   2761
13             град Шумен   2747
14     област Благоевград   2655
15    област Стара Загора   2043
16    град Велико Търново   2029
17       област Пазарджик   1958
18          област Перник   1636
19         област Габрово   1619
20           област Ловеч   1615
21          град Кърджали   1271
22            град Перник   1257
23           област Шумен   1121
24                 Гърция   1073
25            област Русе   1054
26          област Плевен   1026
27             град Враца    962
28       област Кюстендил    882
29         област Хасково    851

Top level 2:

         location_level_2   rows
0                  Център  10654
1       к.к. Слънчев бряг   2912
2          гр. Свети Влас   2500
3       Христо Смирненски   2386
4         Малинова долина   2276
5                Кършияка   2271
6                  Тракия   2155
7             гр. Созопол   1836
8               Остромила   1682
9      Манастирски ливади   1605
10            Кючук Париж   1567
11            гр. Поморие   1549
12                 Виница   1370
13           Широк център   1361
14          Кръстова вада   1357
15             гр. Банско   1299
16                 Витоша   1205
17             Овча купел   1072
18                 Изгрев    977
19            гр. Несебър    977
20               с. Равда    968
21                  Бояна    958
22             гр. Балчик    931
23                   Бриз    929
24             Беломорски    878
25         Идеален център    872
26              гр. Банкя    833
27  Владислав Варненчик 1    805
28               гр. Бяла    795
29             с. Марково    782
30             гр. Царево    772
31               Дружба 2    752
32                Лозенец    744
33       Кайсиева градина    725
34             Аспарухово    723
35          гр. Приморско    722
36         гр. Асеновград    717
37             Драгалевци    714
38        Студентски град    711
39              Младост 4    672
40               с. Лозен    655
41                   Южен    653
42               Дружба 1    653
43                  Изток    648
44               Сарафово    641
45              Младост 1    639
46                Гагарин    616
47               Банишора    609
48            с. Кошарица    595
49          гр. Велинград    584

Top level 3:

             location_level_3    rows
0                        None  135623
1                      Център     499
2                      център     258
3       бул. Симеоновско шосе     157
4             бул. Черни връх     130
5                 Гребна база     121
6                     Гагарин     109
7        ул. Околовръстен път     102
8                        Южен     101
9                      Пощата      98
10                  Остромила      98
11              бул. България      90
12                бул. 'Южен'      90
13                        ВМИ      88
14     бул. Ботевградско шосе      79
15                      центр      78
16                    ул. Рая      77
17           бул. Иван Иванов      73
18            Коматевско шосе      72
19      бул. Ал. Стамболийски      70
20         бул. Цар Борис III      69
21              бул. Сливница      68
22           Коматевски възел      64
23             ул. Монтевидео      64
24                    Кабакум      63
25                  бул. Южен      62
26               ул. Луи Айер      58
27          ул. Димитър Пешев      57
28                     ЦЕНТЪР      57
29                бул. Витоша      56
30               ул. Обиколна      55
31  бул. Св. Климент Охридски      53
32                бул. Европа      53
33                   Герджика      52
34        бул.  3-ти март  54      52
35           бул. Ломско шосе      52
36             Идеален център      51
37                   Нов град      51
38                   Общината      50
39  бул. Проф. Цветан Лазаров      49
40            Автогара Родопи      49
41             ул. Цар Симеон      49
42    бул. Александър Малинов      49
43               Широк център      48
44              кв. Михайлово      46
45                  улица Рая      46
46                     Пазара      45
47           х-л Ст.Петербург      45
48                  м. Мисаря      45
49          ул. Георги Райчев      44

In [45]:
# ------------------------------------------------------------
# Normalize location levels lightly
# Keep it conservative: strip whitespace and lowercase only for model versions
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

for col in ["location_level_1", "location_level_2", "location_level_3"]:
    model_col = f"{col}_model"
    
    df_model_base[model_col] = (
        df_model_base[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

    df_model_base[model_col] = df_model_base[model_col].replace(
        {
            "": pd.NA,
            "none": pd.NA,
            "nan": pd.NA,
        }
    )

print("Unique location_level_1_model:", df_model_base["location_level_1_model"].nunique(dropna=False))
print("Unique location_level_2_model:", df_model_base["location_level_2_model"].nunique(dropna=False))
print("Unique location_level_3_model:", df_model_base["location_level_3_model"].nunique(dropna=False))

print("\nTop location_level_1_model:")
display(
    df_model_base["location_level_1_model"]
    .value_counts(dropna=False)
    .head(30)
    .rename_axis("location_level_1_model")
    .reset_index(name="rows")
)

print("\nTop location_level_2_model:")
display(
    df_model_base["location_level_2_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2_model")
    .reset_index(name="rows")
)

Unique location_level_1_model: 261
Unique location_level_2_model: 3803
Unique location_level_3_model: 8929

Top location_level_1_model:

   location_level_1_model   rows
0              град софия  34409
1           област бургас  17790
2              град варна  17578
3            град пловдив  17158
4          област пловдив   7785
5            област софия   5017
6             град бургас   4482
7   област велико търново   3819
8            област варна   3737
9           област добрич   3443
10      град стара загора   3319
11              град русе   3116
12            град плевен   2761
13             град шумен   2747
14     област благоевград   2655
15    област стара загора   2043
16    град велико търново   2029
17       област пазарджик   1958
18          област перник   1636
19         област габрово   1619
20           област ловеч   1615
21          град кърджали   1271
22            град перник   1257
23           област шумен   1121
24                 гърция   1073
25            област русе   1054
26          област плевен   1026
27             град враца    962
28       област кюстендил    882
29         област хасково    851

Top location_level_2_model:

   location_level_2_model   rows
0                  център  10654
1       к.к. слънчев бряг   2912
2          гр. свети влас   2500
3       христо смирненски   2386
4         малинова долина   2276
5                кършияка   2271
6                  тракия   2155
7             гр. созопол   1836
8               остромила   1682
9      манастирски ливади   1605
10            кючук париж   1567
11            гр. поморие   1549
12                 виница   1370
13           широк център   1361
14          кръстова вада   1357
15             гр. банско   1299
16                 витоша   1205
17             овча купел   1072
18            гр. несебър    977
19                 изгрев    977
20               с. равда    968
21                  бояна    958
22             гр. балчик    931
23                   бриз    929
24             беломорски    878
25         идеален център    872
26              гр. банкя    833
27  владислав варненчик 1    805
28               гр. бяла    795
29             с. марково    782
30             гр. царево    772
31               дружба 2    752
32                лозенец    744
33       кайсиева градина    725
34             аспарухово    723
35          гр. приморско    722
36         гр. асеновград    717
37             драгалевци    714
38        студентски град    711
39              младост 4    672
40               с. лозен    655
41               дружба 1    653
42                   южен    653
43                  изток    648
44               сарафово    641
45              младост 1    639
46                гагарин    616
47               банишора    609
48            с. кошарица    595
49          гр. велинград    584

In [46]:
# ------------------------------------------------------------
# Create interpretable geo category bucket
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

capital_center_areas = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}

large_regional_cities = {
    "град пловдив",
    "град варна",
    "град бургас",
}

regional_cities = {
    "град русе",
    "град стара загора",
    "град плевен",
    "град велико търново",
    "град шумен",
    "град добрич",
    "град сливен",
    "град хасково",
    "град ямбол",
    "град перник",
    "град благоевград",
    "град пазарджик",
    "град врачa",
    "град враца",
    "град габрово",
    "град кърджали",
    "град кюстендил",
    "град ловеч",
    "град монтана",
    "град разград",
    "град силистра",
    "град смолян",
    "град търговище",
    "град видин",
}

sea_resorts = {
    "свети влас",
    "слънчев бряг",
    "несебър",
    "поморие",
    "равда",
    "созопол",
    "черноморец",
    "приморско",
    "китен",
    "лозенец",
    "царево",
    "ахтопол",
    "обзор",
    "бяла",
    "златни пясъци",
    "св. св. константин и елена",
    "св. константин",
    "кабакум",
    "албена",
    "кранево",
    "балчик",
    "кавaрна",
    "каварна",
    "шкорпиловци",
    "синеморец",
    "дюни",
    "еленѝте",
    "елените",
}

mountain_resorts = {
    "банско",
    "разлог",
    "добринище",
    "боровец",
    "самоков",
    "пампорово",
    "чепеларе",
    "смолян",
    "велинград",
    "сапарева баня",
    "трявна",
    "априлци",
    "троян",
}


def map_geo_category(row):
    level_1 = row.get("location_level_1_model")
    level_2 = row.get("location_level_2_model")

    level_1 = "" if pd.isna(level_1) else str(level_1).strip().lower()
    level_2 = "" if pd.isna(level_2) else str(level_2).strip().lower()

    # 1/2. Sofia split into center vs non-center
    if level_1 == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # 5. Sea resort: check both levels
    if level_1 in sea_resorts or level_2 in sea_resorts:
        return "sea_resort"

    # 6. Mountain resort: check both levels
    if level_1 in mountain_resorts or level_2 in mountain_resorts:
        return "mountain_resort"

    # 3. Large regional city
    if level_1 in large_regional_cities:
        return "large_regional_city"

    # 4. Regional city
    if level_1 in regional_cities:
        return "regional_city"

    # 8. Village / settlement under oblast
    if level_1.startswith("област ") and (
        level_2.startswith("с. ")
        or level_2.startswith("село ")
    ):
        return "village"

    # 7. Smaller city/town under oblast
    if level_1.startswith("област ") and (
        level_2.startswith("гр. ")
        or level_2.startswith("град ")
    ):
        return "small_city"

    # 7. Other city
    if level_1.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nGeo category by property type:")
display(
    pd.crosstab(
        df_model_base["geo_category"],
        df_model_base["property_type_raw"],
        margins=True
    )
)

cleanup_actions.append({
    "rule": "create_geo_category_bucket",
    "reason": "Mapped hierarchical location fields into interpretable market-location buckets for regression modeling",
    "rows_affected": 0,
    "columns_added": 1,
})

Geo category distribution:

          geo_category   rows
0  large_regional_city  39218
1              village  31330
2   capital_non_center  28984
3           small_city  26264
4        regional_city  23934
5       capital_center   5425
6        other_unknown   5305
7      mountain_resort     76
8           sea_resort      4

Geo category by property type:

property_type_raw    1-СТАЕН  2-СТАЕН  3-СТАЕН  4-СТАЕН  АВТОМИВКА  АВТОСЕРВИЗ  АКВАПАРК  АПТЕКА  АТЕЛИЕ, ТАВАН  БАНКОВ ОФИС  БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ  ВИЛА  ВИЛНО СЕЛИЩЕ  ГАРАЖ  ГАРАЖ, ПАРКОМЯСТО  ДЕТСКИ ЦЕНТЪР  ДОМ ЗА ВЪЗРАСТНИ ХОРА  ЕТАЖ ОТ КЪЩА  ЗАВЕДЕНИЕ  ЗЕМЕДЕЛСКА ЗЕМЯ  КЛИНИКА   КЪЩА  ЛЕКАРСКИ КАБИНЕТ  МАГАЗИН  МЕЗОНЕТ  МНОГОСТАЕН  ОФИС  ПАРКИНГ  ПАРКОМЯСТО  ПАРЦЕЛ  ПРОМ. ПОМЕЩЕНИЕ  САМОСТОЯТЕЛНА СГРАДА  СКЛАД  СОЛАРЕН ПАРК  СПА/СОЛАРНО СТУДИО  СТОМАТОЛОГИЧЕН КАБИНЕТ  ТЪРГОВСКИ КОМПЛЕКС  ФАБРИКА/ЗАВОД  ФЕРМА  ФИТНЕС ЗАЛА  ФОТОГРАФСКО СТУДИО  ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН  ХЛАДИЛЕН СКЛАД  ХОТЕЛ     All
geo_category
capital_center           132     1274     1901      475          0           0         0       0             19            5                          0     1             0     70                  0              2                      0            32         98                0       13     92                 5      292       99         332   322        0          42     119               10                    29      8             0                   6                       4                  10              0      0            8                   0                           13               0     12    5425
capital_non_center       803     6637     8402     1674          0           8         1       5             53            5                          1    16             5    300                  3             17                      4           142        138                0       25   1712                 8      641      367         685   605        1         157    6169              116                    71     95             3                   4                       6                  20             17      3           28                   0                           17               0     20   28984
large_regional_city     1276    13504    12187     1435          5           5         2       9             21            5                          1    46             3    428                  4              2                      3           306        223                1       16   2150                18      888      351         920   715        0         391    3770              166                    45    135             2                  12                       9                  16             12      1           12                   1                           28               0     94   39218
mountain_resort            2       12       18        8          0           0         0       0              0            0                          0     0             0      2                  0              0                      0             2          1                0        0     10                 0        0        0           5     1        0           1      10                0                     0      2             0                   0                       0                   0              0      0            0                   0                            0               0      2      76
other_unknown            885     1325     1077       93          0           0         1       0              6            1                          3   218            11      4                  0              0                      0             5         39                9        0    539                 0       52       98          46    20        1          11     757                4                     7      6             2                   2                       0                   5              3      0            1                   0                            0               0     74    5305
regional_city            701     4470     5886     1059          3          36         0       4             68            2                         13   354             4    623                 26              6                      1           727        298                7       12   1757                22     1082      229         668   555        3         132    3935              638                    89    249             3                   9                       8                  60             69      3           23                   0                           32               2     66   23934
sea_resort                 0        1        0        0          0           0         0       0              0            0                          0     0             0      0                  0              0                      0             0          0                0        0      1                 0        1        0           0     1        0           0       0                0                     0      0             0                   0                       0                   0              0      0            0                   0                            0               0      0       4
small_city              1900     5519     3327      461          3          13         3       3             19            6                         11   207            27     75                  5              2                      7           534        178              842        4   4186                 8      355      197         387   148        5          23    6407              486                   115    140            18                   9                       0                  56             94     39            6                   0                            9               1    429   26264
village                  320      951      644       53          0          14         2       1              2            0                         13   348            43      2                  1              2                     15           103        107             1376        0  11742                 0      123       41          29    13        8           1   14055              558                   105    132            34                   1                       0                  44             54     97            0                   0                            0               1    295   31330
All                     6019    33693    33442     5258         11          76         9      22            188           24                         42  1190            93   1504                 39             31                     30          1851       1082             2235       70  22189                61     3434     1382        3072  2380       18         758   35222             1978                   461    767            62                  43                      27                 211            249    143           78                   1                           99               4    992  160540

In [47]:
# ------------------------------------------------------------
# Improved geo category mapping with settlement prefix normalization
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

def normalize_settlement_name(value):
    if pd.isna(value):
        return ""

    value = str(value).strip().lower()
    value = value.replace("ё", "е")
    value = value.replace("̀", "")
    value = value.replace("'", "")
    value = value.replace('"', "")
    value = " ".join(value.split())

    prefixes = [
        "гр. ",
        "град ",
        "с. ",
        "село ",
        "к.к. ",
        "кк ",
        "курорт ",
        "в.з. ",
        "м-т ",
        "м. ",
        "местност ",
    ]

    changed = True
    while changed:
        changed = False
        for prefix in prefixes:
            if value.startswith(prefix):
                value = value[len(prefix):].strip()
                changed = True

    return value


df_model_base["location_level_1_norm"] = df_model_base["location_level_1_model"].apply(
    normalize_settlement_name
)

df_model_base["location_level_2_norm"] = df_model_base["location_level_2_model"].apply(
    normalize_settlement_name
)

df_model_base["location_level_3_norm"] = df_model_base["location_level_3_model"].apply(
    normalize_settlement_name
)


capital_center_areas = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}

large_regional_cities = {
    "пловдив",
    "варна",
    "бургас",
}

regional_cities = {
    "русе",
    "стара загора",
    "плевен",
    "велико търново",
    "шумен",
    "добрич",
    "сливен",
    "хасково",
    "ямбол",
    "перник",
    "благоевград",
    "пазарджик",
    "враца",
    "габрово",
    "кърджали",
    "кюстендил",
    "ловеч",
    "монтана",
    "разград",
    "силистра",
    "смолян",
    "търговище",
    "видин",
}

sea_resorts = {
    "свети влас",
    "слънчев бряг",
    "несебър",
    "поморие",
    "равда",
    "созопол",
    "черноморец",
    "приморско",
    "китен",
    "лозенец",
    "царево",
    "ахтопол",
    "обзор",
    "бяла",
    "златни пясъци",
    "св. св. константин и елена",
    "св св константин и елена",
    "св. константин",
    "кабакум",
    "албена",
    "кранево",
    "балчик",
    "каварна",
    "шкорпиловци",
    "синеморец",
    "дюни",
    "елените",
    "аркутино",
    "сарафово",
    "черно море",
}

mountain_resorts = {
    "банско",
    "разлог",
    "добринище",
    "боровец",
    "самоков",
    "пампорово",
    "чепеларе",
    "смолян",
    "велинград",
    "сапарева баня",
    "трявна",
    "априлци",
    "троян",
}


def map_geo_category(row):
    level_1_raw = "" if pd.isna(row.get("location_level_1_model")) else str(row.get("location_level_1_model")).strip().lower()
    level_2_raw = "" if pd.isna(row.get("location_level_2_model")) else str(row.get("location_level_2_model")).strip().lower()

    level_1 = row.get("location_level_1_norm", "")
    level_2 = row.get("location_level_2_norm", "")
    level_3 = row.get("location_level_3_norm", "")

    level_1 = "" if pd.isna(level_1) else str(level_1)
    level_2 = "" if pd.isna(level_2) else str(level_2)
    level_3 = "" if pd.isna(level_3) else str(level_3)

    # Sofia first, because Sofia has "Лозенец", which should not become sea_resort.
    if level_1_raw == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # Resort checks after Sofia exception.
    if level_1 in sea_resorts or level_2 in sea_resorts or level_3 in sea_resorts:
        return "sea_resort"

    if level_1 in mountain_resorts or level_2 in mountain_resorts or level_3 in mountain_resorts:
        return "mountain_resort"

    if level_1 in large_regional_cities:
        return "large_regional_city"

    if level_1 in regional_cities:
        return "regional_city"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("с. ")
        or level_2_raw.startswith("село ")
    ):
        return "village"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("гр. ")
        or level_2_raw.startswith("град ")
    ):
        return "small_city"

    if level_1_raw.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nGeo category by property type:")
display(
    pd.crosstab(
        df_model_base["geo_category"],
        df_model_base["property_type_raw"],
        margins=True
    )
)

print("\nSea resort sample:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("sea_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "sea_resort").sum()),
        random_state=42,
    )
)

print("\nMountain resort sample:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("mountain_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "mountain_resort").sum()),
        random_state=42,
    )
)

Geo category distribution:

          geo_category   rows
0  large_regional_city  37982
1              village  29409
2   capital_non_center  28984
3        regional_city  23734
4           sea_resort  17823
5           small_city  11362
6       capital_center   5425
7      mountain_resort   3979
8        other_unknown   1842

Geo category by property type:

property_type_raw    1-СТАЕН  2-СТАЕН  3-СТАЕН  4-СТАЕН  АВТОМИВКА  АВТОСЕРВИЗ  АКВАПАРК  АПТЕКА  АТЕЛИЕ, ТАВАН  БАНКОВ ОФИС  БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ  ВИЛА  ВИЛНО СЕЛИЩЕ  ГАРАЖ  ГАРАЖ, ПАРКОМЯСТО  ДЕТСКИ ЦЕНТЪР  ДОМ ЗА ВЪЗРАСТНИ ХОРА  ЕТАЖ ОТ КЪЩА  ЗАВЕДЕНИЕ  ЗЕМЕДЕЛСКА ЗЕМЯ  КЛИНИКА   КЪЩА  ЛЕКАРСКИ КАБИНЕТ  МАГАЗИН  МЕЗОНЕТ  МНОГОСТАЕН  ОФИС  ПАРКИНГ  ПАРКОМЯСТО  ПАРЦЕЛ  ПРОМ. ПОМЕЩЕНИЕ  САМОСТОЯТЕЛНА СГРАДА  СКЛАД  СОЛАРЕН ПАРК  СПА/СОЛАРНО СТУДИО  СТОМАТОЛОГИЧЕН КАБИНЕТ  ТЪРГОВСКИ КОМПЛЕКС  ФАБРИКА/ЗАВОД  ФЕРМА  ФИТНЕС ЗАЛА  ФОТОГРАФСКО СТУДИО  ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН  ХЛАДИЛЕН СКЛАД  ХОТЕЛ     All
geo_category
capital_center           132     1274     1901      475          0           0         0       0             19            5                          0     1             0     70                  0              2                      0            32         98                0       13     92                 5      292       99         332   322        0          42     119               10                    29      8             0                   6                       4                  10              0      0            8                   0                           13               0     12    5425
capital_non_center       803     6637     8402     1674          0           8         1       5             53            5                          1    16             5    300                  3             17                      4           142        138                0       25   1712                 8      641      367         685   605        1         157    6169              116                    71     95             3                   4                       6                  20             17      3           28                   0                           17               0     20   28984
large_regional_city     1183    13050    11890     1423          5           5         2       9             21            5                          1    45             1    421                  4              2                      3           304        218                1       16   1997                18      868      328         892   713        0         389    3657              166                    45    135             2                   9                       9                  16             12      1           12                   1                           28               0     75   37982
mountain_resort          403      868      428       61          0           1         1       1              4            1                          2    22             8     14                  1              0                      2            51         41               90        0    550                 1       42       33          33    27        1          10    1071               41                    17     10             0                   5                       0                   8             13      2            3                   0                            1               0    112    3979
other_unknown             44      164      201       39          0           0         0       0              0            1                          3   207            10      0                  0              0                      0             2          4                9        0    460                 0        5       55          27     4        0           1     562                3                     1      2             2                   0                       0                   1              2      0            0                   0                            0               0     33    1842
regional_city            698     4459     5880     1055          3          36         0       4             68            2                         12   353             4    623                 26              6                      1           715        292                4       12   1739                22     1076      229         668   552        3         132    3827              629                    87    249             3                   9                       8                  58             67      3           23                   0                           32               2     63   23734
sea_resort              2533     6098     3562      276          1           3         1       0             21            0                          0    86             8     26                  2              1                      0            86        108              116        1   1508                 0      199      231         257    58        1          21    2282               15                    17      9             0                   7                       0                  12              2      1            4                   0                            5               0    265   17823
small_city               139      811      859      231          2          10         2       2              2            5                         10   125            16     49                  2              1                      5           422         86              667        3   2561                 7      205       26         168    87        4           5    3848              441                    90    128            18                   2                       0                  44             82     37            0                   0                            3               1    156   11362
village                   84      332      319       24          0          13         2       1              0            0                         13   335            41      1                  1              2                     15            97         97             1348        0  11570                 0      106       14          10    12        8           1   13687              557                   104    131            34                   1                       0                  42             54     96            0                   0                            0               1    256   29409
All                     6019    33693    33442     5258         11          76         9      22            188           24                         42  1190            93   1504                 39             31                     30          1851       1082             2235       70  22189                61     3434     1382        3072  2380       18         758   35222             1978                   461    767            62                  43                      27                 211            249    143           78                   1                           99               4    992  160540

Sea resort sample:

                    ad_id property_type_raw                                     location_raw location_level_1_model location_level_2_model location_level_2_norm  total_price  area_sqm  price_per_sqm
126340  1r163653125350608            ПАРЦЕЛ                   град Варна, к.к. Златни пясъци             град варна     к.к. златни пясъци         златни пясъци    1200000.0    3490.0         343.84
21848   1b176639461350960           2-СТАЕН                       област Бургас, гр. Несебър          област бургас            гр. несебър               несебър     148680.0      59.0        2520.00
60623   1c177056093558783           3-СТАЕН                    област Бургас, гр. Свети Влас          област бургас         гр. свети влас            свети влас     102000.0      70.0        1457.14
145580  1r176003382617583            ПАРЦЕЛ                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     487500.0    3900.0         125.00
125772  1r161730271864565            ПАРЦЕЛ                       област Добрич, гр. Каварна          област добрич            гр. каварна               каварна       7360.0     810.0           9.09
14110   1b175465581787926           2-СТАЕН                     област Бургас, гр. Приморско          област бургас          гр. приморско             приморско      82000.0      57.0        1438.60
23391   1b176881062686085           2-СТАЕН                            град Бургас, Сарафово            град бургас               сарафово              сарафово     108000.0      60.0        1800.00
22342   1b176785839083593           2-СТАЕН                        област Бургас, гр. Царево          област бургас             гр. царево                царево      99583.0      66.0        1508.83
82435   1f172121490629155           МЕЗОНЕТ                    област Бургас, гр. Свети Влас          област бургас         гр. свети влас            свети влас     210000.0     124.0        1693.55
53897   1c176192648645367           3-СТАЕН                           област Варна, гр. Бяла           област варна               гр. бяла                  бяла     184800.0     154.0        1200.00
16799   1b175973592600095           2-СТАЕН                 област Бургас, к.к. Слънчев бряг          област бургас      к.к. слънчев бряг          слънчев бряг      84500.0      54.0        1564.81
179     1a168492262637147           1-СТАЕН                       област Бургас, гр. Поморие          област бургас            гр. поморие               поморие      52000.0      48.0        1083.33
671     1a173764306991312           1-СТАЕН                           област Варна, гр. Бяла           област варна               гр. бяла                  бяла      94600.0      86.0        1100.00
131085  1r170600247334698            ПАРЦЕЛ                        област Бургас, гр. Царево          област бургас             гр. царево                царево      29500.0     890.0          33.15
218     1a169555257334795           1-СТАЕН  област Бургас, к.к. Слънчев бряг, гардения хилс          област бургас      к.к. слънчев бряг          слънчев бряг      49000.0      54.0         907.41
97473   1j175690849334662              КЪЩА                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     629000.0     207.0        3038.65
59518   1c176958860673746           3-СТАЕН     област Добрич, гр. Каварна, Крайбрежна  зона          област добрич            гр. каварна               каварна      79900.0     106.0         753.77
77127   1d177011290972703           4-СТАЕН                 област Бургас, к.к. Слънчев бряг          област бургас      к.к. слънчев бряг          слънчев бряг     139000.0      96.0        1447.92
125612  1r161287513662733            ПАРЦЕЛ   област Бургас, гр. Свети Влас, Вилна зона Зора          област бургас         гр. свети влас            свети влас    3551240.0   25366.0         140.00
8026    1b171765724330786           2-СТАЕН                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     156900.0      75.0        2092.00
11044   1b174463248966663           2-СТАЕН                            град Бургас, Сарафово            град бургас               сарафово              сарафово     114400.0      67.0        1707.46
54676   1c176303525948124           3-СТАЕН                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     154990.0     112.0        1383.84
70916   1c177762630304669           3-СТАЕН                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     356400.0     107.0        3330.84
128412  1r167776634795757            ПАРЦЕЛ                област Добрич, с. Кранево, Албена          област добрич             с. кранево               кранево      97500.0   15000.0           6.50
13233   1b175240654209122           2-СТАЕН                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол      69900.0      57.0        1226.32
122189  1q172431130981257             ХОТЕЛ                       област Бургас, гр. Несебър          област бургас            гр. несебър               несебър     999000.0     480.0        2081.25
6817    1b167636436242769           2-СТАЕН               област Бургас, гр. Ахтопол, Център          област бургас            гр. ахтопол               ахтопол     123360.0      62.0        1989.68
50505   1c175655028737424           3-СТАЕН            област Бургас, гр. Китен, ул.Корал  9          област бургас              гр. китен                 китен     178000.0     126.0        1412.70
9774    1b173807096990160           2-СТАЕН                       област Бургас, гр. Созопол          област бургас            гр. созопол               созопол     145000.0      85.0        1705.88
8516    1b172552634027995           2-СТАЕН  област Бургас, гр. Свети Влас, на 160м от плажа          област бургас         гр. свети влас            свети влас     115000.0      59.0        1949.15

Mountain resort sample:

                    ad_id     property_type_raw                                          location_raw location_level_1_model location_level_2_model location_level_2_norm  total_price  area_sqm  price_per_sqm
6204    1b155065661529311               2-СТАЕН        област Пазарджик, гр. Велинград, ул цар Самуил       област пазарджик          гр. велинград             велинград     68900.00      53.0        1300.00
138155  1r173883336280454                ПАРЦЕЛ                        област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог     85000.00    2947.0          28.84
14106   1b175459215901819               2-СТАЕН                       област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград     73600.00      67.0        1098.51
162639  1t173857642345325  САМОСТОЯТЕЛНА СГРАДА                             област Ловеч, гр. Априлци           област ловеч            гр. априлци               априлци    235000.00    1000.0         235.00
104290  1j177159902226159                  КЪЩА                               област Ловеч, гр. Троян           област ловеч              гр. троян                 троян     82900.00     120.0         690.83
76276   1d176338384334120               4-СТАЕН                               град Търговище, Боровец         град търговище                боровец               боровец    117000.00     109.0        1073.39
144685  1r175802906258765                ПАРЦЕЛ                            област Габрово, гр. Трявна         област габрово             гр. трявна                трявна     17445.00    1163.0          15.00
129843  1r169349227151701                ПАРЦЕЛ                             област София, гр. Самоков           област софия            гр. самоков               самоков    132500.00    5359.0          24.72
6056    1a177884966323693               1-СТАЕН            област Благоевград, гр. Разлог, Аспен Вали     област благоевград             гр. разлог                разлог     32990.00      47.0         701.91
62158   1c177185028753691               3-СТАЕН       област Благоевград, гр. Разлог, Грийн Ууд Хотел     област благоевград             гр. разлог                разлог     76990.00      78.0         987.05
124012  1r150116197077885                ПАРЦЕЛ                        област Благоевград, гр. Банско     област благоевград             гр. банско                банско     80000.00    8000.0          10.00
122852  1r122147286701850                ПАРЦЕЛ                        област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог     50000.00    2000.0          25.00
130797  1r170263350517749                ПАРЦЕЛ                            област София, к.к. Боровец           област софия           к.к. боровец               боровец    174850.00    3497.0          50.00
160007  1s174039233296100       ЗЕМЕДЕЛСКА ЗЕМЯ                        област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог      6997.00    1999.0           3.50
49415   1c175397694380869               3-СТАЕН                       област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград    109250.00     115.0         950.00
6206    1b155740459566565               2-СТАЕН              област Пазарджик, гр. Велинград, Кристал       област пазарджик          гр. велинград             велинград     49300.00      51.0         966.67
1454    1a175641190985095               1-СТАЕН                        област Благоевград, гр. Банско     област благоевград             гр. банско                банско     42999.00      34.0        1264.68
89717   1j167759385642120                  КЪЩА                            област Габрово, гр. Трявна         област габрово             гр. трявна                трявна     15287.63      20.0         764.38
72593   1c177857435605692               3-СТАЕН                        област Благоевград, гр. Банско     област благоевград             гр. банско                банско    135000.00     116.0        1163.79
6658    1b166377574785170               2-СТАЕН                       област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград     55250.00      55.0        1004.55
39751   1b177879254343143               2-СТАЕН                       област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград     76160.00      64.0        1190.00
7930    1b171578447292700               2-СТАЕН              област Пазарджик, гр. Велинград, Льджене       област пазарджик          гр. велинград             велинград     74000.00      74.0        1000.00
117665  1o172786172785953                 ГАРАЖ  област Благоевград, гр. Банско, ул. Муратово езеро 3     област благоевград             гр. банско                банско     20000.00      30.0         666.67
29486   1b177365389559201               2-СТАЕН                област Благоевград, гр. Банско, център     област благоевград             гр. банско                банско     87550.00      60.0        1459.17
130928  1r170472017533919                ПАРЦЕЛ                            област София, к.к. Боровец           област софия           к.к. боровец               боровец    250000.00    1300.0         192.31
116088  1m174963070320321             ЗАВЕДЕНИЕ        област Благоевград, гр. Банско,  м. Свети Иван     област благоевград             гр. банско                банско    200340.00     542.0         369.63
159402  1s171334843021801       ЗЕМЕДЕЛСКА ЗЕМЯ                             област Ловеч, гр. Априлци           област ловеч            гр. априлци               априлци     11000.00    3212.0           3.42
21260   1b176546553579039               2-СТАЕН                        област Благоевград, гр. Банско     област благоевград             гр. банско                банско     89900.00      53.0        1696.23
127305  1r165692670769737                ПАРЦЕЛ                       област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград    699000.00    1140.0         613.16
4341    1a177462242025205               1-СТАЕН                 област Благоевград, гр. Банско, Гинес     област благоевград             гр. банско                банско     42500.00      40.0        1062.50

In [48]:
# ------------------------------------------------------------
# Safer geo category mapping
# Fix false positives like "град Търговище, Боровец"
# ------------------------------------------------------------

def map_geo_category(row):
    level_1_raw = "" if pd.isna(row.get("location_level_1_model")) else str(row.get("location_level_1_model")).strip().lower()
    level_2_raw = "" if pd.isna(row.get("location_level_2_model")) else str(row.get("location_level_2_model")).strip().lower()

    level_1 = row.get("location_level_1_norm", "")
    level_2 = row.get("location_level_2_norm", "")
    level_3 = row.get("location_level_3_norm", "")

    level_1 = "" if pd.isna(level_1) else str(level_1)
    level_2 = "" if pd.isna(level_2) else str(level_2)
    level_3 = "" if pd.isna(level_3) else str(level_3)

    # Sofia first, because Sofia has "Лозенец", which should not become sea_resort.
    if level_1_raw == "град софия":
        if level_2 in capital_center_areas:
            return "capital_center"
        return "capital_non_center"

    # Sea resort:
    # Allow direct city resort, or resort settlement inside oblast.
    if (
        level_1 in sea_resorts
        or (
            level_1_raw.startswith("област ")
            and level_2 in sea_resorts
        )
    ):
        return "sea_resort"

    # Mountain resort:
    # Context-aware to avoid false positives like "град Търговище, Боровец".
    if level_1 in mountain_resorts:
        return "mountain_resort"

    if level_1_raw.startswith("област ") and level_2 in mountain_resorts:
        return "mountain_resort"

    # Special case: Borovets should only be mountain resort if under Sofia/Samokov context.
    if level_2 == "боровец":
        if (
            level_1_raw == "област софия"
            or level_1 == "самоков"
        ):
            return "mountain_resort"

    if level_1 in large_regional_cities:
        return "large_regional_city"

    if level_1 in regional_cities:
        return "regional_city"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("с. ")
        or level_2_raw.startswith("село ")
    ):
        return "village"

    if level_1_raw.startswith("област ") and (
        level_2_raw.startswith("гр. ")
        or level_2_raw.startswith("град ")
        or level_2_raw.startswith("к.к. ")
    ):
        return "small_city"

    if level_1_raw.startswith("град "):
        return "small_city"

    return "other_unknown"


df_model_base["geo_category"] = df_model_base.apply(map_geo_category, axis=1)

print("Geo category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

print("\nMountain resort sample after fix:")
display(
    df_model_base.loc[
        df_model_base["geo_category"].eq("mountain_resort"),
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ].sample(
        min(30, (df_model_base["geo_category"] == "mountain_resort").sum()),
        random_state=42,
    )
)

Geo category distribution:

          geo_category   rows
0  large_regional_city  39218
1              village  29441
2   capital_non_center  28984
3        regional_city  23813
4           sea_resort  16553
5           small_city  11392
6       capital_center   5425
7      mountain_resort   3897
8        other_unknown   1817

Mountain resort sample after fix:

                    ad_id     property_type_raw                                      location_raw location_level_1_model location_level_2_model location_level_2_norm  total_price  area_sqm  price_per_sqm
155469  1r177589367713294                ПАРЦЕЛ                           област Ловеч, гр. Троян           област ловеч              гр. троян                 троян     35800.00     895.0          40.00
24719   1b176995290931352               2-СТАЕН                     област Смолян, к.к. Пампорово          област смолян         к.к. пампорово             пампорово     41876.00      61.0         686.49
4333    1a177461265048521               1-СТАЕН         област Благоевград, гр. Банско, Грамадето     област благоевград             гр. банско                банско     42950.00      40.0        1073.75
94233   1j173736843539885                  КЪЩА                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско    356904.00     200.0        1784.52
57135   1c176641806681911               3-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско    120000.00      86.0        1395.35
5122    1a177702374871254               1-СТАЕН        област Благоевград, гр. Банско, Ул. Глазне     област благоевград             гр. банско                банско     51000.00      42.0        1214.29
88826   1j163671878392466                  КЪЩА                        област Габрово, гр. Трявна         област габрово             гр. трявна                трявна    450000.00     325.0        1384.62
58653   1c176881686251915               3-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско    180000.00     102.0        1764.71
122112  1q171894748311195                 ХОТЕЛ                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско   2100000.00    4457.0         471.17
129213  1r168614145557071                ПАРЦЕЛ                         област Ловеч, гр. Априлци           област ловеч            гр. априлци               априлци      3221.14     333.0           9.67
110356  1j177865510640569                  КЪЩА                         област София, гр. Самоков           област софия            гр. самоков               самоков    350000.00     182.0        1923.08
72630   1c177857686566507               3-СТАЕН                         област София, гр. Самоков           област софия            гр. самоков               самоков    130000.00      78.0        1666.67
163217  1t176528773104840  САМОСТОЯТЕЛНА СГРАДА                        област Габрово, гр. Трявна         област габрово             гр. трявна                трявна    120000.00     415.0         289.16
124030  1r150303996250353                ПАРЦЕЛ                   област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград    320000.00    3900.0          82.05
124730  1r156216912229777                ПАРЦЕЛ  област Смолян, гр. Чепеларе, Лифта долна станция          област смолян           гр. чепеларе              чепеларе     29500.00    1187.0          24.85
150680  1r176968088310458                ПАРЦЕЛ                    област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог     85000.00    2000.0          42.50
67032   1c177532635109012               3-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско    105000.00      80.0        1312.50
164     1a168190924386136               1-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско     37000.00      38.0         973.68
28636   1b177307209916662               2-СТАЕН                    област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог     63204.00      89.0         710.16
51401   1c175821368574878               3-СТАЕН                   област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград    139950.00     103.0        1358.74
20088   1b176414525377658               2-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско     83863.00      65.0        1290.20
6699    1b166808763035252               2-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско     80000.00      57.0        1403.51
160369  1s174913184742762       ЗЕМЕДЕЛСКА ЗЕМЯ                    област Благоевград, гр. Разлог     област благоевград             гр. разлог                разлог     58900.00    1473.0          39.99
163709  1t177734949629554                АПТЕКА                   област Пазарджик, гр. Велинград       област пазарджик          гр. велинград             велинград    409000.00     209.0        1956.94
89905   1j168309132116084                  КЪЩА                         област Ловеч, гр. Априлци           област ловеч            гр. априлци               априлци     92400.00     254.0         363.78
4337    1a177461341563349               1-СТАЕН         област Благоевград, гр. Банско, Грамадето     област благоевград             гр. банско                банско     36400.00      35.0        1040.00
124181  1r151827887982993                ПАРЦЕЛ                           град Смолян, Нов център            град смолян             нов център            нов център    308240.00    1380.0         223.36
72454   1c177850644449573               3-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско     87500.00      79.0        1107.59
105765  1j177383588225736                  КЪЩА                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско    160000.00      77.0        2077.92
38691   1b177850843275147               2-СТАЕН                    област Благоевград, гр. Банско     област благоевград             гр. банско                банско     59999.00      50.0        1199.98

In [49]:
# ------------------------------------------------------------
# Inspect rows classified as other_unknown
# ------------------------------------------------------------

other_unknown_geo = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("other_unknown rows:", len(other_unknown_geo))
print("Share of df_model_base:", round(len(other_unknown_geo) / len(df_model_base) * 100, 2), "%")

print("\nTop location_level_1_model in other_unknown:")
display(
    other_unknown_geo["location_level_1_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_1_model")
    .reset_index(name="rows")
)

print("\nTop location_level_2_model in other_unknown:")
display(
    other_unknown_geo["location_level_2_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("location_level_2_model")
    .reset_index(name="rows")
)

print("\nTop normalized level 1 / level 2 combos:")
display(
    other_unknown_geo
    .groupby(["location_level_1_model", "location_level_2_model"], dropna=False)
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample other_unknown rows:")
display(
    other_unknown_geo[
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sample(min(50, len(other_unknown_geo)), random_state=42)
)

other_unknown rows: 1817
Share of df_model_base: 1.13 %

Top location_level_1_model in other_unknown:

                                                                                                                                                                                                                                                                                                                                                                                                                                              location_level_1_model  rows
0                                                                                                                                                                                                                                                                                                                                                                                                                                                             гърция  1073
1                                                                                                                                                                                                                                                                                                                                                                                                                                                   област пазарджик   211
2                                                                                                                                                                                                                                                                                                                                                                                                                                                     област пловдив    58
3                                                                                                                                                                                                                                                                                                                                                                                                                                                       област софия    52
4                                                                                                                                                                                                                                                                                                                                                                                                                                                      област перник    28
5                                                                                                                                                                                                                                                                                                                                                                                                                                            апартамент с три спални    20
6                                                                                                                                                                                                                                                                                                                                                                                                                                                област стара загора    15
7                                                                                                                                                                                                                                                                                                                                                                                             тристайния апартамент е разположен в северната част на гр.стара загора    12
8                                                                                                                                                                                                                                                                                                                                                                                                                                                    област кърджали    11
9                                                                                                                                                                                                                                                                                                                                                                                                                                                        област русе     8
10                                                                                                                                                                                                                                                                                                                                                            комплесът се намира в непосредствена близост до основни пътни връзки и различни удобства като магазини     8
11                                                                                                                                                                                                                                                                                                                                                                                                имотът е разположен в престижната част на идеален център гр. шумен     7
12                                                                                                                                                                                                                                                                                                                                                                                                       сградата е разположена на изключително комуникативно място:     7
13                                                                                                                                                                                                                                                                                                                                                                                                                                             област велико търново     7
14                                                                                                                                                                                                                                                                                                                                                                                                                                                      област ловеч     7
15                                                                                                                                                                                                                                                                                                                                                                                                                                                     област плевен     7
16                                                                                                                                                                                                                                                                                                                                                                                                                                                    област хасково     6
17                                                                                                                                                                                                                                                                                                                                                                    курортът свети влас (свети влас) българия е малък уютен град на южното крайбрежие на българия.     6
18                                                                                                                                                                                                                                                                                                                                                                                                                             в околността има изобилие от магазини     6
19                                                                                                                                                                                                                                                                                                                                                                                                                                               двустаен апартамент     5
20                                                                                                                                                                                                                                                                                                                                                                                                                                                нов жилищен проект     5
21                                                                                                                                                                                                                                                                                                                                                                                                                                                област благоевград     5
22                                                                                                                                                                                                                                                                                                                                                                                                                                                     област бургас     5
23                                                                                                                                                                                                                                                                                                        слънчев бряг е един от най-големите семейни курорти в българия. намира се на 42 км северно от бургас и на 90 км от варна. курортът се намира в малък залив     5
24                                                                                                                                                                                                                                                                                                                                                                                                          комплекс sun city apartments е позициониран в к.к. чайка     5
25                                                                                                                                                                                                                                                                                                                                                    апартаментът е в един от най- предпочитаните райони в града-в близост до гпче 'ромен ролан'( езикова гимназия)     3
26                                                                                                                                                                                                                                                                                                                                                                             свети влас е уникално по своята природа място - благодарение на съчетанието на морски     3
27                                                                                                                                                                                                                                                                                                                                                                                               апартаментът се намира в тихата и предпочитана част на квартал южен     3
28                                                                                                                                                                                                                                                                                                                                                                                                                                  приморско е малък български град     3
29                                                                                                                                                                                                                                                                                                                                                                                          свети влас е уникално място в природата-благодарение на избора на морски     3
30                                                                                                                                                                                                                                                                                                                                                                                     кв.владислав варненчик е най-големия в гр.варна. в него има обособени паркове     3
31                                                                                                                                                                                                                                                                                                                                                                                                                                                      област варна     3
32                                                                                                                                                                                                                                                                                                                                                                                                           - комплексът се намира само на 200 м от бреговата линия     3
33                                                                                                                                                                                                                                                                                                                                                                                                                                                  + кв. овча купел     3
34  курортът свети влас (свети влас) българия е малък уютен град на южното крайбрежие на българия. свети влас принадлежи към бургаска област и е част от община несебър. курортът получи статут на град през 2006 година. но създаването на курортна зона започна тук след откриването на санаториум за лечение на белодробни заболявания. през 1963 г.свети влас е признат за климатичен морски курорт. свети влас е разположен на кръстопътя на планината и морето     2
35                                                                                                                                                                                                                                                                                                                                                                                                                                             комуникативна локация     2
36                                                                                                                                                                                                                                                                                                                                                         имотът се намира в предпочитан и добре устроен район на града кв. запад. в близост са разположени училища     2
37                                                                                                                                                                                                                                                                                                                                                              един от най-предпочитаните райони на града в непосредствена близост до факултет по дентална медицина     2
38                                                                                                                                                                                                                                                                                                                                                                                                                        апартаментът се намира в местност ален мак     2
39                                                                                                                                                                                                                                                                                                                                                                                                                                                   📍 в близост до:     2
40                                                                                                                                                                                                                                                                                           слънчев бряг е един от най-големите семейни курорти в българия. намира се е на 42 км северно от бургас и на 90 км от варна. курортът се намира на входа на малкия залив     2
41                                                                                                                                                                                                                                                                                                                                                                                                                                        подходящ за строеж на къща     2

Top location_level_2_model in other_unknown:

                                                                                                                location_level_2_model  rows
0                                                                                                                            халкидики   567
1                                                                                                                                солун   198
2                                                                                                                               кавала   161
3                                                                                                                       м-т цигов чарк   139
4                                                                                                                    магистрала тракия    67
5                                                                                                                                 <NA>    65
6                                                                                                                            яз. батак    53
7                                                                                                                            в.з.ярема    26
8                                                                                                                               пиерия    25
9                                                                                                                         хижа здравец    23
10                                                                                                                         яз. пчелина    20
11                                                                                      разположен в северната част на гр.стара загора    20
12                                                                                                                      главен път е85    19
13                                                                                                                               тасос    18
14                                                                                                                                 сяр    18
15                                                                                                                              ксанти    17
16                                                                    на тихо и спокойно място за живеене в близост до парк 'аязмото'.    12
17                                                                                                                      главен път е79    12
18                                                                                                                            закинтос    11
19                                                                                                                        яз. кърджали    10
20                                                                                                                         м-т мечката     9
21                                                                                                                       източна атика     8
22                                                                                                                       гара лакатник     8
23                                                                                                                           заведения     8
24                                                                                                                               евбея     8
25                                                                                                                      главен път е83     7
26                                                                                                                             училища     7
27                                                                                                                             локация     7
28                                                                                                                              лесбос     6
29                                                                                                                               атина     6
30                                                                                                                             циклади     5
31                                                                          в непосредствена близост до к.к. св.св. константин и елена     5
32                                                                                               в северната част на град стара загора     5
33                                                                                                                   магистрала марица     5
34                                                                                                                            гара бов     5
35  разположен в предпочитания район болница в шумен тиха и същевременно комуникативна зона с бърз достъп до централната част на града     5
36                                                                        а северната му част е затворена от стара планина-всичко това     5
37                                                                                                    в близост до хранителни магазини     4
38                                                                                                                           яз. сопот     4
39                                    планински и горски въздух в курорта преобладава особен микроклимат. освен с красивата си природа     3
40                                                                                                                             стадион     3
41                                                                                                                              родопи     3
42                                                планински и горски курорт има специален микроклимат. осветен от красивата си природа     3
43                                                                                                                       м-т яз. искър     3
44                                                                                                                    магистрала хемус     3
45                                                                                                                    магистрала люлин     3
46                                                                                                                яз. ал. стамболийски     3
47                                                                                                                          додеканези     3
48                                                    много популярен сред туристите. намира се в югоизточна българия близо до созопол     3
49                                                                                                което осигурява бърз достъп до плажа     3

Top normalized level 1 / level 2 combos:

                                                                       location_level_1_model                                  location_level_2_model  rows
70                                                                                     гърция                                               халкидики   567
67                                                                                     гърция                                                   солун   198
53                                                                                     гърция                                                  кавала   161
158                                                                          област пазарджик                                          м-т цигов чарк   139
160                                                                          област пазарджик                                               яз. батак    53
..                                                                                        ...                                                     ...   ...
251                                         топ локация в града- на метри от пешеходната зона  подходящ имот за всякакъв вид обществена дейност- офис     1
250                                                          тихо и спокойно място за живеене                   предпочитан квартал близо до центъра.     1
249                                                         строителство: хотелът е триетажен                                                  тухла.     1
248  стойностен имот само на 30км от гр. стара загора с бърз и лесен достъп по живописен път.                                                    <NA>     1
247                                              старозагорските бани е желано място за отдих                                                     спа     1

[100 rows x 3 columns]

Sample other_unknown rows:

                    ad_id property_type_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       location_raw                                                                                                                                                        location_level_1_model                                                                                                                              location_level_2_model                                                                                                                                                         location_level_1_norm                                                                                                                               location_level_2_norm  total_price  area_sqm  price_per_sqm
134482  1r172440028200494            ПАРЦЕЛ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Гърция, Халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики   5000000.00   15674.0         319.00
92764   1j172484811890372              КЪЩА                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Гърция, Халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики    195000.00     170.0        1147.06
24881   1b177010856919940           2-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Имотът е разположен в престижната част на Идеален център   гр. Шумен, локация, която предлага спокойствие, удобство и бърз достъп до всички ключови градски точки.                                                                                                            имотът е разположен в престижната част на идеален център гр. шумен                                                                                                                                             локация                                                                                                            имотът е разположен в престижната част на идеален център гр. шумен                                                                                                                                             локация    129737.00      75.0        1729.83
74057   1d169115367173039           4-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          АПАРТАМЕНТ с ТРИ СПАЛНИ, разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                                                                       апартамент с три спални                                                                                                      разположен в северната част на гр.стара загора                                                                                                                                                       апартамент с три спални                                                                                                      разположен в северната част на гр.стара загора    180000.00     153.0        1176.47
90116   1j168727291053050              КЪЩА                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Гърция, Халкидики, Неа Каликратия                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики    240000.00      85.0        2823.53
154190  1r177438816741806            ПАРЦЕЛ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Гърция, Халкидики, Nea Potidea Chalkidiki                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики     11000.00     364.0          30.22
50282   1c175619625640256           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   кв.  Железник   изток    предпочитан заради спокойната среда и бързата връзка с централната част на Стара Загора                                                                    кв. железник изток предпочитан заради спокойната среда и бързата връзка с централната част на стара загора                                                                                                                                                <NA>                                                                    кв. железник изток предпочитан заради спокойната среда и бързата връзка с централната част на стара загора                                                                                                                                                        109900.00      99.0        1110.10
136526  1r173264521999665            ПАРЦЕЛ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            област София, в.з.Ярема                                                                                                                                                                  област софия                                                                                                                                           в.з.ярема                                                                                                                                                                  област софия                                                                                                                                           в.з.ярема    105000.00     586.0         179.18
127361  1r165771258372659            ПАРЦЕЛ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   област Пазарджик, м-т Цигов чарк                                                                                                                                                              област пазарджик                                                                                                                                      м-т цигов чарк                                                                                                                                                              област пазарджик                                                                                                                                          цигов чарк     55725.00     743.0          75.00
102170  1j176803561516289              КЪЩА                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Гърция, Халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики    750000.00     160.0        4687.50
88779   1j163230617533206              КЪЩА                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Гърция, Халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики                                                                                                                                                                        гърция                                                                                                                                           халкидики    270000.00     125.0        2160.00
60637   1c177038829046258           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Имотът е разположен в престижната част на Идеален център   гр. Шумен, локация, която предлага спокойствие, удобство и бърз достъп до всички ключови градски точки.                                                                                                            имотът е разположен в престижната част на идеален център гр. шумен                                                                                                                                             локация                                                                                                            имотът е разположен в престижната част на идеален център гр. шумен                                                                                                                                             локация    154819.00      83.0        1865.29
79368   1e169115613930842        МНОГОСТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          АПАРТАМЕНТ с ТРИ СПАЛНИ, разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                                                                       апартамент с три спални                                                                                                      разположен в северната част на гр.стара загора                                                                                                                                                       апартамент с три спални                                                                                                      разположен в северната част на гр.стара загора    215000.00     206.0        1043.69

In [50]:
# ------------------------------------------------------------
# Geo cleanup: drop Greece and reclassify oblast unknowns
# ------------------------------------------------------------

before_rows = len(df_model_base)

# 1. Drop Greece / foreign Greece listings
drop_greece_mask = (
    df_model_base["location_level_1_model"]
    .astype("string")
    .str.lower()
    .eq("гърция")
)

dropped_greece = df_model_base.loc[drop_greece_mask].copy()

df_model_base = df_model_base.loc[~drop_greece_mask].copy()

after_greece_rows = len(df_model_base)

print("Dropped Greece rows:", before_rows - after_greece_rows)


# 2. Reclassify other_unknown rows that start with "област" as small_city
reclass_oblast_unknown_mask = (
    df_model_base["geo_category"].eq("other_unknown")
    & df_model_base["location_level_1_model"].astype("string").str.startswith("област", na=False)
)

reclassified_oblast_unknown = df_model_base.loc[reclass_oblast_unknown_mask].copy()

df_model_base.loc[reclass_oblast_unknown_mask, "geo_category"] = "small_city"

print("Reclassified oblast other_unknown rows:", len(reclassified_oblast_unknown))
print("Rows before:", before_rows)
print("Rows after:", len(df_model_base))


# 3. Inspect updated geo distribution
print("\nUpdated geo_category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)


# 4. Inspect remaining other_unknown
remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("\nRemaining other_unknown rows:", len(remaining_other_unknown))

display(
    remaining_other_unknown[
        [
            "ad_id",
            "property_type_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)


# 5. Log cleanup actions
cleanup_actions.append({
    "rule": "drop_greece_listings",
    "reason": "Greece listings are outside the target Bulgarian real estate market and irrelevant for the planned regression model",
    "rows_affected": len(dropped_greece),
})

cleanup_actions.append({
    "rule": "reclassify_oblast_other_unknown_to_small_city",
    "reason": "Rows classified as other_unknown but starting with oblast are Bulgarian regional listings and should be treated as small_city for coarse geo bucketing",
    "rows_affected": len(reclassified_oblast_unknown),
})

Dropped Greece rows: 1073
Reclassified oblast other_unknown rows: 430
Rows before: 160540
Rows after: 159467

Updated geo_category distribution:

          geo_category   rows
0  large_regional_city  39218
1              village  29441
2   capital_non_center  28984
3        regional_city  23813
4           sea_resort  16553
5           small_city  11822
6       capital_center   5425
7      mountain_resort   3897
8        other_unknown    314

Remaining other_unknown rows: 314

                   ad_id property_type_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             location_raw                                                                                                                                                   location_level_1_model                                                                      location_level_2_model                                                                                                                                                    location_level_1_norm                                                                       location_level_2_norm  total_price  area_sqm  price_per_sqm
1404   1a175559624267113           1-СТАЕН                                                                                                                                                                                                                                                                                    Комплекс  SUN CITY APARTMENTS  е позициониран в к.к. Чайка, в непосредствена близост до к.к.  Св.Св. Константин и Елена, к.к.  Слънчев ден  и известният плаж  Кабакум. В съседство са разположени спирки на градския транспорт, заведения за хранене, магазини за хранителни стоки, ВСУ Черноризец Храбър, а супермаркет  Lidl  се намира само на 3 мин с автомобил.                                                                                                                 комплекс sun city apartments е позициониран в к.к. чайка                                  в непосредствена близост до к.к. св.св. константин и елена                                                                                                                 комплекс sun city apartments е позициониран в к.к. чайка                                  в непосредствена близост до к.к. св.св. константин и елена      99900.0      47.0        2125.53
1869   1a176068114364174           1-СТАЕН  Слънчев бряг е един от най-големите семейни курорти в България. Намира се е на 42 км северно от Бургас и на 90 км от Варна. Курортът се намира на входа на малкия залив, а северната част на Стара планина-ярко осветен е великолепен изглед към морето и планината, дава естествена защита от студено ветровито и лошо време. Климат е мек средиземноморски, има 1700 слънчеви часа от май до септември. Средната температура за лят е + 27 0, а за вода +24 0.Нема отителна топлина, благодарност на мекия морски бриз. Курортът е удостоен с Международната награда Син Флаг, за доказване на еко-наследство в Черноморското крайбрежие на България.  слънчев бряг е един от най-големите семейни курорти в българия. намира се е на 42 км северно от бургас и на 90 км от варна. курортът се намира на входа на малкия залив  а северната част на стара планина-ярко осветен е великолепен изглед към морето и планината  слънчев бряг е един от най-големите семейни курорти в българия. намира се е на 42 км северно от бургас и на 90 км от варна. курортът се намира на входа на малкия залив  а северната част на стара планина-ярко осветен е великолепен изглед към морето и планината      59000.0      36.0        1638.89
1873   1a176068121961856           1-СТАЕН  Слънчев бряг е един от най-големите семейни курорти в България. Намира се е на 42 км северно от Бургас и на 90 км от Варна. Курортът се намира на входа на малкия залив, а северната част на Стара планина-ярко осветен е великолепен изглед към морето и планината, дава естествена защита от студено ветровито и лошо време. Климат е мек средиземноморски, има 1700 слънчеви часа от май до септември. Средната температура за лят е + 27 0, а за вода +24 0.Нема отителна топлина, благодарност на мекия морски бриз. Курортът е удостоен с Международната награда Син Флаг, за доказване на еко-наследство в Черноморското крайбрежие на България.  слънчев бряг е един от най-големите семейни курорти в българия. намира се е на 42 км северно от бургас и на 90 км от варна. курортът се намира на входа на малкия залив  а северната част на стара планина-ярко осветен е великолепен изглед към морето и планината  слънчев бряг е един от най-големите семейни курорти в българия. намира се е на 42 км северно от бургас и на 90 км от варна. курортът се намира на входа на малкия залив  а северната част на стара планина-ярко осветен е великолепен изглед към морето и планината      58000.0      42.0        1380.95
2093   1a176251323867030           1-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Само 100 метра от супермаркет  Меркурий  и спирка на градския транспорт                                                                                                    само 100 метра от супермаркет меркурий и спирка на градския транспорт                                                                                        <NA>                                                                                                    само 100 метра от супермаркет меркурий и спирка на градския транспорт                                                                                                  56000.0      36.0        1555.56
2179   1a176311612121480           1-СТАЕН                                                                                                                                                                                                                                                                                                                       кв.Владислав Варненчик е най-големия в гр.Варна. В него има обособени паркове, стадион, супермаркети, закусвални, барове, заведения за хранене, детски кът, многобройни детски площадки, офиси на куриери, поликлиника,пазар, училища, детски градини, ясли. Транспортът осигурява възможност да стигнете до всяка точка на града.                                                                                            кв.владислав варненчик е най-големия в гр.варна. в него има обособени паркове                                                                                     стадион                                                                                            кв.владислав варненчик е най-големия в гр.варна. в него има обособени паркове                                                                                     стадион      58450.0      42.0        1391.67
...                  ...               ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...                                                                                                                                                                      ...                                                                                         ...                                                                                                                                                                      ...                                                                                         ...          ...       ...            ...
41361  1c169115253683302           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ТРИСТАЙНИЯ апартамент е разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                            на тихо и спокойно място за живеене в близост до парк 'аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                              на тихо и спокойно място за живеене в близост до парк аязмото.     164750.0     119.0        1384.45
41366  1c169115199268387           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ТРИСТАЙНИЯ апартамент е разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                            на тихо и спокойно място за живеене в близост до парк 'аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                              на тихо и спокойно място за живеене в близост до парк аязмото.     164750.0     102.0        1615.20
41376  1c169115182021618           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ТРИСТАЙНИЯ апартамент е разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                            на тихо и спокойно място за живеене в близост до парк 'аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                              на тихо и спокойно място за живеене в близост до парк аязмото.     164750.0      96.0        1716.15
41377  1c169115108040106           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ТРИСТАЙНИЯ апартамент е разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                            на тихо и спокойно място за живеене в близост до парк 'аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                              на тихо и спокойно място за живеене в близост до парк аязмото.     164750.0     113.0        1457.96
41378  1c169115117846254           3-СТАЕН                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ТРИСТАЙНИЯ апартамент е разположен в северната част на гр.Стара Загора, на тихо и спокойно място за живеене в близост до парк 'Аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                            на тихо и спокойно място за живеене в близост до парк 'аязмото'.                                                                                                   тристайния апартамент е разположен в северната част на гр.стара загора                              на тихо и спокойно място за живеене в близост до парк аязмото.     164750.0     102.0        1615.20

[100 rows x 10 columns]

In [51]:
# ------------------------------------------------------------
# Inspect remaining other_unknown by title_city_raw
# ------------------------------------------------------------

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("Remaining other_unknown rows:", len(remaining_other_unknown))

print("\nTop title_city_raw values:")
display(
    remaining_other_unknown["title_city_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTitle city + location level combo:")
display(
    remaining_other_unknown
    .groupby(
        [
            "title_city_raw",
            "location_level_1_model",
            "location_level_2_model",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample remaining other_unknown:")
display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["title_city_raw", "property_type_raw", "price_per_sqm"])
    .head(100)
)

Remaining other_unknown rows: 314

Top title_city_raw values:

           title_city_raw  rows
0           област Бургас    83
1       град Стара Загора    67
2              град София    43
3              град Варна    28
4              град Шумен    13
5     област Стара Загора    10
6            област София     8
7          област Пловдив     7
8          град Пазарджик     7
9        област Пазарджик     5
10           град Пловдив     4
11           област Варна     4
12            град Бургас     4
13       град Благоевград     3
14           град Хасково     3
15           област Ловеч     3
16           област Шумен     3
17         област Хасково     2
18          област Перник     2
19            град Перник     2
20  област Велико Търново     2
21     област Благоевград     2
22          област Смолян     1
23             град Ямбол     1
24       област Търговище     1
25          област Добрич     1
26            област Русе     1
27       област Кюстендил     1
28         област Габрово     1
29                 Гърция     1
30           област Ямбол     1

Title city + location level combo:

        title_city_raw                                                                                  location_level_1_model                                                                                           location_level_2_model  rows
55   град Стара Загора                                                                                 апартамент с три спални                                                                   разположен в северната част на гр.стара загора    20
83   град Стара Загора                                  тристайния апартамент е разположен в северната част на гр.стара загора                                                 на тихо и спокойно място за живеене в близост до парк 'аязмото'.    12
15          град Варна  комплесът се намира в непосредствена близост до основни пътни връзки и различни удобства като магазини                                                                                                        заведения     8
50          град София                                             сградата е разположена на изключително комуникативно място:                                                                                                             <NA>     7
88          град Шумен                                      имотът е разположен в престижната част на идеален център гр. шумен                                                                                                          локация     7
..                 ...                                                                                                     ...                                                                                                              ...   ...
90          град Шумен                                                                     отлична локация - в близост до гора                                                                                                          училища     1
91          град Ямбол                                            апартаментът се намира на трети етаж с изложение изток-запад  което гарантира добра осветеност и естествена топлина през целия ден. локацията е отлична в близост до магазини     1
97       област Бургас                        апартаментът се намира в слънчев бряг най-търсения черноморски курорт в българия                         на достъпна цена за международни и местни купувачи. в непосредствена близост се намират:     1
93  област Благоевград                                                 село хърсово се намира в санданско-петричката котловина                                                                                            на 20 км от сандански     1
95       област Бургас                                                                             - на 100м от плаж харманите                                                                                                             <NA>     1

[100 rows x 4 columns]

Sample remaining other_unknown:

                    ad_id                                                                                                            ad_url property_type_raw     title_city_raw                                                                                                                                                                      location_raw                                                                                                                                       location_level_1_model                                                     location_level_2_model                                                                                                                                        location_level_1_norm                                                      location_level_2_norm  total_price  area_sqm  price_per_sqm
145894  1r176062111749471                      https://www.imot.bg/obiava-1r176062111749471-prodava-partsel-gartsiya-ksanti-avdira-lefkipos            ПАРЦЕЛ             Гърция  На уникално място, само на една крачка от пристанището (както се вижда на въздушната снимка), се предлага за продажба поземлен имот извън регулация с възможност за застрояване.                                                                                                                                            на уникално място  само на една крачка от пристанището (както се вижда на въздушната снимка)                                                                                                                                            на уникално място  само на една крачка от пристанището (както се вижда на въздушната снимка)     480000.0    4957.0          96.83
48443   1c175144452019710          https://www.imot.bg/obiava-1c175144452019710-prodava-tristaen-apartament-grad-blagoevgrad-shirok-tsentar           3-СТАЕН   град Благоевград                                Апартаментът се намира в нова сграда пред АКТ 15 на много комуникативно място   в близост до училище, детска градина, автобусна спирка и магазини.                                                           апартаментът се намира в нова сграда пред акт 15 на много комуникативно място в близост до училище                                                             детска градина                                                           апартаментът се намира в нова сграда пред акт 15 на много комуникативно място в близост до училище                                                             детска градина     111300.0      86.0        1294.19
65669   1c177442836123156          https://www.imot.bg/obiava-1c177442836123156-prodava-tristaen-apartament-grad-blagoevgrad-shirok-tsentar           3-СТАЕН   град Благоевград                                Апартаментът се намира в нова сграда пред АКТ 15 на много комуникативно място - в близост до училище, детска градина, автобусна спирка и магазини.                                                         апартаментът се намира в нова сграда пред акт 15 на много комуникативно място - в близост до училище                                                             детска градина                                                         апартаментът се намира в нова сграда пред акт 15 на много комуникативно място - в близост до училище                                                             детска градина     142038.0     109.0        1303.10
81600   1e177445296590308              https://www.imot.bg/obiava-1e177445296590308-prodava-mnogostaen-apartament-grad-blagoevgrad-strumsko        МНОГОСТАЕН   град Благоевград                                                Намира се в началото на кв. Струмско, в близост до училище, детска градина, детски площадки, спирки на градски транспорт магазини.                                                                                                                         намира се в началото на кв. струмско                                                       в близост до училище                                                                                                                         намира се в началото на кв. струмско                                                       в близост до училище     110000.0      96.0        1145.83
163703  1t177670051572842                  https://www.imot.bg/obiava-1t177670051572842-prodava-biznes-imot-grad-burgas-meden-rudnik-zona-v       БАНКОВ ОФИС        град Бургас                     Търговски обект в активен търговски център в ж.к. Меден рудник   зона В. Директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.  търговски обект в активен търговски център в ж.к. меден рудник зона в. директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.                                                                       <NA>  търговски обект в активен търговски център в ж.к. меден рудник зона в. директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.                                                                                285000.0     166.0        1716.87
...                   ...                                                                                                               ...               ...                ...                                                                                                                                                                               ...                                                                                                                                                          ...                                                                        ...                                                                                                                                                          ...                                                                        ...          ...       ...            ...
7135    1b169114979536316               https://www.imot.bg/obiava-1b169114979536316-prodava-dvustaen-apartament-grad-stara-zagora-ayazmoto           2-СТАЕН  град Стара Загора                                                        ДВУСТАЕН  апартамент, в северната част на град Стара Загора,на тихо и спокойно място за живеене в близост до парк Аязмото.                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора      74000.0      67.0        1104.48
7136    1b169114971299767               https://www.imot.bg/obiava-1b169114971299767-prodava-dvustaen-apartament-grad-stara-zagora-ayazmoto           2-СТАЕН  град Стара Загора                                                        ДВУСТАЕН  апартамент, в северната част на град Стара Загора,на тихо и спокойно място за живеене в близост до парк Аязмото.                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора      74000.0      67.0        1104.48
7137    1b169114988704669               https://www.imot.bg/obiava-1b169114988704669-prodava-dvustaen-apartament-grad-stara-zagora-ayazmoto           2-СТАЕН  град Стара Загора                                                        ДВУСТАЕН  апартамент, в северната част на град Стара Загора,на тихо и спокойно място за живеене в близост до парк Аязмото.                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора                                                                                                                                          двустаен апартамент                                      в северната част на град стара загора      74000.0      67.0        1104.48
9539    1b173650127192070         https://www.imot.bg/obiava-1b173650127192070-prodava-dvustaen-apartament-grad-stara-zagora-kazanski-iztok           2-СТАЕН  град Стара Загора                                                                                       Казански- изток е тих, спокоен квартал в близост до парк Артелирийски, VОУ, детска градина.                                                                                                                                        казански- изток е тих                             спокоен квартал в близост до парк артелирийски                                                                                                                                        казански- изток е тих                             спокоен квартал в близост до парк артелирийски      88000.0      74.0        1189.19
6403    1b163428249531820  https://www.imot.bg/obiava-1b163428249531820-prodava-dvustaen-apartament-grad-stara-zagora-ayazmoto-mol-galeriya           2-СТАЕН  град Стара Загора                                    ДВУСТАЕН апартамент в близост до бул. Патриарх Евтимий, осигурява бърз достъп до централната част на града, в близост до магазини и заведения.                                                                                                       двустаен апартамент в близост до бул. патриарх евтимий                         осигурява бърз достъп до централната част на града                                                                                                       двустаен апартамент в близост до бул. патриарх евтимий                         осигурява бърз достъп до централната част на града      74000.0      62.0        1193.55

[100 rows x 12 columns]

In [52]:
# ------------------------------------------------------------
# Re-inspect remaining other_unknown using title_city_raw + title_geo_2_raw
# No mutation
# ------------------------------------------------------------

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

# Normalize for inspection only
remaining_other_unknown["title_city_model_inspect"] = (
    remaining_other_unknown["title_city_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

remaining_other_unknown["title_geo_2_model_inspect"] = (
    remaining_other_unknown["title_geo_2_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

print("Remaining other_unknown rows:", len(remaining_other_unknown))

print("\nTop title_city_raw:")
display(
    remaining_other_unknown["title_city_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_city_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTop title_geo_2_raw:")
display(
    remaining_other_unknown["title_geo_2_raw"]
    .value_counts(dropna=False)
    .rename_axis("title_geo_2_raw")
    .reset_index(name="rows")
    .head(100)
)

print("\nTop title_city_raw + title_geo_2_raw combos:")
display(
    remaining_other_unknown
    .groupby(
        [
            "title_city_raw",
            "title_geo_2_raw",
        ],
        dropna=False,
    )
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(100)
)

print("\nSample rows:")
display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "title_geo_2_raw",
            "location_raw",
            "location_level_1_model",
            "location_level_2_model",
            "location_level_1_norm",
            "location_level_2_norm",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["title_city_raw", "title_geo_2_raw", "property_type_raw"])
    .head(150)
)

Remaining other_unknown rows: 314

Top title_city_raw:

           title_city_raw  rows
0           област Бургас    83
1       град Стара Загора    67
2              град София    43
3              град Варна    28
4              град Шумен    13
5     област Стара Загора    10
6            област София     8
7          област Пловдив     7
8          град Пазарджик     7
9        област Пазарджик     5
10           град Пловдив     4
11           област Варна     4
12            град Бургас     4
13       град Благоевград     3
14           град Хасково     3
15           област Ловеч     3
16           област Шумен     3
17         област Хасково     2
18          област Перник     2
19            град Перник     2
20  област Велико Търново     2
21     област Благоевград     2
22          област Смолян     1
23             град Ямбол     1
24       област Търговище     1
25          област Добрич     1
26            област Русе     1
27       област Кюстендил     1
28         област Габрово     1
29                 Гърция     1
30           област Ямбол     1

Top title_geo_2_raw:

      title_geo_2_raw  rows
0             Аязмото    39
1      гр. Свети Влас    25
2   к.к. Слънчев бряг    24
3              Център    22
4              Виница     8
..                ...   ...
95           с. Селце     1
96      с. Царев брод     1
97     с. Малка Верея     1
98  с. Граф Игнатиево     1
99        гр. Дряново     1

[100 rows x 2 columns]

Top title_city_raw + title_geo_2_raw combos:

       title_city_raw    title_geo_2_raw  rows
46  град Стара Загора            Аязмото    39
68      област Бургас     гр. Свети Влас    25
71      област Бургас  к.к. Слънчев бряг    24
55  град Стара Загора             Център     9
5          град Варна             Виница     8
..                ...                ...   ...
92   област Пазарджик      с. Гелеменово     1
90       област Ловеч        с. Рибарица     1
89       област Ловеч          с. Орешак     1
87   област Кюстендил       с. Мало село     1
97     област Пловдив          гр. Сопот     1

[100 rows x 3 columns]

Sample rows:

                    ad_id                                                                                                           ad_url property_type_raw     title_city_raw title_geo_2_raw                                                                                                                                                                      location_raw                                                                                                                                       location_level_1_model                                                                  location_level_2_model                                                                                                                                        location_level_1_norm                                                                   location_level_2_norm  total_price  area_sqm  price_per_sqm
145894  1r176062111749471                     https://www.imot.bg/obiava-1r176062111749471-prodava-partsel-gartsiya-ksanti-avdira-lefkipos            ПАРЦЕЛ             Гърция          Ксанти  На уникално място, само на една крачка от пристанището (както се вижда на въздушната снимка), се предлага за продажба поземлен имот извън регулация с възможност за застрояване.                                                                                                                                            на уникално място               само на една крачка от пристанището (както се вижда на въздушната снимка)                                                                                                                                            на уникално място               само на една крачка от пристанището (както се вижда на въздушната снимка)     480000.0    4957.0          96.83
81600   1e177445296590308             https://www.imot.bg/obiava-1e177445296590308-prodava-mnogostaen-apartament-grad-blagoevgrad-strumsko        МНОГОСТАЕН   град Благоевград        Струмско                                                Намира се в началото на кв. Струмско, в близост до училище, детска градина, детски площадки, спирки на градски транспорт магазини.                                                                                                                         намира се в началото на кв. струмско                                                                    в близост до училище                                                                                                                         намира се в началото на кв. струмско                                                                    в близост до училище     110000.0      96.0        1145.83
48443   1c175144452019710         https://www.imot.bg/obiava-1c175144452019710-prodava-tristaen-apartament-grad-blagoevgrad-shirok-tsentar           3-СТАЕН   град Благоевград    Широк център                                Апартаментът се намира в нова сграда пред АКТ 15 на много комуникативно място   в близост до училище, детска градина, автобусна спирка и магазини.                                                           апартаментът се намира в нова сграда пред акт 15 на много комуникативно място в близост до училище                                                                          детска градина                                                           апартаментът се намира в нова сграда пред акт 15 на много комуникативно място в близост до училище                                                                          детска градина     111300.0      86.0        1294.19
65669   1c177442836123156         https://www.imot.bg/obiava-1c177442836123156-prodava-tristaen-apartament-grad-blagoevgrad-shirok-tsentar           3-СТАЕН   град Благоевград    Широк център                                Апартаментът се намира в нова сграда пред АКТ 15 на много комуникативно място - в близост до училище, детска градина, автобусна спирка и магазини.                                                         апартаментът се намира в нова сграда пред акт 15 на много комуникативно място - в близост до училище                                                                          детска градина                                                         апартаментът се намира в нова сграда пред акт 15 на много комуникативно място - в близост до училище                                                                          детска градина     142038.0     109.0        1303.10
163703  1t177670051572842                 https://www.imot.bg/obiava-1t177670051572842-prodava-biznes-imot-grad-burgas-meden-rudnik-zona-v       БАНКОВ ОФИС        град Бургас    Меден рудник                     Търговски обект в активен търговски център в ж.к. Меден рудник   зона В. Директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.  търговски обект в активен търговски център в ж.к. меден рудник зона в. директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.                                                                                    <NA>  търговски обект в активен търговски център в ж.к. меден рудник зона в. директна видимост и лице към главен булевард с висок пешеходен и автомобилен трафик.                                                                                             285000.0     166.0        1716.87
...                   ...                                                                                                              ...               ...                ...             ...                                                                                                                                                                               ...                                                                                                                                                          ...                                                                                     ...                                                                                                                                                          ...                                                                                     ...          ...       ...            ...
60074   1c177011747505526              https://www.imot.bg/obiava-1c177011747505526-prodava-tristaen-apartament-grad-stara-zagora-samara-2           3-СТАЕН  град Стара Загора        Самара 2                                                                                                           Тихо и спокойно място за живеене, предпочитан квартал близо до центъра.                                                                                                                             тихо и спокойно място за живеене                                                   предпочитан квартал близо до центъра.                                                                                                                             тихо и спокойно място за живеене                                                   предпочитан квартал близо до центъра.      90000.0      55.0        1636.36
91348   1j171023598790456                           https://www.imot.bg/obiava-1j171023598790456-prodava-kashta-grad-stara-zagora-samara-3              КЪЩА  град Стара Загора        Самара 3                                                      НОВА КЪЩА в източен добре инфраструктуриран квартал- Самара 3. Квартал с бързо развиващо се строителство, в близост до парк.                                                     нова къща в източен добре инфраструктуриран квартал- самара 3. квартал с бързо развиващо се строителство                                                                      в близост до парк.                                                     нова къща в източен добре инфраструктуриран квартал- самара 3. квартал с бързо развиващо се строителство                                                                      в близост до парк.     175000.0     140.0        1250.00
52732   1c176043831222730  https://www.imot.bg/obiava-1c176043831222730-prodava-tristaen-apartament-grad-stara-zagora-tri-chuchura-tsentar           3-СТАЕН  град Стара Загора      Три чучура                         Тристаен апартамент на среден етаж в монолитен блок в западен тих, спокоен и зелен квартал. Места за отдих и детски игри пред блока и места за паркиране.                                                                                            тристаен апартамент на среден етаж в монолитен блок в западен тих  спокоен и зелен квартал. места за отдих и детски игри пред блока и места за паркиране.                                                                                            тристаен апартамент на среден етаж в монолитен блок в западен тих  спокоен и зелен квартал. места за отдих и детски игри пред блока и места за паркиране.      72000.0      62.0        1161.29
56751   1c176579229020544    https://www.imot.bg/obiava-1c176579229020544-prodava-tristaen-apartament-grad-stara-zagora-tri-chuchura-sever           3-СТАЕН  град Стара Загора      Три чучура                                                         ТРИСТАЕН апартамент в кв.  Трите чучура - север   , Стара Загора. В близост до училище, детска градина, автобусна спирка.                                                                                                               тристаен апартамент в кв. трите чучура - север                                                      стара загора. в близост до училище                                                                                                               тристаен апартамент в кв. трите чучура - север                                                      стара загора. в близост до училище      83142.0      92.0         903.72
7133    1b169114963672173               https://www.imot.bg/obiava-1b169114963672173-prodava-dvustaen-apartament-grad-stara-zagora-tsentar           2-СТАЕН  град Стара Загора          Център                                                        ДВУСТАЕН  апартамент, в северната част на град Стара Загора,на тихо и спокойно място за живеене в близост до парк Аязмото.                                                                                                                                          двустаен апартамент                                                   в северната част на град стара загора                                                                                                                                          двустаен апартамент                                                   в северната част на град стара загора      88000.0      67.0        1313.43

[150 rows x 13 columns]

In [53]:
# ------------------------------------------------------------
# Better fix for remaining other_unknown using title_city_raw + title_geo_2_raw
# No blanket "oblast -> small_city"
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

# Normalize title fields
df_model_base["title_city_model"] = (
    df_model_base["title_city_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

df_model_base["title_geo_2_model"] = (
    df_model_base["title_geo_2_raw"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

# Drop Greece based on title_city_raw
before_rows = len(df_model_base)

drop_greece_mask = df_model_base["title_city_model"].eq("гърция")

dropped_greece_title_city = df_model_base.loc[drop_greece_mask].copy()
df_model_base = df_model_base.loc[~drop_greece_mask].copy()

print("Dropped Greece rows:", len(dropped_greece_title_city))


large_regional_city_titles = {
    "град пловдив",
    "град варна",
    "град бургас",
}

regional_city_titles = {
    "град русе",
    "град стара загора",
    "град плевен",
    "град велико търново",
    "град шумен",
    "град добрич",
    "град сливен",
    "град хасково",
    "град ямбол",
    "град перник",
    "град благоевград",
    "град пазарджик",
    "град враца",
    "град габрово",
    "град кърджали",
    "град кюстендил",
    "град ловеч",
    "град монтана",
    "град разград",
    "град силистра",
    "град смолян",
    "град търговище",
    "град видин",
}

capital_center_areas_from_title = {
    "център",
    "идеален център",
    "докторски паметник",
    "яворов",
    "оборише",
    "оборище",
    "лозенец",
    "иван вазов",
    "зона б-5",
    "зона б-18",
    "зона б-19",
    "банишора",
    "сердика",
    "възраждане",
    "медицинска академия",
    "редута",
}


def map_unknown_from_title_city_geo(row):
    title_city = row.get("title_city_model")
    title_geo_2 = row.get("title_geo_2_model")

    title_city = "" if pd.isna(title_city) else str(title_city).strip().lower()
    title_geo_2 = "" if pd.isna(title_geo_2) else str(title_geo_2).strip().lower()

    # Sofia: use title_geo_2 to split center vs non-center
    if title_city == "град софия":
        if title_geo_2 in capital_center_areas_from_title:
            return "capital_center"
        return "capital_non_center"

    # Villages under oblast
    if title_city.startswith("област ") and (
        title_geo_2.startswith("с. ")
        or title_geo_2.startswith("село ")
    ):
        return "village"

    # Towns under oblast
    if title_city.startswith("област ") and (
        title_geo_2.startswith("гр. ")
        or title_geo_2.startswith("град ")
        or title_geo_2.startswith("к.к. ")
    ):
        return "small_city"

    # Large regional city direct
    if title_city in large_regional_city_titles:
        return "large_regional_city"

    # Regional city direct
    if title_city in regional_city_titles:
        return "regional_city"

    # Other direct city
    if title_city.startswith("град "):
        return "small_city"

    # Region without usable settlement detail
    if title_city.startswith("област "):
        return "small_city"

    return "other_unknown"


# Reclassify only remaining other_unknown
remaining_unknown_mask = df_model_base["geo_category"].eq("other_unknown")

reclassified_from_title_fields = df_model_base.loc[remaining_unknown_mask].copy()

df_model_base.loc[remaining_unknown_mask, "geo_category"] = (
    df_model_base.loc[remaining_unknown_mask]
    .apply(map_unknown_from_title_city_geo, axis=1)
)

print("Rows before:", before_rows)
print("Rows after:", len(df_model_base))
print("Rows reclassified from title fields:", len(reclassified_from_title_fields))

print("\nUpdated geo_category distribution:")
display(
    df_model_base["geo_category"]
    .value_counts(dropna=False)
    .rename_axis("geo_category")
    .reset_index(name="rows")
)

remaining_other_unknown = df_model_base.loc[
    df_model_base["geo_category"].eq("other_unknown")
].copy()

print("\nRemaining other_unknown rows:", len(remaining_other_unknown))

display(
    remaining_other_unknown[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_raw",
            "title_geo_2_raw",
            "location_raw",
            "title_city_model",
            "title_geo_2_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)

cleanup_actions.append({
    "rule": "drop_greece_by_title_city",
    "reason": "Greece listings are outside the Bulgarian target market; title_city_raw is the reliable field when location_raw is corrupted",
    "rows_affected": len(dropped_greece_title_city),
})

cleanup_actions.append({
    "rule": "reclassify_other_unknown_using_title_city_and_geo_2",
    "reason": "Rows with corrupted location_raw were reclassified using title_city_raw and title_geo_2_raw, preserving village vs small-city distinction",
    "rows_affected": len(reclassified_from_title_fields),
})

Dropped Greece rows: 1
Rows before: 159467
Rows after: 159466
Rows reclassified from title fields: 313

Updated geo_category distribution:

          geo_category   rows
0  large_regional_city  39254
1              village  29495
2   capital_non_center  29014
3        regional_city  23909
4           sea_resort  16553
5           small_city  11906
6       capital_center   5438
7      mountain_resort   3897

Remaining other_unknown rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_raw, title_geo_2_raw, location_raw, title_city_model, title_geo_2_model, total_price, area_sqm, price_per_sqm]
Index: []

In [54]:
# ------------------------------------------------------------
# Normalize title_city_raw and title_geo_2_raw
# - lowercase
# - trim whitespace
# - remove settlement prefixes from title_geo_2
# ------------------------------------------------------------

df_model_base = df_model_base.copy()


def normalize_bg_text(value):
    if pd.isna(value):
        return pd.NA

    value = str(value).strip().lower()
    value = value.replace("ё", "е")
    value = value.replace("̀", "")
    value = value.replace("'", "")
    value = value.replace('"', "")
    value = " ".join(value.split())

    if value in {"", "none", "nan", "<na>"}:
        return pd.NA

    return value


def remove_geo_prefix(value):
    if pd.isna(value):
        return pd.NA

    value = normalize_bg_text(value)

    if pd.isna(value):
        return pd.NA

    prefixes = [
        "гр. ",
        "град ",
        "с. ",
        "село ",
        "к.к. ",
        "кк ",
        "курорт ",
        "ж.к. ",
        "кв. ",
        "м-т ",
        "м. ",
        "местност ",
        "в.з. ",
        "с.о. ",
        "п.к. ",
    ]

    changed = True
    while changed:
        changed = False

        for prefix in prefixes:
            if value.startswith(prefix):
                value = value[len(prefix):].strip()
                changed = True

    return value if value else pd.NA


# Normalized city field
df_model_base["title_city_model"] = (
    df_model_base["title_city_raw"]
    .apply(normalize_bg_text)
)

# Normalized geo_2 field, with prefix removed
df_model_base["title_geo_2_model"] = (
    df_model_base["title_geo_2_raw"]
    .apply(remove_geo_prefix)
)


print("Unique title_city_raw:", df_model_base["title_city_raw"].nunique(dropna=False))
print("Unique title_city_model:", df_model_base["title_city_model"].nunique(dropna=False))

print("Unique title_geo_2_raw:", df_model_base["title_geo_2_raw"].nunique(dropna=False))
print("Unique title_geo_2_model:", df_model_base["title_geo_2_model"].nunique(dropna=False))


print("\nTop title_city_model:")
display(
    df_model_base["title_city_model"]
    .value_counts(dropna=False)
    .head(50)
    .rename_axis("title_city_model")
    .reset_index(name="rows")
)

print("\nTop title_geo_2_model:")
display(
    df_model_base["title_geo_2_model"]
    .value_counts(dropna=False)
    .head(100)
    .rename_axis("title_geo_2_model")
    .reset_index(name="rows")
)


cleanup_actions.append({
    "rule": "normalize_title_city_and_geo_2",
    "reason": "Created lowercase normalized location fields and removed settlement/location prefixes from title_geo_2 for cleaner geo mapping",
    "rows_affected": 0,
    "columns_added": 2,
})

Unique title_city_raw: 54
Unique title_city_model: 54
Unique title_geo_2_raw: 3593
Unique title_geo_2_model: 3462

Top title_city_model:

         title_city_model   rows
0              град софия  34452
1           област бургас  17875
2              град варна  17606
3            град пловдив  17162
4          област пловдив   7792
5            област софия   5025
6             град бургас   4486
7   област велико търново   3821
8            област варна   3742
9           област добрич   3444
10      град стара загора   3386
11              град русе   3116
12            град плевен   2761
13             град шумен   2760
14     област благоевград   2657
15    област стара загора   2053
16    град велико търново   2029
17       област пазарджик   1963
18          област перник   1638
19         област габрово   1620
20           област ловеч   1619
21          град кърджали   1271
22            град перник   1259
23           област шумен   1124
24            област русе   1055
25          област плевен   1026
26             град враца    962
27       област кюстендил    883
28         област хасково    853
29         град пазарджик    832
30          област смолян    804
31           град габрово    778
32       град благоевград    746
33            град добрич    725
34           град хасково    705
35         град търговище    584
36           област враца    539
37        област кърджали    537
38         област монтана    342
39           град разград    332
40           град монтана    324
41             град видин    298
42             град ловеч    280
43            град сливен    264
44           област видин    259
45       област търговище    238
46           област ямбол    229
47             град ямбол    207
48          област сливен    201
49            град смолян    199

Top title_geo_2_model:

    title_geo_2_model   rows
0              център  10676
1        слънчев бряг   2936
2          свети влас   2525
3   христо смирненски   2386
4     малинова долина   2276
..                ...    ...
95       възраждане 3    301
96              елена    298
97           казанлък    285
98             герман    277
99      хаджи димитър    276

[100 rows x 2 columns]

In [55]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 36 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ad_id                   159466 non-null  object
 1   ad_url                  159466 non-null  object
 2   listing_type            159466 non-null  object
 3   property_type_raw       159466 non-null  object
 4   title_city_raw          159466 non-null  object
 5   title_geo_2_raw         159463 non-null  object
 6   title_area_sqm          157231 non-null  float64
 7   seller_name_raw         149523 non-null  object
 8   total_price             159466 non-null  float64
 9   currency                159466 non-null  object
 10  vat_status              159466 non-null  object
 11  area_sqm                159466 non-null  float64
 12  price_per_sqm           159466 non-null  float64
 13  floor                   97454 non-null   float64
 14  total_floors            90480 non-null   float64
 15  construction_type       120724 non-null  object
 16  construction_year       159466 non-null  int64
 17  location_raw            159466 non-null  object
 18  features_pipe           139702 non-null  object
 19  features_count          159466 non-null  int64
 20  published_raw           41998 non-null   object
 21  views                   159466 non-null  float64
 22  area_sqm_raw            159466 non-null  float64
 23  price_per_sqm_raw       159466 non-null  float64
 24  location_level_1        159466 non-null  object
 25  location_level_2        159397 non-null  object
 26  location_level_3        24383 non-null   object
 27  location_level_1_model  159466 non-null  string
 28  location_level_2_model  159397 non-null  string
 29  location_level_3_model  24383 non-null   string
 30  geo_category            159466 non-null  object
 31  location_level_1_norm   159466 non-null  object
 32  location_level_2_norm   159466 non-null  object
 33  location_level_3_norm   159466 non-null  object
 34  title_city_model        159466 non-null  object
 35  title_geo_2_model       159463 non-null  object
dtypes: float64(9), int64(2), object(22), string(3)
memory usage: 45.0+ MB

In [56]:
# ------------------------------------------------------------
# Keep only useful columns and overwrite df_model_base
# ------------------------------------------------------------

useful_columns = [
    # Traceability
    "ad_id",
    "ad_url",

    # Core listing attributes
    "listing_type",
    "property_type_raw",

    # Target / price
    "total_price",
    "currency",
    "vat_status",
    "area_sqm",
    "price_per_sqm",

    # Building / physical features
    "floor",
    "total_floors",
    "construction_type",
    "construction_year",

    # Clean geo features
    "title_city_model",
    "title_geo_2_model",
    "geo_category",

    # Feature engineering inputs
    "features_pipe",
    "features_count",

    # Listing metadata
    "views",
]

df_model_base = df_model_base[useful_columns].copy()

print("Rows:", len(df_model_base))
print("Columns:", df_model_base.shape[1])

display(df_model_base.info())

Rows: 159466
Columns: 19
<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ad_id              159466 non-null  object
 1   ad_url             159466 non-null  object
 2   listing_type       159466 non-null  object
 3   property_type_raw  159466 non-null  object
 4   total_price        159466 non-null  float64
 5   currency           159466 non-null  object
 6   vat_status         159466 non-null  object
 7   area_sqm           159466 non-null  float64
 8   price_per_sqm      159466 non-null  float64
 9   floor              97454 non-null   float64
 10  total_floors       90480 non-null   float64
 11  construction_type  120724 non-null  object
 12  construction_year  159466 non-null  int64
 13  title_city_model   159466 non-null  object
 14  title_geo_2_model  159463 non-null  object
 15  geo_category       159466 non-null  object
 16  features_pipe      139702 non-null  object
 17  features_count     159466 non-null  int64
 18  views              159466 non-null  float64
dtypes: float64(6), int64(2), object(11)
memory usage: 24.3+ MB

None

In [57]:
# ------------------------------------------------------------
# Explore construction_type and construction_year
# ------------------------------------------------------------

print("Rows:", len(df_model_base))

print("\nconstruction_type missing:")
print(df_model_base["construction_type"].isna().sum())
print(round(df_model_base["construction_type"].isna().mean() * 100, 2), "%")

print("\nconstruction_type distribution:")
display(
    df_model_base["construction_type"]
    .value_counts(dropna=False)
    .rename_axis("construction_type")
    .reset_index(name="rows")
)

print("\nconstruction_year summary:")
display(
    df_model_base["construction_year"]
    .describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999])
)

Rows: 159466

construction_type missing:
38742
24.29 %

construction_type distribution:

       construction_type    rows
0                  Тухла  107224
1                   None   38742
2                  Панел    7358
3               Гредоред    3000
4                    ЕПК    1864
5  Сглобяема конструкция     588
6      Ново строителство     482
7                Монолит     152
8           Стоманобетон      44
9     Старо строителство      12

construction_year summary:

count    159466.000000
mean       2017.746824
std          16.849006
min        1950.000000
0.1%       1950.000000
0.5%       1950.000000
1%         1960.000000
5%         1980.000000
50%        2026.000000
95%        2027.000000
99%        2028.000000
99.5%      2029.000000
99.9%      2030.000000
max        2049.000000
Name: construction_year, dtype: float64

In [58]:
# ------------------------------------------------------------
# Inspect suspicious construction_year values
# ------------------------------------------------------------

suspicious_years = df_model_base.loc[
    (df_model_base["construction_year"] <= 1800)
    | (df_model_base["construction_year"] > 2035)
].copy()

print("Suspicious construction_year rows:", len(suspicious_years))

display(
    suspicious_years[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_year",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values("construction_year")
    .head(100)
)

Suspicious construction_year rows: 86

                    ad_id                                                                                                ad_url property_type_raw     title_city_model   title_geo_2_model         geo_category construction_type  construction_year  total_price  area_sqm  price_per_sqm
123501  1r141093463707645      https://www.imot.bg/obiava-1r141093463707645-prodava-partsel-oblast-pleven-s-yasen-do-detelinata            ПАРЦЕЛ        област плевен                ясен              village              None               2036      14000.0    2036.0           6.88
123935  1r149211805106805                     https://www.imot.bg/obiava-1r149211805106805-prodava-partsel-grad-sofiya-lyulin-5            ПАРЦЕЛ           град софия             люлин 5   capital_non_center              None               2036     420000.0    2036.0         206.29
106813  1j177503553254998  https://www.imot.bg/obiava-1j177503553254998-prodava-kashta-oblast-stara-zagora-s-starozagorski-bani              КЪЩА  област стара загора  старозагорски бани              village             Тухла               2036     295000.0     300.0         983.33
130793  1r170239284876614                      https://www.imot.bg/obiava-1r170239284876614-prodava-partsel-grad-sofiya-s-lozen            ПАРЦЕЛ           град софия               лозен   capital_non_center              None               2036     244400.0    2036.0         120.04
142640  1r175275665954514          https://www.imot.bg/obiava-1r175275665954514-prodava-partsel-oblast-pernik-magistrala-lyulin            ПАРЦЕЛ        област перник    магистрала люлин           small_city              None               2036     420000.0    2036.0         206.29
...                   ...                                                                                                   ...               ...                  ...                 ...                  ...               ...                ...          ...       ...            ...
157265  1r177788627944412                https://www.imot.bg/obiava-1r177788627944412-prodava-partsel-grad-sofiya-m-t-yaz-iskar            ПАРЦЕЛ           град софия           яз. искър   capital_non_center              None               2048     179995.0    2048.0          87.89
150859  1r177002934856978     https://www.imot.bg/obiava-1r177002934856978-prodava-partsel-grad-plovdiv-industrialna-zona-sever            ПАРЦЕЛ         град пловдив   индустриална зона  large_regional_city              None               2048     103000.0    2048.0          50.29
127187  1r165451031003426                  https://www.imot.bg/obiava-1r165451031003426-prodava-partsel-grad-sofiya-s-busmantsi            ПАРЦЕЛ           град софия            бусманци   capital_non_center              None               2049     160000.0    2049.0          78.09
152491  1r177221122834853                      https://www.imot.bg/obiava-1r177221122834853-prodava-partsel-grad-ruse-druzhba-3            ПАРЦЕЛ            град русе            дружба 3        regional_city              None               2049      80000.0    2049.0          39.04
148317  1r176485620257607          https://www.imot.bg/obiava-1r176485620257607-prodava-partsel-oblast-stara-zagora-s-novo-selo            ПАРЦЕЛ  област стара загора           ново село              village              None               2049      20000.0    2049.0           9.76

[86 rows x 11 columns]

In [59]:
# ------------------------------------------------------------
# construction_type x construction_year profile
# ------------------------------------------------------------

construction_profile = (
    df_model_base
    .groupby("construction_type", dropna=False)
    .agg(
        rows=("ad_id", "count"),
        min_year=("construction_year", "min"),
        p05_year=("construction_year", lambda s: s.quantile(0.05)),
        median_year=("construction_year", "median"),
        p95_year=("construction_year", lambda s: s.quantile(0.95)),
        max_year=("construction_year", "max"),
        median_price=("total_price", "median"),
        median_ppsqm=("price_per_sqm", "median"),
    )
    .reset_index()
    .sort_values("rows", ascending=False)
)

display(construction_profile)

       construction_type    rows  min_year  p05_year  median_year  p95_year  max_year  median_price  median_ppsqm
8                  Тухла  107224      1950   1970.00       2026.0    2028.0      2048    150000.000      1555.560
9                    NaN   38742      1950   2022.00       2026.0    2026.0      2049     71400.000        47.480
4                  Панел    7358      1950   1970.00       1990.0    2026.0      2040    120000.000      1581.535
0               Гредоред    3000      1950   1950.00       2025.0    2026.0      2032     43379.905       442.795
1                    ЕПК    1864      1950   1970.00       1990.0    2026.0      2028    150000.000      1907.580
5  Сглобяема конструкция     588      1960   1990.00       2025.0    2026.0      2029    130000.000       747.500
3      Ново строителство     482      1960   2023.00       2026.0    2026.0      2026     66467.470       140.030
2                Монолит     152      1960   2000.00       2026.0    2026.0      2026     44229.905       102.190
7           Стоманобетон      44      1970   2009.15       2026.0    2026.0      2027    243500.000        89.155
6     Старо строителство      12      1990   2009.25       2026.0    2026.0      2026     20999.500       694.445

In [60]:
# ------------------------------------------------------------
# Inspect land-related listings vs missing construction fields
# ------------------------------------------------------------

land_property_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

df_land_check = df_model_base.copy()

df_land_check["is_land_related"] = df_land_check["property_type_raw"].isin(land_property_types)

# 1. Count land vs non-land
print("Land-related rows:")
display(
    df_land_check["is_land_related"]
    .value_counts(dropna=False)
    .rename_axis("is_land_related")
    .reset_index(name="rows")
)

# 2. Property type distribution for land-related candidates
print("\nLand-related property_type_raw distribution:")
display(
    df_land_check.loc[df_land_check["is_land_related"], "property_type_raw"]
    .value_counts(dropna=False)
    .rename_axis("property_type_raw")
    .reset_index(name="rows")
)

# 3. Compare missing construction_type by land flag
print("\nMissing construction_type by land flag:")
display(
    df_land_check
    .assign(construction_type_missing=df_land_check["construction_type"].isna())
    .groupby("is_land_related")
    .agg(
        rows=("ad_id", "count"),
        missing_construction_type=("construction_type_missing", "sum"),
        missing_construction_type_pct=("construction_type_missing", lambda s: round(s.mean() * 100, 2)),
        non_missing_construction_type=("construction_type", lambda s: s.notna().sum()),
    )
    .reset_index()
)

# 4. Construction year completeness by land flag
print("\nConstruction year check by land flag:")
display(
    df_land_check
    .assign(
        construction_year_missing=df_land_check["construction_year"].isna(),
        construction_year_zero=df_land_check["construction_year"].eq(0),
        construction_year_positive=df_land_check["construction_year"].gt(0),
    )
    .groupby("is_land_related")
    .agg(
        rows=("ad_id", "count"),
        missing_year=("construction_year_missing", "sum"),
        zero_year=("construction_year_zero", "sum"),
        positive_year=("construction_year_positive", "sum"),
        min_year=("construction_year", "min"),
        median_year=("construction_year", "median"),
        max_year=("construction_year", "max"),
    )
    .reset_index()
)

# 5. Cross-tab: land-related vs construction_type
print("\nconstruction_type distribution for land-related rows:")
display(
    df_land_check.loc[df_land_check["is_land_related"], "construction_type"]
    .value_counts(dropna=False)
    .rename_axis("construction_type")
    .reset_index(name="rows")
)

# 6. Land rows with non-null construction_type
print("\nLand rows with non-null construction_type:")
land_with_construction_type = df_land_check.loc[
    df_land_check["is_land_related"]
    & df_land_check["construction_type"].notna()
].copy()

print("Rows:", len(land_with_construction_type))

display(
    land_with_construction_type[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_year",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .head(100)
)

Land-related rows:

   is_land_related    rows
0            False  122212
1             True   37254

Land-related property_type_raw distribution:

  property_type_raw   rows
0            ПАРЦЕЛ  35019
1   ЗЕМЕДЕЛСКА ЗЕМЯ   2235

Missing construction_type by land flag:

   is_land_related    rows  missing_construction_type  missing_construction_type_pct  non_missing_construction_type
0            False  122212                       2189                           1.79                         120023
1             True   37254                      36553                          98.12                            701

Construction year check by land flag:

   is_land_related    rows  missing_year  zero_year  positive_year  min_year  median_year  max_year
0            False  122212             0          0         122212      1950       2026.0      2048
1             True   37254             0          0          37254      1950       2026.0      2049

construction_type distribution for land-related rows:

       construction_type   rows
0                   None  36553
1      Ново строителство    349
2                  Панел    159
3                Монолит    103
4           Стоманобетон     30
5  Сглобяема конструкция     23
6               Гредоред     16
7                  Тухла     16
8     Старо строителство      4
9                    ЕПК      1

Land rows with non-null construction_type:
Rows: 701

                    ad_id                                                                                                       ad_url property_type_raw  title_city_model title_geo_2_model         geo_category      construction_type  construction_year  total_price  area_sqm  price_per_sqm
122795  1r117222015891705  https://www.imot.bg/obiava-1r117222015891705-prodava-partsel-oblast-sofiya-s-herakovo-boben-mestnost-gerena            ПАРЦЕЛ      област софия          хераково              village      Ново строителство               2026     54825.00     731.0          75.00
122842  1r121939266470060                            https://www.imot.bg/obiava-1r121939266470060-prodava-partsel-grad-gabrovo-tsentar            ПАРЦЕЛ      град габрово            център        regional_city                Монолит               2026    133680.00    3342.0          40.00
122843  1r121939503137224                            https://www.imot.bg/obiava-1r121939503137224-prodava-partsel-grad-gabrovo-tsentar            ПАРЦЕЛ      град габрово            център        regional_city                Монолит               2000     90000.00    2000.0          45.00
122844  1r121939276274603                      https://www.imot.bg/obiava-1r121939276274603-prodava-partsel-oblast-gabrovo-s-kmetovtsi            ПАРЦЕЛ    област габрово          кметовци              village                Монолит               2026     15338.76     854.0          17.96
122881  1r122156113495258                  https://www.imot.bg/obiava-1r122156113495258-prodava-partsel-oblast-sofiya-s-herakovo-boben            ПАРЦЕЛ      област софия          хераково              village      Ново строителство               2026    106650.00    1422.0          75.00
...                   ...                                                                                                          ...               ...               ...               ...                  ...                    ...                ...          ...       ...            ...
129663  1r169147757241353                       https://www.imot.bg/obiava-1r169147757241353-prodava-partsel-oblast-dobrich-s-snyagovo            ПАРЦЕЛ     област добрич           снягово              village                  Панел               2023    138810.00   13881.0          10.00
129723  1r169217424964662                    https://www.imot.bg/obiava-1r169217424964662-prodava-partsel-oblast-sofiya-gr-bozhurishte            ПАРЦЕЛ      област софия          божурище           small_city      Ново строителство               2026     68000.00     800.0          85.00
129752  1r169234995761783                  https://www.imot.bg/obiava-1r169234995761783-prodava-partsel-oblast-pazardzhik-s-zhrebichko            ПАРЦЕЛ  област пазарджик          жребичко              village                Монолит               2026     45000.00     346.0         130.06
129984  1r169505445719617              https://www.imot.bg/obiava-1r169505445719617-prodava-partsel-oblast-shumen-gr-novi-pazar-s-stan            ПАРЦЕЛ      област шумен        нови пазар           small_city  Сглобяема конструкция               2024     15338.76     710.0          21.60
130047  1r169563809121530                           https://www.imot.bg/obiava-1r169563809121530-prodava-partsel-grad-varna-m-t-priboy            ПАРЦЕЛ        град варна            прибой  large_regional_city      Ново строителство               2026    621000.00    5400.0         115.00

[100 rows x 11 columns]

In [61]:
# ------------------------------------------------------------
# Clean construction fields for land-related property types
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

land_property_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
}

is_land_related = df_model_base["property_type_raw"].isin(land_property_types)

# Create model-safe construction fields
df_model_base["construction_type_model"] = df_model_base["construction_type"]
df_model_base["construction_year_model"] = df_model_base["construction_year"].astype("float")

# For land, construction fields are not applicable
df_model_base.loc[is_land_related, "construction_type_model"] = "not_applicable_land"
df_model_base.loc[is_land_related, "construction_year_model"] = pd.NA

print("Land-related rows:", is_land_related.sum())

print("\nconstruction_type_model distribution:")
display(
    df_model_base["construction_type_model"]
    .value_counts(dropna=False)
    .rename_axis("construction_type_model")
    .reset_index(name="rows")
)

print("\nconstruction_year_model summary, non-land only:")
display(
    df_model_base.loc[~is_land_related, "construction_year_model"]
    .describe(percentiles=[0.001, 0.005, 0.01, 0.05, 0.5, 0.95, 0.99, 0.995, 0.999])
)

cleanup_actions.append({
    "rule": "set_construction_fields_not_applicable_for_land",
    "reason": "Land listings had nonsensical construction_type/construction_year values such as Панел, Монолит, and Ново строителство; these fields are not applicable to land",
    "rows_affected": int(is_land_related.sum()),
})

Land-related rows: 37254

construction_type_model distribution:

   construction_type_model    rows
0                    Тухла  107208
1      not_applicable_land   37254
2                    Панел    7199
3                 Гредоред    2984
4                     None    2189
5                      ЕПК    1863
6    Сглобяема конструкция     565
7        Ново строителство     133
8                  Монолит      49
9             Стоманобетон      14
10      Старо строителство       8

construction_year_model summary, non-land only:

count    122212.000000
mean       2015.582864
std          18.485471
min        1950.000000
0.1%       1950.000000
0.5%       1950.000000
1%         1960.000000
5%         1970.000000
50%        2026.000000
95%        2028.000000
99%        2028.000000
99.5%      2029.000000
99.9%      2029.000000
max        2048.000000
Name: construction_year_model, dtype: float64

In [62]:
# ------------------------------------------------------------
# Inspect suspicious construction years for non-land buildings only
# ------------------------------------------------------------

non_land = ~df_model_base["property_type_raw"].isin(land_property_types)

suspicious_building_years = df_model_base.loc[
    non_land
    & (
        df_model_base["construction_year_model"].isna()
        | df_model_base["construction_year_model"].le(1800)
        | df_model_base["construction_year_model"].gt(2035)
    )
].copy()

print("Suspicious non-land construction_year rows:", len(suspicious_building_years))

display(
    suspicious_building_years[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "construction_type",
            "construction_type_model",
            "construction_year",
            "construction_year_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["construction_year_model", "property_type_raw"], na_position="first")
    .head(100)
)

Suspicious non-land construction_year rows: 26

                    ad_id                                                                                                                          ad_url     property_type_raw     title_city_model   title_geo_2_model         geo_category construction_type construction_type_model  construction_year  construction_year_model  total_price  area_sqm  price_per_sqm
106813  1j177503553254998                            https://www.imot.bg/obiava-1j177503553254998-prodava-kashta-oblast-stara-zagora-s-starozagorski-bani                  КЪЩА  област стара загора  старозагорски бани              village             Тухла                   Тухла               2036                   2036.0     295000.0     300.0         983.33
16660   1b175939463648337  https://www.imot.bg/obiava-1b175939463648337-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16711   1b175942336350299  https://www.imot.bg/obiava-1b175942336350299-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16713   1b175942646181887  https://www.imot.bg/obiava-1b175942646181887-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16714   1b175942739693686  https://www.imot.bg/obiava-1b175942739693686-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16717   1b175947149899002  https://www.imot.bg/obiava-1b175947149899002-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16719   1b175947246966478  https://www.imot.bg/obiava-1b175947246966478-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-96               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      85200.0      71.0        1200.00
16720   1b175947177600145  https://www.imot.bg/obiava-1b175947177600145-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16734   1b175947094326386  https://www.imot.bg/obiava-1b175947094326386-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
52105   1c175939413046355  https://www.imot.bg/obiava-1c175939413046355-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     157300.0     121.0        1300.00
52130   1c175942595661197  https://www.imot.bg/obiava-1c175942595661197-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     157300.0     121.0        1300.00
52134   1c175942704703701  https://www.imot.bg/obiava-1c175942704703701-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     149500.0     115.0        1300.00
52141   1c175947126668213  https://www.imot.bg/obiava-1c175947126668213-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     148200.0     114.0        1300.00
52142   1c175947210627923  https://www.imot.bg/obiava-1c175947210627923-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     143000.0     110.0        1300.00
52144   1c175947323261485                          https://www.imot.bg/obiava-1c175947323261485-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2040                   2040.0     136500.0     105.0        1300.00
52153   1c175947380590029                          https://www.imot.bg/obiava-1c175947380590029-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2040                   2040.0     154700.0     119.0        1300.00
52154   1c175942777587753  https://www.imot.bg/obiava-1c175942777587753-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     149500.0     115.0        1300.00
82515   1f172961668221214                              https://www.imot.bg/obiava-1f172961668221214-prodava-mezonet-grad-sofiya-gotse-delchev-ul-lui-ayer               МЕЗОНЕТ           град софия         гоце делчев   capital_non_center             Тухла                   Тухла               2040                   2040.0     340000.0     200.0        1700.00
120894  1p174833764685538                                 https://www.imot.bg/obiava-1p174833764685538-prodava-promishleno-pomeshtenie-grad-sofiya-obelya       ПРОМ. ПОМЕЩЕНИЕ           град софия               обеля   capital_non_center             Панел                   Панел               2040                   2040.0    2550000.0    2040.0        1250.00
121002  1p175338395348022                              https://www.imot.bg/obiava-1p175338395348022-prodava-promishleno-pomeshtenie-grad-sofiya-s-voluyak       ПРОМ. ПОМЕЩЕНИЕ           град софия              волуяк   capital_non_center             Панел                   Панел               2040                   2040.0    2448000.0    2040.0        1200.00
117010  1n175471955713641                                              https://www.imot.bg/obiava-1n175471955713641-prodava-sklad-grad-sofiya-vrabnitsa-2                 СКЛАД           град софия          връбница 2   capital_non_center             Панел                   Панел               2040                   2040.0    2550000.0    2040.0        1250.00
120636  1p173338715705181                 https://www.imot.bg/obiava-1p173338715705181-prodava-promishleno-pomeshtenie-grad-plovdiv-industrialna-zona-yug       ПРОМ. ПОМЕЩЕНИЕ         град пловдив   индустриална зона  large_regional_city             Тухла                   Тухла               2042                   2042.0    2500000.0    2042.0        1224.29
105460  1j177343897083535                                            https://www.imot.bg/obiava-1j177343897083535-prodava-kashta-oblast-dobrich-s-dabovik                  КЪЩА        област добрич             дъбовик              village             Тухла                   Тухла               2044                   2044.0      32000.0    2044.0          15.66
120571  1p172588346121420                            https://www.imot.bg/obiava-1p172588346121420-prodava-promishleno-pomeshtenie-oblast-dobrich-s-pobeda       ПРОМ. ПОМЕЩЕНИЕ        област добрич              победа              village             Тухла                   Тухла               2046                   2046.0     435000.0    2046.0         212.61
163157  1t176354667650491                                  https://www.imot.bg/obiava-1t176354667650491-prodava-biznes-imot-grad-pleven-industrialna-zona  САМОСТОЯТЕЛНА СГРАДА          град плевен   индустриална зона        regional_city             Тухла                   Тухла               2047                   2047.0     700000.0    2047.0         341.96
120553  1p172440864698814                                https://www.imot.bg/obiava-1p172440864698814-prodava-promishleno-pomeshtenie-grad-sliven-tsentar       ПРОМ. ПОМЕЩЕНИЕ          град сливен              център        regional_city             Тухла                   Тухла               2048                   2048.0    1300000.0    2048.0         634.77

In [63]:
# ------------------------------------------------------------
# Manually correct confirmed construction_year parser errors
# ------------------------------------------------------------

manual_year_corrections = {
    # Previously confirmed
    "1t176354667650491": 1970,
    "1p172440864698814": 1970,

    # Newly confirmed
    "1p172588346121420": 1980,
    "1j177343897083535": 1960,  # true unknown, pragmatic proxy
    "1p173338715705181": 2023,
    "1n175471955713641": 2025,
    "1p175338395348022": 2016,
    "1p174833764685538": 2025,
    "1f172961668221214": 2020,  # true unknown, pragmatic proxy

    # All of these should be 2026
    "1j177503553254998": 2026,
    "1b175939463648337": 2026,
    "1b175942336350299": 2026,
    "1b175942646181887": 2026,
    "1b175942739693686": 2026,
    "1b175947149899002": 2026,
    "1b175947246966478": 2026,
    "1b175947177600145": 2026,
    "1b175947094326386": 2026,
    "1c175939413046355": 2026,
    "1c175942595661197": 2026,
    "1c175942704703701": 2026,
    "1c175947126668213": 2026,
    "1c175947210627923": 2026,
    "1c175947323261485": 2026,
    "1c175947380590029": 2026,
    "1c175942777587753": 2026,
}

# Check whether all provided ad_ids exist
provided_ids = set(manual_year_corrections.keys())
existing_ids = set(df_model_base["ad_id"])

missing_ids = sorted(provided_ids - existing_ids)

if missing_ids:
    print("WARNING - these ad_ids were not found in df_model_base:")
    print(missing_ids)

before_values = df_model_base.loc[
    df_model_base["ad_id"].isin(provided_ids),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type",
        "construction_type_model",
        "construction_year",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

for ad_id, corrected_year in manual_year_corrections.items():
    mask = df_model_base["ad_id"].eq(ad_id)

    df_model_base.loc[mask, "construction_year"] = corrected_year
    df_model_base.loc[mask, "construction_year_model"] = corrected_year

after_values = df_model_base.loc[
    df_model_base["ad_id"].isin(provided_ids),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type",
        "construction_type_model",
        "construction_year",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

print("Provided correction IDs:", len(provided_ids))
print("Corrected rows found:", len(after_values))
print("Missing IDs:", len(missing_ids))

print("\nBefore:")
display(before_values.sort_values("ad_id"))

print("\nAfter:")
display(after_values.sort_values("ad_id"))

cleanup_actions.append({
    "rule": "manual_correct_future_construction_years_extended",
    "reason": "Confirmed parser errors in future construction years; manually corrected based on listing inspection",
    "rows_affected": len(after_values),
})

Provided correction IDs: 26
Corrected rows found: 26
Missing IDs: 0

Before:

                    ad_id                                                                                                                          ad_url     property_type_raw     title_city_model   title_geo_2_model         geo_category construction_type construction_type_model  construction_year  construction_year_model  total_price  area_sqm  price_per_sqm
16660   1b175939463648337  https://www.imot.bg/obiava-1b175939463648337-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16711   1b175942336350299  https://www.imot.bg/obiava-1b175942336350299-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16713   1b175942646181887  https://www.imot.bg/obiava-1b175942646181887-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16714   1b175942739693686  https://www.imot.bg/obiava-1b175942739693686-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16734   1b175947094326386  https://www.imot.bg/obiava-1b175947094326386-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16717   1b175947149899002  https://www.imot.bg/obiava-1b175947149899002-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16720   1b175947177600145  https://www.imot.bg/obiava-1b175947177600145-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      93600.0      72.0        1300.00
16719   1b175947246966478  https://www.imot.bg/obiava-1b175947246966478-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-96               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0      85200.0      71.0        1200.00
52105   1c175939413046355  https://www.imot.bg/obiava-1c175939413046355-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     157300.0     121.0        1300.00
52130   1c175942595661197  https://www.imot.bg/obiava-1c175942595661197-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     157300.0     121.0        1300.00
52134   1c175942704703701  https://www.imot.bg/obiava-1c175942704703701-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     149500.0     115.0        1300.00
52154   1c175942777587753  https://www.imot.bg/obiava-1c175942777587753-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     149500.0     115.0        1300.00
52141   1c175947126668213  https://www.imot.bg/obiava-1c175947126668213-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     148200.0     114.0        1300.00
52142   1c175947210627923  https://www.imot.bg/obiava-1c175947210627923-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2040                   2040.0     143000.0     110.0        1300.00
52144   1c175947323261485                          https://www.imot.bg/obiava-1c175947323261485-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2040                   2040.0     136500.0     105.0        1300.00
52153   1c175947380590029                          https://www.imot.bg/obiava-1c175947380590029-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2040                   2040.0     154700.0     119.0        1300.00
82515   1f172961668221214                              https://www.imot.bg/obiava-1f172961668221214-prodava-mezonet-grad-sofiya-gotse-delchev-ul-lui-ayer               МЕЗОНЕТ           град софия         гоце делчев   capital_non_center             Тухла                   Тухла               2040                   2040.0     340000.0     200.0        1700.00
105460  1j177343897083535                                            https://www.imot.bg/obiava-1j177343897083535-prodava-kashta-oblast-dobrich-s-dabovik                  КЪЩА        област добрич             дъбовик              village             Тухла                   Тухла               2044                   2044.0      32000.0    2044.0          15.66
106813  1j177503553254998                            https://www.imot.bg/obiava-1j177503553254998-prodava-kashta-oblast-stara-zagora-s-starozagorski-bani                  КЪЩА  област стара загора  старозагорски бани              village             Тухла                   Тухла               2036                   2036.0     295000.0     300.0         983.33
117010  1n175471955713641                                              https://www.imot.bg/obiava-1n175471955713641-prodava-sklad-grad-sofiya-vrabnitsa-2                 СКЛАД           град софия          връбница 2   capital_non_center             Панел                   Панел               2040                   2040.0    2550000.0    2040.0        1250.00
120553  1p172440864698814                                https://www.imot.bg/obiava-1p172440864698814-prodava-promishleno-pomeshtenie-grad-sliven-tsentar       ПРОМ. ПОМЕЩЕНИЕ          град сливен              център        regional_city             Тухла                   Тухла               2048                   2048.0    1300000.0    2048.0         634.77
120571  1p172588346121420                            https://www.imot.bg/obiava-1p172588346121420-prodava-promishleno-pomeshtenie-oblast-dobrich-s-pobeda       ПРОМ. ПОМЕЩЕНИЕ        област добрич              победа              village             Тухла                   Тухла               2046                   2046.0     435000.0    2046.0         212.61
120636  1p173338715705181                 https://www.imot.bg/obiava-1p173338715705181-prodava-promishleno-pomeshtenie-grad-plovdiv-industrialna-zona-yug       ПРОМ. ПОМЕЩЕНИЕ         град пловдив   индустриална зона  large_regional_city             Тухла                   Тухла               2042                   2042.0    2500000.0    2042.0        1224.29
120894  1p174833764685538                                 https://www.imot.bg/obiava-1p174833764685538-prodava-promishleno-pomeshtenie-grad-sofiya-obelya       ПРОМ. ПОМЕЩЕНИЕ           град софия               обеля   capital_non_center             Панел                   Панел               2040                   2040.0    2550000.0    2040.0        1250.00
121002  1p175338395348022                              https://www.imot.bg/obiava-1p175338395348022-prodava-promishleno-pomeshtenie-grad-sofiya-s-voluyak       ПРОМ. ПОМЕЩЕНИЕ           град софия              волуяк   capital_non_center             Панел                   Панел               2040                   2040.0    2448000.0    2040.0        1200.00
163157  1t176354667650491                                  https://www.imot.bg/obiava-1t176354667650491-prodava-biznes-imot-grad-pleven-industrialna-zona  САМОСТОЯТЕЛНА СГРАДА          град плевен   индустриална зона        regional_city             Тухла                   Тухла               2047                   2047.0     700000.0    2047.0         341.96

After:

                    ad_id                                                                                                                          ad_url     property_type_raw     title_city_model   title_geo_2_model         geo_category construction_type construction_type_model  construction_year  construction_year_model  total_price  area_sqm  price_per_sqm
16660   1b175939463648337  https://www.imot.bg/obiava-1b175939463648337-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16711   1b175942336350299  https://www.imot.bg/obiava-1b175942336350299-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16713   1b175942646181887  https://www.imot.bg/obiava-1b175942646181887-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16714   1b175942739693686  https://www.imot.bg/obiava-1b175942739693686-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16734   1b175947094326386  https://www.imot.bg/obiava-1b175947094326386-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16717   1b175947149899002  https://www.imot.bg/obiava-1b175947149899002-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16720   1b175947177600145  https://www.imot.bg/obiava-1b175947177600145-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      93600.0      72.0        1300.00
16719   1b175947246966478  https://www.imot.bg/obiava-1b175947246966478-prodava-dvustaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-96               2-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0      85200.0      71.0        1200.00
52105   1c175939413046355  https://www.imot.bg/obiava-1c175939413046355-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     157300.0     121.0        1300.00
52130   1c175942595661197  https://www.imot.bg/obiava-1c175942595661197-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     157300.0     121.0        1300.00
52134   1c175942704703701  https://www.imot.bg/obiava-1c175942704703701-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     149500.0     115.0        1300.00
52154   1c175942777587753  https://www.imot.bg/obiava-1c175942777587753-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     149500.0     115.0        1300.00
52141   1c175947126668213  https://www.imot.bg/obiava-1c175947126668213-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     148200.0     114.0        1300.00
52142   1c175947210627923  https://www.imot.bg/obiava-1c175947210627923-prodava-tristaen-apartament-grad-plovdiv-komatevsko-shose-bul-komatevsko-shose-95               3-СТАЕН         град пловдив     коматевско шосе  large_regional_city             Тухла                   Тухла               2026                   2026.0     143000.0     110.0        1300.00
52144   1c175947323261485                          https://www.imot.bg/obiava-1c175947323261485-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2026                   2026.0     136500.0     105.0        1300.00
52153   1c175947380590029                          https://www.imot.bg/obiava-1c175947380590029-prodava-tristaen-apartament-grad-plovdiv-proslav-ul-elena               3-СТАЕН         град пловдив             прослав  large_regional_city             Тухла                   Тухла               2026                   2026.0     154700.0     119.0        1300.00
82515   1f172961668221214                              https://www.imot.bg/obiava-1f172961668221214-prodava-mezonet-grad-sofiya-gotse-delchev-ul-lui-ayer               МЕЗОНЕТ           град софия         гоце делчев   capital_non_center             Тухла                   Тухла               2020                   2020.0     340000.0     200.0        1700.00
105460  1j177343897083535                                            https://www.imot.bg/obiava-1j177343897083535-prodava-kashta-oblast-dobrich-s-dabovik                  КЪЩА        област добрич             дъбовик              village             Тухла                   Тухла               1960                   1960.0      32000.0    2044.0          15.66
106813  1j177503553254998                            https://www.imot.bg/obiava-1j177503553254998-prodava-kashta-oblast-stara-zagora-s-starozagorski-bani                  КЪЩА  област стара загора  старозагорски бани              village             Тухла                   Тухла               2026                   2026.0     295000.0     300.0         983.33
117010  1n175471955713641                                              https://www.imot.bg/obiava-1n175471955713641-prodava-sklad-grad-sofiya-vrabnitsa-2                 СКЛАД           град софия          връбница 2   capital_non_center             Панел                   Панел               2025                   2025.0    2550000.0    2040.0        1250.00
120553  1p172440864698814                                https://www.imot.bg/obiava-1p172440864698814-prodava-promishleno-pomeshtenie-grad-sliven-tsentar       ПРОМ. ПОМЕЩЕНИЕ          град сливен              център        regional_city             Тухла                   Тухла               1970                   1970.0    1300000.0    2048.0         634.77
120571  1p172588346121420                            https://www.imot.bg/obiava-1p172588346121420-prodava-promishleno-pomeshtenie-oblast-dobrich-s-pobeda       ПРОМ. ПОМЕЩЕНИЕ        област добрич              победа              village             Тухла                   Тухла               1980                   1980.0     435000.0    2046.0         212.61
120636  1p173338715705181                 https://www.imot.bg/obiava-1p173338715705181-prodava-promishleno-pomeshtenie-grad-plovdiv-industrialna-zona-yug       ПРОМ. ПОМЕЩЕНИЕ         град пловдив   индустриална зона  large_regional_city             Тухла                   Тухла               2023                   2023.0    2500000.0    2042.0        1224.29
120894  1p174833764685538                                 https://www.imot.bg/obiava-1p174833764685538-prodava-promishleno-pomeshtenie-grad-sofiya-obelya       ПРОМ. ПОМЕЩЕНИЕ           град софия               обеля   capital_non_center             Панел                   Панел               2025                   2025.0    2550000.0    2040.0        1250.00
121002  1p175338395348022                              https://www.imot.bg/obiava-1p175338395348022-prodava-promishleno-pomeshtenie-grad-sofiya-s-voluyak       ПРОМ. ПОМЕЩЕНИЕ           град софия              волуяк   capital_non_center             Панел                   Панел               2016                   2016.0    2448000.0    2040.0        1200.00
163157  1t176354667650491                                  https://www.imot.bg/obiava-1t176354667650491-prodava-biznes-imot-grad-pleven-industrialna-zona  САМОСТОЯТЕЛНА СГРАДА          град плевен   индустриална зона        regional_city             Тухла                   Тухла               1970                   1970.0     700000.0    2047.0         341.96

In [64]:
# ------------------------------------------------------------
# Recheck future construction years after manual corrections
# ------------------------------------------------------------

future_years = df_model_base.loc[
    df_model_base["construction_year_model"].gt(2035),
    [
        "ad_id",
        "ad_url",
        "property_type_raw",
        "title_city_model",
        "title_geo_2_model",
        "geo_category",
        "construction_type_model",
        "construction_year_model",
        "total_price",
        "area_sqm",
        "price_per_sqm",
    ],
].copy()

print("Remaining future construction_year_model rows:", len(future_years))

display(
    future_years
    .sort_values("construction_year_model", ascending=False)
    .head(100)
)

Remaining future construction_year_model rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_model, title_geo_2_model, geo_category, construction_type_model, construction_year_model, total_price, area_sqm, price_per_sqm]
Index: []

In [65]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    159466 non-null  object
 1   ad_url                   159466 non-null  object
 2   listing_type             159466 non-null  object
 3   property_type_raw        159466 non-null  object
 4   total_price              159466 non-null  float64
 5   currency                 159466 non-null  object
 6   vat_status               159466 non-null  object
 7   area_sqm                 159466 non-null  float64
 8   price_per_sqm            159466 non-null  float64
 9   floor                    97454 non-null   float64
 10  total_floors             90480 non-null   float64
 11  construction_type        120724 non-null  object
 12  construction_year        159466 non-null  int64
 13  title_city_model         159466 non-null  object
 14  title_geo_2_model        159463 non-null  object
 15  geo_category             159466 non-null  object
 16  features_pipe            139702 non-null  object
 17  features_count           159466 non-null  int64
 18  views                    159466 non-null  float64
 19  construction_type_model  157277 non-null  object
 20  construction_year_model  122212 non-null  float64
dtypes: float64(7), int64(2), object(12)
memory usage: 26.8+ MB

In [69]:
# ------------------------------------------------------------
# Inspect non-building property types with floor data
# ------------------------------------------------------------

floor_not_applicable_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
    "СОЛАРЕН ПАРК",
}

non_building_with_floor = df_model_base.loc[
    df_model_base["property_type_raw"].isin(floor_not_applicable_types)
    & (
        df_model_base["floor"].notna()
        | df_model_base["total_floors"].notna()
    )
].copy()

print("Non-building rows with floor/total_floors populated:", len(non_building_with_floor))

display(
    non_building_with_floor[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor", "total_floors"])
    .head(100)
)

Non-building rows with floor/total_floors populated: 8

                    ad_id                                                                                            ad_url property_type_raw title_city_model title_geo_2_model   geo_category  floor  total_floors  total_price  area_sqm  price_per_sqm
162248  1t169269241339101          https://www.imot.bg/obiava-1t169269241339101-prodava-biznes-imot-oblast-shumen-s-novosel      СОЛАРЕН ПАРК     област шумен           новосел        village    0.0           1.0     76693.78     663.0         115.68
162912  1t175342694532880  https://www.imot.bg/obiava-1t175342694532880-prodava-biznes-imot-grad-ruse-v-z-obraztsov-chiflik      СОЛАРЕН ПАРК        град русе   образцов чифлик  regional_city    0.0           1.0   6250000.00   53670.0         116.45
163383  1t177028156147273              https://www.imot.bg/obiava-1t177028156147273-prodava-biznes-imot-grad-vratsa-dabnika      СОЛАРЕН ПАРК       град враца           дъбника  regional_city    0.0           1.0    989000.00   23000.0          43.00
163586  1t177461364893028     https://www.imot.bg/obiava-1t177461364893028-prodava-biznes-imot-oblast-plovdiv-gr-asenovgrad      СОЛАРЕН ПАРК   област пловдив        асеновград     small_city    0.0           1.0    799000.00   15527.0          51.46
163657  1t177591914946249         https://www.imot.bg/obiava-1t177591914946249-prodava-biznes-imot-oblast-ruse-gr-glodzhevo      СОЛАРЕН ПАРК      област русе          глоджево     small_city    0.0           1.0     64000.00    2000.0          32.00
162765  1t174472037331298          https://www.imot.bg/obiava-1t174472037331298-prodava-biznes-imot-oblast-shumen-s-srednya      СОЛАРЕН ПАРК     област шумен            средня        village    1.0           1.0     76700.00    1501.0          51.10
162832  1t174945852611903        https://www.imot.bg/obiava-1t174945852611903-prodava-biznes-imot-oblast-dobrich-s-donchevo      СОЛАРЕН ПАРК    област добрич           дончево        village    1.0           1.0   6267500.00   26133.0         239.83
163526  1t177340724318112           https://www.imot.bg/obiava-1t177340724318112-prodava-biznes-imot-oblast-ruse-s-tabachka      СОЛАРЕН ПАРК      област русе           табачка        village    2.0           2.0     60000.00    2200.0          27.27

In [71]:
# ------------------------------------------------------------
# Create model-safe floor fields and mark non-building floors as N/A
# ------------------------------------------------------------

df_model_base = df_model_base.copy()

floor_not_applicable_types = {
    "ПАРЦЕЛ",
    "ЗЕМЕДЕЛСКА ЗЕМЯ",
    "СОЛАРЕН ПАРК",
}

is_floor_not_applicable = df_model_base["property_type_raw"].isin(floor_not_applicable_types)

df_model_base["floor_model"] = df_model_base["floor"].astype("float")
df_model_base["total_floors_model"] = df_model_base["total_floors"].astype("float")

df_model_base["floor_applicability"] = "applicable"
df_model_base.loc[is_floor_not_applicable, "floor_applicability"] = "not_applicable_non_building"

df_model_base.loc[is_floor_not_applicable, "floor_model"] = pd.NA
df_model_base.loc[is_floor_not_applicable, "total_floors_model"] = pd.NA

print("Rows marked floor not applicable:", int(is_floor_not_applicable.sum()))

display(
    df_model_base["floor_applicability"]
    .value_counts(dropna=False)
    .rename_axis("floor_applicability")
    .reset_index(name="rows")
)

cleanup_actions.append({
    "rule": "set_floor_fields_not_applicable_for_non_building_types",
    "reason": "Floor and total_floors are not meaningful for land, parking-only, and solar park listings",
    "rows_affected": int(is_floor_not_applicable.sum()),
})

Rows marked floor not applicable: 37316

           floor_applicability    rows
0                   applicable  122150
1  not_applicable_non_building   37316

In [72]:
# ------------------------------------------------------------
# Inspect suspicious floor values for floor-applicable listings
# ------------------------------------------------------------

floor_applicable = df_model_base["floor_applicability"].eq("applicable")

suspicious_floor_rows = df_model_base.loc[
    floor_applicable
    & (
        df_model_base["floor_model"].lt(-5)
        | df_model_base["floor_model"].gt(60)
        | df_model_base["total_floors_model"].gt(80)
        | (
            df_model_base["floor_model"].notna()
            & df_model_base["total_floors_model"].notna()
            & df_model_base["floor_model"].gt(df_model_base["total_floors_model"] + 2)
        )
    )
].copy()

print("Suspicious floor rows:", len(suspicious_floor_rows))

display(
    suspicious_floor_rows[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "floor_model",
            "total_floors_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor_model", "total_floors_model"])
    .head(100)
)

Suspicious floor rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_model, title_geo_2_model, geo_category, floor, total_floors, floor_model, total_floors_model, total_price, area_sqm, price_per_sqm]
Index: []

In [73]:
# ------------------------------------------------------------
# Inspect suspicious floor values for floor-applicable listings
# ------------------------------------------------------------

floor_applicable = df_model_base["floor_applicability"].eq("applicable")

suspicious_floor_rows = df_model_base.loc[
    floor_applicable
    & (
        df_model_base["floor_model"].lt(-5)
        | df_model_base["floor_model"].gt(60)
        | df_model_base["total_floors_model"].gt(80)
        | (
            df_model_base["floor_model"].notna()
            & df_model_base["total_floors_model"].notna()
            & df_model_base["floor_model"].gt(df_model_base["total_floors_model"] + 2)
        )
    )
].copy()

print("Suspicious floor rows:", len(suspicious_floor_rows))

display(
    suspicious_floor_rows[
        [
            "ad_id",
            "ad_url",
            "property_type_raw",
            "title_city_model",
            "title_geo_2_model",
            "geo_category",
            "floor",
            "total_floors",
            "floor_model",
            "total_floors_model",
            "total_price",
            "area_sqm",
            "price_per_sqm",
        ]
    ]
    .sort_values(["property_type_raw", "floor_model", "total_floors_model"])
    .head(100)
)

Suspicious floor rows: 0

Empty DataFrame
Columns: [ad_id, ad_url, property_type_raw, title_city_model, title_geo_2_model, geo_category, floor, total_floors, floor_model, total_floors_model, total_price, area_sqm, price_per_sqm]
Index: []

In [74]:
df_model_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    159466 non-null  object
 1   ad_url                   159466 non-null  object
 2   listing_type             159466 non-null  object
 3   property_type_raw        159466 non-null  object
 4   total_price              159466 non-null  float64
 5   currency                 159466 non-null  object
 6   vat_status               159466 non-null  object
 7   area_sqm                 159466 non-null  float64
 8   price_per_sqm            159466 non-null  float64
 9   floor                    97454 non-null   float64
 10  total_floors             90480 non-null   float64
 11  construction_type        120724 non-null  object
 12  construction_year        159466 non-null  int64
 13  title_city_model         159466 non-null  object
 14  title_geo_2_model        159463 non-null  object
 15  geo_category             159466 non-null  object
 16  features_pipe            139702 non-null  object
 17  features_count           159466 non-null  int64
 18  views                    159466 non-null  float64
 19  construction_type_model  157277 non-null  object
 20  construction_year_model  122212 non-null  float64
 21  floor_model              97446 non-null   float64
 22  total_floors_model       90472 non-null   float64
 23  floor_applicability      159466 non-null  object
dtypes: float64(9), int64(2), object(13)
memory usage: 30.4+ MB

In [76]:
# ------------------------------------------------------------
# Final cleanup: create ML-ready dataset and save to Parquet
# ------------------------------------------------------------

# Choose your output path
ML_OUTPUT_PATH = PARSED_DATA_DIR / "imot_ml_ready.parquet"

df_ml_ready = df_model_base.copy()

# ------------------------------------------------------------
# 1. Keep only model-useful columns
# ------------------------------------------------------------

ml_ready_columns = [
    # Traceability - keep for audit, drop before fitting if needed
    "ad_id",
    "ad_url",

    # Core categorical features
    "listing_type",
    "property_type_raw",
    "currency",
    "vat_status",
    "title_city_model",
    "title_geo_2_model",
    "geo_category",

    # Numeric target / features
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "views",
    "features_count",

    # Cleaned construction features
    "construction_type_model",
    "construction_year_model",

    # Cleaned floor features
    "floor_model",
    "total_floors_model",
    "floor_applicability",

    # Feature engineering input
    "features_pipe",
]

ml_ready_columns = [
    col for col in ml_ready_columns
    if col in df_ml_ready.columns
]

df_ml_ready = df_ml_ready[ml_ready_columns].copy()


# ------------------------------------------------------------
# 2. Standardize missing categorical values
# ------------------------------------------------------------

categorical_cols = [
    "listing_type",
    "property_type_raw",
    "currency",
    "vat_status",
    "title_city_model",
    "title_geo_2_model",
    "geo_category",
    "construction_type_model",
    "floor_applicability",
    "features_pipe",
]

for col in categorical_cols:
    if col in df_ml_ready.columns:
        df_ml_ready[col] = (
            df_ml_ready[col]
            .astype("string")
            .str.strip()
        )
        df_ml_ready[col] = df_ml_ready[col].fillna("unknown")


# ------------------------------------------------------------
# 3. Ensure numeric columns are numeric
# ------------------------------------------------------------

numeric_cols = [
    "total_price",
    "area_sqm",
    "price_per_sqm",
    "views",
    "features_count",
    "construction_year_model",
    "floor_model",
    "total_floors_model",
]

for col in numeric_cols:
    if col in df_ml_ready.columns:
        df_ml_ready[col] = pd.to_numeric(df_ml_ready[col], errors="coerce")


# ------------------------------------------------------------
# 4. Final sanity checks
# ------------------------------------------------------------

print("ML-ready rows:", len(df_ml_ready))
print("ML-ready columns:", df_ml_ready.shape[1])

print("\nColumns:")
print(df_ml_ready.columns.tolist())

print("\nMissing values:")
display(
    df_ml_ready
    .isna()
    .sum()
    .rename("missing")
    .reset_index()
    .rename(columns={"index": "column"})
    .sort_values("missing", ascending=False)
)

print("\nInfo:")
display(df_ml_ready.info())


# ------------------------------------------------------------
# 5. Save to Parquet
# ------------------------------------------------------------

ML_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

df_ml_ready.to_parquet(
    ML_OUTPUT_PATH,
    index=False,
)

print(f"\nSaved ML-ready dataset to: {ML_OUTPUT_PATH}")
print("Saved rows:", len(df_ml_ready))
print("Saved columns:", df_ml_ready.shape[1])


# ------------------------------------------------------------
# 6. Optional: verify reload
# ------------------------------------------------------------

df_ml_ready_check = pd.read_parquet(ML_OUTPUT_PATH)

print("\nReload check:")
print("Rows:", len(df_ml_ready_check))
print("Columns:", df_ml_ready_check.shape[1])

display(df_ml_ready_check.head())

ML-ready rows: 159466
ML-ready columns: 20

Columns:
['ad_id', 'ad_url', 'listing_type', 'property_type_raw', 'currency', 'vat_status', 'title_city_model', 'title_geo_2_model', 'geo_category', 'total_price', 'area_sqm', 'price_per_sqm', 'views', 'features_count', 'construction_type_model', 'construction_year_model', 'floor_model', 'total_floors_model', 'floor_applicability', 'features_pipe']

Missing values:

                     column  missing
17       total_floors_model    68994
16              floor_model    62020
15  construction_year_model    37254
0                     ad_id        0
3         property_type_raw        0
2              listing_type        0
1                    ad_url        0
4                  currency        0
8              geo_category        0
5                vat_status        0
6          title_city_model        0
7         title_geo_2_model        0
11            price_per_sqm        0
10                 area_sqm        0
9               total_price        0
12                    views        0
14  construction_type_model        0
13           features_count        0
18      floor_applicability        0
19            features_pipe        0

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 159466 entries, 0 to 163846
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ad_id                    159466 non-null  object
 1   ad_url                   159466 non-null  object
 2   listing_type             159466 non-null  string
 3   property_type_raw        159466 non-null  string
 4   currency                 159466 non-null  string
 5   vat_status               159466 non-null  string
 6   title_city_model         159466 non-null  string
 7   title_geo_2_model        159466 non-null  string
 8   geo_category             159466 non-null  string
 9   total_price              159466 non-null  float64
 10  area_sqm                 159466 non-null  float64
 11  price_per_sqm            159466 non-null  float64
 12  views                    159466 non-null  float64
 13  features_count           159466 non-null  int64
 14  construction_type_model  159466 non-null  string
 15  construction_year_model  122212 non-null  float64
 16  floor_model              97446 non-null   float64
 17  total_floors_model       90472 non-null   float64
 18  floor_applicability      159466 non-null  string
 19  features_pipe            159466 non-null  string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 25.5+ MB

None

Saved ML-ready dataset to: D:\users\kamen.dimitrov\desktop\SOFTUNI\AI_and_ML_upskill_program\real_estate_valuation\data\parsed_sales_full\imot_ml_ready.parquet
Saved rows: 159466
Saved columns: 20

Reload check:
Rows: 159466
Columns: 20

               ad_id                                                                                                                          ad_url             listing_type property_type_raw currency vat_status       title_city_model title_geo_2_model     geo_category  total_price  area_sqm  price_per_sqm   views  features_count construction_type_model  construction_year_model  floor_model  total_floors_model floor_applicability                                                                                                                                           features_pipe
0  1a129794411209548                          https://www.imot.bg/obiava-1a129794411209548-prodava-ednostaen-apartament-oblast-blagoevgrad-gr-bansko  single_property_listing           1-СТАЕН      EUR     no_vat     област благоевград            банско  mountain_resort      36000.0      35.0        1028.57  5834.0               3                   Тухла                   2010.0          3.0                 5.0          applicable                                                                                                                      Тухла|Обзаведен|Контрол на достъпа
1  1a127539284802892                             https://www.imot.bg/obiava-1a127539284802892-prodava-ednostaen-apartament-oblast-dobrich-gr-balchik  single_property_listing           1-СТАЕН      EUR     no_vat          област добрич            балчик       sea_resort      75000.0      51.0        1470.59  2391.0               8                   Тухла                   2008.0          3.0                 5.0          applicable                                                 Тухла|Асансьор|Интернет връзка|Обзаведен|Видео наблюдение|Контрол на достъпа|Охрана|В затворен комплекс
2  1a126881929164804              https://www.imot.bg/obiava-1a126881929164804-prodava-ednostaen-apartament-grad-pleven-druzhba-1-bivshiyat-bikarnik  single_property_listing           1-СТАЕН      EUR     no_vat            град плевен          дружба 1    regional_city      53500.0      40.0        1337.50  6579.0               1                   Панел                   2026.0          4.0                 8.0          applicable                                                                                                                                                   Панел
3  1a130799086731769                                 https://www.imot.bg/obiava-1a130799086731769-prodava-ednostaen-apartament-grad-pleven-druzhba-4  single_property_listing           1-СТАЕН      EUR     no_vat            град плевен          дружба 4    regional_city      52000.0      40.0        1300.00  4282.0               2                   Панел                   1970.0          8.0                 8.0          applicable                                                                                                                                          Панел|Асансьор
4  1a140309247069043  https://www.imot.bg/obiava-1a140309247069043-prodava-ednostaen-apartament-oblast-veliko-tarnovo-gr-gorna-oryahovitsa-kv-prolet  single_property_listing           1-СТАЕН      EUR    unknown  област велико търново   горна оряховица       small_city      49450.0      42.0        1177.38     3.0              14                   Панел                   2026.0          1.0                 6.0          applicable  Панел|С преход|Асансьор|С гараж|С паркинг|Лизинг|Бартер|Интернет връзка|С действащ бизнес|Обзаведен|Видео наблюдение|Контрол на достъпа|Охрана|Саниран