In [1]:
%matplotlib inline

In [2]:
#Import Libraries here

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
from pathlib import Path
from IPython.display import display

In [3]:
#Import your modules here
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
PARSED_DATA_DIR = PROJECT_ROOT / "data" / "parsed_sales_full"

In [4]:
ml_model_base_df = pd.read_parquet(PARSED_DATA_DIR / "imot_ml_ready.parquet")
ml_model_base_df

,ad_id,ad_url,listing_type,property_type_raw,currency,vat_status,title_city_model,title_geo_2_model,geo_category,total_price,area_sqm,price_per_sqm,views,features_count,construction_type_model,construction_year_model,floor_model,total_floors_model,floor_applicability,features_pipe
0,1a129794411209548,https://www.imot.bg/obiava-1a129794411209548-p...,single_property_listing,1-СТАЕН,EUR,no_vat,област благоевград,банско,mountain_resort,36000.0,35.0,1028.57,5834.0,3,Тухла,2010.0,3.0,5.0,applicable,Тухла|Обзаведен|Контрол на достъпа
1,1a127539284802892,https://www.imot.bg/obiava-1a127539284802892-p...,single_property_listing,1-СТАЕН,EUR,no_vat,област добрич,балчик,sea_resort,75000.0,51.0,1470.59,2391.0,8,Тухла,2008.0,3.0,5.0,applicable,Тухла|Асансьор|Интернет връзка|Обзаведен|Видео...
2,1a126881929164804,https://www.imot.bg/obiava-1a126881929164804-p...,single_property_listing,1-СТАЕН,EUR,no_vat,град плевен,дружба 1,regional_city,53500.0,40.0,1337.50,6579.0,1,Панел,2026.0,4.0,8.0,applicable,Панел
3,1a130799086731769,https://www.imot.bg/obiava-1a130799086731769-p...,single_property_listing,1-СТАЕН,EUR,no_vat,град плевен,дружба 4,regional_city,52000.0,40.0,1300.00,4282.0,2,Панел,1970.0,8.0,8.0,applicable,Панел|Асансьор
4,1a140309247069043,https://www.imot.bg/obiava-1a140309247069043-p...,single_property_listing,1-СТАЕН,EUR,unknown,област велико търново,горна оряховица,small_city,49450.0,42.0,1177.38,3.0,14,Панел,2026.0,1.0,6.0,applicable,Панел|С преход|Асансьор|С гараж|С паркинг|Лизи...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159461,1t177883753392599,https://www.imot.bg/obiava-1t177883753392599-p...,single_property_listing,ВИЛНО СЕЛИЩЕ,EUR,with_vat,област бургас,велика,village,659900.0,1680.0,392.80,34.0,1,Тухла,2026.0,NaN,NaN,applicable,Тухла
159462,1t177870422636588,https://www.imot.bg/obiava-1t177870422636588-p...,single_property_listing,ФАБРИКА/ЗАВОД,EUR,without_vat,област кърджали,джебел,small_city,2000000.0,2725.0,733.94,41.0,2,Тухла,2026.0,NaN,NaN,applicable,Тухла|Саниран
159463,1t177882534906657,https://www.imot.bg/obiava-1t177882534906657-p...,single_property_listing,АВТОСЕРВИЗ,EUR,unknown,град варна,тополи,large_regional_city,165800.0,2068.0,80.17,38.0,3,Панел,2026.0,NaN,NaN,applicable,Сглобяема конструкция|С паркинг|С действащ бизнес
159464,1t177876453886021,https://www.imot.bg/obiava-1t177876453886021-p...,single_property_listing,ПАРКИНГ,EUR,with_vat,област софия,ботевград,small_city,3800000.0,12000.0,316.67,49.0,1,Тухла,2026.0,NaN,NaN,applicable,Тухла
159465,1t177876677138531,https://www.imot.bg/obiava-1t177876677138531-p...,single_property_listing,БАНКОВ ОФИС,EUR,no_vat,област софия,костинброд,small_city,299000.0,403.0,741.94,67.0,1,Тухла,1980.0,2.0,2.0,applicable,Тухла

In [5]:
ml_model_base_df.title_city_model.value_counts()

title_city_model
град софия               34452
област бургас            17875
град варна               17606
град пловдив             17162
област пловдив            7792
област софия              5025
град бургас               4486
област велико търново     3821
област варна              3742
област добрич             3444
град стара загора         3386
град русе                 3116
град плевен               2761
град шумен                2760
област благоевград        2657
област стара загора       2053
град велико търново       2029
област пазарджик          1963
област перник             1638
област габрово            1620
област ловеч              1619
град кърджали             1271
град перник               1259
област шумен              1124
област русе               1055
област плевен             1026
град враца                 962
област кюстендил           883
област хасково             853
град пазарджик             832
област смолян              804
град габрово               778
град благоевград           746
град добрич                725
град хасково               705
град търговище             584
област враца               539
област кърджали            537
област монтана             342
град разград               332
град монтана               324
град видин                 298
град ловеч                 280
град сливен                264
област видин               259
област търговище           238
област ямбол               229
град ямбол                 207
област сливен              201
град смолян                199
град кюстендил             193
област разград             159
област силистра            154
град силистра               97
Name: count, dtype: Int64

In [6]:
model_sofia = ml_model_base_df[ml_model_base_df.title_city_model == "град софия"]
model_sofia.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34452 entries, 8 to 159459
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ad_id                    34452 non-null  object
 1   ad_url                   34452 non-null  object
 2   listing_type             34452 non-null  string
 3   property_type_raw        34452 non-null  string
 4   currency                 34452 non-null  string
 5   vat_status               34452 non-null  string
 6   title_city_model         34452 non-null  string
 7   title_geo_2_model        34452 non-null  string
 8   geo_category             34452 non-null  string
 9   total_price              34452 non-null  float64
 10  area_sqm                 34452 non-null  float64
 11  price_per_sqm            34452 non-null  float64
 12  views                    34452 non-null  float64
 13  features_count           34452 non-null  int64
 14  construction_type_model  34452 non-null  string
 15  construction_year_model  28160 non-null  float64
 16  floor_model              26040 non-null  float64
 17  total_floors_model       25421 non-null  float64
 18  floor_applicability      34452 non-null  string
 19  features_pipe            34452 non-null  string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 5.5+ MB

In [8]:
model_sofia.geo_category.value_counts()

geo_category
capital_non_center    29014
capital_center         5438
Name: count, dtype: Int64

In [10]:
model_sofia_non_center = model_sofia[model_sofia.geo_category == 'capital_non_center']
model_sofia_non_center.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29014 entries, 8 to 159459
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ad_id                    29014 non-null  object
 1   ad_url                   29014 non-null  object
 2   listing_type             29014 non-null  string
 3   property_type_raw        29014 non-null  string
 4   currency                 29014 non-null  string
 5   vat_status               29014 non-null  string
 6   title_city_model         29014 non-null  string
 7   title_geo_2_model        29014 non-null  string
 8   geo_category             29014 non-null  string
 9   total_price              29014 non-null  float64
 10  area_sqm                 29014 non-null  float64
 11  price_per_sqm            29014 non-null  float64
 12  views                    29014 non-null  float64
 13  features_count           29014 non-null  int64
 14  construction_type_model  29014 non-null  string
 15  construction_year_model  22841 non-null  float64
 16  floor_model              21026 non-null  float64
 17  total_floors_model       20449 non-null  float64
 18  floor_applicability      29014 non-null  string
 19  features_pipe            29014 non-null  string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 4.6+ MB

In [11]:
model_sofia_non_center.property_type_raw.value_counts()

property_type_raw
3-СТАЕН                        8417
2-СТАЕН                        6642
ПАРЦЕЛ                         6173
КЪЩА                           1715
4-СТАЕН                        1675
1-СТАЕН                         803
МНОГОСТАЕН                      685
МАГАЗИН                         641
ОФИС                            606
МЕЗОНЕТ                         367
ГАРАЖ                           300
ПАРКОМЯСТО                      158
ЕТАЖ ОТ КЪЩА                    142
ЗАВЕДЕНИЕ                       138
ПРОМ. ПОМЕЩЕНИЕ                 116
СКЛАД                            95
САМОСТОЯТЕЛНА СГРАДА             71
АТЕЛИЕ, ТАВАН                    53
ФИТНЕС ЗАЛА                      28
КЛИНИКА                          25
ТЪРГОВСКИ КОМПЛЕКС               20
ХОТЕЛ                            20
ФАБРИКА/ЗАВОД                    17
ДЕТСКИ ЦЕНТЪР                    17
ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН      17
ВИЛА                             16
ЛЕКАРСКИ КАБИНЕТ                  8
АВТОСЕРВИЗ                        8
СТОМАТОЛОГИЧЕН КАБИНЕТ            6
БАНКОВ ОФИС                       5
АПТЕКА                            5
ВИЛНО СЕЛИЩЕ                      5
ДОМ ЗА ВЪЗРАСТНИ ХОРА             4
СПА/СОЛАРНО СТУДИО                4
ГАРАЖ, ПАРКОМЯСТО                 3
ФЕРМА                             3
СОЛАРЕН ПАРК                      3
БЕНЗИНОСТАНЦИЯ/ГАЗСТАНЦИЯ         1
ПАРКИНГ                           1
АКВАПАРК                          1
Name: count, dtype: Int64

In [16]:
model_sofia_non_center_office = model_sofia_non_center[model_sofia_non_center.property_type_raw == 'ОФИС']
model_sofia_non_center_office

,ad_id,ad_url,listing_type,property_type_raw,currency,vat_status,title_city_model,title_geo_2_model,geo_category,total_price,area_sqm,price_per_sqm,views,features_count,construction_type_model,construction_year_model,floor_model,total_floors_model,floor_applicability,features_pipe
82553,1g132688996806749,https://www.imot.bg/obiava-1g132688996806749-p...,single_property_listing,ОФИС,EUR,without_vat,град софия,манастирски ливади,capital_non_center,1307460.0,396.0,3301.67,1705.0,6,Тухла,2024.0,5.0,11.0,applicable,Тухла|Асансьор|С паркинг|Видео наблюдение|Конт...
82554,1g142200775141318,https://www.imot.bg/obiava-1g142200775141318-p...,single_property_listing,ОФИС,EUR,with_vat,град софия,изгрев,capital_non_center,1230000.0,325.0,3784.62,294.0,1,Тухла,2010.0,1.0,9.0,applicable,Тухла
82557,1g140466442256617,https://www.imot.bg/obiava-1g140466442256617-p...,single_property_listing,ОФИС,EUR,with_vat,град софия,овча купел 2,capital_non_center,185980.0,80.0,2324.75,3674.0,2,Тухла,2023.0,1.0,7.0,applicable,Тухла|Асансьор
82558,1g144353854582676,https://www.imot.bg/obiava-1g144353854582676-p...,single_property_listing,ОФИС,EUR,no_vat,град софия,полигона,capital_non_center,200000.0,165.0,1212.12,9.0,10,Тухла,2026.0,5.0,10.0,applicable,Тухла|Асансьор|С гараж|С паркинг|Интернет връз...
82562,1g141623904781217,https://www.imot.bg/obiava-1g141623904781217-p...,single_property_listing,ОФИС,EUR,no_vat,град софия,дървеница,capital_non_center,540000.0,365.0,1479.45,11173.0,6,Панел,1980.0,2.0,6.0,applicable,Панел|Асансьор|С паркинг|С действащ бизнес|Кон...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84899,1g177877065764720,https://www.imot.bg/obiava-1g177877065764720-p...,single_property_listing,ОФИС,EUR,no_vat,град софия,малинова долина,capital_non_center,186000.0,81.0,2296.30,37.0,3,Тухла,2025.0,0.0,6.0,applicable,Тухла|Асансьор|Саниран
84900,1g177874933122530,https://www.imot.bg/obiava-1g177874933122530-p...,single_property_listing,ОФИС,EUR,no_vat,град софия,красно село,capital_non_center,99000.0,22.0,4500.00,100.0,1,Тухла,2026.0,0.0,10.0,applicable,Тухла
84934,1g177883099223155,https://www.imot.bg/obiava-1g177883099223155-p...,single_property_listing,ОФИС,EUR,no_vat,град софия,люлин 10,capital_non_center,247000.0,146.0,1691.78,34.0,3,ЕПК,2026.0,0.0,16.0,applicable,ЕПК|С паркинг|Контрол на достъпа
84936,1g177889768462295,https://www.imot.bg/obiava-1g177889768462295-p...,single_property_listing,ОФИС,EUR,with_vat,град софия,манастирски ливади,capital_non_center,360000.0,124.0,2903.23,33.0,2,Тухла,2017.0,NaN,NaN,applicable,Тухла|Саниран
84939,1g177887680041966,https://www.imot.bg/obiava-1g177887680041966-p...,single_property_listing,ОФИС,EUR,without_vat,град софия,изток,capital_non_center,116500.0,26.0,4480.77,79.0,4,Тухла,2025.0,0.0,6.0,applicable,Тухла|Асансьор|С гараж|С паркинг

In [17]:
model_sofia_non_center_office.price_per_sqm.describe()

count     606.000000
mean     2284.840083
std      1001.631433
min        16.660000
25%      1617.395000
50%      2103.575000
75%      2725.452500
max      9258.760000
Name: price_per_sqm, dtype: float64

In [19]:
office_types = [
    'ЗАВЕДЕНИЕ',
    'МАГАЗИН',
    'ТЪРГОВСКИ КОМПЛЕКС',
    'СПА/СОЛАРНО СТУДИО',
    'АПТЕКА',
    'БАНКОВ ОФИС',
    'ФИТНЕС ЗАЛА',
    'ДЕТСКИ ЦЕНТЪР',
    'ФРИЗЬОРСКИ/КОЗМЕТИЧЕН САЛОН',
    'ЛЕКАРСКИ КАБИНЕТ',
    'СТОМАТОЛОГИЧЕН КАБИНЕТ'
]

model_sofia_non_center_shops = model_sofia_non_center[
    model_sofia_non_center['property_type_raw'].isin(office_types)
]

model_sofia_non_center_shops.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 109811 to 159451
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ad_id                    889 non-null    object
 1   ad_url                   889 non-null    object
 2   listing_type             889 non-null    string
 3   property_type_raw        889 non-null    string
 4   currency                 889 non-null    string
 5   vat_status               889 non-null    string
 6   title_city_model         889 non-null    string
 7   title_geo_2_model        889 non-null    string
 8   geo_category             889 non-null    string
 9   total_price              889 non-null    float64
 10  area_sqm                 889 non-null    float64
 11  price_per_sqm            889 non-null    float64
 12  views                    889 non-null    float64
 13  features_count           889 non-null    int64
 14  construction_type_model  889 non-null    string
 15  construction_year_model  889 non-null    float64
 16  floor_model              769 non-null    float64
 17  total_floors_model       769 non-null    float64
 18  floor_applicability      889 non-null    string
 19  features_pipe            889 non-null    string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 145.9+ KB

In [20]:
model_sofia_non_center_shops.price_per_sqm.describe()

count     889.000000
mean     2326.216322
std      1187.185530
min       118.570000
25%      1580.000000
50%      2016.130000
75%      2833.330000
max      9999.930000
Name: price_per_sqm, dtype: float64

In [25]:
parking_types = [
    'ПАРКОМЯСТО',

]

model_sofia_non_center_parking = model_sofia_non_center[
    model_sofia_non_center['property_type_raw'].isin(parking_types)
]

model_sofia_non_center_parking.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 115112 to 117381
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ad_id                    158 non-null    object
 1   ad_url                   158 non-null    object
 2   listing_type             158 non-null    string
 3   property_type_raw        158 non-null    string
 4   currency                 158 non-null    string
 5   vat_status               158 non-null    string
 6   title_city_model         158 non-null    string
 7   title_geo_2_model        158 non-null    string
 8   geo_category             158 non-null    string
 9   total_price              158 non-null    float64
 10  area_sqm                 158 non-null    float64
 11  price_per_sqm            158 non-null    float64
 12  views                    158 non-null    float64
 13  features_count           158 non-null    int64
 14  construction_type_model  158 non-null    string
 15  construction_year_model  158 non-null    float64
 16  floor_model              126 non-null    float64
 17  total_floors_model       126 non-null    float64
 18  floor_applicability      158 non-null    string
 19  features_pipe            158 non-null    string
dtypes: float64(7), int64(1), object(2), string(10)
memory usage: 25.9+ KB

In [26]:
model_sofia_non_center_parking.price_per_sqm.describe()

count     158.000000
mean     1758.615759
std       747.098316
min       416.650000
25%      1330.592500
50%      1666.670000
75%      2058.820000
max      6666.670000
Name: price_per_sqm, dtype: float64

In [30]:
output_path = r"D:\Users\kamen.dimitrov\Desktop\sofia_non_center_market_data.xlsx"

with pd.ExcelWriter(output_path, engine="xlsxwriter") as writer:
    model_sofia_non_center_shops.to_excel(writer, sheet_name="Shops", index=False)
    model_sofia_non_center_office.to_excel(writer, sheet_name="Office", index=False)
    model_sofia_non_center_parking.to_excel(writer, sheet_name="Parking", index=False)